from django.urls import path

from .views import (
    ClassArchiveView,
    ClassDetailView,
    ClassListCreateView,
    ClassRestoreView,
    DepartmentArchiveView,
    DepartmentDetailView,
    DepartmentRestoreView,
    DepartmentListCreateView,
    LevelBulkCreateView,
    LevelArchiveView,
    LevelDetailView,
    LevelRestoreView,
    GenerateArmsView,
    LevelListCreateView,
    OverviewView,
    ProgramArchiveView,
    ProgramDetailView,
    ProgramRestoreView,
    ProgramListCreateView,
    SessionActivateView,
    SessionArchiveView,
    SessionRollForwardView,
    SessionDetailView,
    SessionListCreateView,
    StructureTreeView,
    SubjectArchiveView,
    SubjectDetailView,
    SubjectRestoreView,
    SubjectListCreateView,
    SubjectOfferingsView,
    TermDetailView,
    TermListCreateView,
)

urlpatterns = [
    path("sessions/", SessionListCreateView.as_view(), name="academics-session-list"),
    path("sessions/<int:pk>/", SessionDetailView.as_view(), name="academics-session-detail"),
    path("sessions/<int:pk>/activate/", SessionActivateView.as_view(), name="academics-session-activate"),
    path("sessions/<int:pk>/archive/", SessionArchiveView.as_view(), name="academics-session-archive"),
    path(
        "sessions/<int:pk>/roll-forward/", SessionRollForwardView.as_view(),
        name="academics-session-roll-forward",
    ),
    path("sessions/<int:pk>/terms/", TermListCreateView.as_view(), name="academics-term-list"),
    # No archive route for a term, deliberately. See TermDetailView's docstring;
    # test_no_standalone_term_archive_route asserts the absence.
    path("terms/<int:pk>/", TermDetailView.as_view(), name="academics-term-detail"),

    path("departments/", DepartmentListCreateView.as_view(), name="academics-department-list"),
    path("departments/<int:pk>/", DepartmentDetailView.as_view(), name="academics-department-detail"),
    path("departments/<int:pk>/archive/", DepartmentArchiveView.as_view(), name="academics-department-archive"),
    path("departments/<int:pk>/restore/", DepartmentRestoreView.as_view(), name="academics-department-restore"),

    path("programs/", ProgramListCreateView.as_view(), name="academics-program-list"),
    path("programs/<int:pk>/", ProgramDetailView.as_view(), name="academics-program-detail"),
    path("programs/<int:pk>/archive/", ProgramArchiveView.as_view(), name="academics-program-archive"),
    path("programs/<int:pk>/restore/", ProgramRestoreView.as_view(), name="academics-program-restore"),
    path("programs/<int:pk>/levels/", LevelListCreateView.as_view(), name="academics-level-list"),
    path("programs/<int:pk>/levels/bulk/", LevelBulkCreateView.as_view(), name="academics-level-bulk"),
    path("levels/<int:pk>/", LevelDetailView.as_view(), name="academics-level-detail"),
    path("levels/<int:pk>/archive/", LevelArchiveView.as_view(), name="academics-level-archive"),
    path("levels/<int:pk>/restore/", LevelRestoreView.as_view(), name="academics-level-restore"),

    path("classes/", ClassListCreateView.as_view(), name="academics-class-list"),
    path("classes/generate-arms/", GenerateArmsView.as_view(), name="academics-class-arms"),
    path("classes/<int:pk>/", ClassDetailView.as_view(), name="academics-class-detail"),
    path("classes/<int:pk>/archive/", ClassArchiveView.as_view(), name="academics-class-archive"),
    path("classes/<int:pk>/restore/", ClassRestoreView.as_view(), name="academics-class-restore"),

    path("subjects/", SubjectListCreateView.as_view(), name="academics-subject-list"),
    path("subjects/<int:pk>/", SubjectDetailView.as_view(), name="academics-subject-detail"),
    path("subjects/<int:pk>/archive/", SubjectArchiveView.as_view(), name="academics-subject-archive"),
    path("subjects/<int:pk>/restore/", SubjectRestoreView.as_view(), name="academics-subject-restore"),
    path("subjects/<int:pk>/offerings/", SubjectOfferingsView.as_view(), name="academics-subject-offerings"),

    path("structure/tree/", StructureTreeView.as_view(), name="academics-structure-tree"),
    path("overview/", OverviewView.as_view(), name="academics-overview"),
]
