"""URL routes for the vs_finance REST API (mounted at ``/v1/finance/``).

Families: entity-scoped master-data / document lists + actions, the financial-statement
reports, and the operational/setup surface (reference data, banking, expense claims,
payroll, budgets, fixed assets, audit) wired from :mod:`vs_finance.views_ops`. Every
endpoint expects ``?entity=<id or code>`` - except the **global** currency/FX routes.
"""
from django.urls import path

from .views_accruals import (
    CustomerDepositForfeitView,
    CustomerDepositListView,
    CustomerDepositReleaseView,
    DeferredIncomeReleaseView,
    DeferredIncomeReverseView,
    DeferredIncomeView,
    DoubtfulDebtProvisionDetailView,
    DoubtfulDebtProvisionListCreateView,
    DoubtfulDebtProvisionPostView,
    DoubtfulDebtProvisionSubmitView,
    FinanceReceivablesSettingsView,
    WriteOffRecoverView,
)

from .views import (
    AccountActivityView,
    AccountDetailView,
    AccountListCreateView,
    AnalyticsSliceView,
    ARAgingView,
    ARReconciliationView,
    BalanceSheetView,
    CashFlowView,
    ChangesInEquityView,
    DirectEntryCreateView,
    EntityListCreateView,
    FinanceDashboardView,
    FinanceReceivablesDashboardView,
    FinanceSpendDashboardView,
    FiscalPeriodListView,
    FiscalYearCloseView,
    FiscalYearListView,
    FiscalYearReopenView,
    IncomeStatementView,
    InvoiceDetailView,
    InvoiceDocumentView,
    InvoiceListCreateView,
    InvoiceSummaryView,
    JournalEntryDetailView,
    JournalEntryListView,
    JournalSummaryView,
    JournalPostView,
    JournalReverseView,
    JournalSubmitView,
    PeriodCloseView,
    PeriodLockView,
    PeriodReopenView,
    PostingWindowView,
    StatutoryPackView,
    TrialBalanceView,
)
from .views_public import (
    PublicInvoiceCheckoutView,
    PublicInvoiceLogoView,
    PublicInvoicePayView,
)
from .views_document_email import (
    CustomerStatementEmailView,
    FinanceDeliveryRetryView,
    InvoiceEmailView,
    PaymentEmailView,
)
from .views_ar import (
    ARAdjustmentBatchView,
    ConcessionDetailView,
    ConcessionListCreateView,
    ConcessionPostView,
    ConcessionSubmitView,
    ConcessionSummaryView,
    ConcessionVoidView,
    CreditNoteAllocateView,
    CreditNoteDetailView,
    CreditNoteListCreateView,
    CreditNotePostView,
    CreditNoteSubmitView,
    CreditNoteVoidView,
    CustomerCreditTransferDetailView,
    CustomerCreditTransferListCreateView,
    CustomerCreditTransferSubmitView,
    CustomerCreditTransferVoidView,
    CustomerDetailView,
    CustomerListCreateView,
    CustomerOpeningInvoiceImportView,
    FeeItemAssignmentView,
    CustomerReceiptView,
    CustomerSummaryView,
    PaymentAllocateView,
    PaymentDetailView,
    PaymentListView,
    PaymentReceiptView,
    PaymentSummaryView,
    PaymentVoidView,
    CustomerStatementView,
    FeeStructureDetailView,
    FeeStructureDuplicateView,
    FeeStructureGenerateView,
    FeeStructureListCreateView,
    DunningGenerateView,
    DunningSummaryView,
    DunningNoticeCancelView,
    DunningNoticeDetailView,
    DunningNoticeListCreateView,
    DunningNoticeSendView,
    DunningPolicyDetailView,
    DunningPolicyListCreateView,
    InvoicePayView,
    InvoiceRemindView,
    InvoiceRevokePayLinkView,
    InvoiceVoidView,
    InvoiceWriteOffView,
    ARAdjustmentListView,
    PaymentPlanActivateView,
    PaymentPlanCancelView,
    PaymentPlanDetailView,
    PaymentPlanListCreateView,
    PaymentPlanRefreshView,
    RefundDetailView,
    RefundAvailabilityView,
    RefundListCreateView,
    RefundPostView,
    RefundSubmitView,
    RefundVoidView,
    WriteOffRequestDetailView,
    WriteOffRequestListCreateView,
    WriteOffRequestPostView,
    WriteOffRequestSubmitView,
)
from .views_settings import (
    FinanceAccountSettingsView,
    FinanceBankingSettingsView,
    FinanceCalendarSettingsView,
    FinanceDocumentSettingsView,
    FinancePayrollSettingsView,
)
from .views_ops.payroll_statutory import (
    EmployeeDeductionDetailView,
    EmployeeDeductionListCreateView,
    EmployeeSalaryHistoryView,
    EmployeeSalaryTaxSummaryView,
    MyPayslipDetailView,
    MyPayslipListView,
    MyTaxSummaryView,
    PayeTaxTableDetailView,
    PayeTaxTableListCreateView,
    PayrollDeductionTypeDetailView,
    PayrollDeductionTypeListCreateView,
    PayrollLinePayslipView,
    PensionFundAdministratorDetailView,
    PensionFundAdministratorListCreateView,
    SalaryStructureHistoryView,
    TaxFilingScheduleView,
    TaxJurisdictionDetailView,
    TaxJurisdictionListCreateView,
)
from .views_ops import (
    BankAccountDetailView,
    BankAccountListCreateView,
    BankTransactionDetailView,
    BankTransactionListCreateView,
    BankTransactionVoidView,
    BankTransferDetailView,
    BankTransferListCreateView,
    BankTransferVoidView,
    HeldReceiptDetailView,
    HeldReceiptForwardView,
    HeldReceiptListCreateView,
    HeldReceiptVoidView,
    InterBranchBalancesView,
    InterBranchConfirmView,
    InterBranchDeclineView,
    InterBranchReceivableMoveView,
    InterBranchRequestView,
    InterBranchSendView,
    InterBranchTransferDetailView,
    InterBranchTransferListCreateView,
    InterBranchVoidView,
    RechargeDetailView,
    RechargeListCreateView,
    RechargeVoidView,
    SharedCostRuleDetailView,
    SharedCostRuleListCreateView,
    BankAutoReconcileView,
    BankBookLinesView,
    BankReconcileCompleteView,
    BankSplitMatchView,
    BankStatementLineAdjustView,
    BankStatementLineGroupMatchView,
    BankStatementLineIgnoreView,
    BankStatementDetailView,
    BankStatementImportTemplateView,
    BankStatementImportWizardView,
    BankStatementLineDetailView,
    BankStatementLineMatchView,
    BankStatementLineUnmatchView,
    BankStatementLineView,
    BudgetApproveView,
    BudgetDetailView,
    BudgetHeatmapView,
    BudgetLineCreateView,
    BudgetLineDetailView,
    BudgetListCreateView,
    BudgetRollupView,
    BudgetVarianceView,
    CostCenterListCreateView,
    CurrencyListCreateView,
    DimensionListCreateView,
    ExpenseClaimDetailView,
    ExpenseClaimListCreateView,
    ExpenseClaimPostView,
    ExpenseClaimReceiptView,
    ExpenseClaimRejectView,
    ExpenseClaimSettleView,
    ExpenseClaimSubmitView,
    ExpenseClaimSummaryView,
    ExpenseClaimVoidView,
    FinanceAuditFacetsView,
    FinanceAuditLogDetailView,
    FinanceAuditLogListView,
    FixedAssetAcquireView,
    FixedAssetDepreciateView,
    FixedAssetDetailView,
    FixedAssetDisposeView,
    FixedAssetListCreateView,
    FixedAssetRunDepreciationView,
    FixedAssetSummaryView,
    FxRateListCreateView,
    EmployeeSalaryDetailView,
    EmployeeSalaryListCreateView,
    PayrollRunCancelView,
    PayrollRunDetailView,
    PayrollRunGenerateView,
    PayrollRunListCreateView,
    PayrollRunPayView,
    PayrollRunPostView,
    PayrollRunSummaryView,
    SalaryStructureDetailView,
    SalaryStructureListCreateView,
    PettyCashFundDetailView,
    PettyCashFundEstablishView,
    PettyCashFundListCreateView,
    PettyCashFundReplenishView,
    PettyCashStatusView,
    PettyCashVoucherDetailView,
    PettyCashVoucherListCreateView,
    PettyCashVoucherPostView,
    PettyCashVoucherVoidView,
    PettyCashFundCloseView,
    PettyCashFundReduceView,
    PettyCashFundReopenView,
    PettyCashReturnDetailView,
    PettyCashReturnListView,
    PettyCashReturnVoidView,
    PettyCashVoucherCancelView,
    TaxCodeListCreateView,
    TaxFilingDetailView,
    TaxFilingFileView,
    TaxFilingListCreateView,
    TaxFilingPayView,
    TaxFilingUnfileView,
    TaxRemittanceReverseView,
    TaxFilingSummaryView,
    TaxObligationDetailView,
    TaxObligationListCreateView,
    TaxObligationOutstandingView,
)

urlpatterns = [
    # Public pay-an-invoice page. No session: the signed token in the URL names
    # the invoice, and the amount is read when the payer clicks, not when the
    # invoice email was written.
    path("public/invoices/<str:token>/", PublicInvoicePayView.as_view(),
         name="public-invoice-pay"),
    path("public/invoices/<str:token>/checkout/", PublicInvoiceCheckoutView.as_view(),
         name="public-invoice-checkout"),
    path("public/invoices/<str:token>/logo/", PublicInvoiceLogoView.as_view(),
         name="public-invoice-logo"),

    # Master data + documents
    path("entities/", EntityListCreateView.as_view(), name="finance-entity-list"),
    path("settings/account-mappings/", FinanceAccountSettingsView.as_view(),
         name="finance-account-settings"),
    path("settings/documents/", FinanceDocumentSettingsView.as_view(),
         name="finance-document-settings"),
    path("settings/banking/", FinanceBankingSettingsView.as_view(),
         name="finance-banking-settings"),
    path("settings/calendar/", FinanceCalendarSettingsView.as_view(),
         name="finance-calendar-settings"),
    path("settings/receivables/", FinanceReceivablesSettingsView.as_view(),
         name="finance-receivables-settings"),
    path("settings/payroll/", FinancePayrollSettingsView.as_view(),
         name="finance-payroll-settings"),
    path("accounts/", AccountListCreateView.as_view(), name="finance-account-list"),
    path("accounts/<int:pk>/activity/", AccountActivityView.as_view(), name="finance-account-activity"),
    path("accounts/<int:pk>/", AccountDetailView.as_view(), name="finance-account-detail"),
    path("periods/", FiscalPeriodListView.as_view(), name="finance-period-list"),
    path("posting-window/", PostingWindowView.as_view(), name="finance-posting-window"),
    path("fiscal-years/", FiscalYearListView.as_view(), name="finance-fiscal-year-list"),
    path("fiscal-years/<int:id>/close/", FiscalYearCloseView.as_view(), name="finance-fiscal-year-close"),
    path("fiscal-years/<int:id>/reopen/", FiscalYearReopenView.as_view(), name="finance-fiscal-year-reopen"),
    path("journals/", JournalEntryListView.as_view(), name="finance-journal-list"),
    path("journals/summary/", JournalSummaryView.as_view(), name="finance-journal-summary"),
    path("journals/<int:id>/", JournalEntryDetailView.as_view(), name="finance-journal-detail"),
    path("customers/", CustomerListCreateView.as_view(), name="finance-customer-list"),
    path("customers/summary/", CustomerSummaryView.as_view(), name="finance-customer-summary"),
    path("customers/opening/", CustomerOpeningInvoiceImportView.as_view(),
         name="finance-customer-opening-import"),
    path("customers/<str:pk>/", CustomerDetailView.as_view(), name="finance-customer-detail"),
    path("customers/<str:pk>/receipt/", CustomerReceiptView.as_view(), name="finance-customer-receipt"),
    path("payments/", PaymentListView.as_view(), name="finance-payment-list"),
    path("payments/summary/", PaymentSummaryView.as_view(), name="finance-payment-summary"),
    path("payments/<int:pk>/", PaymentDetailView.as_view(), name="finance-payment-detail"),
    path("payments/<int:pk>/receipt/", PaymentReceiptView.as_view(), name="finance-payment-receipt"),
    path("payments/<int:pk>/allocate/", PaymentAllocateView.as_view(), name="finance-payment-allocate"),
    path("payments/<int:pk>/void/", PaymentVoidView.as_view(), name="finance-payment-void"),
    path("fee-structures/", FeeStructureListCreateView.as_view(), name="finance-fee-structure-list"),
    path("fee-structures/<str:pk>/", FeeStructureDetailView.as_view(), name="finance-fee-structure-detail"),
    path("fee-structures/<str:pk>/generate/", FeeStructureGenerateView.as_view(), name="finance-fee-structure-generate"),
    path("fee-structures/<str:pk>/duplicate/", FeeStructureDuplicateView.as_view(), name="finance-fee-structure-duplicate"),
    path("fee-structures/<str:pk>/items/<int:item_pk>/assignments/", FeeItemAssignmentView.as_view(),
         name="finance-fee-item-assignments"),
    path("invoices/", InvoiceListCreateView.as_view(), name="finance-invoice-list"),
    path("invoices/summary/", InvoiceSummaryView.as_view(), name="finance-invoice-summary"),
    path("invoices/<int:pk>/", InvoiceDetailView.as_view(), name="finance-invoice-detail"),
    path("invoices/<int:pk>/document/", InvoiceDocumentView.as_view(), name="finance-invoice-document"),
    path("invoices/<int:pk>/pay/", InvoicePayView.as_view(), name="finance-invoice-pay"),
    path("invoices/<int:pk>/remind/", InvoiceRemindView.as_view(), name="finance-invoice-remind"),
    path("invoices/<int:pk>/revoke-pay-link/", InvoiceRevokePayLinkView.as_view(),
         name="finance-invoice-revoke-pay-link"),
    # Customer document email: GET previews recipients and lists history, POST sends.
    path("invoices/<int:pk>/email/", InvoiceEmailView.as_view(), name="finance-invoice-email"),
    path("payments/<int:pk>/email/", PaymentEmailView.as_view(), name="finance-payment-email"),
    path("customers/<str:pk>/statement-email/", CustomerStatementEmailView.as_view(),
         name="finance-customer-statement-email"),
    path("document-deliveries/<int:pk>/retry/", FinanceDeliveryRetryView.as_view(),
         name="finance-document-delivery-retry"),
    path("invoices/<int:pk>/void/", InvoiceVoidView.as_view(), name="finance-invoice-void"),

    # AR adjustments - credit/debit notes, refunds, write-offs
    path("credit-notes/", CreditNoteListCreateView.as_view(), name="finance-creditnote-list"),
    path("credit-notes/<int:pk>/", CreditNoteDetailView.as_view(), name="finance-creditnote-detail"),
    path("credit-notes/<int:pk>/submit/", CreditNoteSubmitView.as_view(), name="finance-creditnote-submit"),
    path("credit-notes/<int:pk>/post/", CreditNotePostView.as_view(), name="finance-creditnote-post"),
    path("credit-notes/<int:pk>/allocate/", CreditNoteAllocateView.as_view(),
         name="finance-creditnote-allocate"),
    path("credit-notes/<int:pk>/void/", CreditNoteVoidView.as_view(),
         name="finance-creditnote-void"),
    path("refunds/availability/", RefundAvailabilityView.as_view(),
         name="finance-refund-availability"),
    path("refunds/", RefundListCreateView.as_view(), name="finance-refund-list"),
    path("refunds/<int:pk>/", RefundDetailView.as_view(), name="finance-refund-detail"),
    path("refunds/<int:pk>/submit/", RefundSubmitView.as_view(), name="finance-refund-submit"),
    path("refunds/<int:pk>/post/", RefundPostView.as_view(), name="finance-refund-post"),
    path("refunds/<int:pk>/void/", RefundVoidView.as_view(), name="finance-refund-void"),
    path("write-offs/", WriteOffRequestListCreateView.as_view(), name="finance-writeoff-list"),
    path("write-offs/<int:pk>/", WriteOffRequestDetailView.as_view(), name="finance-writeoff-detail"),
    path("write-offs/<int:pk>/submit/", WriteOffRequestSubmitView.as_view(), name="finance-writeoff-submit"),
    path("write-offs/<int:pk>/post/", WriteOffRequestPostView.as_view(), name="finance-writeoff-post"),
    path("write-offs/<int:pk>/recover/", WriteOffRecoverView.as_view(),
         name="finance-writeoff-recover"),
    # Receivables accruals - deferred income, doubtful-debt provision, deposits
    path("deferred-income/", DeferredIncomeView.as_view(), name="finance-deferred-income"),
    path("deferred-income/release/", DeferredIncomeReleaseView.as_view(),
         name="finance-deferred-income-release"),
    path("deferred-income/reverse/", DeferredIncomeReverseView.as_view(),
         name="finance-deferred-income-reverse"),
    path("provisions/", DoubtfulDebtProvisionListCreateView.as_view(),
         name="finance-provision-list"),
    path("provisions/<int:pk>/", DoubtfulDebtProvisionDetailView.as_view(),
         name="finance-provision-detail"),
    path("provisions/<int:pk>/submit/", DoubtfulDebtProvisionSubmitView.as_view(),
         name="finance-provision-submit"),
    path("provisions/<int:pk>/post/", DoubtfulDebtProvisionPostView.as_view(),
         name="finance-provision-post"),
    path("deposits/", CustomerDepositListView.as_view(), name="finance-deposit-list"),
    path("deposits/release/", CustomerDepositReleaseView.as_view(),
         name="finance-deposit-release"),
    path("deposits/forfeit/", CustomerDepositForfeitView.as_view(),
         name="finance-deposit-forfeit"),
    path("invoices/<int:pk>/write-off/", InvoiceWriteOffView.as_view(), name="finance-invoice-writeoff"),
    path("ar-adjustments/batch/", ARAdjustmentBatchView.as_view(), name="finance-ar-adjustment-batch"),
    path("ar-adjustments/", ARAdjustmentListView.as_view(), name="finance-ar-adjustments"),

    # Customer credit transfers - the approved way credit moves between customers
    path("credit-transfers/", CustomerCreditTransferListCreateView.as_view(),
         name="finance-credit-transfer-list"),
    path("credit-transfers/<int:pk>/", CustomerCreditTransferDetailView.as_view(),
         name="finance-credit-transfer-detail"),
    path("credit-transfers/<int:pk>/submit/", CustomerCreditTransferSubmitView.as_view(),
         name="finance-credit-transfer-submit"),
    path("credit-transfers/<int:pk>/void/", CustomerCreditTransferVoidView.as_view(),
         name="finance-credit-transfer-void"),
    # Concessions - discounts / waivers / scholarships
    path("concessions/", ConcessionListCreateView.as_view(), name="finance-concession-list"),
    path("concessions/summary/", ConcessionSummaryView.as_view(), name="finance-concession-summary"),
    path("concessions/<int:pk>/", ConcessionDetailView.as_view(), name="finance-concession-detail"),
    path("concessions/<int:pk>/submit/", ConcessionSubmitView.as_view(), name="finance-concession-submit"),
    path("concessions/<int:pk>/post/", ConcessionPostView.as_view(), name="finance-concession-post"),
    path("concessions/<int:pk>/void/", ConcessionVoidView.as_view(), name="finance-concession-void"),

    # Installment payment plans
    path("payment-plans/", PaymentPlanListCreateView.as_view(), name="finance-paymentplan-list"),
    path("payment-plans/<int:pk>/", PaymentPlanDetailView.as_view(), name="finance-paymentplan-detail"),
    path("payment-plans/<int:pk>/activate/", PaymentPlanActivateView.as_view(),
         name="finance-paymentplan-activate"),
    path("payment-plans/<int:pk>/refresh/", PaymentPlanRefreshView.as_view(),
         name="finance-paymentplan-refresh"),
    path("payment-plans/<int:pk>/cancel/", PaymentPlanCancelView.as_view(),
         name="finance-paymentplan-cancel"),

    # Dunning - policies + automated reminder notices
    path("dunning-policies/", DunningPolicyListCreateView.as_view(), name="finance-dunning-policy-list"),
    path("dunning-policies/<int:pk>/", DunningPolicyDetailView.as_view(),
         name="finance-dunning-policy-detail"),
    path("dunning/generate/", DunningGenerateView.as_view(), name="finance-dunning-generate"),
    path("dunning/summary/", DunningSummaryView.as_view(), name="finance-dunning-summary"),
    path("dunning-notices/", DunningNoticeListCreateView.as_view(), name="finance-dunning-notice-list"),
    path("dunning-notices/<int:pk>/", DunningNoticeDetailView.as_view(),
         name="finance-dunning-notice-detail"),
    path("dunning-notices/<int:pk>/send/", DunningNoticeSendView.as_view(),
         name="finance-dunning-notice-send"),
    path("dunning-notices/<int:pk>/cancel/", DunningNoticeCancelView.as_view(),
         name="finance-dunning-notice-cancel"),

    # Actions
    path("journals/<int:id>/submit/", JournalSubmitView.as_view(), name="finance-journal-submit"),
    path("journals/<int:id>/post/", JournalPostView.as_view(), name="finance-journal-post"),
    path("journals/<int:id>/reverse/", JournalReverseView.as_view(), name="finance-journal-reverse"),
    path("direct-entries/", DirectEntryCreateView.as_view(), name="finance-direct-entry-create"),
    path("periods/<int:id>/checklist/", PeriodCloseView.as_view(), name="finance-period-checklist"),
    path("periods/<int:id>/close/", PeriodCloseView.as_view(), name="finance-period-close"),
    path("periods/<int:id>/reopen/", PeriodReopenView.as_view(), name="finance-period-reopen"),
    path("periods/<int:id>/lock/", PeriodLockView.as_view(), name="finance-period-lock"),

    # Reports / financial statements
    path("reports/dashboard/", FinanceDashboardView.as_view(), name="finance-dashboard"),
    path("reports/dashboard/receivables/", FinanceReceivablesDashboardView.as_view(),
         name="finance-dashboard-receivables"),
    path("reports/dashboard/spend/", FinanceSpendDashboardView.as_view(),
         name="finance-dashboard-spend"),
    path("reports/trial-balance/", TrialBalanceView.as_view(), name="finance-trial-balance"),
    path("reports/income-statement/", IncomeStatementView.as_view(), name="finance-income-statement"),
    path("reports/balance-sheet/", BalanceSheetView.as_view(), name="finance-balance-sheet"),
    path("reports/cash-flow/", CashFlowView.as_view(), name="finance-cash-flow"),
    path("reports/analytics-slice/", AnalyticsSliceView.as_view(), name="finance-analytics-slice"),
    path("reports/changes-in-equity/", ChangesInEquityView.as_view(), name="finance-changes-in-equity"),
    path("reports/statutory-pack/", StatutoryPackView.as_view(), name="finance-statutory-pack"),
    path("reports/ar-aging/", ARAgingView.as_view(), name="finance-ar-aging"),
    path("reports/ar-reconciliation/", ARReconciliationView.as_view(), name="finance-ar-reconciliation"),
    path("reports/customer-statement/", CustomerStatementView.as_view(), name="finance-customer-statement"),

    # Setup / reference data (currencies + FX rates are GLOBAL - no ?entity)
    path("currencies/", CurrencyListCreateView.as_view(), name="finance-currency-list"),
    path("fx-rates/", FxRateListCreateView.as_view(), name="finance-fxrate-list"),
    path("tax-codes/", TaxCodeListCreateView.as_view(), name="finance-taxcode-list"),
    path("cost-centers/", CostCenterListCreateView.as_view(), name="finance-costcenter-list"),
    path("dimensions/", DimensionListCreateView.as_view(), name="finance-dimension-list"),

    # Banking + reconciliation
    path("bank-accounts/", BankAccountListCreateView.as_view(), name="finance-bank-list"),
    path("bank-accounts/<int:pk>/", BankAccountDetailView.as_view(), name="finance-bank-detail"),
    path("bank-transactions/", BankTransactionListCreateView.as_view(),
         name="finance-bank-transaction-list"),
    path("bank-transactions/<int:pk>/", BankTransactionDetailView.as_view(),
         name="finance-bank-transaction-detail"),
    path("bank-transactions/<int:pk>/void/", BankTransactionVoidView.as_view(),
         name="finance-bank-transaction-void"),
    path("bank-transfers/", BankTransferListCreateView.as_view(),
         name="finance-bank-transfer-list"),
    path("bank-transfers/<int:pk>/", BankTransferDetailView.as_view(),
         name="finance-bank-transfer-detail"),
    path("bank-transfers/<int:pk>/void/", BankTransferVoidView.as_view(),
         name="finance-bank-transfer-void"),
    path("inter-branch-transfers/", InterBranchTransferListCreateView.as_view(),
         name="finance-inter-branch-transfer-list"),
    path("inter-branch-transfers/requests/", InterBranchRequestView.as_view(),
         name="finance-inter-branch-transfer-request"),
    path("inter-branch-transfers/receivable-moves/", InterBranchReceivableMoveView.as_view(),
         name="finance-inter-branch-receivable-move"),
    path("inter-branch-transfers/<int:pk>/", InterBranchTransferDetailView.as_view(),
         name="finance-inter-branch-transfer-detail"),
    path("inter-branch-transfers/<int:pk>/send/", InterBranchSendView.as_view(),
         name="finance-inter-branch-transfer-send"),
    path("inter-branch-transfers/<int:pk>/decline/", InterBranchDeclineView.as_view(),
         name="finance-inter-branch-transfer-decline"),
    path("inter-branch-transfers/<int:pk>/confirm/", InterBranchConfirmView.as_view(),
         name="finance-inter-branch-transfer-confirm"),
    path("inter-branch-transfers/<int:pk>/void/", InterBranchVoidView.as_view(),
         name="finance-inter-branch-transfer-void"),
    path("inter-branch-balances/", InterBranchBalancesView.as_view(),
         name="finance-inter-branch-balances"),
    path("held-receipts/", HeldReceiptListCreateView.as_view(),
         name="finance-held-receipt-list"),
    path("held-receipts/<int:pk>/", HeldReceiptDetailView.as_view(),
         name="finance-held-receipt-detail"),
    path("held-receipts/<int:pk>/forward/", HeldReceiptForwardView.as_view(),
         name="finance-held-receipt-forward"),
    path("held-receipts/<int:pk>/void/", HeldReceiptVoidView.as_view(),
         name="finance-held-receipt-void"),
    path("recharges/", RechargeListCreateView.as_view(), name="finance-recharge-list"),
    path("recharges/<int:pk>/", RechargeDetailView.as_view(), name="finance-recharge-detail"),
    path("recharges/<int:pk>/void/", RechargeVoidView.as_view(), name="finance-recharge-void"),
    path("shared-cost-rules/", SharedCostRuleListCreateView.as_view(),
         name="finance-shared-cost-rule-list"),
    path("shared-cost-rules/<int:pk>/", SharedCostRuleDetailView.as_view(),
         name="finance-shared-cost-rule-detail"),
    path("bank-accounts/<int:pk>/statement-lines/", BankStatementLineView.as_view(),
         name="finance-bank-statement-lines"),
    path("bank-accounts/<int:pk>/statements/<int:statement_id>/",
         BankStatementDetailView.as_view(),
         name="finance-bank-statement-detail"),
    path("bank-accounts/<int:pk>/statement-imports/template/",
         BankStatementImportTemplateView.as_view(),
         name="finance-bank-statement-import-template"),
    path("bank-accounts/<int:pk>/statement-imports/",
         BankStatementImportWizardView.as_view(),
         name="finance-bank-statement-import-wizard"),
    path("bank-accounts/<int:pk>/auto-reconcile/", BankAutoReconcileView.as_view(),
         name="finance-bank-auto-reconcile"),
    path("bank-accounts/<int:pk>/book-lines/", BankBookLinesView.as_view(),
         name="finance-bank-book-lines"),
    path("bank-accounts/<int:pk>/split-match/", BankSplitMatchView.as_view(),
         name="finance-bank-split-match"),
    path("bank-accounts/<int:pk>/reconcile/complete/", BankReconcileCompleteView.as_view(),
         name="finance-bank-reconcile-complete"),
    path("statement-lines/<int:pk>/match/", BankStatementLineMatchView.as_view(),
         name="finance-statement-line-match"),
    path("statement-lines/<int:pk>/", BankStatementLineDetailView.as_view(),
         name="finance-statement-line-detail"),
    path("statement-lines/<int:pk>/match-group/", BankStatementLineGroupMatchView.as_view(),
         name="finance-statement-line-match-group"),
    path("statement-lines/<int:pk>/adjust/", BankStatementLineAdjustView.as_view(),
         name="finance-statement-line-adjust"),
    path("statement-lines/<int:pk>/unmatch/", BankStatementLineUnmatchView.as_view(),
         name="finance-statement-line-unmatch"),
    path("statement-lines/<int:pk>/ignore/", BankStatementLineIgnoreView.as_view(),
         name="finance-statement-line-ignore"),

    # Expense claims
    path("expense-claims/", ExpenseClaimListCreateView.as_view(), name="finance-expense-list"),
    path("expense-claims/summary/", ExpenseClaimSummaryView.as_view(), name="finance-expense-summary"),
    path("expense-claims/<int:pk>/", ExpenseClaimDetailView.as_view(), name="finance-expense-detail"),
    path("expense-claims/<int:pk>/post/", ExpenseClaimPostView.as_view(), name="finance-expense-post"),
    path("expense-claims/<int:pk>/submit/", ExpenseClaimSubmitView.as_view(), name="finance-expense-submit"),
    path("expense-claims/<int:pk>/reject/", ExpenseClaimRejectView.as_view(), name="finance-expense-reject"),
    path("expense-claims/<int:pk>/settle/", ExpenseClaimSettleView.as_view(), name="finance-expense-settle"),
    path("expense-claims/<int:pk>/void/", ExpenseClaimVoidView.as_view(), name="finance-expense-void"),
    path("expense-claims/<int:pk>/lines/<int:line_id>/receipt/", ExpenseClaimReceiptView.as_view(),
         name="finance-expense-line-receipt"),

    # Petty cash - funds, vouchers, replenishment
    path("petty-cash-funds/", PettyCashFundListCreateView.as_view(), name="finance-pettycash-fund-list"),
    path("petty-cash-funds/<int:pk>/", PettyCashFundDetailView.as_view(),
         name="finance-pettycash-fund-detail"),
    path("petty-cash-funds/<int:pk>/establish/", PettyCashFundEstablishView.as_view(),
         name="finance-pettycash-fund-establish"),
    path("petty-cash-funds/<int:pk>/replenish/", PettyCashFundReplenishView.as_view(),
         name="finance-pettycash-fund-replenish"),
    path("petty-cash-status/", PettyCashStatusView.as_view(), name="finance-pettycash-status"),
    path("petty-cash-vouchers/", PettyCashVoucherListCreateView.as_view(),
         name="finance-pettycash-voucher-list"),
    path("petty-cash-vouchers/<int:pk>/", PettyCashVoucherDetailView.as_view(),
         name="finance-pettycash-voucher-detail"),
    path("petty-cash-vouchers/<int:pk>/post/", PettyCashVoucherPostView.as_view(),
         name="finance-pettycash-voucher-post"),
    path("petty-cash-vouchers/<int:pk>/void/", PettyCashVoucherVoidView.as_view(),
         name="finance-pettycash-voucher-void"),
    # Petty cash - counting the tin and banking its cash
    path("petty-cash-vouchers/<int:pk>/cancel/", PettyCashVoucherCancelView.as_view(),
         name="finance-pettycash-voucher-cancel"),
    path("petty-cash-funds/<int:pk>/reduce/", PettyCashFundReduceView.as_view(),
         name="finance-pettycash-fund-reduce"),
    path("petty-cash-funds/<int:pk>/close/", PettyCashFundCloseView.as_view(),
         name="finance-pettycash-fund-close"),
    path("petty-cash-funds/<int:pk>/reopen/", PettyCashFundReopenView.as_view(),
         name="finance-pettycash-fund-reopen"),
    path("petty-cash-returns/", PettyCashReturnListView.as_view(),
         name="finance-pettycash-return-list"),
    path("petty-cash-returns/<int:pk>/", PettyCashReturnDetailView.as_view(),
         name="finance-pettycash-return-detail"),
    path("petty-cash-returns/<int:pk>/void/", PettyCashReturnVoidView.as_view(),
         name="finance-pettycash-return-void"),

    # Tax remittance / filing
    path("tax-obligations/", TaxObligationListCreateView.as_view(), name="finance-tax-obligation-list"),
    path("tax-obligations/<int:pk>/", TaxObligationDetailView.as_view(),
         name="finance-tax-obligation-detail"),
    path("tax-obligations/outstanding/", TaxObligationOutstandingView.as_view(),
         name="finance-tax-outstanding"),
    path("tax-filings/", TaxFilingListCreateView.as_view(), name="finance-tax-filing-list"),
    path("tax-filings/summary/", TaxFilingSummaryView.as_view(), name="finance-tax-filing-summary"),
    path("tax-filings/<int:pk>/", TaxFilingDetailView.as_view(), name="finance-tax-filing-detail"),
    path("tax-filings/<int:pk>/file/", TaxFilingFileView.as_view(), name="finance-tax-filing-file"),
    path("tax-filings/<int:pk>/unfile/", TaxFilingUnfileView.as_view(), name="finance-tax-filing-unfile"),
    path("tax-filings/<int:pk>/pay/", TaxFilingPayView.as_view(), name="finance-tax-filing-pay"),
    path("tax-filings/<int:pk>/schedule/", TaxFilingScheduleView.as_view(),
         name="finance-tax-filing-schedule"),
    path("tax-filings/<int:pk>/remittances/<int:remittance_pk>/reverse/",
         TaxRemittanceReverseView.as_view(), name="finance-tax-remittance-reverse"),

    # Payroll
    path("payroll-runs/", PayrollRunListCreateView.as_view(), name="finance-payroll-list"),
    path("payroll-runs/summary/", PayrollRunSummaryView.as_view(), name="finance-payroll-summary"),
    path("payroll-runs/generate/", PayrollRunGenerateView.as_view(), name="finance-payroll-generate"),
    path("employee-salaries/", EmployeeSalaryListCreateView.as_view(), name="finance-employee-salary-list"),
    path("employee-salaries/<int:pk>/", EmployeeSalaryDetailView.as_view(), name="finance-employee-salary-detail"),
    path("salary-structures/", SalaryStructureListCreateView.as_view(), name="finance-salary-structure-list"),
    path("salary-structures/<int:pk>/", SalaryStructureDetailView.as_view(), name="finance-salary-structure-detail"),
    path("payroll-runs/<int:pk>/", PayrollRunDetailView.as_view(), name="finance-payroll-detail"),
    path("payroll-runs/<int:pk>/post/", PayrollRunPostView.as_view(), name="finance-payroll-post"),
    path("payroll-runs/<int:pk>/pay/", PayrollRunPayView.as_view(), name="finance-payroll-pay"),
    path("payroll-runs/<int:pk>/cancel/", PayrollRunCancelView.as_view(), name="finance-payroll-cancel"),
    path("payroll-runs/<int:pk>/lines/<int:line_pk>/payslip/", PayrollLinePayslipView.as_view(),
         name="finance-payroll-line-payslip"),
    path("employee-salaries/<int:pk>/history/", EmployeeSalaryHistoryView.as_view(),
         name="finance-employee-salary-history"),
    path("employee-salaries/<int:pk>/deductions/", EmployeeDeductionListCreateView.as_view(),
         name="finance-employee-deduction-list"),
    path("employee-salaries/<int:pk>/tax-summary/", EmployeeSalaryTaxSummaryView.as_view(),
         name="finance-employee-salary-tax-summary"),
    path("employee-deductions/<int:pk>/", EmployeeDeductionDetailView.as_view(),
         name="finance-employee-deduction-detail"),
    path("salary-structures/<int:pk>/history/", SalaryStructureHistoryView.as_view(),
         name="finance-salary-structure-history"),
    path("payroll/deduction-types/", PayrollDeductionTypeListCreateView.as_view(),
         name="finance-payroll-deduction-type-list"),
    path("payroll/deduction-types/<int:pk>/", PayrollDeductionTypeDetailView.as_view(),
         name="finance-payroll-deduction-type-detail"),
    path("payroll/tax-tables/", PayeTaxTableListCreateView.as_view(),
         name="finance-paye-tax-table-list"),
    path("payroll/tax-tables/<int:pk>/", PayeTaxTableDetailView.as_view(),
         name="finance-paye-tax-table-detail"),
    path("payroll/tax-states/", TaxJurisdictionListCreateView.as_view(),
         name="finance-tax-jurisdiction-list"),
    path("payroll/tax-states/<int:pk>/", TaxJurisdictionDetailView.as_view(),
         name="finance-tax-jurisdiction-detail"),
    path("payroll/pension-fund-administrators/", PensionFundAdministratorListCreateView.as_view(),
         name="finance-pfa-list"),
    path("payroll/pension-fund-administrators/<int:pk>/", PensionFundAdministratorDetailView.as_view(),
         name="finance-pfa-detail"),
    path("my-payslips/", MyPayslipListView.as_view(), name="finance-my-payslips"),
    path("my-payslips/<int:pk>/", MyPayslipDetailView.as_view(), name="finance-my-payslip-detail"),
    path("my-tax-summary/", MyTaxSummaryView.as_view(), name="finance-my-tax-summary"),

    # Budgets
    path("budgets/", BudgetListCreateView.as_view(), name="finance-budget-list"),
    path("budgets/rollup/", BudgetRollupView.as_view(), name="finance-budget-rollup"),
    path("budgets/<int:pk>/", BudgetDetailView.as_view(), name="finance-budget-detail"),
    path("budgets/<int:pk>/lines/", BudgetLineCreateView.as_view(), name="finance-budget-line"),
    path("budgets/<int:pk>/lines/<int:line_id>/", BudgetLineDetailView.as_view(), name="finance-budget-line-detail"),
    path("budgets/<int:pk>/approve/", BudgetApproveView.as_view(), name="finance-budget-approve"),
    path("budgets/<int:pk>/variance/", BudgetVarianceView.as_view(), name="finance-budget-variance"),
    path("budgets/<int:pk>/heatmap/", BudgetHeatmapView.as_view(), name="finance-budget-heatmap"),

    # Fixed assets
    path("fixed-assets/", FixedAssetListCreateView.as_view(), name="finance-asset-list"),
    path("fixed-assets/summary/", FixedAssetSummaryView.as_view(), name="finance-asset-summary"),
    path("fixed-assets/run-depreciation/", FixedAssetRunDepreciationView.as_view(), name="finance-asset-run-depreciation"),
    path("fixed-assets/<int:pk>/", FixedAssetDetailView.as_view(), name="finance-asset-detail"),
    path("fixed-assets/<int:pk>/acquire/", FixedAssetAcquireView.as_view(), name="finance-asset-acquire"),
    path("fixed-assets/<int:pk>/depreciate/", FixedAssetDepreciateView.as_view(),
         name="finance-asset-depreciate"),
    path("fixed-assets/<int:pk>/dispose/", FixedAssetDisposeView.as_view(), name="finance-asset-dispose"),

    # Audit trail
    path("audit-logs/", FinanceAuditLogListView.as_view(), name="finance-audit-list"),
    path("audit-logs/facets/", FinanceAuditFacetsView.as_view(), name="finance-audit-facets"),
    path("audit-logs/<int:pk>/", FinanceAuditLogDetailView.as_view(), name="finance-audit-detail"),
]
