"""URL routes for the vs_finance REST API (mounted at ``/v1/finance/``).

Families: entity-scoped master-data / document lists + actions, the financial-statement
reports, and the operational/setup surface (reference data, banking, expense claims,
payroll, budgets, fixed assets, audit) wired from :mod:`vs_finance.views_ops`. Every
endpoint expects ``?entity=<id or code>`` — except the **global** currency/FX routes.
"""
from django.urls import path

from .views import (
    AccountDetailView,
    AccountListCreateView,
    ARAgingView,
    ARReconciliationView,
    BalanceSheetView,
    CashFlowView,
    ChangesInEquityView,
    DirectEntryCreateView,
    EntityListCreateView,
    FinanceDashboardView,
    FiscalPeriodListView,
    FiscalYearListView,
    IncomeStatementView,
    InvoiceDetailView,
    InvoiceListView,
    InvoiceSummaryView,
    JournalEntryDetailView,
    JournalEntryListView,
    JournalSummaryView,
    JournalPostView,
    JournalReverseView,
    PeriodCloseView,
    StatutoryPackView,
    TrialBalanceView,
)
from .views_ar import (
    ConcessionDetailView,
    ConcessionListCreateView,
    ConcessionPostView,
    ConcessionSummaryView,
    CreditNoteAllocateView,
    CreditNoteDetailView,
    CreditNoteListCreateView,
    CreditNotePostView,
    CustomerDetailView,
    CustomerListCreateView,
    CustomerReceiptView,
    PaymentAllocateView,
    PaymentDetailView,
    PaymentListView,
    CustomerStatementView,
    FeeStructureDetailView,
    FeeStructureDuplicateView,
    FeeStructureGenerateView,
    FeeStructureListCreateView,
    DunningGenerateView,
    DunningSummaryView,
    DunningNoticeCancelView,
    DunningNoticeDetailView,
    DunningNoticeListCreateView,
    DunningNoticeSendView,
    DunningPolicyDetailView,
    DunningPolicyListCreateView,
    InvoicePayView,
    InvoiceRemindView,
    InvoiceWriteOffView,
    ARAdjustmentListView,
    PaymentPlanActivateView,
    PaymentPlanCancelView,
    PaymentPlanDetailView,
    PaymentPlanListCreateView,
    PaymentPlanRefreshView,
    RefundDetailView,
    RefundListCreateView,
    RefundPostView,
)
from .views_ops import (
    BankAccountDetailView,
    BankAccountListCreateView,
    BankAutoReconcileView,
    BankBookLinesView,
    BankReconcileCompleteView,
    BankStatementLineAdjustView,
    BankStatementLineMatchView,
    BankStatementLineUnmatchView,
    BankStatementLineView,
    BudgetApproveView,
    BudgetDetailView,
    BudgetHeatmapView,
    BudgetLineCreateView,
    BudgetLineDetailView,
    BudgetListCreateView,
    BudgetVarianceView,
    CostCenterListCreateView,
    CurrencyListCreateView,
    DimensionListCreateView,
    ExpenseClaimDetailView,
    ExpenseClaimListCreateView,
    ExpenseClaimPostView,
    ExpenseClaimReceiptView,
    ExpenseClaimRejectView,
    ExpenseClaimSettleView,
    FinanceAuditLogListView,
    FixedAssetAcquireView,
    FixedAssetDepreciateView,
    FixedAssetDetailView,
    FixedAssetListCreateView,
    FxRateListCreateView,
    EmployeeSalaryDetailView,
    EmployeeSalaryListCreateView,
    PayrollRunDetailView,
    PayrollRunGenerateView,
    PayrollRunListCreateView,
    PayrollRunPayView,
    PayrollRunPostView,
    SalaryStructureDetailView,
    SalaryStructureListCreateView,
    PettyCashFundDetailView,
    PettyCashFundEstablishView,
    PettyCashFundListCreateView,
    PettyCashFundReplenishView,
    PettyCashStatusView,
    PettyCashVoucherDetailView,
    PettyCashVoucherListCreateView,
    PettyCashVoucherPostView,
    TaxCodeListCreateView,
    TaxFilingDetailView,
    TaxFilingFileView,
    TaxFilingListCreateView,
    TaxFilingPayView,
    TaxObligationDetailView,
    TaxObligationListCreateView,
    TaxObligationOutstandingView,
)

urlpatterns = [
    # Master data + documents
    path("entities/", EntityListCreateView.as_view(), name="finance-entity-list"),
    path("accounts/", AccountListCreateView.as_view(), name="finance-account-list"),
    path("accounts/<int:pk>/", AccountDetailView.as_view(), name="finance-account-detail"),
    path("periods/", FiscalPeriodListView.as_view(), name="finance-period-list"),
    path("fiscal-years/", FiscalYearListView.as_view(), name="finance-fiscal-year-list"),
    path("journals/", JournalEntryListView.as_view(), name="finance-journal-list"),
    path("journals/summary/", JournalSummaryView.as_view(), name="finance-journal-summary"),
    path("journals/<int:id>/", JournalEntryDetailView.as_view(), name="finance-journal-detail"),
    path("customers/", CustomerListCreateView.as_view(), name="finance-customer-list"),
    path("customers/<str:pk>/", CustomerDetailView.as_view(), name="finance-customer-detail"),
    path("customers/<str:pk>/receipt/", CustomerReceiptView.as_view(), name="finance-customer-receipt"),
    path("payments/", PaymentListView.as_view(), name="finance-payment-list"),
    path("payments/<int:pk>/", PaymentDetailView.as_view(), name="finance-payment-detail"),
    path("payments/<int:pk>/allocate/", PaymentAllocateView.as_view(), name="finance-payment-allocate"),
    path("fee-structures/", FeeStructureListCreateView.as_view(), name="finance-fee-structure-list"),
    path("fee-structures/<str:pk>/", FeeStructureDetailView.as_view(), name="finance-fee-structure-detail"),
    path("fee-structures/<str:pk>/generate/", FeeStructureGenerateView.as_view(), name="finance-fee-structure-generate"),
    path("fee-structures/<str:pk>/duplicate/", FeeStructureDuplicateView.as_view(), name="finance-fee-structure-duplicate"),
    path("invoices/", InvoiceListView.as_view(), name="finance-invoice-list"),
    path("invoices/summary/", InvoiceSummaryView.as_view(), name="finance-invoice-summary"),
    path("invoices/<int:pk>/", InvoiceDetailView.as_view(), name="finance-invoice-detail"),
    path("invoices/<int:pk>/pay/", InvoicePayView.as_view(), name="finance-invoice-pay"),
    path("invoices/<int:pk>/remind/", InvoiceRemindView.as_view(), name="finance-invoice-remind"),

    # AR adjustments — credit/debit notes, refunds, write-offs
    path("credit-notes/", CreditNoteListCreateView.as_view(), name="finance-creditnote-list"),
    path("credit-notes/<int:pk>/", CreditNoteDetailView.as_view(), name="finance-creditnote-detail"),
    path("credit-notes/<int:pk>/post/", CreditNotePostView.as_view(), name="finance-creditnote-post"),
    path("credit-notes/<int:pk>/allocate/", CreditNoteAllocateView.as_view(),
         name="finance-creditnote-allocate"),
    path("refunds/", RefundListCreateView.as_view(), name="finance-refund-list"),
    path("refunds/<int:pk>/", RefundDetailView.as_view(), name="finance-refund-detail"),
    path("refunds/<int:pk>/post/", RefundPostView.as_view(), name="finance-refund-post"),
    path("invoices/<int:pk>/write-off/", InvoiceWriteOffView.as_view(), name="finance-invoice-writeoff"),
    path("ar-adjustments/", ARAdjustmentListView.as_view(), name="finance-ar-adjustments"),

    # Concessions — discounts / waivers / scholarships
    path("concessions/", ConcessionListCreateView.as_view(), name="finance-concession-list"),
    path("concessions/summary/", ConcessionSummaryView.as_view(), name="finance-concession-summary"),
    path("concessions/<int:pk>/", ConcessionDetailView.as_view(), name="finance-concession-detail"),
    path("concessions/<int:pk>/post/", ConcessionPostView.as_view(), name="finance-concession-post"),

    # Installment payment plans
    path("payment-plans/", PaymentPlanListCreateView.as_view(), name="finance-paymentplan-list"),
    path("payment-plans/<int:pk>/", PaymentPlanDetailView.as_view(), name="finance-paymentplan-detail"),
    path("payment-plans/<int:pk>/activate/", PaymentPlanActivateView.as_view(),
         name="finance-paymentplan-activate"),
    path("payment-plans/<int:pk>/refresh/", PaymentPlanRefreshView.as_view(),
         name="finance-paymentplan-refresh"),
    path("payment-plans/<int:pk>/cancel/", PaymentPlanCancelView.as_view(),
         name="finance-paymentplan-cancel"),

    # Dunning — policies + automated reminder notices
    path("dunning-policies/", DunningPolicyListCreateView.as_view(), name="finance-dunning-policy-list"),
    path("dunning-policies/<int:pk>/", DunningPolicyDetailView.as_view(),
         name="finance-dunning-policy-detail"),
    path("dunning/generate/", DunningGenerateView.as_view(), name="finance-dunning-generate"),
    path("dunning/summary/", DunningSummaryView.as_view(), name="finance-dunning-summary"),
    path("dunning-notices/", DunningNoticeListCreateView.as_view(), name="finance-dunning-notice-list"),
    path("dunning-notices/<int:pk>/", DunningNoticeDetailView.as_view(),
         name="finance-dunning-notice-detail"),
    path("dunning-notices/<int:pk>/send/", DunningNoticeSendView.as_view(),
         name="finance-dunning-notice-send"),
    path("dunning-notices/<int:pk>/cancel/", DunningNoticeCancelView.as_view(),
         name="finance-dunning-notice-cancel"),

    # Actions
    path("journals/<int:id>/post/", JournalPostView.as_view(), name="finance-journal-post"),
    path("journals/<int:id>/reverse/", JournalReverseView.as_view(), name="finance-journal-reverse"),
    path("direct-entries/", DirectEntryCreateView.as_view(), name="finance-direct-entry-create"),
    path("periods/<int:id>/checklist/", PeriodCloseView.as_view(), name="finance-period-checklist"),
    path("periods/<int:id>/close/", PeriodCloseView.as_view(), name="finance-period-close"),

    # Reports / financial statements
    path("reports/dashboard/", FinanceDashboardView.as_view(), name="finance-dashboard"),
    path("reports/trial-balance/", TrialBalanceView.as_view(), name="finance-trial-balance"),
    path("reports/income-statement/", IncomeStatementView.as_view(), name="finance-income-statement"),
    path("reports/balance-sheet/", BalanceSheetView.as_view(), name="finance-balance-sheet"),
    path("reports/cash-flow/", CashFlowView.as_view(), name="finance-cash-flow"),
    path("reports/changes-in-equity/", ChangesInEquityView.as_view(), name="finance-changes-in-equity"),
    path("reports/statutory-pack/", StatutoryPackView.as_view(), name="finance-statutory-pack"),
    path("reports/ar-aging/", ARAgingView.as_view(), name="finance-ar-aging"),
    path("reports/ar-reconciliation/", ARReconciliationView.as_view(), name="finance-ar-reconciliation"),
    path("reports/customer-statement/", CustomerStatementView.as_view(), name="finance-customer-statement"),

    # Setup / reference data (currencies + FX rates are GLOBAL — no ?entity)
    path("currencies/", CurrencyListCreateView.as_view(), name="finance-currency-list"),
    path("fx-rates/", FxRateListCreateView.as_view(), name="finance-fxrate-list"),
    path("tax-codes/", TaxCodeListCreateView.as_view(), name="finance-taxcode-list"),
    path("cost-centers/", CostCenterListCreateView.as_view(), name="finance-costcenter-list"),
    path("dimensions/", DimensionListCreateView.as_view(), name="finance-dimension-list"),

    # Banking + reconciliation
    path("bank-accounts/", BankAccountListCreateView.as_view(), name="finance-bank-list"),
    path("bank-accounts/<int:pk>/", BankAccountDetailView.as_view(), name="finance-bank-detail"),
    path("bank-accounts/<int:pk>/statement-lines/", BankStatementLineView.as_view(),
         name="finance-bank-statement-lines"),
    path("bank-accounts/<int:pk>/auto-reconcile/", BankAutoReconcileView.as_view(),
         name="finance-bank-auto-reconcile"),
    path("bank-accounts/<int:pk>/book-lines/", BankBookLinesView.as_view(),
         name="finance-bank-book-lines"),
    path("bank-accounts/<int:pk>/reconcile/complete/", BankReconcileCompleteView.as_view(),
         name="finance-bank-reconcile-complete"),
    path("statement-lines/<int:pk>/match/", BankStatementLineMatchView.as_view(),
         name="finance-statement-line-match"),
    path("statement-lines/<int:pk>/adjust/", BankStatementLineAdjustView.as_view(),
         name="finance-statement-line-adjust"),
    path("statement-lines/<int:pk>/unmatch/", BankStatementLineUnmatchView.as_view(),
         name="finance-statement-line-unmatch"),

    # Expense claims
    path("expense-claims/", ExpenseClaimListCreateView.as_view(), name="finance-expense-list"),
    path("expense-claims/<int:pk>/", ExpenseClaimDetailView.as_view(), name="finance-expense-detail"),
    path("expense-claims/<int:pk>/post/", ExpenseClaimPostView.as_view(), name="finance-expense-post"),
    path("expense-claims/<int:pk>/reject/", ExpenseClaimRejectView.as_view(), name="finance-expense-reject"),
    path("expense-claims/<int:pk>/settle/", ExpenseClaimSettleView.as_view(), name="finance-expense-settle"),
    path("expense-claims/<int:pk>/lines/<int:line_id>/receipt/", ExpenseClaimReceiptView.as_view(),
         name="finance-expense-line-receipt"),

    # Petty cash — funds, vouchers, replenishment
    path("petty-cash-funds/", PettyCashFundListCreateView.as_view(), name="finance-pettycash-fund-list"),
    path("petty-cash-funds/<int:pk>/", PettyCashFundDetailView.as_view(),
         name="finance-pettycash-fund-detail"),
    path("petty-cash-funds/<int:pk>/establish/", PettyCashFundEstablishView.as_view(),
         name="finance-pettycash-fund-establish"),
    path("petty-cash-funds/<int:pk>/replenish/", PettyCashFundReplenishView.as_view(),
         name="finance-pettycash-fund-replenish"),
    path("petty-cash-status/", PettyCashStatusView.as_view(), name="finance-pettycash-status"),
    path("petty-cash-vouchers/", PettyCashVoucherListCreateView.as_view(),
         name="finance-pettycash-voucher-list"),
    path("petty-cash-vouchers/<int:pk>/", PettyCashVoucherDetailView.as_view(),
         name="finance-pettycash-voucher-detail"),
    path("petty-cash-vouchers/<int:pk>/post/", PettyCashVoucherPostView.as_view(),
         name="finance-pettycash-voucher-post"),

    # Tax remittance / filing
    path("tax-obligations/", TaxObligationListCreateView.as_view(), name="finance-tax-obligation-list"),
    path("tax-obligations/<int:pk>/", TaxObligationDetailView.as_view(),
         name="finance-tax-obligation-detail"),
    path("tax-obligations/outstanding/", TaxObligationOutstandingView.as_view(),
         name="finance-tax-outstanding"),
    path("tax-filings/", TaxFilingListCreateView.as_view(), name="finance-tax-filing-list"),
    path("tax-filings/<int:pk>/", TaxFilingDetailView.as_view(), name="finance-tax-filing-detail"),
    path("tax-filings/<int:pk>/file/", TaxFilingFileView.as_view(), name="finance-tax-filing-file"),
    path("tax-filings/<int:pk>/pay/", TaxFilingPayView.as_view(), name="finance-tax-filing-pay"),

    # Payroll
    path("payroll-runs/", PayrollRunListCreateView.as_view(), name="finance-payroll-list"),
    path("payroll-runs/generate/", PayrollRunGenerateView.as_view(), name="finance-payroll-generate"),
    path("employee-salaries/", EmployeeSalaryListCreateView.as_view(), name="finance-employee-salary-list"),
    path("employee-salaries/<int:pk>/", EmployeeSalaryDetailView.as_view(), name="finance-employee-salary-detail"),
    path("salary-structures/", SalaryStructureListCreateView.as_view(), name="finance-salary-structure-list"),
    path("salary-structures/<int:pk>/", SalaryStructureDetailView.as_view(), name="finance-salary-structure-detail"),
    path("payroll-runs/<int:pk>/", PayrollRunDetailView.as_view(), name="finance-payroll-detail"),
    path("payroll-runs/<int:pk>/post/", PayrollRunPostView.as_view(), name="finance-payroll-post"),
    path("payroll-runs/<int:pk>/pay/", PayrollRunPayView.as_view(), name="finance-payroll-pay"),

    # Budgets
    path("budgets/", BudgetListCreateView.as_view(), name="finance-budget-list"),
    path("budgets/<int:pk>/", BudgetDetailView.as_view(), name="finance-budget-detail"),
    path("budgets/<int:pk>/lines/", BudgetLineCreateView.as_view(), name="finance-budget-line"),
    path("budgets/<int:pk>/lines/<int:line_id>/", BudgetLineDetailView.as_view(), name="finance-budget-line-detail"),
    path("budgets/<int:pk>/approve/", BudgetApproveView.as_view(), name="finance-budget-approve"),
    path("budgets/<int:pk>/variance/", BudgetVarianceView.as_view(), name="finance-budget-variance"),
    path("budgets/<int:pk>/heatmap/", BudgetHeatmapView.as_view(), name="finance-budget-heatmap"),

    # Fixed assets
    path("fixed-assets/", FixedAssetListCreateView.as_view(), name="finance-asset-list"),
    path("fixed-assets/<int:pk>/", FixedAssetDetailView.as_view(), name="finance-asset-detail"),
    path("fixed-assets/<int:pk>/acquire/", FixedAssetAcquireView.as_view(), name="finance-asset-acquire"),
    path("fixed-assets/<int:pk>/depreciate/", FixedAssetDepreciateView.as_view(),
         name="finance-asset-depreciate"),

    # Audit trail
    path("audit-logs/", FinanceAuditLogListView.as_view(), name="finance-audit-list"),
]
