# Generated by Django 5.2.10 on 2026-08-25 07:34

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vs_tenants", "0008_alter_branch_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("is_school_wide", models.BooleanField(db_index=True, default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="academic_sessions",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="AcademicTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("order_index", models.PositiveSmallIntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="vs_academics.academicsession",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="academic_terms",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index"],
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for an item the whole school shares.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vs_tenants.branch",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20)),
                ("order_index", models.PositiveSmallIntegerField(default=0)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for an item the whole school shares.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vs_tenants.branch",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programs",
                        to="vs_academics.department",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index", "name"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=60)),
                ("code", models.CharField(max_length=20)),
                ("order_index", models.PositiveSmallIntegerField()),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for an item the whole school shares.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vs_tenants.branch",
                    ),
                ),
                (
                    "next_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_levels",
                        to="vs_academics.level",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vs_tenants.tenant",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="levels",
                        to="vs_academics.program",
                    ),
                ),
            ],
            options={
                "ordering": ["program", "order_index"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=60)),
                ("code", models.CharField(max_length=20)),
                ("arm", models.CharField(blank=True, default="", max_length=30)),
                ("capacity", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for an item the whole school shares.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vs_tenants.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classes",
                        to="vs_academics.level",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["level", "name"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SessionBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="academic_sessions",
                        to="vs_tenants.branch",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_links",
                        to="vs_academics.academicsession",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="session_branches",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20)),
                ("is_core", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for an item the whole school shares.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vs_tenants.branch",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subjects",
                        to="vs_academics.department",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SubjectOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_core", models.BooleanField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subject_offerings",
                        to="vs_academics.level",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offerings",
                        to="vs_academics.subject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subject_offerings",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="subject",
            name="levels",
            field=models.ManyToManyField(
                related_name="subjects",
                through="vs_academics.SubjectOffering",
                to="vs_academics.level",
            ),
        ),
        migrations.AddIndex(
            model_name="academicsession",
            index=models.Index(
                fields=["tenant", "status"], name="vs_academic_tenant__8011ab_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="academicsession",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("tenant"),
                name="uq_academic_session_tenant_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="academicsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_school_wide", True), ("status", "ACTIVE")),
                fields=("tenant",),
                name="uq_academic_session_one_active_school_wide",
            ),
        ),
        migrations.AddConstraint(
            model_name="academicsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gt", models.F("start_date"))),
                name="ck_academic_session_dates",
            ),
        ),
        migrations.AddConstraint(
            model_name="academicterm",
            constraint=models.UniqueConstraint(
                fields=("session", "order_index"), name="uq_academic_term_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="academicterm",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("session"),
                name="uq_academic_term_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="academicterm",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gt", models.F("start_date"))),
                name="ck_academic_term_dates",
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["tenant", "branch", "is_active"],
                name="vs_academic_tenant__fd7f14_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("tenant"),
                name="uq_academic_department_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"),
                models.F("tenant"),
                name="uq_academic_department_code",
            ),
        ),
        migrations.AddIndex(
            model_name="program",
            index=models.Index(
                fields=["tenant", "branch", "is_active"],
                name="vs_academic_tenant__c01497_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="program",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("tenant"),
                name="uq_academic_program_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="program",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"),
                models.F("tenant"),
                name="uq_academic_program_code",
            ),
        ),
        migrations.AddIndex(
            model_name="level",
            index=models.Index(
                fields=["tenant", "branch", "is_active"],
                name="vs_academic_tenant__cc7c5f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="level",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("program"),
                name="uq_academic_level_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="level",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"),
                models.F("program"),
                name="uq_academic_level_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="level",
            constraint=models.UniqueConstraint(
                fields=("program", "order_index"), name="uq_academic_level_order"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolclass",
            index=models.Index(
                fields=["tenant", "branch", "is_active"],
                name="vs_academic_tenant__a1e7c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="schoolclass",
            index=models.Index(
                fields=["level", "is_active"], name="vs_academic_level_i_014991_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolclass",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("level"),
                models.F("branch"),
                condition=models.Q(("branch__isnull", False)),
                name="uq_academic_class_level_branch_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolclass",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("level"),
                condition=models.Q(("branch__isnull", True)),
                name="uq_academic_class_level_name_nobranch",
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolclass",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"),
                models.F("tenant"),
                name="uq_academic_class_code",
            ),
        ),
        migrations.AddIndex(
            model_name="sessionbranch",
            index=models.Index(
                fields=["tenant", "branch"], name="vs_academic_tenant__c1be4d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionbranch",
            constraint=models.UniqueConstraint(
                fields=("session", "branch"), name="uq_session_branch"
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionbranch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session_status", "ACTIVE")),
                fields=("branch",),
                name="uq_session_branch_one_active",
            ),
        ),
        migrations.AddIndex(
            model_name="subjectoffering",
            index=models.Index(
                fields=["tenant", "level"], name="vs_academic_tenant__738750_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectoffering",
            constraint=models.UniqueConstraint(
                fields=("subject", "level"), name="uq_academic_offering"
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["tenant", "branch", "is_active"],
                name="vs_academic_tenant__ff2492_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("tenant"),
                name="uq_academic_subject_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"),
                models.F("tenant"),
                name="uq_academic_subject_code",
            ),
        ),
    ]
