# Generated by Django 5.2.10 on 2026-08-25 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_academics", "0001_initial"),
        ("vs_tenants", "0008_alter_branch_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank for an item the whole school shares.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="departments",
                to="vs_tenants.branch",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="departments",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="level",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank for an item the whole school shares.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="levels",
                to="vs_tenants.branch",
            ),
        ),
        migrations.AlterField(
            model_name="level",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="levels",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank for an item the whole school shares.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programs",
                to="vs_tenants.branch",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programs",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="schoolclass",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank for an item the whole school shares.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classes",
                to="vs_tenants.branch",
            ),
        ),
        migrations.AlterField(
            model_name="schoolclass",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classes",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank for an item the whole school shares.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subjects",
                to="vs_tenants.branch",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subjects",
                to="vs_tenants.tenant",
            ),
        ),
    ]
