# Generated by Django 5.2.10 on 2026-08-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_academics", "0002_reverse_accessors"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="program",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
