# Generated by Django 5.2.10 on 2026-08-25 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_academics", "0003_level_description_program_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectoffering",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_offerings",
                to="vs_academics.level",
            ),
        ),
    ]
