# Generated by Django 5.2.10 on 2026-09-05 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_academics", "0008_a_level_says_whether_it_ends"),
        ("vs_staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolclass",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes_led",
                to="vs_staff.staffprofile",
            ),
        ),
    ]
