# Generated by Django 5.2.10 on 2026-03-29 16:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlatformRoleChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("DENIED", "Denied"),
                            ("APPLY_FAILED", "Apply Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("justification", models.TextField()),
                ("reviewer_notes", models.TextField(blank=True)),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("impact_summary", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="PlatformRolePermission",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("granted", models.BooleanField(default=True)),
                ("granted_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="PlatformRoleTemplate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("is_system_role", models.BooleanField(default=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="PlatformUserRoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment_status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("REVOKED", "Revoked")],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("reason_note", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="RoleChangeDeltaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operation",
                    models.CharField(
                        choices=[("ADD", "Add"), ("REMOVE", "Remove")], max_length=8
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoleChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("DENIED", "Denied"),
                            ("APPLY_FAILED", "Apply Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("justification", models.TextField()),
                ("reviewer_notes", models.TextField(blank=True)),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("impact_summary", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("granted", models.BooleanField(default=True)),
                ("granted_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="RoleTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("is_system_role", models.BooleanField(default=False)),
                ("is_locked", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="UserRoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment_status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("REVOKED", "Revoked")],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("reason_note", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(max_length=180, primary_key=True, serialize=False),
                ),
                ("module_key", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True)),
                (
                    "sensitivity_level",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("SENSITIVE", "Sensitive"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="NORMAL",
                        max_length=16,
                    ),
                ),
                ("is_restricted", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["module_key", "action"],
                        name="vs_rbac_per_module__20e8c1_idx",
                    ),
                    models.Index(
                        fields=["is_restricted", "sensitivity_level"],
                        name="vs_rbac_per_is_rest_8b0cd7_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PermissionDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "depends_on",
                    models.ForeignKey(
                        db_column="depends_on_key",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_by",
                        to="vs_rbac.permission",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        db_column="permission_key",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="vs_rbac.permission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlatformRoleChangeDeltaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operation",
                    models.CharField(
                        choices=[("ADD", "Add"), ("REMOVE", "Remove")], max_length=8
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        db_column="permission_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="platform_delta_items",
                        to="vs_rbac.permission",
                    ),
                ),
            ],
        ),
    ]
