# Generated by Django 5.2.10 on 2026-07-14 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vs_rbac", "0001_initial"),
        ("vs_schools", "0001_initial"),
        ("vs_tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rbacauditlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rbac_audit_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tenantrolechangedeltaitem",
            name="permission",
            field=models.ForeignKey(
                db_column="permission_key",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tenant_delta_items",
                to="vs_rbac.permission",
            ),
        ),
        migrations.AddField(
            model_name="tenantrolechangerequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tenant_role_change_requests_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tenantrolechangerequest",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tenant_role_change_requests_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tenantrolechangerequest",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="role_change_requests",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="tenantrolechangedeltaitem",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delta_items",
                to="vs_rbac.tenantrolechangerequest",
            ),
        ),
        migrations.AddField(
            model_name="tenantrolegroup",
            name="attached_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attached_tenant_role_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tenantrolegroup",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenant_role_attachments",
                to="vs_rbac.permissiongroup",
            ),
        ),
        migrations.AddField(
            model_name="tenantrolepermission",
            name="granted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="granted_tenant_role_permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tenantrolepermission",
            name="permission",
            field=models.ForeignKey(
                db_column="permission_key",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenant_role_permissions",
                to="vs_rbac.permission",
            ),
        ),
        migrations.AddField(
            model_name="tenantroletemplate",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tenant_role_templates",
                to="vs_schools.branch",
            ),
        ),
        migrations.AddField(
            model_name="tenantroletemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tenant_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tenantroletemplate",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="role_templates",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="tenantrolepermission",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_permissions",
                to="vs_rbac.tenantroletemplate",
            ),
        ),
        migrations.AddField(
            model_name="tenantrolegroup",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_groups",
                to="vs_rbac.tenantroletemplate",
            ),
        ),
        migrations.AddField(
            model_name="tenantrolechangerequest",
            name="target_role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="change_requests",
                to="vs_rbac.tenantroletemplate",
            ),
        ),
        migrations.AddField(
            model_name="tenantuserroleassignment",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tenant_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tenantuserroleassignment",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tenant_role_assignments",
                to="vs_schools.branch",
            ),
        ),
        migrations.AddField(
            model_name="tenantuserroleassignment",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revoked_tenant_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tenantuserroleassignment",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_assignments",
                to="vs_rbac.tenantroletemplate",
            ),
        ),
        migrations.AddField(
            model_name="tenantuserroleassignment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="role_assignments",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="tenantuserroleassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenant_role_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="permissiondependency",
            constraint=models.UniqueConstraint(
                fields=("permission", "depends_on"), name="uq_permission_dependency"
            ),
        ),
        migrations.AddIndex(
            model_name="permissiongroup",
            index=models.Index(
                fields=["is_active"], name="vs_rbac_per_is_acti_6d65a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grouppermission",
            index=models.Index(fields=["group"], name="vs_rbac_gro_group_i_108750_idx"),
        ),
        migrations.AddIndex(
            model_name="grouppermission",
            index=models.Index(
                fields=["permission"], name="vs_rbac_gro_permiss_1b4eb3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="grouppermission",
            constraint=models.UniqueConstraint(
                fields=("group", "permission"), name="uq_group_permission_once"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="permissionresource",
            unique_together={("module", "name")},
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(
                fields=["module", "action"], name="vs_rbac_per_module__5ed1a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(
                fields=["is_restricted", "sensitivity_level"],
                name="vs_rbac_per_is_rest_8b0cd7_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="prebuiltrolepermission",
            unique_together={("prebuilt_role", "permission")},
        ),
        migrations.AddIndex(
            model_name="rbacauditlog",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="vs_rbac_rba_entity__c44b07_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rbacauditlog",
            index=models.Index(
                fields=["action_type", "created_at"],
                name="vs_rbac_rba_action__78b141_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rbacauditlog",
            index=models.Index(
                fields=["school_id", "created_at"],
                name="vs_rbac_rba_school__58e95e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantrolechangedeltaitem",
            constraint=models.UniqueConstraint(
                fields=("request", "permission", "operation"),
                name="uq_tenant_request_permission_operation",
            ),
        ),
        migrations.AddIndex(
            model_name="tenantroletemplate",
            index=models.Index(
                fields=["tenant", "status"], name="vs_rbac_ten_tenant__413a05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantroletemplate",
            index=models.Index(
                fields=["tenant", "branch", "status"],
                name="vs_rbac_ten_tenant__d03e62_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantroletemplate",
            constraint=models.UniqueConstraint(
                fields=("tenant", "key"), name="uq_tenant_role_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantroletemplate",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="uq_tenant_role_name"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantrolepermission",
            index=models.Index(
                fields=["role", "granted"], name="vs_rbac_ten_role_id_85cdd2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantrolepermission",
            index=models.Index(
                fields=["permission", "granted"], name="vs_rbac_ten_permiss_c8ccda_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantrolepermission",
            constraint=models.UniqueConstraint(
                fields=("role", "permission"), name="uq_tenant_role_permission"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantrolegroup",
            constraint=models.UniqueConstraint(
                fields=("role", "group"), name="uq_tenant_role_group"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantrolechangerequest",
            index=models.Index(
                fields=["tenant", "status", "submitted_at"],
                name="vs_rbac_ten_tenant__38b8e1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tenantrolechangerequest",
            index=models.Index(
                fields=["status", "submitted_at"], name="vs_rbac_ten_status_2cdb5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantuserroleassignment",
            index=models.Index(
                fields=["tenant", "user", "assignment_status"],
                name="vs_rbac_ten_tenant__f60116_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tenantuserroleassignment",
            index=models.Index(
                fields=["tenant", "role", "assignment_status"],
                name="vs_rbac_ten_tenant__7e6054_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantuserroleassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("assignment_status", "ACTIVE")),
                fields=("tenant", "user", "role"),
                name="uq_active_tenant_user_role",
            ),
        ),
    ]
