# Generated by Django 5.2.13 on 2026-04-18 10:14

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_rbac", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "permission",
                    models.ForeignKey(
                        db_column="permission_key",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to="vs_rbac.permission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PermissionGroup",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("is_system", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="groups",
                        through="vs_rbac.GroupPermission",
                        to="vs_rbac.permission",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="grouppermission",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_permissions",
                to="vs_rbac.permissiongroup",
            ),
        ),
        migrations.CreateModel(
            name="PlatformRoleGroup",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "attached_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "attached_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attached_platform_role_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_role_attachments",
                        to="vs_rbac.permissiongroup",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_groups",
                        to="vs_rbac.platformroletemplate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="platformroletemplate",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="platform_roles",
                through="vs_rbac.PlatformRoleGroup",
                to="vs_rbac.permissiongroup",
            ),
        ),
        migrations.CreateModel(
            name="RoleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attached_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "attached_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attached_role_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_attachments",
                        to="vs_rbac.permissiongroup",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_groups",
                        to="vs_rbac.roletemplate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="roletemplate",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="roles",
                through="vs_rbac.RoleGroup",
                to="vs_rbac.permissiongroup",
            ),
        ),
        migrations.AddIndex(
            model_name="permissiongroup",
            index=models.Index(
                django.db.models.functions.text.Lower("name"),
                name="idx_perm_group_name_lower",
            ),
        ),
        migrations.AddIndex(
            model_name="permissiongroup",
            index=models.Index(
                fields=["is_active"], name="vs_rbac_per_is_acti_6d65a1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="permissiongroup",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="uq_perm_group_name_ci",
            ),
        ),
        migrations.AddIndex(
            model_name="grouppermission",
            index=models.Index(fields=["group"], name="vs_rbac_gro_group_i_108750_idx"),
        ),
        migrations.AddIndex(
            model_name="grouppermission",
            index=models.Index(
                fields=["permission"], name="vs_rbac_gro_permiss_1b4eb3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="grouppermission",
            constraint=models.UniqueConstraint(
                fields=("group", "permission"), name="uq_group_permission_once"
            ),
        ),
        migrations.AddIndex(
            model_name="platformrolegroup",
            index=models.Index(fields=["role"], name="vs_rbac_pla_role_id_00e9b2_idx"),
        ),
        migrations.AddIndex(
            model_name="platformrolegroup",
            index=models.Index(fields=["group"], name="vs_rbac_pla_group_i_2739de_idx"),
        ),
        migrations.AddConstraint(
            model_name="platformrolegroup",
            constraint=models.UniqueConstraint(
                fields=("role", "group"), name="uq_platform_role_group_once"
            ),
        ),
        migrations.AddIndex(
            model_name="rolegroup",
            index=models.Index(fields=["role"], name="vs_rbac_rol_role_id_4a91f7_idx"),
        ),
        migrations.AddIndex(
            model_name="rolegroup",
            index=models.Index(fields=["group"], name="vs_rbac_rol_group_i_9474f1_idx"),
        ),
        migrations.AddConstraint(
            model_name="rolegroup",
            constraint=models.UniqueConstraint(
                fields=("role", "group"), name="uq_role_group_once"
            ),
        ),
    ]
