# Generated by Django 5.2.13 on 2026-06-09 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_rbac", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="resource",
            field=models.ForeignKey(
                db_column="resource_key",
                db_constraint=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="permissions",
                to="vs_rbac.permissionresource",
            ),
        ),
    ]
