# Generated by Django 5.2.10 on 2026-07-12 11:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_rbac", "0002_initial"),
        ("vs_schools", "0003_school_tenant"),
        (
            "vs_tenants",
            "0003_rename_vs_tenants_kind_status_idx_vs_tenants__kind_580eca_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantRoleTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=120)),
                ("name", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("is_system_role", models.BooleanField(default=False)),
                ("is_locked", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_role_templates",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tenant_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_templates",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TenantRolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("granted", models.BooleanField(default=True)),
                ("granted_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_tenant_role_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        db_column="permission_key",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_role_permissions",
                        to="vs_rbac.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="vs_rbac.tenantroletemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TenantRoleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attached_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "attached_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attached_tenant_role_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_role_attachments",
                        to="vs_rbac.permissiongroup",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_groups",
                        to="vs_rbac.tenantroletemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TenantUserRoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment_status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("REVOKED", "Revoked")],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("reason_note", models.TextField(blank=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tenant_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_role_assignments",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_tenant_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_assignments",
                        to="vs_rbac.tenantroletemplate",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_assignments",
                        to="vs_tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_role_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="tenantroletemplate",
            index=models.Index(
                fields=["tenant", "status"], name="vs_rbac_ten_tenant__413a05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantroletemplate",
            index=models.Index(
                fields=["tenant", "branch", "status"],
                name="vs_rbac_ten_tenant__d03e62_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantroletemplate",
            constraint=models.UniqueConstraint(
                fields=("tenant", "key"), name="uq_tenant_role_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantroletemplate",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="uq_tenant_role_name"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantrolepermission",
            index=models.Index(
                fields=["role", "granted"], name="vs_rbac_ten_role_id_85cdd2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantrolepermission",
            index=models.Index(
                fields=["permission", "granted"], name="vs_rbac_ten_permiss_c8ccda_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantrolepermission",
            constraint=models.UniqueConstraint(
                fields=("role", "permission"), name="uq_tenant_role_permission"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantrolegroup",
            constraint=models.UniqueConstraint(
                fields=("role", "group"), name="uq_tenant_role_group"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantuserroleassignment",
            index=models.Index(
                fields=["tenant", "user", "assignment_status"],
                name="vs_rbac_ten_tenant__f60116_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tenantuserroleassignment",
            index=models.Index(
                fields=["tenant", "role", "assignment_status"],
                name="vs_rbac_ten_tenant__7e6054_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantuserroleassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("assignment_status", "ACTIVE")),
                fields=("tenant", "user", "role"),
                name="uq_active_tenant_user_role",
            ),
        ),
    ]
