# Generated by Django 5.2.13 on 2026-04-24 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_rbac", "0003_grouppermission_permissiongroup_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="permissiongroup",
            name="uq_perm_group_name_ci",
        ),
        migrations.RemoveConstraint(
            model_name="platformroletemplate",
            name="uq_platform_role_name_ci",
        ),
        migrations.RemoveConstraint(
            model_name="platformuserroleassignment",
            name="uq_active_platform_assignment_user_role",
        ),
        migrations.RemoveConstraint(
            model_name="roletemplate",
            name="uq_role_name_per_school_ci",
        ),
        migrations.RemoveConstraint(
            model_name="userroleassignment",
            name="uq_active_assignment_user_role_school",
        ),
        migrations.RemoveIndex(
            model_name="permissiongroup",
            name="idx_perm_group_name_lower",
        ),
        migrations.RemoveIndex(
            model_name="platformroletemplate",
            name="idx_platform_role_name_lower",
        ),
        migrations.RemoveIndex(
            model_name="roletemplate",
            name="idx_role_name_lower",
        ),
    ]
