# Generated by Django 5.2.10 on 2026-06-11 13:17

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_rbac", "0003_alter_permission_resource"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schoolrolechangerequest",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="schoolroletemplate",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="schooluserroleassignment",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelManagers(
            name="schoolrolechangerequest",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="schoolroletemplate",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="schooluserroleassignment",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
