# Generated by Django 5.2.13 on 2026-04-28 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_rbac", "0004_remove_mariadb_unsupported_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuggestedRoleTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("institution", "Institution-wide"),
                            ("branch", "Branch-scoped"),
                            ("class", "Class-scoped"),
                            ("portal", "Portal only"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("A", "Core"),
                            ("B", "Module-Dependent"),
                            ("C", "Optional"),
                        ],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Suggested Role Template",
                "verbose_name_plural": "Suggested Role Templates",
                "ordering": ["tier", "name"],
            },
        ),
        migrations.AddField(
            model_name="roletemplate",
            name="scope",
            field=models.CharField(
                blank=True,
                choices=[
                    ("institution", "Institution-wide"),
                    ("branch", "Branch-scoped"),
                    ("class", "Class-scoped"),
                    ("portal", "Portal only"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="roletemplate",
            name="suggested_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_roles",
                to="vs_rbac.suggestedroletemplate",
            ),
        ),
        migrations.CreateModel(
            name="SuggestedRolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        db_column="permission_key",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_role_defaults",
                        to="vs_rbac.permission",
                    ),
                ),
                (
                    "suggested_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="default_permissions",
                        to="vs_rbac.suggestedroletemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suggested Role Permission",
                "verbose_name_plural": "Suggested Role Permissions",
                "unique_together": {("suggested_role", "permission")},
            },
        ),
    ]
