# Generated by Django 5.2.10 on 2026-06-11 14:08

from django.conf import settings
from django.db import migrations, models


def _dedupe(apps, schema_editor):
    """Rename duplicate role names so the unique constraints can apply.

    Keeps the oldest row's name untouched; later duplicates get a numeric
    suffix (e.g. "Branch Admin (2)"). Existing assignments keep pointing at
    the same rows — only the display name changes.
    """
    SchoolRoleTemplate = apps.get_model("vs_rbac", "SchoolRoleTemplate")
    PlatformRoleTemplate = apps.get_model("vs_rbac", "PlatformRoleTemplate")

    def dedupe(qs, keys):
        seen = {}
        for row in qs.order_by(*keys, "created_at", "pk"):
            key = tuple(getattr(row, k) for k in keys)
            n = seen.get(key, 0) + 1
            seen[key] = n
            if n > 1:
                row.name = f"{row.name} ({n})"
                row.save(update_fields=["name"])

    dedupe(SchoolRoleTemplate.objects.all(), ["school_id", "name"])
    dedupe(PlatformRoleTemplate.objects.all(), ["name"])


class Migration(migrations.Migration):
    dependencies = [
        ("vs_rbac", "0004_alter_schoolrolechangerequest_options_and_more"),
        ("vs_schools", "0002_alter_branch_options_alter_branch_managers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_dedupe, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="platformroletemplate",
            constraint=models.UniqueConstraint(
                fields=("name",), name="uq_platform_role_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolroletemplate",
            constraint=models.UniqueConstraint(
                fields=("school", "name"), name="uq_school_role_name"
            ),
        ),
    ]
