# Generated by Django 5.2.13 on 2026-04-28 07:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_rbac", "0005_suggestedroletemplate_roletemplate_scope_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roletemplate",
            name="scope",
        ),
    ]
