# Generated by Django 5.2.10 on 2026-08-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_rbac", "0005_branch_scoped_role_assignments"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="scope",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TENANT", "Tenant (any tenant may hold it)"),
                    ("PLATFORM", "Platform (CX staff only)"),
                ],
                db_index=True,
                help_text="Who may hold this key: TENANT (any tenant) or PLATFORM (CX only).",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="permissiongroup",
            name="scope",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TENANT", "Tenant (any tenant may hold it)"),
                    ("PLATFORM", "Platform (CX staff only)"),
                ],
                db_index=True,
                help_text="Who may hold this bundle: TENANT (any tenant) or PLATFORM (CX only).",
                max_length=16,
            ),
        ),
    ]
