# Generated by Django 5.2.10 on 2026-07-12 23:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_rbac", "0005_seed_impersonation_permissions"),
        ("vs_tenants", "0004_backfill_business_tenants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantRoleChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("DENIED", "Denied"),
                            ("APPLY_FAILED", "Apply Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("justification", models.TextField()),
                ("reviewer_notes", models.TextField(blank=True)),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("impact_summary", models.JSONField(blank=True, default=dict)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_role_change_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenant_role_change_requests_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="change_requests",
                        to="vs_rbac.tenantroletemplate",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_change_requests",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TenantRoleChangeDeltaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operation",
                    models.CharField(
                        choices=[("ADD", "Add"), ("REMOVE", "Remove")], max_length=8
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        db_column="permission_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_delta_items",
                        to="vs_rbac.permission",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delta_items",
                        to="vs_rbac.tenantrolechangerequest",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="tenantrolechangerequest",
            index=models.Index(
                fields=["tenant", "status", "submitted_at"],
                name="vs_rbac_ten_tenant__38b8e1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tenantrolechangerequest",
            index=models.Index(
                fields=["status", "submitted_at"], name="vs_rbac_ten_status_2cdb5b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantrolechangedeltaitem",
            constraint=models.UniqueConstraint(
                fields=("request", "permission", "operation"),
                name="uq_tenant_request_permission_operation",
            ),
        ),
    ]
