# Generated by Django 5.2.10 on 2026-06-11 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_rbac", "0005_platformroletemplate_uq_platform_role_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RBACAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_type", models.CharField(max_length=40)),
                ("severity", models.CharField(default="INFO", max_length=16)),
                ("status", models.CharField(default="SUCCESS", max_length=16)),
                ("school_id", models.CharField(blank=True, default="", max_length=80)),
                ("entity_type", models.CharField(max_length=80)),
                ("entity_id", models.CharField(max_length=180)),
                (
                    "entity_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("summary", models.TextField(blank=True, default="")),
                ("before_data", models.JSONField(blank=True, null=True)),
                ("diff_data", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rbac_audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="vs_rbac_rba_entity__c44b07_idx",
                    ),
                    models.Index(
                        fields=["action_type", "created_at"],
                        name="vs_rbac_rba_action__78b141_idx",
                    ),
                    models.Index(
                        fields=["school_id", "created_at"],
                        name="vs_rbac_rba_school__58e95e_idx",
                    ),
                ],
            },
        ),
    ]
