# Generated by Django 5.2.13 on 2026-04-28 09:33

from django.db import migrations, models
from django.utils.text import slugify


def _populate_roletemplate_slugs(apps, schema_editor):
    RoleTemplate = apps.get_model("vs_rbac", "RoleTemplate")
    seen = set()
    for role in RoleTemplate.objects.all().order_by("id"):
        base = slugify(role.name) or f"role-{role.pk}"
        slug = base
        n = 1
        while slug in seen:
            slug = f"{base}-{n}"
            n += 1
        seen.add(slug)
        role.slug = slug
        role.save(update_fields=["slug"])


def _populate_platformrole_ids(apps, schema_editor):
    PlatformRoleTemplate = apps.get_model("vs_rbac", "PlatformRoleTemplate")
    seen = set()
    for role in PlatformRoleTemplate.objects.all().order_by("name"):
        base = slugify(role.name) or f"platform-role-{role.pk}"
        slug = base
        n = 1
        while slug in seen:
            slug = f"{base}-{n}"
            n += 1
        seen.add(slug)
        role.id = slug
        role.save(update_fields=["id"])


class Migration(migrations.Migration):
    dependencies = [
        ("vs_rbac", "0006_remove_roletemplate_scope"),
    ]

    operations = [
        # Add slug as nullable first so existing rows don't violate unique.
        # db_index=False prevents the _like (varchar_pattern_ops) index from
        # being created here; AlterField below creates it alongside unique=True.
        migrations.AddField(
            model_name="roletemplate",
            name="slug",
            field=models.SlugField(blank=True, db_index=False, max_length=120, null=True),
        ),
        # Backfill slugs for existing rows
        migrations.RunPython(_populate_roletemplate_slugs, migrations.RunPython.noop),
        # Now enforce unique + drop null
        migrations.AlterField(
            model_name="roletemplate",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name="platformroletemplate",
            name="id",
            field=models.SlugField(
                editable=False, max_length=120, primary_key=True, serialize=False
            ),
        ),
    ]
