# Generated by Django 5.2.13 on 2026-04-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_rbac", "0007_roletemplate_slug_alter_platformroletemplate_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roletemplate",
            name="slug",
        ),
        migrations.AlterField(
            model_name="roletemplate",
            name="id",
            field=models.SlugField(
                editable=False, max_length=120, primary_key=True, serialize=False
            ),
        ),
    ]
