# Generated by Django 5.2.13 on 2026-05-05 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_rbac", "0011_rename_suggested_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prebuiltrolepermission",
            options={
                "verbose_name": "Prebuilt Role Permission",
                "verbose_name_plural": "Prebuilt Role Permissions",
            },
        ),
        migrations.AlterModelOptions(
            name="prebuiltroletemplate",
            options={
                "ordering": ["tier", "name"],
                "verbose_name": "Prebuilt Role Template",
                "verbose_name_plural": "Prebuilt Role Templates",
            },
        ),
        migrations.RenameIndex(
            model_name="schoolrolechangerequest",
            new_name="vs_rbac_sch_school__4c0dde_idx",
            old_name="vs_rbac_rol_school__c70fff_idx",
        ),
        migrations.RenameIndex(
            model_name="schoolrolechangerequest",
            new_name="vs_rbac_sch_status_12dfa0_idx",
            old_name="vs_rbac_rol_status_029cfc_idx",
        ),
        migrations.RenameIndex(
            model_name="schoolrolegroup",
            new_name="vs_rbac_sch_role_id_16a2f8_idx",
            old_name="vs_rbac_rol_role_id_4a91f7_idx",
        ),
        migrations.RenameIndex(
            model_name="schoolrolegroup",
            new_name="vs_rbac_sch_group_i_af7cdd_idx",
            old_name="vs_rbac_rol_group_i_9474f1_idx",
        ),
        migrations.RenameIndex(
            model_name="schoolrolepermission",
            new_name="vs_rbac_sch_role_id_14af46_idx",
            old_name="vs_rbac_rol_role_id_83e13f_idx",
        ),
        migrations.RenameIndex(
            model_name="schoolrolepermission",
            new_name="vs_rbac_sch_permiss_0fb3e1_idx",
            old_name="vs_rbac_rol_permiss_98bad6_idx",
        ),
        migrations.RenameIndex(
            model_name="schoolroletemplate",
            new_name="vs_rbac_sch_school__fd59cf_idx",
            old_name="vs_rbac_rol_school__5b38c4_idx",
        ),
        migrations.RenameIndex(
            model_name="schoolroletemplate",
            new_name="vs_rbac_sch_school__8eb498_idx",
            old_name="vs_rbac_rol_school__919f8c_idx",
        ),
        migrations.RenameIndex(
            model_name="schooluserroleassignment",
            new_name="vs_rbac_sch_school__255e25_idx",
            old_name="vs_rbac_use_school__997e88_idx",
        ),
        migrations.RenameIndex(
            model_name="schooluserroleassignment",
            new_name="vs_rbac_sch_school__8b36b3_idx",
            old_name="vs_rbac_use_school__29168a_idx",
        ),
        migrations.AddField(
            model_name="permission",
            name="resource",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="prebuiltrolepermission",
            name="permission",
            field=models.ForeignKey(
                db_column="permission_key",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prebuilt_role_defaults",
                to="vs_rbac.permission",
            ),
        ),
    ]
