# Generated by Django 5.2.10 on 2026-09-06 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_config", "0010_a_module_sold_whole_and_used_in_slices"),
        ("vs_rbac", "0014_a_school_owns_the_roles_and_rules_codex_set_up"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="capability",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permissions",
                to="vs_config.capability",
            ),
        ),
    ]
