# Generated by Django 5.2.13 on 2026-05-13 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_rbac", "0015_permission_fk_non_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="action",
            field=models.ForeignKey(
                db_column="action_key",
                db_constraint=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="permissions",
                to="vs_rbac.permissionaction",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="module",
            field=models.ForeignKey(
                db_column="module_key",
                db_constraint=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="permissions",
                to="vs_rbac.permissionmodule",
            ),
        ),
    ]
