# Generated by Django 5.2.13 on 2026-05-17 07:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_rbac", "0017_vocab_key_to_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permissionmodule",
            options={"ordering": ["-updated_at", "name"]},
        ),
    ]
