# Generated by Django 5.2.13 on 2026-05-17 07:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_rbac", "0018_alter_permissionmodule_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permissionaction",
            options={"ordering": ["-updated_at", "name"]},
        ),
        migrations.AlterModelOptions(
            name="permissionresource",
            options={"ordering": ["-updated_at", "module", "name"]},
        ),
    ]
