# Generated by Django 5.2.13 on 2026-05-17 07:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_rbac", "0019_alter_permissionaction_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permission",
            options={"ordering": ["-updated_at", "module", "resource", "action"]},
        ),
        migrations.AlterModelOptions(
            name="permissiongroup",
            options={"ordering": ["-updated_at", "name"]},
        ),
    ]
