# Generated by Django 5.2.10 on 2026-09-14 19:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_rbac", "0021_a_reclassified_key_leaves_no_grants_behind"),
    ]

    operations = [
        migrations.AddField(
            model_name="permissionmodule",
            name="label",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="permissionresource",
            name="label",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name="FieldDefinition",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("name", models.SlugField(max_length=64)),
                ("api_names", models.JSONField(blank=True, default=list)),
                ("label", models.CharField(max_length=120)),
                ("group", models.CharField(blank=True, max_length=60)),
                ("description", models.TextField(blank=True)),
                ("sensitive", models.BooleanField(default=False)),
                ("writable", models.BooleanField(default=True)),
                (
                    "scope",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TENANT", "Tenant (any tenant may hold it)"),
                            ("PLATFORM", "Platform (CX staff only)"),
                        ],
                        help_text="Who may be granted this field: TENANT (any tenant) or PLATFORM (CX only).",
                        max_length=16,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fields",
                        to="vs_rbac.permissionresource",
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
                "indexes": [
                    models.Index(
                        fields=["resource", "is_active"],
                        name="rbac_field_resource_active",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("resource", "name"),
                        name="rbac_field_unique_per_resource",
                    )
                ],
            },
        ),
    ]
