# Generated by Django 5.2.10 on 2026-09-15 06:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_rbac", "0022_a_field_is_named_under_its_resource"),
        ("vs_tenants", "0010_remove_branch__type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrebuiltRoleFieldAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_read", models.BooleanField(default=False)),
                ("can_write", models.BooleanField(default=False)),
                (
                    "field",
                    models.ForeignKey(
                        db_column="field_key",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prebuilt_role_access",
                        to="vs_rbac.fielddefinition",
                    ),
                ),
                (
                    "prebuilt_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="default_field_access",
                        to="vs_rbac.prebuiltroletemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prebuilt Role Field Access",
                "verbose_name_plural": "Prebuilt Role Field Access",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("prebuilt_role", "field"),
                        name="uq_prebuilt_role_field_access",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("can_write", False), ("can_read", True), _connector="OR"
                        ),
                        name="ck_prebuilt_role_field_write_implies_read",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RoleFieldAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("can_read", models.BooleanField(default=False)),
                ("can_write", models.BooleanField(default=False)),
                ("set_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "field",
                    models.ForeignKey(
                        db_column="field_key",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_access",
                        to="vs_rbac.fielddefinition",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_access",
                        to="vs_rbac.tenantroletemplate",
                    ),
                ),
                (
                    "set_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="set_role_field_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["field", "can_read"], name="rbac_rfa_field_read"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("role", "field"), name="uq_role_field_access"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("can_write", False), ("can_read", True), _connector="OR"
                        ),
                        name="ck_role_field_write_implies_read",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserFieldAccessOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "access",
                    models.CharField(
                        choices=[("READ", "Read"), ("WRITE", "Write")], max_length=8
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("ALLOW", "Allow (extra access)"),
                            ("DENY", "Deny (exception)"),
                        ],
                        max_length=8,
                    ),
                ),
                ("reason", models.TextField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_field_access_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        db_column="field_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_overrides",
                        to="vs_rbac.fielddefinition",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_field_access_overrides",
                        to="vs_tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_access_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "user", "expires_at"],
                        name="rbac_ufao_tenant_user_exp",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "field", "access"),
                        name="uq_user_field_access_override",
                    )
                ],
            },
        ),
    ]
