# Generated by Django 5.2.10 on 2026-09-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_rbac", "0023_a_role_decides_who_reads_each_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="fielddefinition",
            name="open_on_create",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Set freely while the record is created; the write switch "
                    "governs later changes only."
                ),
            ),
        ),
    ]
