"""A role grant carrying restricted permissions waits for approval.

Adds ``TenantRoleGrantRequest``: the grant somebody asked for, held until the
``rbac.role_grant`` ladder decides it. Nothing existing changes shape, so the
reverse drops the table and loses only requests still waiting.
"""
# Generated by Django 5.2.10 on 2026-09-26 17:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_rbac", "0028_role_additional_branches"),
        ("vs_tenants", "0010_remove_branch__type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantRoleGrantRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason_note", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("DENIED", "Denied"),
                            ("APPLY_FAILED", "Apply Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grant_request",
                        to="vs_rbac.tenantuserroleassignment",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_grant_requests",
                        to="vs_tenants.branch",
                    ),
                ),
                (
                    "replaces",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replacement_requests",
                        to="vs_rbac.tenantuserroleassignment",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_role_grant_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenant_role_grant_requests_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grant_requests",
                        to="vs_rbac.tenantroletemplate",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_grant_requests",
                        to="vs_tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_role_grant_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "status", "submitted_at"],
                        name="vs_rbac_ten_tenant__956df6_idx",
                    ),
                    models.Index(
                        fields=["tenant", "user", "status"],
                        name="vs_rbac_ten_tenant__2e03b3_idx",
                    ),
                ],
            },
        ),
    ]
