# Generated by Django 5.2.10 on 2026-07-14 16:09

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
import vs_user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("vs_rbac", "0001_initial"),
        ("vs_schools", "0001_initial"),
        ("vs_tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("MALE", "Male"), ("FEMALE", "Female")],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, default="", max_length=32, null=True),
                ),
                (
                    "uid",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("CX_STAFF", "CX Staff"),
                            ("SCHOOL_ADMIN", "School Admin"),
                            ("BRANCH_ADMIN", "Branch Admin"),
                            ("STAFF", "Staff"),
                            ("STUDENT", "Student"),
                            ("PARENT", "Parent/Guardian"),
                        ],
                        help_text="Inert domain marker for the person's persona. Migrates into the future profile models and MUST NEVER drive authorization — all access decisions run through tenant RBAC, not this field.",
                        max_length=32,
                    ),
                ),
                ("role", models.CharField(blank=True, default="", max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("PENDING", "Pending Activation"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("LOCKED", "Locked (security)"),
                            ("DEACTIVATED", "Deactivated"),
                            ("REJECTED", "Creation Rejected"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "activation_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("password_changed_at", models.DateTimeField(blank=True, null=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL for Vision Staff and School Admins.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invited_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Canonical home tenant.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="vs_tenants.tenant",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "vs_users_user",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", vs_user.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AccountLockout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                (
                    "locked_reason",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_failure_ip",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lockout",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AuthAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email_entered", models.EmailField(max_length=254)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAIL", "Fail"),
                            ("BLOCKED", "Blocked (policy)"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "failure_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. INVALID_CREDENTIALS / SCHOOL_MISMATCH / LOCKED",
                        max_length=64,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auth_attempts",
                        to="vs_tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auth_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="AuthEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("USER_CREATED", "User Created"),
                            ("INVITATION_SENT", "Invitation Sent"),
                            ("ACCOUNT_ACTIVATED", "Account Activated"),
                            ("LOGIN_SUCCESS", "Login Success"),
                            ("LOGIN_FAILURE", "Login Failure"),
                            ("TOKEN_REVOKED", "Token Revoked"),
                            ("FORCE_LOGOUT", "Force Logout"),
                            ("ACCOUNT_LOCKED", "Account Locked"),
                            ("ACCOUNT_UNLOCKED", "Account Unlocked"),
                            ("ACCOUNT_SUSPENDED", "Account Suspended"),
                            ("ACCOUNT_REACTIVATED", "Account Reactivated"),
                            ("ACCOUNT_DEACTIVATED", "Account Deactivated"),
                            ("PASSWORD_RESET_REQUESTED", "Password Reset Requested"),
                            ("PASSWORD_RESET_COMPLETED", "Password Reset Completed"),
                            ("PASSWORD_CHANGED", "Password Changed"),
                            ("EMAIL_CHANGED", "Email Changed"),
                        ],
                        max_length=40,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auth_events_as_actor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auth_events_as_subject",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auth_events",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="LoginSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                (
                    "device_label",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "refresh_jti",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "end_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="LOGOUT / FORCE_LOGOUT / EXPIRED",
                        max_length=64,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="login_sessions",
                        to="vs_tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen_at"],
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="OrgNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=40, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("DIVISION", "Division"),
                            ("DEPARTMENT", "Department"),
                            ("TEAM", "Team"),
                        ],
                        default="DEPARTMENT",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="vs_user.orgnode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Org Node",
                "db_table": "vs_users_org_node",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.CharField(
                        choices=[
                            ("SELF", "Self-Service"),
                            ("ADMIN", "Admin-Initiated"),
                        ],
                        default="SELF",
                        max_length=10,
                    ),
                ),
                ("requested_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("requested_user_agent", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_resets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=40, unique=True)),
                ("headcount", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "default_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_positions",
                        to="vs_rbac.tenantroletemplate",
                    ),
                ),
                (
                    "org_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="vs_user.orgnode",
                    ),
                ),
                (
                    "reports_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_reports",
                        to="vs_user.position",
                    ),
                ),
            ],
            options={
                "verbose_name": "Position",
                "db_table": "vs_users_position",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="PlatformStaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED", "Married"),
                            ("DIVORCED", "Divorced"),
                            ("WIDOWED", "Widowed"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "state_of_origin",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="platform_staff/photos/"
                    ),
                ),
                ("bio", models.TextField(blank=True, default="")),
                (
                    "personal_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "alternate_phone",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("residential_address", models.TextField(blank=True, default="")),
                ("city", models.CharField(blank=True, default="", max_length=80)),
                ("state", models.CharField(blank=True, default="", max_length=80)),
                ("nok_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "nok_relationship",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("nok_phone", models.CharField(blank=True, default="", max_length=32)),
                ("nok_address", models.TextField(blank=True, default="")),
                (
                    "employee_id",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                ("job_title", models.CharField(blank=True, default="", max_length=120)),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FULL_TIME", "Full-time"),
                            ("PART_TIME", "Part-time"),
                            ("CONTRACT", "Contract"),
                            ("INTERN", "Intern"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ON_LEAVE", "On Leave"),
                            ("SUSPENDED", "Suspended"),
                            ("EXITED", "Exited"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("date_joined", models.DateField(blank=True, null=True)),
                ("date_exited", models.DateField(blank=True, null=True)),
                ("bank_name", models.CharField(blank=True, default="", max_length=120)),
                (
                    "account_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "account_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_profiles",
                        to="vs_user.position",
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Staff Profile",
                "db_table": "vs_users_platform_staff_profile",
            },
        ),
        migrations.AddField(
            model_name="orgnode",
            name="head_position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="heads_node",
                to="vs_user.position",
            ),
        ),
        migrations.CreateModel(
            name="MatrixReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship_label",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matrix_reports",
                        to="vs_user.position",
                    ),
                ),
                (
                    "reports_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matrix_directs",
                        to="vs_user.position",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matrix Report",
                "db_table": "vs_users_matrix_report",
            },
        ),
        migrations.CreateModel(
            name="PositionAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_primary", models.BooleanField(default=True)),
                ("is_acting", models.BooleanField(default=False)),
                (
                    "start_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="vs_user.position",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Position Assignment",
                "db_table": "vs_users_position_assignment",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="UserInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                (
                    "email_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("email_last_error", models.TextField(blank=True, default="")),
                ("email_attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["tenant", "user_type", "status"],
                name="vs_users_us_tenant__2ea349_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["tenant", "branch"], name="vs_users_us_tenant__6bd0c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["email", "status"], name="vs_users_us_email_0e8449_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("branch__isnull", True), ("user_type", "CX_STAFF")),
                    models.Q(("user_type", "CX_STAFF"), _negated=True),
                    _connector="OR",
                ),
                name="ck_vision_staff_no_branch",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user_type__in", ["CX_STAFF", "SCHOOL_ADMIN"]),
                    ("branch__isnull", False),
                    _connector="OR",
                ),
                name="ck_branch_required_for_branch_level_users",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user_type", "CX_STAFF"), _negated=True),
                fields=("tenant", "uid"),
                name="unique_uid_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user_type", "CX_STAFF")),
                fields=("uid",),
                name="unique_uid_vision_staff",
            ),
        ),
        migrations.AddIndex(
            model_name="authattempt",
            index=models.Index(
                fields=["email_entered"], name="vs_user_aut_email_e_38a6f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authattempt",
            index=models.Index(
                fields=["created_at"], name="vs_user_aut_created_44e324_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authattempt",
            index=models.Index(
                fields=["user", "result"], name="vs_user_aut_user_id_1d7a6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginsession",
            index=models.Index(
                fields=["user", "is_active"], name="vs_user_log_user_id_02e305_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginsession",
            index=models.Index(
                fields=["is_active", "last_seen_at"],
                name="vs_user_log_is_acti_7f93cc_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="passwordresetrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("used_at__isnull", True)),
                fields=("user",),
                name="one_active_reset_per_user",
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["org_node", "is_active"], name="pos_orgnode_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["reports_to"], name="vs_users_po_reports_de5b51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(fields=["code"], name="vs_users_po_code_b3439a_idx"),
        ),
        migrations.AddIndex(
            model_name="platformstaffprofile",
            index=models.Index(
                fields=["position", "employment_status"],
                name="vs_users_pl_positio_39f6ca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="platformstaffprofile",
            index=models.Index(
                fields=["employee_id"], name="vs_users_pl_employe_199da9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orgnode",
            index=models.Index(
                fields=["parent", "is_active"], name="vs_users_or_parent__ebdb8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orgnode",
            index=models.Index(fields=["kind"], name="vs_users_or_kind_8d6382_idx"),
        ),
        migrations.AddIndex(
            model_name="orgnode",
            index=models.Index(fields=["code"], name="vs_users_or_code_cb717e_idx"),
        ),
        migrations.AddConstraint(
            model_name="orgnode",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", False)),
                fields=("name", "parent"),
                name="unique_org_node_name_per_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="orgnode",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("name",),
                name="unique_org_node_name_top_level",
            ),
        ),
        migrations.AddIndex(
            model_name="matrixreport",
            index=models.Index(
                fields=["position"], name="vs_users_ma_positio_23f96e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matrixreport",
            index=models.Index(
                fields=["reports_to"], name="vs_users_ma_reports_14ffe8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="matrixreport",
            unique_together={("position", "reports_to")},
        ),
        migrations.AddIndex(
            model_name="positionassignment",
            index=models.Index(
                fields=["user", "end_date"], name="vs_users_po_user_id_8d1d7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="positionassignment",
            index=models.Index(
                fields=["position", "end_date"], name="vs_users_po_positio_bb6630_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="positionassignment",
            index=models.Index(
                fields=["is_primary", "end_date"], name="vs_users_po_is_prim_eba6e6_idx"
            ),
        ),
    ]
