# Generated by Django 5.2.10 on 2026-03-07 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("vs_institutions", "0001_initial"),
        ("vs_user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="useraccount",
            name="uq_user_email_lower_per_institution",
        ),
        migrations.RemoveConstraint(
            model_name="useraccount",
            name="uq_vision_staff_email_lower",
        ),
        migrations.RemoveConstraint(
            model_name="useraccount",
            name="ck_user_institution_binding",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="institution",
        ),
        migrations.AddField(
            model_name="useraccount",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="NULL only for Vision staff accounts.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="vs_institutions.branch",
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("VS_STAFF", "Vision Staff"),
                    ("IN_AD", "Institution Admin"),
                    ("STAFF", "Staff"),
                    ("STUDENT", "Student"),
                    ("PARENT", "Parent/Guardian"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="useraccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("branch__isnull", True), ("user_type", "VS_STAFF")),
                    models.Q(("user_type", "VS_STAFF"), _negated=True),
                    _connector="OR",
                ),
                name="ck_user_branch_binding",
            ),
        ),
    ]
