# Generated by Django 5.2.10 on 2026-07-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("PENDING", "Pending Activation"),
                    ("ACTIVE", "Active"),
                    ("SUSPENDED", "Suspended"),
                    ("LOCKED", "Locked (security)"),
                    ("DEACTIVATED", "Deactivated"),
                    ("REJECTED", "Creation Rejected"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
    ]
