# Generated by Django 5.2.13 on 2026-04-12 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passwordresetrequest",
            name="token_hash",
        ),
    ]
