# Generated by Django 5.2.10 on 2026-06-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_user", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="orgnode",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", False)),
                fields=("name", "parent"),
                name="unique_org_node_name_per_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="orgnode",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("name",),
                name="unique_org_node_name_top_level",
            ),
        ),
    ]
