# Generated by Django 5.2.13 on 2026-04-24 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_user", "0002_remove_passwordresetrequest_token_hash"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-updated_at"]},
        ),
    ]
