# Generated by Django 5.2.10 on 2026-03-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_user", "0002_remove_useraccount_login_id_alter_useraccount_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=32, null=True),
        ),
    ]
