# Generated by Django 5.2.10 on 2026-07-27 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_user", "0003_alter_platformstaffprofile_job_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgnode",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="vs_user.orgnode",
            ),
        ),
    ]
