# Generated by Django 5.2.13 on 2026-04-25 21:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_user", "0003_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loginsession",
            options={"ordering": ["-last_seen_at"]},
        ),
    ]
