# Generated by Django 5.2.13 on 2026-04-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_user", "0004_alter_loginsession_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="invited_by_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
