# Generated by Django 5.2.13 on 2026-04-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_user", "0005_user_invited_by_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("MALE", "Male"), ("FEMALE", "Female")],
                default="",
                max_length=20,
            ),
        ),
    ]
