# Generated by Django 5.2.13 on 2026-06-09 08:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_user", "0005_alter_user_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformStaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED", "Married"),
                            ("DIVORCED", "Divorced"),
                            ("WIDOWED", "Widowed"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "state_of_origin",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="platform_staff/photos/"
                    ),
                ),
                ("bio", models.TextField(blank=True, default="")),
                (
                    "personal_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "alternate_phone",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("residential_address", models.TextField(blank=True, default="")),
                ("city", models.CharField(blank=True, default="", max_length=80)),
                ("state", models.CharField(blank=True, default="", max_length=80)),
                ("nok_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "nok_relationship",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("nok_phone", models.CharField(blank=True, default="", max_length=32)),
                ("nok_address", models.TextField(blank=True, default="")),
                (
                    "employee_id",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                ("job_title", models.CharField(blank=True, default="", max_length=120)),
                (
                    "department",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FULL_TIME", "Full-time"),
                            ("PART_TIME", "Part-time"),
                            ("CONTRACT", "Contract"),
                            ("INTERN", "Intern"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ON_LEAVE", "On Leave"),
                            ("SUSPENDED", "Suspended"),
                            ("EXITED", "Exited"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("date_joined", models.DateField(blank=True, null=True)),
                ("date_exited", models.DateField(blank=True, null=True)),
                ("bank_name", models.CharField(blank=True, default="", max_length=120)),
                (
                    "account_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "account_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "line_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_staff_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Staff Profile",
                "db_table": "vs_users_platform_staff_profile",
                "indexes": [
                    models.Index(
                        fields=["department", "employment_status"],
                        name="vs_users_pl_departm_4985e5_idx",
                    ),
                    models.Index(
                        fields=["employee_id"], name="vs_users_pl_employe_199da9_idx"
                    ),
                ],
            },
        ),
    ]
