# Generated by Django 5.2.13 on 2026-06-09 11:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_rbac", "0003_alter_permission_resource"),
        ("vs_user", "0006_platformstaffprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=40, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Department",
                "db_table": "vs_users_department",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MatrixReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship_label",
                    models.CharField(blank=True, default="", max_length=120),
                ),
            ],
            options={
                "verbose_name": "Matrix Report",
                "db_table": "vs_users_matrix_report",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=40, unique=True)),
                ("headcount", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Position",
                "db_table": "vs_users_position",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="PositionAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_primary", models.BooleanField(default=True)),
                ("is_acting", models.BooleanField(default=False)),
                (
                    "start_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Position Assignment",
                "db_table": "vs_users_position_assignment",
                "ordering": ["-start_date"],
            },
        ),
        migrations.RenameIndex(
            model_name="platformstaffprofile",
            new_name="vs_users_pl_departm_c3b068_idx",
            old_name="vs_users_pl_departm_4985e5_idx",
        ),
        migrations.RemoveField(
            model_name="platformstaffprofile",
            name="line_manager",
        ),
        migrations.AddField(
            model_name="department",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="vs_user.department",
            ),
        ),
        migrations.AlterField(
            model_name="platformstaffprofile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_profiles",
                to="vs_user.department",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="default_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_positions",
                to="vs_rbac.platformroletemplate",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="positions",
                to="vs_user.department",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="reports_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_reports",
                to="vs_user.position",
            ),
        ),
        migrations.AddField(
            model_name="matrixreport",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matrix_reports",
                to="vs_user.position",
            ),
        ),
        migrations.AddField(
            model_name="matrixreport",
            name="reports_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matrix_directs",
                to="vs_user.position",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="head_position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="heads_department",
                to="vs_user.position",
            ),
        ),
        migrations.AddField(
            model_name="positionassignment",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="vs_user.position",
            ),
        ),
        migrations.AddField(
            model_name="positionassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="position_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["department", "is_active"],
                name="vs_users_po_departm_d20905_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["reports_to"], name="vs_users_po_reports_de5b51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(fields=["code"], name="vs_users_po_code_b3439a_idx"),
        ),
        migrations.AddIndex(
            model_name="matrixreport",
            index=models.Index(
                fields=["position"], name="vs_users_ma_positio_23f96e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matrixreport",
            index=models.Index(
                fields=["reports_to"], name="vs_users_ma_reports_14ffe8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="matrixreport",
            unique_together={("position", "reports_to")},
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["parent", "is_active"], name="vs_users_de_parent__639495_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["code"], name="vs_users_de_code_3a685b_idx"),
        ),
        migrations.AddIndex(
            model_name="positionassignment",
            index=models.Index(
                fields=["user", "end_date"], name="vs_users_po_user_id_8d1d7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="positionassignment",
            index=models.Index(
                fields=["position", "end_date"], name="vs_users_po_positio_bb6630_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="positionassignment",
            index=models.Index(
                fields=["is_primary", "end_date"], name="vs_users_po_is_prim_eba6e6_idx"
            ),
        ),
    ]
