# Generated by Django 5.2.13 on 2026-05-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("vs_schools", "0002_remove_mariadb_unsupported_constraints"),
        ("vs_user", "0006_alter_user_gender"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authattempt",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="autheventlog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddIndex(
            model_name="authattempt",
            index=models.Index(
                fields=["email_entered"], name="vs_user_aut_email_e_38a6f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authattempt",
            index=models.Index(
                fields=["created_at"], name="vs_user_aut_created_44e324_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authattempt",
            index=models.Index(
                fields=["user", "result"], name="vs_user_aut_user_id_1d7a6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginsession",
            index=models.Index(
                fields=["user", "is_active"], name="vs_user_log_user_id_02e305_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginsession",
            index=models.Index(
                fields=["is_active", "last_seen_at"],
                name="vs_user_log_is_acti_7f93cc_idx",
            ),
        ),
        # Expire duplicate unused resets before adding the unique constraint.
        # Keeps the most recent unused record per user; marks older ones as used now.
        migrations.RunSQL(
            sql="""
                UPDATE vs_user_passwordresetrequest
                SET used_at = NOW()
                WHERE used_at IS NULL
                  AND id NOT IN (
                      SELECT DISTINCT ON (user_id) id
                      FROM vs_user_passwordresetrequest
                      WHERE used_at IS NULL
                      ORDER BY user_id, created_at DESC
                  );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddConstraint(
            model_name="passwordresetrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("used_at__isnull", True)),
                fields=("user",),
                name="one_active_reset_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user_type__in", ["VISION_STAFF", "SCHOOL_ADMIN"]),
                    ("branch__isnull", False),
                    _connector="OR",
                ),
                name="ck_branch_required_for_branch_level_users",
            ),
        ),
    ]
