# Generated by Django 5.2.10 on 2026-07-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("vs_schools", "0004_require_school_tenant"),
        ("vs_tenants", "0004_backfill_business_tenants"),
        ("vs_user", "0006_session_logs_and_position_role_to_tenant"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="ck_vision_staff_no_school",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="ck_school_bound_users",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_uid_per_school",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="vs_users_us_school__35d5ec_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="vs_users_us_school__2680c2_idx",
        ),
        migrations.RemoveField(
            model_name="user",
            name="school",
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("CX_STAFF", "CX Staff"),
                    ("SCHOOL_ADMIN", "School Admin"),
                    ("BRANCH_ADMIN", "Branch Admin"),
                    ("STAFF", "Staff"),
                    ("STUDENT", "Student"),
                    ("PARENT", "Parent/Guardian"),
                ],
                help_text="Inert domain marker for the person's persona. Migrates into the future profile models and MUST NEVER drive authorization — all access decisions run through tenant RBAC, not this field.",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["tenant", "user_type", "status"],
                name="vs_users_us_tenant__2ea349_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["tenant", "branch"], name="vs_users_us_tenant__6bd0c2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("branch__isnull", True), ("user_type", "CX_STAFF")),
                    models.Q(("user_type", "CX_STAFF"), _negated=True),
                    _connector="OR",
                ),
                name="ck_vision_staff_no_branch",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user_type", "CX_STAFF"), _negated=True),
                fields=("tenant", "uid"),
                name="unique_uid_per_tenant",
            ),
        ),
    ]
