# Generated by Django 5.2.13 on 2026-05-01 08:42

from django.db import migrations, models
from django.db.models import Max
from django.utils import timezone


def expire_duplicate_resets(apps, schema_editor):
    PasswordResetRequest = apps.get_model("vs_user", "PasswordResetRequest")

    # Collect the ID of the most-recent unused reset per user
    keep_ids = []
    for row in (
        PasswordResetRequest.objects.filter(used_at__isnull=True)
        .values("user_id")
        .annotate(max_created=Max("created_at"))
    ):
        record_id = (
            PasswordResetRequest.objects.filter(
                user_id=row["user_id"],
                created_at=row["max_created"],
                used_at__isnull=True,
            )
            .order_by("id")
            .values_list("id", flat=True)
            .first()
        )
        if record_id:
            keep_ids.append(record_id)

    PasswordResetRequest.objects.filter(used_at__isnull=True).exclude(
        id__in=keep_ids
    ).update(used_at=timezone.now())


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("vs_schools", "0002_remove_mariadb_unsupported_constraints"),
        ("vs_user", "0006_alter_user_gender"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authattempt",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="autheventlog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddIndex(
            model_name="authattempt",
            index=models.Index(
                fields=["email_entered"], name="vs_user_aut_email_e_38a6f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authattempt",
            index=models.Index(
                fields=["created_at"], name="vs_user_aut_created_44e324_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authattempt",
            index=models.Index(
                fields=["user", "result"], name="vs_user_aut_user_id_1d7a6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginsession",
            index=models.Index(
                fields=["user", "is_active"], name="vs_user_log_user_id_02e305_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginsession",
            index=models.Index(
                fields=["is_active", "last_seen_at"],
                name="vs_user_log_is_acti_7f93cc_idx",
            ),
        ),
        # Expire duplicate unused resets before adding the unique constraint.
        # Keeps the most recent unused record per user; marks older ones as used now.
        migrations.RunPython(expire_duplicate_resets, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="passwordresetrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("used_at__isnull", True)),
                fields=("user",),
                name="one_active_reset_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user_type__in", ["VISION_STAFF", "SCHOOL_ADMIN"]),
                    ("branch__isnull", False),
                    _connector="OR",
                ),
                name="ck_branch_required_for_branch_level_users",
            ),
        ),
    ]
