# Generated by Django 5.2.13 on 2026-06-09 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "vs_user",
            "0007_department_matrixreport_position_positionassignment_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="platformstaffprofile",
            name="vs_users_pl_departm_c3b068_idx",
        ),
        migrations.RemoveField(
            model_name="platformstaffprofile",
            name="department",
        ),
        migrations.AddField(
            model_name="platformstaffprofile",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_profiles",
                to="vs_user.position",
            ),
        ),
        migrations.AddIndex(
            model_name="platformstaffprofile",
            index=models.Index(
                fields=["position", "employment_status"],
                name="vs_users_pl_positio_39f6ca_idx",
            ),
        ),
    ]
