# Generated by Django 5.2.13 on 2026-05-08 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_user", "0008_userinvitation_email_tracking"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-created_at"]},
        ),
    ]
