# Generated by Django 5.2.13 on 2026-06-10 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_rbac", "0003_alter_permission_resource"),
        ("vs_user", "0009_rename_department_to_orgnode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orgnode",
            options={"ordering": ["name"], "verbose_name": "Org Node"},
        ),
        # The Position(department, is_active) index now covers (org_node_id,
        # is_active) after the 0009 column rename — it's the same physical index,
        # so just rename it. Dropping it would trip MariaDB's FK auto-index
        # management (it would try to reindex the now-renamed FK column).
        migrations.RenameIndex(
            model_name="position",
            new_name="vs_users_po_org_nod_43bb45_idx",
            old_name="vs_users_po_departm_d20905_idx",
        ),
        migrations.RenameIndex(
            model_name="orgnode",
            new_name="vs_users_or_parent__ebdb8f_idx",
            old_name="vs_users_de_parent__639495_idx",
        ),
        migrations.RenameIndex(
            model_name="orgnode",
            new_name="vs_users_or_code_cb717e_idx",
            old_name="vs_users_de_code_3a685b_idx",
        ),
        migrations.AlterField(
            model_name="orgnode",
            name="head_position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="heads_node",
                to="vs_user.position",
            ),
        ),
        migrations.AddIndex(
            model_name="orgnode",
            index=models.Index(fields=["kind"], name="vs_users_or_kind_8d6382_idx"),
        ),
    ]
