# Generated by Django 5.2.13 on 2026-05-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("vs_schools", "0005_school_status_default_pending"),
        ("vs_user", "0009_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uid",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("school__isnull", False)),
                fields=("school", "uid"),
                name="unique_uid_per_school",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user_type", "VISION_STAFF")),
                fields=("uid",),
                name="unique_uid_vision_staff",
            ),
        ),
    ]
