# Generated by Django 5.2.13 on 2026-05-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_user", "0010_user_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("CX_STAFF", "CX Staff"),
                    ("SCHOOL_ADMIN", "School Admin"),
                    ("BRANCH_ADMIN", "Branch Admin"),
                    ("STAFF", "Staff"),
                    ("STUDENT", "Student"),
                    ("PARENT", "Parent/Guardian"),
                ],
                max_length=32,
            ),
        ),
    ]
