# Generated by Django 5.2.13 on 2026-05-18 09:53

from django.db import migrations, models


def rename_vision_staff_to_cx_staff(apps, schema_editor):
    User = apps.get_model("vs_user", "User")
    User.objects.filter(user_type="VISION_STAFF").update(user_type="CX_STAFF")


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("vs_schools", "0005_school_status_default_pending"),
        ("vs_user", "0011_alter_user_user_type"),
    ]

    operations = [
        migrations.RunPython(rename_vision_staff_to_cx_staff, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="user",
            name="ck_vision_staff_no_school",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="ck_school_bound_users",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="ck_branch_required_for_branch_level_users",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_uid_vision_staff",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("branch__isnull", True),
                        ("school__isnull", True),
                        ("user_type", "CX_STAFF"),
                    ),
                    models.Q(("user_type", "CX_STAFF"), _negated=True),
                    _connector="OR",
                ),
                name="ck_vision_staff_no_school",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user_type", "CX_STAFF"),
                    ("school__isnull", False),
                    _connector="OR",
                ),
                name="ck_school_bound_users",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user_type__in", ["CX_STAFF", "SCHOOL_ADMIN"]),
                    ("branch__isnull", False),
                    _connector="OR",
                ),
                name="ck_branch_required_for_branch_level_users",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user_type", "CX_STAFF")),
                fields=("uid",),
                name="unique_uid_vision_staff",
            ),
        ),
    ]
