# Generated by Django 5.2.10 on 2026-09-26 12:19

"""Drop the ``AuthEventLog`` table.

No production code wrote to it: every identity event is recorded by
``vs_user.services.audit.log_auth_event`` as an ``AuditEvent`` in the identity
module, and every reader queries that. Only the dev seeder wrote rows here, and
those rows made a reader of this table look correct in development while it
showed nothing anywhere else. The event names it carried live on as
``vs_user.auth_events.AuthEvent``.

Irreversible for whatever rows a seeded database held; they were seed data.
"""
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_user", "0014_guard_additional_user_branches"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuthEventLog",
        ),
    ]
