# Generated by Django 5.2.10 on 2026-08-29 15:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vs_academics", "0008_a_level_says_whether_it_ends"),
        ("vs_finance", "0024_employeesalary_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeStructureTermLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fee_structure",
                    models.OneToOneField(
                        help_text="The neutral billing template this link gives a term to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fal_term_link",
                        to="vs_finance.feestructure",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="The academic year the structure bills for.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fee_structure_links",
                        to="vs_academics.academicsession",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        blank=True,
                        help_text="The term inside that session, or empty for a whole-session fee.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fee_structure_links",
                        to="vs_academics.academicterm",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "term", "fee_structure"],
                "indexes": [
                    models.Index(
                        fields=["session", "term"],
                        name="fal_feestru_session_5e6fa2_idx",
                    )
                ],
            },
        ),
    ]
