# Generated by Django 5.2.10 on 2026-09-04 09:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fal", "0001_initial"),
        ("vs_tenants", "0008_alter_branch_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolFeeDuePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("TERM_END", "End of the term billed"),
                            ("SESSION_END", "End of the session billed"),
                            ("MONTH_END", "End of the month the bill is raised"),
                            ("DAYS_AFTER", "A set number of days after the bill"),
                        ],
                        default="TERM_END",
                        help_text="Which date the school wants its fee bills to fall due on.",
                        max_length=16,
                    ),
                ),
                (
                    "days_after",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="Days after the bill date, used only when the basis is DAYS_AFTER.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        help_text="The school this rule belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_due_policy",
                        to="vs_tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fee_due_policy_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "school fee due policies",
            },
        ),
    ]
