# Generated by Django 5.2.10 on 2026-07-14 16:09

import django.db.models.manager
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "module_key",
                    models.CharField(
                        choices=[
                            ("ONBOARDING", "Onboarding"),
                            ("IDENTITY", "Identity & Auth"),
                            ("USER", "User Management"),
                            ("RBAC", "Roles & Permissions"),
                            ("IMPORT", "Data Import"),
                            ("CONFIG", "System Configuration"),
                            ("FINANCE", "Finance"),
                            ("PROCUREMENT", "Procurement"),
                            ("SCHOOL", "School Management"),
                            ("BRANCH", "Branch Management"),
                            ("SYSTEM", "System"),
                            ("PLATFORM", "Platform Operations"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("USER_CREATED", "User Created"),
                            ("USER_INVITED", "User Invited"),
                            ("ACCOUNT_ACTIVATED", "Account Activated"),
                            ("LOGIN_SUCCESS", "Login Success"),
                            ("LOGIN_FAILED", "Login Failed"),
                            ("TOKEN_REVOKED", "Token Revoked"),
                            ("FORCE_LOGOUT", "Force Logout"),
                            ("ACCOUNT_LOCKED", "Account Locked"),
                            ("ACCOUNT_UNLOCKED", "Account Unlocked"),
                            ("ACCOUNT_SUSPENDED", "Account Suspended"),
                            ("ACCOUNT_REACTIVATED", "Account Reactivated"),
                            ("ACCOUNT_DEACTIVATED", "Account Deactivated"),
                            ("PASSWORD_RESET_REQUESTED", "Password Reset Requested"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("PASSWORD_CHANGED", "Password Changed"),
                            ("EMAIL_CHANGED", "Email Changed"),
                            ("DATA_FILE_UPLOADED", "Data File Uploaded"),
                            ("DATA_IMPORT_STARTED", "Data Import Started"),
                            ("DATA_IMPORT_ROW_PROCESSED", "Data Import Row Processed"),
                            ("DATA_IMPORT_COMPLETED", "Data Import Completed"),
                            ("DATA_IMPORT_FAILED", "Data Import Failed"),
                            ("DATA_IMPORT_ROLLED_BACK", "Data Import Rolled Back"),
                            ("ROLE_ASSIGNED", "Role Assigned"),
                            ("ROLE_CHANGED", "Role Changed"),
                            ("PERMISSION_CHANGED", "Permission Changed"),
                            ("IMPERSONATION_STARTED", "Impersonation Started"),
                            ("IMPERSONATION_ENDED", "Impersonation Ended"),
                            ("IMPERSONATED_REQUEST", "Impersonated Request"),
                            ("CONFIG_CHANGED", "Configuration Changed"),
                            ("FINANCIAL_TRANSACTION", "Financial Transaction"),
                            ("PROCUREMENT_ACTION", "Procurement Action"),
                            ("EXPORT_REQUESTED", "Export Requested"),
                            ("EXPORT_COMPLETED", "Export Completed"),
                            ("EXPORT_FAILED", "Export Failed"),
                            ("CUSTOM", "Custom"),
                        ],
                        db_index=True,
                        max_length=80,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="INFO",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("DENIED", "Denied"),
                            ("PARTIAL", "Partial"),
                        ],
                        db_index=True,
                        default="SUCCESS",
                        max_length=20,
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[("USER", "User"), ("SYSTEM", "System")],
                        db_index=True,
                        default="USER",
                        max_length=20,
                    ),
                ),
                (
                    "actor_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable fallback for system or service actors (email, name, service id).",
                        max_length=255,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True,
                        help_text="Examples: UserAccount, School, ImportJob, Invoice, TenantRoleTemplate",
                        max_length=100,
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        db_index=True,
                        help_text="Stored as string so UUID/int/external refs can all fit.",
                        max_length=100,
                    ),
                ),
                (
                    "entity_label",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable target label.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Short explanation of what happened.",
                        null=True,
                    ),
                ),
                (
                    "before_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="State before the action. Keep lightweight and safe.",
                    ),
                ),
                (
                    "diff_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Field-level diff: {field: {before, after}}. Summary of what changed.",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "event_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=True,
                        editable=False,
                        help_text="Audit rows are append-only and must not be edited/deleted normally.",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditExportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[("CSV", "CSV")], default="CSV", max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "filter_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores search/date/action/entity filters used for this export.",
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=255)),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path/object key in storage.",
                        max_length=500,
                    ),
                ),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("failure_reason", models.TextField(blank=True)),
                (
                    "requested_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceRule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("RETENTION", "Retention"),
                            ("MASKING", "Masking"),
                            ("ACCESS", "Access"),
                            ("EXPORT", "Export"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "module_key",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ONBOARDING", "Onboarding"),
                            ("IDENTITY", "Identity & Auth"),
                            ("USER", "User Management"),
                            ("RBAC", "Roles & Permissions"),
                            ("IMPORT", "Data Import"),
                            ("CONFIG", "System Configuration"),
                            ("FINANCE", "Finance"),
                            ("PROCUREMENT", "Procurement"),
                            ("SCHOOL", "School Management"),
                            ("BRANCH", "Branch Management"),
                            ("SYSTEM", "System"),
                            ("PLATFORM", "Platform Operations"),
                        ],
                        help_text="Optional: restrict rule to one module.",
                        max_length=40,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        blank=True,
                        help_text="Optional: restrict rule to one action.",
                        max_length=80,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Used mainly for retention rules.",
                        null=True,
                    ),
                ),
                (
                    "masking_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Field names to mask in before/after/metadata/export.",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra policy configuration.",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="EntityAuditTrail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entity_type", models.CharField(db_index=True, max_length=100)),
                ("entity_id", models.CharField(db_index=True, max_length=100)),
                ("entity_label", models.CharField(blank=True, max_length=255)),
                ("event_count", models.PositiveIntegerField(default=0)),
                ("first_event_at", models.DateTimeField(blank=True, null=True)),
                ("last_event_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
