# Generated by Django 5.2.10 on 2026-03-07 13:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vs_institutions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditExportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[("CSV", "CSV")], default="CSV", max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "filter_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores search/date/action/entity filters used for this export.",
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=255)),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path/object key in storage.",
                        max_length=500,
                    ),
                ),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("failure_reason", models.TextField(blank=True)),
                (
                    "requested_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_audit_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="EntityAuditTrail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entity_type", models.CharField(db_index=True, max_length=100)),
                ("entity_id", models.CharField(db_index=True, max_length=100)),
                ("entity_label", models.CharField(blank=True, max_length=255)),
                ("event_count", models.PositiveIntegerField(default=0)),
                ("first_event_at", models.DateTimeField(blank=True, null=True)),
                ("last_event_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="vs_audit_en_entity__96f326_idx",
                    ),
                    models.Index(
                        fields=["last_event_at"], name="vs_audit_en_last_ev_64561f_idx"
                    ),
                ],
                "unique_together": {("entity_type", "entity_id")},
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "module_key",
                    models.CharField(
                        choices=[
                            ("ONBOARDING", "Onboarding"),
                            ("IDENTITY", "Identity"),
                            ("RBAC", "Roles & Permissions"),
                            ("IMPORT", "Data Import"),
                            ("CONFIG", "System Configuration"),
                            ("FINANCE", "Finance"),
                            ("PROCUREMENT", "Procurement"),
                            ("INSTITUTION", "Institution Management"),
                            ("SYSTEM", "System"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("INSTITUTION_CREATED", "Institution Created"),
                            ("BRANCH_CREATED", "Branch Created"),
                            ("INSTITUTION_UPDATED", "Institution Updated"),
                            ("BRANCH_UPDATED", "Branch Updated"),
                            ("USER_CREATED", "User Created"),
                            ("LOGIN_SUCCESS", "Login Success"),
                            ("LOGIN_FAILED", "Login Failed"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("DATA_FILE_UPLOADED", "Data File Uploaded"),
                            ("DATA_IMPORT_STARTED", "Data Import Started"),
                            ("DATA_IMPORT_COMPLETED", "Data Import Completed"),
                            ("DATA_IMPORT_FAILED", "Data Import Failed"),
                            ("ROLE_CHANGED", "Role Changed"),
                            ("PERMISSION_CHANGED", "Permission Changed"),
                            ("CONFIG_CHANGED", "Configuration Changed"),
                            ("FINANCIAL_TRANSACTION", "Financial Transaction"),
                            ("PROCUREMENT_ACTION", "Procurement Action"),
                            ("EXPORT_REQUESTED", "Export Requested"),
                            ("EXPORT_COMPLETED", "Export Completed"),
                            ("EXPORT_FAILED", "Export Failed"),
                            ("CUSTOM", "Custom"),
                        ],
                        db_index=True,
                        max_length=80,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="INFO",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("DENIED", "Denied"),
                            ("PARTIAL", "Partial"),
                        ],
                        db_index=True,
                        default="SUCCESS",
                        max_length=20,
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[("USER", "User"), ("SYSTEM", "System")],
                        db_index=True,
                        default="USER",
                        max_length=20,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True,
                        help_text="Examples: UserAccount, Institution, ImportJob, Invoice, RoleTemplate",
                        max_length=100,
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        db_index=True,
                        help_text="Stored as string so UUID/int/external refs can all fit.",
                        max_length=100,
                    ),
                ),
                (
                    "entity_label",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable target label.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Short explanation of what happened.",
                        null=True,
                    ),
                ),
                (
                    "before_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="State before the action. Keep lightweight and safe.",
                    ),
                ),
                (
                    "diff_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="State diff or change summary. Useful for large objects where before/after would be too heavy.",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "event_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=True,
                        editable=False,
                        help_text="Audit rows are append-only and must not be edited/deleted normally.",
                    ),
                ),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-event_at"],
                "indexes": [
                    models.Index(
                        fields=["module_key", "action_type", "event_at"],
                        name="vs_audit_au_module__f00de3_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id", "event_at"],
                        name="vs_audit_au_entity__9633ff_idx",
                    ),
                    models.Index(
                        fields=["actor_type", "actor_user", "event_at"],
                        name="vs_audit_au_actor_t_01c88d_idx",
                    ),
                    models.Index(
                        fields=["severity", "status", "event_at"],
                        name="vs_audit_au_severit_037672_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComplianceRule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("RETENTION", "Retention"),
                            ("MASKING", "Masking"),
                            ("ACCESS", "Access"),
                            ("EXPORT", "Export"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "module_key",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ONBOARDING", "Onboarding"),
                            ("IDENTITY", "Identity"),
                            ("RBAC", "Roles & Permissions"),
                            ("IMPORT", "Data Import"),
                            ("CONFIG", "System Configuration"),
                            ("FINANCE", "Finance"),
                            ("PROCUREMENT", "Procurement"),
                            ("INSTITUTION", "Institution Management"),
                            ("SYSTEM", "System"),
                        ],
                        help_text="Optional: restrict rule to one module.",
                        max_length=40,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        blank=True,
                        help_text="Optional: restrict rule to one action.",
                        max_length=80,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Used mainly for retention rules.",
                        null=True,
                    ),
                ),
                (
                    "masking_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Field names to mask in before/after/metadata/export.",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra policy configuration.",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null means global rule.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_compliance_rules",
                        to="vs_institutions.institution",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["rule_type", "is_active"],
                        name="vs_audit_co_rule_ty_0e687e_idx",
                    ),
                    models.Index(
                        fields=["institution", "rule_type"],
                        name="vs_audit_co_institu_cd4869_idx",
                    ),
                ],
            },
        ),
    ]
