# Generated by Django 5.2.10 on 2026-07-14 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vs_admin_console", "0002_initial"),
        ("vs_audit", "0001_initial"),
        ("vs_tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="actor_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performed_audit_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="effective_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="effective_audit_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="impersonation_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_events",
                to="vs_admin_console.impersonationsession",
            ),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_events",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="auditexportjob",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_audit_exports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="compliancerule",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Null means a global platform rule.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compliance_rules",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="entityaudittrail",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="vs_audit_en_entity__96f326_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="entityaudittrail",
            index=models.Index(
                fields=["last_event_at"], name="vs_audit_en_last_ev_64561f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="entityaudittrail",
            unique_together={("entity_type", "entity_id")},
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["module_key", "action_type", "event_at"],
                name="vs_audit_au_module__f00de3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["entity_type", "entity_id", "event_at"],
                name="vs_audit_au_entity__9633ff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["actor_type", "actor_user", "event_at"],
                name="vs_audit_au_actor_t_01c88d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["severity", "status", "event_at"],
                name="vs_audit_au_severit_037672_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["tenant", "event_at"], name="vs_audit_au_tenant__d53194_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["impersonation_session", "event_at"],
                name="vs_audit_au_imperso_4016cf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="compliancerule",
            index=models.Index(
                fields=["rule_type", "is_active"], name="vs_audit_co_rule_ty_0e687e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compliancerule",
            index=models.Index(
                fields=["tenant", "rule_type"], name="vs_audit_co_tenant__630979_idx"
            ),
        ),
    ]
