# Generated by Django 5.2.10 on 2026-03-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("LOGIN_SUCCESS", "Login Success"),
                    ("LOGIN_FAILED", "Login Failed"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("DATA_FILE_UPLOADED", "Data File Uploaded"),
                    ("DATA_IMPORT_STARTED", "Data Import Started"),
                    ("DATA_IMPORT_COMPLETED", "Data Import Completed"),
                    ("DATA_IMPORT_FAILED", "Data Import Failed"),
                    ("ROLE_CHANGED", "Role Changed"),
                    ("PERMISSION_CHANGED", "Permission Changed"),
                    ("CONFIG_CHANGED", "Configuration Changed"),
                    ("FINANCIAL_TRANSACTION", "Financial Transaction"),
                    ("PROCUREMENT_ACTION", "Procurement Action"),
                    ("EXPORT_REQUESTED", "Export Requested"),
                    ("EXPORT_COMPLETED", "Export Completed"),
                    ("EXPORT_FAILED", "Export Failed"),
                    ("CUSTOM", "Custom"),
                ],
                db_index=True,
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="module_key",
            field=models.CharField(
                choices=[
                    ("ONBOARDING", "Onboarding"),
                    ("IDENTITY", "Identity"),
                    ("RBAC", "Roles & Permissions"),
                    ("IMPORT", "Data Import"),
                    ("CONFIG", "System Configuration"),
                    ("FINANCE", "Finance"),
                    ("PROCUREMENT", "Procurement"),
                    ("INSTITUTION", "Institution Management"),
                    ("BRANCH", "Branch Management"),
                    ("SYSTEM", "System"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="compliancerule",
            name="module_key",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ONBOARDING", "Onboarding"),
                    ("IDENTITY", "Identity"),
                    ("RBAC", "Roles & Permissions"),
                    ("IMPORT", "Data Import"),
                    ("CONFIG", "System Configuration"),
                    ("FINANCE", "Finance"),
                    ("PROCUREMENT", "Procurement"),
                    ("INSTITUTION", "Institution Management"),
                    ("BRANCH", "Branch Management"),
                    ("SYSTEM", "System"),
                ],
                help_text="Optional: restrict rule to one module.",
                max_length=40,
            ),
        ),
    ]
