# Generated by Django 5.2.10 on 2026-06-11 18:33

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_audit", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="compliancerule",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelManagers(
            name="compliancerule",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
