# Generated by Django 5.2.13 on 2026-04-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_audit", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="actor_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Human-readable fallback for system or service actors (email, name, service id).",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("USER_CREATED", "User Created"),
                    ("USER_INVITED", "User Invited"),
                    ("ACCOUNT_ACTIVATED", "Account Activated"),
                    ("LOGIN_SUCCESS", "Login Success"),
                    ("LOGIN_FAILED", "Login Failed"),
                    ("TOKEN_REVOKED", "Token Revoked"),
                    ("FORCE_LOGOUT", "Force Logout"),
                    ("ACCOUNT_LOCKED", "Account Locked"),
                    ("ACCOUNT_UNLOCKED", "Account Unlocked"),
                    ("ACCOUNT_SUSPENDED", "Account Suspended"),
                    ("ACCOUNT_REACTIVATED", "Account Reactivated"),
                    ("ACCOUNT_DEACTIVATED", "Account Deactivated"),
                    ("PASSWORD_RESET_REQUESTED", "Password Reset Requested"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("PASSWORD_CHANGED", "Password Changed"),
                    ("EMAIL_CHANGED", "Email Changed"),
                    ("DATA_FILE_UPLOADED", "Data File Uploaded"),
                    ("DATA_IMPORT_STARTED", "Data Import Started"),
                    ("DATA_IMPORT_ROW_PROCESSED", "Data Import Row Processed"),
                    ("DATA_IMPORT_COMPLETED", "Data Import Completed"),
                    ("DATA_IMPORT_FAILED", "Data Import Failed"),
                    ("DATA_IMPORT_ROLLED_BACK", "Data Import Rolled Back"),
                    ("ROLE_ASSIGNED", "Role Assigned"),
                    ("ROLE_CHANGED", "Role Changed"),
                    ("PERMISSION_CHANGED", "Permission Changed"),
                    ("CONFIG_CHANGED", "Configuration Changed"),
                    ("FINANCIAL_TRANSACTION", "Financial Transaction"),
                    ("PROCUREMENT_ACTION", "Procurement Action"),
                    ("EXPORT_REQUESTED", "Export Requested"),
                    ("EXPORT_COMPLETED", "Export Completed"),
                    ("EXPORT_FAILED", "Export Failed"),
                    ("CUSTOM", "Custom"),
                ],
                db_index=True,
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="module_key",
            field=models.CharField(
                choices=[
                    ("ONBOARDING", "Onboarding"),
                    ("IDENTITY", "Identity & Auth"),
                    ("USER", "User Management"),
                    ("RBAC", "Roles & Permissions"),
                    ("IMPORT", "Data Import"),
                    ("CONFIG", "System Configuration"),
                    ("FINANCE", "Finance"),
                    ("PROCUREMENT", "Procurement"),
                    ("SCHOOL", "School Management"),
                    ("BRANCH", "Branch Management"),
                    ("SYSTEM", "System"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="compliancerule",
            name="module_key",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ONBOARDING", "Onboarding"),
                    ("IDENTITY", "Identity & Auth"),
                    ("USER", "User Management"),
                    ("RBAC", "Roles & Permissions"),
                    ("IMPORT", "Data Import"),
                    ("CONFIG", "System Configuration"),
                    ("FINANCE", "Finance"),
                    ("PROCUREMENT", "Procurement"),
                    ("SCHOOL", "School Management"),
                    ("BRANCH", "Branch Management"),
                    ("SYSTEM", "System"),
                ],
                help_text="Optional: restrict rule to one module.",
                max_length=40,
            ),
        ),
    ]
