# Generated by Django 5.2.13 on 2026-04-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_audit", "0003_add_actor_label_to_audit_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="diff_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Field-level diff: {field: {before, after}}. Summary of what changed.",
            ),
        ),
    ]
