# Generated by Django 5.2.10 on 2026-07-12 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_audit", "0003_auditevent_effective_user_and_more"),
        (
            "vs_tenants",
            "0003_rename_vs_tenants_kind_status_idx_vs_tenants__kind_580eca_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancerule",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Null means a global platform rule.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compliance_rules",
                to="vs_tenants.tenant",
            ),
        ),
    ]
