# Generated by Django 5.2.10 on 2026-07-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_audit", "0004_compliancerule_tenant"),
        ("vs_tenants", "0004_backfill_business_tenants"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="compliancerule",
            name="vs_audit_co_school__c5758b_idx",
        ),
        migrations.RemoveField(
            model_name="compliancerule",
            name="school",
        ),
        migrations.AddIndex(
            model_name="compliancerule",
            index=models.Index(
                fields=["tenant", "rule_type"], name="vs_audit_co_tenant__630979_idx"
            ),
        ),
    ]
