# Generated by Django 5.2.10 on 2026-08-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_audit", "0006_alter_auditevent_action_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("USER_CREATED", "User Created"),
                    ("USER_INVITED", "User Invited"),
                    ("ACCOUNT_ACTIVATED", "Account Activated"),
                    ("LOGIN_SUCCESS", "Login Success"),
                    ("LOGIN_FAILED", "Login Failed"),
                    ("TOKEN_REVOKED", "Token Revoked"),
                    ("FORCE_LOGOUT", "Force Logout"),
                    ("ACCOUNT_LOCKED", "Account Locked"),
                    ("ACCOUNT_UNLOCKED", "Account Unlocked"),
                    ("ACCOUNT_SUSPENDED", "Account Suspended"),
                    ("ACCOUNT_REACTIVATED", "Account Reactivated"),
                    ("ACCOUNT_DEACTIVATED", "Account Deactivated"),
                    ("PASSWORD_RESET_REQUESTED", "Password Reset Requested"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("PASSWORD_CHANGED", "Password Changed"),
                    ("EMAIL_CHANGED", "Email Changed"),
                    ("DATA_FILE_UPLOADED", "Data File Uploaded"),
                    ("DATA_IMPORT_STARTED", "Data Import Started"),
                    ("DATA_IMPORT_ROW_PROCESSED", "Data Import Row Processed"),
                    ("DATA_IMPORT_COMPLETED", "Data Import Completed"),
                    ("DATA_IMPORT_FAILED", "Data Import Failed"),
                    ("DATA_IMPORT_ROLLED_BACK", "Data Import Rolled Back"),
                    ("ROLE_ASSIGNED", "Role Assigned"),
                    ("ROLE_CHANGED", "Role Changed"),
                    ("PERMISSION_CHANGED", "Permission Changed"),
                    ("OVERRIDE_CREATED", "Permission Override Created"),
                    ("OVERRIDE_LIFTED", "Permission Override Lifted"),
                    ("IMPERSONATION_STARTED", "Impersonation Started"),
                    ("IMPERSONATION_ENDED", "Impersonation Ended"),
                    ("PROXY_CHANGE", "Change Through Proxy"),
                    ("PROXY_ACTION_FAILED", "Proxy Action Failed"),
                    ("CONFIG_CHANGED", "Configuration Changed"),
                    ("FINANCIAL_TRANSACTION", "Financial Transaction"),
                    ("PROCUREMENT_ACTION", "Procurement Action"),
                    ("EXPORT_REQUESTED", "Export Requested"),
                    ("EXPORT_COMPLETED", "Export Completed"),
                    ("EXPORT_FAILED", "Export Failed"),
                    (
                        "EXPORT_DEFINITION_CREATED",
                        "Export Defined (export.definition.created)",
                    ),
                    (
                        "EXPORT_DEFINITION_UPDATED",
                        "Export Changed (export.definition.updated)",
                    ),
                    (
                        "EXPORT_DEFINITION_DELETED",
                        "Export Archived (export.definition.deleted)",
                    ),
                    (
                        "EXPORT_DEFINITION_SHARED",
                        "Export Shared (export.definition.shared)",
                    ),
                    (
                        "EXPORT_SENSITIVE_FIELD_INCLUDED",
                        "Sensitive Field Exported (export.sensitive_field.included)",
                    ),
                    (
                        "EXPORT_RUN_OMITTED_FIELDS",
                        "Export Omitted Fields (export.run.omitted_fields)",
                    ),
                    (
                        "EXPORT_FILE_DOWNLOADED",
                        "Export File Downloaded (export.file.downloaded)",
                    ),
                    (
                        "EXPORT_FILE_DOWNLOAD_REFUSED",
                        "Export Download Refused (export.file.download_refused)",
                    ),
                    (
                        "EXPORT_FILE_EXPIRED",
                        "Export File Expired (export.file.expired)",
                    ),
                    (
                        "EXPORT_ADMIN_VIEWED_ACTIVITY",
                        "Export Activity Viewed (export.admin.viewed_activity)",
                    ),
                    ("CUSTOM", "Custom"),
                ],
                db_index=True,
                max_length=80,
            ),
        ),
    ]
