# Generated by Django 5.2.10 on 2026-07-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_audit", "0006_alter_auditevent_action_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="entity_type",
            field=models.CharField(
                db_index=True,
                help_text="Examples: UserAccount, School, ImportJob, Invoice, TenantRoleTemplate",
                max_length=100,
            ),
        ),
    ]
