# Generated by Django 5.2.10 on 2026-07-14 16:09

import django.db.models.deletion
import django.utils.timezone
import uuid
import vs_health.models.request_metrics
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("error_rate", "Error rate (%)"),
                            ("p95_latency", "p95 latency (ms)"),
                            ("queue_depth", "Queue depth"),
                            ("ssl_days_left", "SSL days left"),
                            ("uptime_pct", "Uptime (%)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "comparator",
                    models.CharField(
                        choices=[
                            ("gt", ">"),
                            ("gte", ">="),
                            ("lt", "<"),
                            ("lte", "<="),
                        ],
                        default="gt",
                        max_length=4,
                    ),
                ),
                ("threshold", models.FloatField()),
                (
                    "duration_sec",
                    models.PositiveIntegerField(
                        default=300, help_text="Sustained-for window before firing."
                    ),
                ),
                (
                    "severity",
                    models.IntegerField(
                        choices=[
                            (1, "SEV1 — Critical"),
                            (2, "SEV2 — Major"),
                            (3, "SEV3 — Minor"),
                            (4, "SEV4 — Low"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "target_queue",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="For queue_depth rules.",
                        max_length=64,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. 'PagerDuty', 'Slack #sre'.",
                        max_length=60,
                    ),
                ),
                ("is_enabled", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.CharField(blank=True, default="", max_length=60)),
                ("environment", models.CharField(default="production", max_length=40)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("deploy", "Deploy"),
                            ("flag", "Feature Flag"),
                            ("config", "Config Change"),
                        ],
                        default="deploy",
                        max_length=12,
                    ),
                ),
                (
                    "actor",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Who/what shipped it (e.g. 'CI/CD').",
                        max_length=120,
                    ),
                ),
                ("text", models.CharField(blank=True, default="", max_length=255)),
                (
                    "deployed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "ordering": ["-deployed_at"],
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Human ref, e.g. 'INC-2041'.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "severity",
                    models.IntegerField(
                        choices=[
                            (1, "SEV1 — Critical"),
                            (2, "SEV2 — Major"),
                            (3, "SEV3 — Minor"),
                            (4, "SEV4 — Low"),
                        ],
                        db_index=True,
                        default=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("investigating", "Investigating"),
                            ("identified", "Identified"),
                            ("monitoring", "Monitoring"),
                            ("resolved", "Resolved"),
                        ],
                        db_index=True,
                        default="investigating",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("auto", "Auto")],
                        default="manual",
                        max_length=8,
                    ),
                ),
                (
                    "owner_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Fallback owner name.",
                        max_length=120,
                    ),
                ),
                ("team", models.CharField(blank=True, default="", max_length=80)),
                ("summary", models.TextField(blank=True, default="")),
                ("postmortem", models.TextField(blank=True, default="")),
                ("affected_tenant_count", models.PositiveIntegerField(default=0)),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="IncidentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("opened", "Opened"),
                            ("ack", "Acknowledged"),
                            ("update", "Update"),
                            ("status", "Status change"),
                            ("resolved", "Resolved"),
                        ],
                        default="update",
                        max_length=12,
                    ),
                ),
                ("who", models.CharField(blank=True, default="", max_length=120)),
                ("text", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MonitoredService",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Stable id, e.g. 'api'.", max_length=40, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "group",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="UI grouping, e.g. 'Core'.",
                        max_length=40,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. 'Tier 1'.",
                        max_length=20,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("internal", "Internal"),
                            ("datastore", "Datastore"),
                            ("external", "External"),
                        ],
                        default="internal",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=12,
                    ),
                ),
                ("status_changed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary probe/display config.",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="QueueSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "captured_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("queue_name", models.CharField(db_index=True, max_length=64)),
                (
                    "depth",
                    models.PositiveIntegerField(
                        default=0, help_text="Messages waiting in the broker."
                    ),
                ),
                (
                    "throughput_per_min",
                    models.FloatField(
                        default=0.0, help_text="Tasks completed in the trailing minute."
                    ),
                ),
                ("failed", models.PositiveIntegerField(default=0)),
                ("retrying", models.PositiveIntegerField(default=0)),
                ("dead", models.PositiveIntegerField(default=0)),
                ("avg_duration_sec", models.FloatField(blank=True, null=True)),
                ("workers_active", models.PositiveIntegerField(default=0)),
                ("workers_idle", models.PositiveIntegerField(default=0)),
                (
                    "retry_storm",
                    models.BooleanField(
                        default=False, help_text="Abnormal retry spike detected."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                            ("unknown", "Unknown"),
                        ],
                        default="healthy",
                        max_length=12,
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bucket_start",
                    models.DateTimeField(
                        db_index=True, help_text="Start of the 1-minute window (UTC)."
                    ),
                ),
                ("route", models.CharField(db_index=True, max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("request_count", models.PositiveIntegerField(default=0)),
                ("status_2xx", models.PositiveIntegerField(default=0)),
                ("status_3xx", models.PositiveIntegerField(default=0)),
                ("status_4xx", models.PositiveIntegerField(default=0)),
                ("status_5xx", models.PositiveIntegerField(default=0)),
                ("throttled_count", models.PositiveIntegerField(default=0)),
                ("latency_sum_ms", models.FloatField(default=0.0)),
                ("latency_max_ms", models.FloatField(default=0.0)),
                (
                    "latency_hist",
                    models.JSONField(
                        default=vs_health.models.request_metrics._empty_hist,
                        help_text="Counts per LATENCY_BUCKETS_MS bucket (+overflow).",
                    ),
                ),
            ],
            options={
                "ordering": ["-bucket_start"],
            },
        ),
        migrations.CreateModel(
            name="SLO",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=120)),
                (
                    "target_pct",
                    models.DecimalField(decimal_places=3, default=99.9, max_digits=6),
                ),
                ("window_days", models.PositiveSmallIntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["service__sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="UptimeCheck",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("http", "HTTP"),
                            ("tcp", "TCP"),
                            ("redis", "Redis ping"),
                            ("postgres", "Postgres query"),
                            ("ssl", "SSL expiry"),
                            ("internal", "Internal/derived"),
                        ],
                        default="http",
                        max_length=12,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="URL / host:port / dsn / domain.",
                        max_length=500,
                    ),
                ),
                ("interval_sec", models.PositiveIntegerField(default=300)),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional probe origin, e.g. 'los'.",
                        max_length=20,
                    ),
                ),
                (
                    "expected",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="e.g. {'status': 200, 'warn_ms': 400}.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["service__sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="UptimeCheckResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=12,
                    ),
                ),
                ("response_ms", models.FloatField(blank=True, null=True)),
                ("status_code", models.PositiveIntegerField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "meta",
                    models.JSONField(
                        blank=True, default=dict, help_text="e.g. {'ssl_days_left': 9}."
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_at"],
            },
        ),
        migrations.CreateModel(
            name="UptimeDailyRollup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("day", models.DateField(db_index=True)),
                (
                    "uptime_pct",
                    models.DecimalField(decimal_places=4, default=100, max_digits=7),
                ),
                (
                    "worst_status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                            ("unknown", "Unknown"),
                        ],
                        default="healthy",
                        max_length=12,
                    ),
                ),
                ("total_checks", models.PositiveIntegerField(default=0)),
                ("failed_checks", models.PositiveIntegerField(default=0)),
                ("avg_response_ms", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-day"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "severity",
                    models.IntegerField(
                        choices=[
                            (1, "SEV1 — Critical"),
                            (2, "SEV2 — Major"),
                            (3, "SEV3 — Minor"),
                            (4, "SEV4 — Low"),
                        ],
                        default=2,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("value", models.FloatField(blank=True, null=True)),
                ("threshold", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("firing", "Firing"), ("resolved", "Resolved")],
                        db_index=True,
                        default="firing",
                        max_length=10,
                    ),
                ),
                (
                    "fired_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="vs_health.alertrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-fired_at"],
            },
        ),
    ]
