# Generated by Django 5.2.10 on 2026-07-14 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vs_health", "0001_initial"),
        ("vs_tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_incidents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="incident",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts",
                to="vs_health.incident",
            ),
        ),
        migrations.AddField(
            model_name="incidentevent",
            name="incident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeline",
                to="vs_health.incident",
            ),
        ),
        migrations.AddIndex(
            model_name="monitoredservice",
            index=models.Index(
                fields=["is_active", "current_status"],
                name="vs_health_m_is_acti_243562_idx",
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="services",
            field=models.ManyToManyField(
                blank=True, related_name="incidents", to="vs_health.monitoredservice"
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="target_service",
            field=models.ForeignKey(
                blank=True,
                help_text="Null = applies platform-wide.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_rules",
                to="vs_health.monitoredservice",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts",
                to="vs_health.monitoredservice",
            ),
        ),
        migrations.AddIndex(
            model_name="queuesnapshot",
            index=models.Index(
                fields=["queue_name", "-captured_at"],
                name="vs_health_q_queue_n_dacaa4_idx",
            ),
        ),
        migrations.AddField(
            model_name="requestmetric",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="slo",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slos",
                to="vs_health.monitoredservice",
            ),
        ),
        migrations.AddField(
            model_name="uptimecheck",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checks",
                to="vs_health.monitoredservice",
            ),
        ),
        migrations.AddField(
            model_name="uptimecheckresult",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="check_results",
                to="vs_health.monitoredservice",
            ),
        ),
        migrations.AddField(
            model_name="uptimecheckresult",
            name="uptime_check",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="vs_health.uptimecheck",
            ),
        ),
        migrations.AddField(
            model_name="uptimedailyrollup",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_uptime",
                to="vs_health.monitoredservice",
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["status", "-started_at"], name="vs_health_i_status_88383e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["severity", "status"], name="vs_health_i_severit_f4550b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["status", "-fired_at"], name="vs_health_a_status_bacca1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="requestmetric",
            index=models.Index(
                fields=["bucket_start", "route"], name="vs_health_r_bucket__8a109f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="requestmetric",
            index=models.Index(
                fields=["bucket_start", "tenant"], name="vs_health_r_bucket_tenant_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="requestmetric",
            unique_together={("bucket_start", "route", "method", "tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="slo",
            unique_together={("service", "name")},
        ),
        migrations.AddIndex(
            model_name="uptimecheckresult",
            index=models.Index(
                fields=["service", "-checked_at"], name="vs_health_u_service_8693a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uptimecheckresult",
            index=models.Index(
                fields=["uptime_check", "-checked_at"],
                name="vs_health_u_uptime__57a5a3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="uptimedailyrollup",
            index=models.Index(
                fields=["service", "-day"], name="vs_health_u_service_191053_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="uptimedailyrollup",
            unique_together={("service", "day")},
        ),
    ]
