# Generated by Django 5.2.10 on 2026-09-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_health", "0003_alert_delivery_and_sustained_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="fault_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Stable identity of one recurring configuration fault, matched exactly so a detector that runs per request opens one incident. Blank for operator-authored and alert-driven incidents.",
                max_length=120,
            ),
        ),
    ]
