# Generated by Django 5.2.10 on 2026-06-12 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("vs_schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Short category for filtering: import, export, email, system…",
                        max_length=64,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human description shown in the queue UI.",
                        max_length=255,
                    ),
                ),
                ("task_name", models.CharField(blank=True, default="", max_length=255)),
                ("celery_task_id", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="QUEUED",
                        max_length=12,
                    ),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="0–100 when the task reports progress.",
                        null=True,
                    ),
                ),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who triggered the task. Null for system/scheduled runs.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="background_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="background_jobs",
                        to="vs_schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "-created_at"],
                        name="core_backgr_owner_i_b5ae8e_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="core_backgr_status_9d70dc_idx",
                    ),
                    models.Index(
                        fields=["kind", "-created_at"],
                        name="core_backgr_kind_819e49_idx",
                    ),
                ],
            },
        ),
    ]
