# Generated by Django 5.2.10 on 2026-07-14 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("vs_tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="backgroundjob",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Who triggered the task. Null for system/scheduled runs.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="background_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="backgroundjob",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="background_jobs",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="storedfile",
            index=models.Index(
                fields=["created_at"], name="core_stored_created_39a011_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="backgroundjob",
            index=models.Index(
                fields=["owner", "-created_at"], name="core_backgr_owner_i_b5ae8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="backgroundjob",
            index=models.Index(
                fields=["status", "-created_at"], name="core_backgr_status_9d70dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="backgroundjob",
            index=models.Index(
                fields=["kind", "-created_at"], name="core_backgr_kind_819e49_idx"
            ),
        ),
    ]
