# Generated by Django 5.2.10 on 2026-07-27 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="backgroundjob",
            name="notify_owner",
            field=models.BooleanField(
                default=True,
                help_text="Whether the owner gets an in-app notification when the task ends. False for per-recipient fan-out plumbing (one invitation email per imported row), where one notification per job would spam the actor — the row is still tracked in View Queues.",
            ),
        ),
        migrations.AlterField(
            model_name="backgroundjob",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="The ACTOR who triggered the task — never the subject the task acts on. An invitation email to Jane queued by admin Ada is owned by Ada. Null for system/scheduled runs.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="background_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
