# Generated by Django 5.2.10 on 2026-06-12 09:47

from django.db import migrations, models


def _drop_celery_results_tables(apps, schema_editor):
    """django-celery-results was retired (core.BackgroundJob supersedes it).

    Drop its orphaned tables and bookkeeping on databases that had it
    installed; fresh databases never create them (IF EXISTS).
    """
    with schema_editor.connection.cursor() as cur:
        for table in (
            "django_celery_results_taskresult",
            "django_celery_results_chordcounter",
            "django_celery_results_groupresult",
        ):
            cur.execute(f'DROP TABLE IF EXISTS "{table}" CASCADE')
        cur.execute(
            "DELETE FROM django_migrations WHERE app = 'django_celery_results'"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_backgroundjob"),
    ]

    operations = [
        migrations.RunPython(_drop_celery_results_tables, migrations.RunPython.noop),
        migrations.AddField(
            model_name="backgroundjob",
            name="traceback",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="backgroundjob",
            name="worker",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
