# Generated by Django 5.2.10 on 2026-08-26 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_backgroundjob_notify_owner_alter_backgroundjob_owner"),
        ("vs_tenants", "0008_alter_branch_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskDiagnostic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(blank=True, default="", max_length=255)),
                ("raw_error", models.TextField(blank=True, default="")),
                ("raw_traceback", models.TextField(blank=True, default="")),
                ("raw_result", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Stamped at write time from TASK_DIAGNOSTIC_RETENTION_DAYS.",
                    ),
                ),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnostic",
                        to="core.backgroundjob",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_diagnostics",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-created_at"],
                        name="core_taskdi_tenant__d2f3b9_idx",
                    )
                ],
            },
        ),
    ]
