# Generated by Django 5.2.10 on 2026-07-12 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_backgroundjob_tenant"),
        ("vs_tenants", "0004_backfill_business_tenants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backgroundjob",
            name="school",
        ),
        migrations.AlterField(
            model_name="backgroundjob",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="background_jobs",
                to="vs_tenants.tenant",
            ),
        ),
    ]
