# Generated by Django 5.2.10 on 2026-08-26 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0004_taskdiagnostic"),
        ("vs_tenants", "0008_alter_branch_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="storedfile",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Whoever was acting when the bytes were written, for audit.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stored_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="storedfile",
            name="owner_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stored_files",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="storedfile",
            name="owner_field",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Which file field on the owning record points here.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="storedfile",
            name="owner_object_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="storedfile",
            name="revoked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when the file stops being current - superseded by a re-upload, or its record deleted. Revoking empties the bytes and closes the URL; it does not remove the row, so an audit still shows the file existed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storedfile",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="The customer whose file this is. Null means the bytes were written with no tenant in context (a management command, a scheduled job); such a row is never served through /media/.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stored_files",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="storedfile",
            index=models.Index(
                fields=["tenant"], name="core_stored_tenant__2eea1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storedfile",
            index=models.Index(
                fields=["owner_content_type", "owner_object_id"],
                name="core_stored_owner_c_70c09e_idx",
            ),
        ),
    ]
