# Generated by Django 5.2.10 on 2026-09-26 04:51

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vs_tenants", "0010_remove_branch__type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_type", models.CharField(max_length=64)),
                ("record_id", models.CharField(max_length=64)),
                ("owners", models.JSONField(blank=True, default=list)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_baseline", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("data", models.JSONField(default=dict)),
                ("changed", models.JSONField(blank=True, default=list)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["record_type", "record_id", "recorded_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["record_type", "record_id", "recorded_at"],
                        name="vs_hist_record_time",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["owners"], name="vs_hist_owners_gin"
                    ),
                ],
            },
        ),
    ]
