# Generated by Django 5.2.10 on 2026-09-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_history", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackingStart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_type", models.CharField(max_length=64, unique=True)),
                ("started_at", models.DateTimeField()),
            ],
        ),
    ]
