# Generated by Django 5.2.10 on 2026-04-10 14:58

import django.utils.timezone
import vs_import_data.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportAuditLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("action", models.CharField(max_length=100)),
                ("entity_type", models.CharField(blank=True, max_length=100)),
                ("entity_id", models.CharField(blank=True, max_length=100)),
                ("before_data", models.JSONField(blank=True, default=dict)),
                ("after_data", models.JSONField(blank=True, default=dict)),
                ("diff_data", models.JSONField(blank=True, default=dict)),
                ("message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "dataset_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("schools", "Schools"),
                            ("branches", "Branches"),
                            ("students", "Students"),
                            ("staff", "Staff"),
                            ("classes", "Classes / Structure"),
                            ("fees", "Fees"),
                            ("vendors", "Vendors"),
                            ("historical", "Historical Data"),
                            ("generic", "Generic / Unknown"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=vs_import_data.models.import_file_upload_to
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("csv", "CSV"),
                            ("xlsx", "Excel (.xlsx)"),
                            ("xls", "Excel (.xls)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("uploaded", "Uploaded"),
                            ("detecting", "Detecting Dataset Type"),
                            ("mapping_required", "Mapping Required"),
                            ("validating", "Validating"),
                            ("validation_failed", "Validation Failed"),
                            ("ready_to_import", "Ready To Import"),
                            ("import_queued", "Import Queued"),
                            ("import_running", "Import Running"),
                            ("import_partial", "Import Partial"),
                            ("import_succeeded", "Import Succeeded"),
                            ("import_failed", "Import Failed"),
                            ("rolled_back", "Rolled Back"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="uploaded",
                        max_length=40,
                    ),
                ),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("total_columns", models.PositiveIntegerField(default=0)),
                ("header_row_index", models.PositiveIntegerField(default=1)),
                ("sheet_name", models.CharField(blank=True, max_length=255)),
                ("uploaded_headers", models.JSONField(blank=True, default=list)),
                (
                    "template_headers_snapshot",
                    models.JSONField(blank=True, default=list),
                ),
                ("structure_matches_template", models.BooleanField(default=False)),
                ("has_critical_errors", models.BooleanField(default=False)),
                ("is_ready_for_import", models.BooleanField(default=False)),
                ("validation_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "validation_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        help_text="Celery/RQ/background worker task identifier",
                        max_length=255,
                    ),
                ),
                ("progress_percent", models.PositiveSmallIntegerField(default=0)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("processed_rows", models.PositiveIntegerField(default=0)),
                ("succeeded_rows", models.PositiveIntegerField(default=0)),
                ("failed_rows", models.PositiveIntegerField(default=0)),
                ("skipped_rows", models.PositiveIntegerField(default=0)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=100)),
                ("last_error_message", models.TextField(blank=True)),
                ("rollback_started_at", models.DateTimeField(blank=True, null=True)),
                ("rollback_completed_at", models.DateTimeField(blank=True, null=True)),
                ("execution_summary", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportJobRowResult",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("row_number", models.PositiveIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("skip", "Skip"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_model", models.CharField(blank=True, max_length=150)),
                ("target_object_pk", models.CharField(blank=True, max_length=100)),
                ("status_message", models.TextField(blank=True)),
                ("error_details", models.JSONField(blank=True, default=dict)),
                ("row_payload", models.JSONField(blank=True, default=dict)),
                ("normalized_payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["row_number"],
            },
        ),
        migrations.CreateModel(
            name="ImportNotification",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Examples: validation_completed, import_succeeded, import_failed",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportRollbackRecord",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("reason", models.TextField(blank=True)),
                ("was_successful", models.BooleanField(default=False)),
                ("reverted_rows_count", models.PositiveIntegerField(default=0)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportRowCorrection",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("column_name", models.CharField(max_length=255)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("reason", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["row_number", "column_name", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportTemplate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Stable internal code. Example: students_master_v1",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "dataset_type",
                    models.CharField(
                        choices=[
                            ("schools", "Schools"),
                            ("branches", "Branches"),
                            ("students", "Students"),
                            ("staff", "Staff"),
                            ("classes", "Classes / Structure"),
                            ("fees", "Fees"),
                            ("vendors", "Vendors"),
                            ("historical", "Historical Data"),
                            ("generic", "Generic / Unknown"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(default="1.0", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "default_file_format",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("xlsx", "Excel (.xlsx)"),
                            ("xls", "Excel (.xls)"),
                        ],
                        default="xlsx",
                        max_length=10,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Plain-language instructions shown to the admin before download/upload.",
                    ),
                ),
                ("allow_sample_row", models.BooleanField(default=True)),
                (
                    "sample_row_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional example row shown in generated template file.",
                    ),
                ),
                (
                    "validation_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional dataset-wide rules or config.",
                    ),
                ),
                ("is_download_enabled", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["dataset_type", "name", "-version"],
            },
        ),
        migrations.CreateModel(
            name="ImportTemplateColumn",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "column_name",
                    models.CharField(
                        help_text="Exact spreadsheet header expected in uploaded file.",
                        max_length=255,
                    ),
                ),
                (
                    "target_field",
                    models.CharField(
                        help_text="Internal field the import engine uses.",
                        max_length=255,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Friendly name shown in docs/UI if needed.",
                        max_length=255,
                    ),
                ),
                (
                    "help_text",
                    models.TextField(
                        blank=True,
                        help_text="Explains what the admin should put in this column.",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("date", "Date"),
                            ("datetime", "Datetime"),
                            ("email", "Email"),
                            ("boolean", "Boolean"),
                            ("choice", "Choice"),
                        ],
                        default="string",
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("is_unique", models.BooleanField(default=False)),
                ("max_length", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "allowed_values",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Used when data_type=choice or where fixed values are expected.",
                    ),
                ),
                ("sample_value", models.CharField(blank=True, max_length=255)),
                ("default_value", models.CharField(blank=True, max_length=255)),
                ("column_order", models.PositiveIntegerField(default=1)),
                (
                    "reference_model",
                    models.CharField(
                        blank=True,
                        help_text="Example: Staff, Campus, ClassRoom",
                        max_length=255,
                    ),
                ),
                (
                    "reference_lookup_field",
                    models.CharField(
                        blank=True,
                        help_text="Example: full_name, name, code",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "ordering": ["column_order", "column_name"],
            },
        ),
        migrations.CreateModel(
            name="ImportValidationIssue",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("error", "Error"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("file_type_invalid", "File Type Invalid"),
                            ("file_empty", "File Empty"),
                            ("sheet_missing", "Sheet Missing"),
                            ("column_missing", "Required Column Missing"),
                            ("column_unknown", "Unknown Column"),
                            ("required_value_missing", "Required Value Missing"),
                            ("invalid_format", "Invalid Format"),
                            ("invalid_choice", "Invalid Choice"),
                            ("duplicate_record", "Duplicate Record"),
                            ("cross_reference_missing", "Cross Reference Missing"),
                            ("dataset_mismatch", "Dataset Type Mismatch"),
                            ("duplicate_mapping", "Duplicate Mapping"),
                            ("business_rule", "Business Rule Violation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                ("help_text", models.TextField(blank=True)),
                ("row_number", models.PositiveIntegerField(blank=True, null=True)),
                ("column_name", models.CharField(blank=True, max_length=255)),
                ("field_name", models.CharField(blank=True, max_length=255)),
                ("raw_value", models.TextField(blank=True)),
                ("normalized_value", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["row_number", "column_name", "created_at"],
            },
        ),
    ]
