# Generated by Django 5.2.13 on 2026-05-21 10:33

import django.db.models.deletion
import django.utils.timezone
import vs_import_data.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vs_schools", "0005_school_status_default_pending"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dataset_type",
                    models.CharField(
                        blank=True, choices=[("schools", "Schools")], max_length=30
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=vs_import_data.models.import_file_upload_to
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("csv", "CSV"),
                            ("xlsx", "Excel (.xlsx)"),
                            ("xls", "Excel (.xls)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("uploaded", "Uploaded"),
                            ("detecting", "Detecting Dataset Type"),
                            ("mapping_required", "Mapping Required"),
                            ("validating", "Validating"),
                            ("validation_failed", "Validation Failed"),
                            ("ready_to_import", "Ready To Import"),
                            ("import_queued", "Import Queued"),
                            ("import_running", "Import Running"),
                            ("import_partial", "Import Partial"),
                            ("import_succeeded", "Import Succeeded"),
                            ("import_failed", "Import Failed"),
                            ("rolled_back", "Rolled Back"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="uploaded",
                        max_length=40,
                    ),
                ),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("total_columns", models.PositiveIntegerField(default=0)),
                ("header_row_index", models.PositiveIntegerField(default=1)),
                ("sheet_name", models.CharField(blank=True, max_length=255)),
                ("uploaded_headers", models.JSONField(blank=True, default=list)),
                (
                    "template_headers_snapshot",
                    models.JSONField(blank=True, default=list),
                ),
                ("structure_matches_template", models.BooleanField(default=False)),
                ("has_critical_errors", models.BooleanField(default=False)),
                ("is_ready_for_import", models.BooleanField(default=False)),
                ("validation_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "validation_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_batches",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_batches",
                        to="vs_schools.school",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        help_text="Celery/RQ/background worker task identifier",
                        max_length=255,
                    ),
                ),
                ("progress_percent", models.PositiveSmallIntegerField(default=0)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("processed_rows", models.PositiveIntegerField(default=0)),
                ("succeeded_rows", models.PositiveIntegerField(default=0)),
                ("failed_rows", models.PositiveIntegerField(default=0)),
                ("skipped_rows", models.PositiveIntegerField(default=0)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=100)),
                ("last_error_message", models.TextField(blank=True)),
                ("rollback_started_at", models.DateTimeField(blank=True, null=True)),
                ("rollback_completed_at", models.DateTimeField(blank=True, null=True)),
                ("execution_summary", models.JSONField(blank=True, default=dict)),
                (
                    "import_batch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_job",
                        to="vs_import_data.importbatch",
                    ),
                ),
                (
                    "queued_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="queued_import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportJobRowResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_number", models.PositiveIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("skip", "Skip"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_model", models.CharField(blank=True, max_length=150)),
                ("target_object_pk", models.CharField(blank=True, max_length=100)),
                ("status_message", models.TextField(blank=True)),
                ("error_details", models.JSONField(blank=True, default=dict)),
                ("row_payload", models.JSONField(blank=True, default=dict)),
                ("normalized_payload", models.JSONField(blank=True, default=dict)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="row_results",
                        to="vs_import_data.importjob",
                    ),
                ),
            ],
            options={
                "ordering": ["row_number"],
            },
        ),
        migrations.CreateModel(
            name="ImportNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        help_text="Examples: validation_completed, import_succeeded, import_failed",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="vs_import_data.importbatch",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportRollbackRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.TextField(blank=True)),
                ("was_successful", models.BooleanField(default=False)),
                ("reverted_rows_count", models.PositiveIntegerField(default=0)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="initiated_import_rollbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rollback_records",
                        to="vs_import_data.importjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportRowCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_number", models.PositiveIntegerField()),
                ("column_name", models.CharField(max_length=255)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "corrected_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_row_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="row_corrections",
                        to="vs_import_data.importbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["row_number", "column_name", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Stable internal code. Example: students_master_v1",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "dataset_type",
                    models.CharField(choices=[("schools", "Schools")], max_length=30),
                ),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(default="1.0", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "default_file_format",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("xlsx", "Excel (.xlsx)"),
                            ("xls", "Excel (.xls)"),
                        ],
                        default="xlsx",
                        max_length=10,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Plain-language instructions shown to the admin before download/upload.",
                    ),
                ),
                ("allow_sample_row", models.BooleanField(default=True)),
                (
                    "sample_row_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional example row shown in generated template file.",
                    ),
                ),
                (
                    "validation_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional dataset-wide rules or config.",
                    ),
                ),
                ("is_download_enabled", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_system_import_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_type", "name", "-version"],
            },
        ),
        migrations.AddField(
            model_name="importbatch",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Official system template chosen for this import batch.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="import_batches",
                to="vs_import_data.importtemplate",
            ),
        ),
        migrations.CreateModel(
            name="ImportTemplateColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "column_name",
                    models.CharField(
                        help_text="Exact spreadsheet header expected in uploaded file.",
                        max_length=255,
                    ),
                ),
                (
                    "target_field",
                    models.CharField(
                        help_text="Internal field the import engine uses.",
                        max_length=255,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Friendly name shown in docs/UI if needed.",
                        max_length=255,
                    ),
                ),
                (
                    "help_text",
                    models.TextField(
                        blank=True,
                        help_text="Explains what the admin should put in this column.",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("date", "Date"),
                            ("datetime", "Datetime"),
                            ("email", "Email"),
                            ("boolean", "Boolean"),
                            ("choice", "Choice"),
                        ],
                        default="string",
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("is_unique", models.BooleanField(default=False)),
                ("max_length", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "allowed_values",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Used when data_type=choice or where fixed values are expected.",
                    ),
                ),
                ("sample_value", models.CharField(blank=True, max_length=255)),
                ("default_value", models.CharField(blank=True, max_length=255)),
                ("column_order", models.PositiveIntegerField(default=1)),
                (
                    "reference_model",
                    models.CharField(
                        blank=True,
                        help_text="Example: Staff, Campus, ClassRoom",
                        max_length=255,
                    ),
                ),
                (
                    "reference_lookup_field",
                    models.CharField(
                        blank=True,
                        help_text="Example: full_name, name, code",
                        max_length=255,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="vs_import_data.importtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["column_order", "column_name"],
            },
        ),
        migrations.CreateModel(
            name="ImportValidationIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("error", "Error"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("file_type_invalid", "File Type Invalid"),
                            ("file_empty", "File Empty"),
                            ("sheet_missing", "Sheet Missing"),
                            ("column_missing", "Required Column Missing"),
                            ("column_unknown", "Unknown Column"),
                            ("required_value_missing", "Required Value Missing"),
                            ("invalid_format", "Invalid Format"),
                            ("invalid_choice", "Invalid Choice"),
                            ("duplicate_record", "Duplicate Record"),
                            ("cross_reference_missing", "Cross Reference Missing"),
                            ("dataset_mismatch", "Dataset Type Mismatch"),
                            ("duplicate_mapping", "Duplicate Mapping"),
                            ("business_rule", "Business Rule Violation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                ("help_text", models.TextField(blank=True)),
                ("row_number", models.PositiveIntegerField(blank=True, null=True)),
                ("column_name", models.CharField(blank=True, max_length=255)),
                ("field_name", models.CharField(blank=True, max_length=255)),
                ("raw_value", models.TextField(blank=True)),
                ("normalized_value", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_issues",
                        to="vs_import_data.importbatch",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_import_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["row_number", "column_name", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(fields=["status"], name="vs_import_d_status_dc59da_idx"),
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(
                fields=["started_at"], name="vs_import_d_started_5d4b98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importjobrowresult",
            index=models.Index(
                fields=["job", "action"], name="vs_import_d_job_id_18fd29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importjobrowresult",
            index=models.Index(
                fields=["job", "row_number"], name="vs_import_d_job_id_f52031_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="importjobrowresult",
            unique_together={("job", "row_number")},
        ),
        migrations.AddIndex(
            model_name="importnotification",
            index=models.Index(
                fields=["recipient", "status"], name="vs_import_d_recipie_63776c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importnotification",
            index=models.Index(
                fields=["event_type"], name="vs_import_d_event_t_6ab3d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importrowcorrection",
            index=models.Index(
                fields=["import_batch", "row_number"],
                name="vs_import_d_import__433283_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="importtemplate",
            index=models.Index(
                fields=["dataset_type", "status"], name="vs_import_d_dataset_05ff2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importtemplate",
            index=models.Index(fields=["code"], name="vs_import_d_code_6a2bcd_idx"),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["school", "status"], name="vs_import_d_school__f81fa8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["school", "dataset_type"], name="vs_import_d_school__c45910_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["branch", "status"], name="vs_import_d_branch__e52e55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["created_at"], name="vs_import_d_created_d24845_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importtemplatecolumn",
            index=models.Index(
                fields=["template", "column_order"],
                name="vs_import_d_templat_49ed89_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="importtemplatecolumn",
            index=models.Index(
                fields=["template", "is_required"],
                name="vs_import_d_templat_8589cf_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="importtemplatecolumn",
            unique_together={("template", "column_name"), ("template", "target_field")},
        ),
        migrations.AddIndex(
            model_name="importvalidationissue",
            index=models.Index(
                fields=["import_batch", "severity"],
                name="vs_import_d_import__eb0a16_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="importvalidationissue",
            index=models.Index(
                fields=["import_batch", "code"], name="vs_import_d_import__fa39bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importvalidationissue",
            index=models.Index(
                fields=["import_batch", "row_number"],
                name="vs_import_d_import__d89a92_idx",
            ),
        ),
    ]
