# Generated by Django 5.2.13 on 2026-04-11 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vs_import_data", "0001_initial"),
        ("vs_schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="importauditlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="import_audit_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="importauditlog",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="import_audit_logs",
                to="vs_schools.branch",
            ),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="import_batches",
                to="vs_schools.branch",
            ),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uploaded_import_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="importauditlog",
            name="import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="vs_import_data.importbatch",
            ),
        ),
        migrations.AddField(
            model_name="importjob",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="import_jobs",
                to="vs_schools.branch",
            ),
        ),
        migrations.AddField(
            model_name="importjob",
            name="import_batch",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="import_job",
                to="vs_import_data.importbatch",
            ),
        ),
        migrations.AddField(
            model_name="importjob",
            name="queued_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="queued_import_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="importauditlog",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="vs_import_data.importjob",
            ),
        ),
        migrations.AddField(
            model_name="importjobrowresult",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="row_results",
                to="vs_import_data.importjob",
            ),
        ),
        migrations.AddField(
            model_name="importnotification",
            name="import_batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="vs_import_data.importbatch",
            ),
        ),
        migrations.AddField(
            model_name="importnotification",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="import_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="importrollbackrecord",
            name="initiated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="initiated_import_rollbacks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="importrollbackrecord",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rollback_records",
                to="vs_import_data.importjob",
            ),
        ),
        migrations.AddField(
            model_name="importrowcorrection",
            name="corrected_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="import_row_corrections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="importrowcorrection",
            name="import_batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="row_corrections",
                to="vs_import_data.importbatch",
            ),
        ),
        migrations.AddField(
            model_name="importtemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_system_import_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Official system template chosen for this import batch.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="import_batches",
                to="vs_import_data.importtemplate",
            ),
        ),
        migrations.AddField(
            model_name="importtemplatecolumn",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="vs_import_data.importtemplate",
            ),
        ),
        migrations.AddField(
            model_name="importvalidationissue",
            name="import_batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="validation_issues",
                to="vs_import_data.importbatch",
            ),
        ),
        migrations.AddField(
            model_name="importvalidationissue",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_import_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(fields=["status"], name="vs_import_d_status_dc59da_idx"),
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(
                fields=["started_at"], name="vs_import_d_started_5d4b98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importauditlog",
            index=models.Index(
                fields=["branch", "action"], name="vs_import_d_branch__207f9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importauditlog",
            index=models.Index(
                fields=["import_batch"], name="vs_import_d_import__ab2c68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importauditlog",
            index=models.Index(fields=["job"], name="vs_import_d_job_id_0eed70_idx"),
        ),
        migrations.AddIndex(
            model_name="importjobrowresult",
            index=models.Index(
                fields=["job", "action"], name="vs_import_d_job_id_18fd29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importjobrowresult",
            index=models.Index(
                fields=["job", "row_number"], name="vs_import_d_job_id_f52031_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="importjobrowresult",
            unique_together={("job", "row_number")},
        ),
        migrations.AddIndex(
            model_name="importnotification",
            index=models.Index(
                fields=["recipient", "status"], name="vs_import_d_recipie_63776c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importnotification",
            index=models.Index(
                fields=["event_type"], name="vs_import_d_event_t_6ab3d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importrowcorrection",
            index=models.Index(
                fields=["import_batch", "row_number"],
                name="vs_import_d_import__433283_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="importtemplate",
            index=models.Index(
                fields=["dataset_type", "status"], name="vs_import_d_dataset_05ff2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importtemplate",
            index=models.Index(fields=["code"], name="vs_import_d_code_6a2bcd_idx"),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["branch", "status"], name="vs_import_d_branch__e52e55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["branch", "dataset_type"], name="vs_import_d_branch__85fdab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["created_at"], name="vs_import_d_created_d24845_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importtemplatecolumn",
            index=models.Index(
                fields=["template", "column_order"],
                name="vs_import_d_templat_49ed89_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="importtemplatecolumn",
            index=models.Index(
                fields=["template", "is_required"],
                name="vs_import_d_templat_8589cf_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="importtemplatecolumn",
            unique_together={("template", "column_name"), ("template", "target_field")},
        ),
        migrations.AddIndex(
            model_name="importvalidationissue",
            index=models.Index(
                fields=["import_batch", "severity"],
                name="vs_import_d_import__eb0a16_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="importvalidationissue",
            index=models.Index(
                fields=["import_batch", "code"], name="vs_import_d_import__fa39bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importvalidationissue",
            index=models.Index(
                fields=["import_batch", "row_number"],
                name="vs_import_d_import__d89a92_idx",
            ),
        ),
    ]
