# Generated by Django 5.2.13 on 2026-05-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_import_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="detected_columns",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="preview_rows",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="source",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="template_version",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="validation_summary",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="importtemplate",
            name="default_file_format",
            field=models.CharField(
                choices=[
                    ("csv", "CSV"),
                    ("xlsx", "Excel (.xlsx)"),
                    ("xls", "Excel (.xls)"),
                ],
                default="csv",
                max_length=10,
            ),
        ),
    ]
