# Generated by Django 5.2.13 on 2026-05-22 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_import_data", "0002_add_missing_fields_to_importbatch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importbatch",
            name="detected_columns",
        ),
        migrations.RemoveField(
            model_name="importbatch",
            name="source",
        ),
        migrations.RemoveField(
            model_name="importbatch",
            name="template_version",
        ),
    ]
