# Generated by Django 5.2.13 on 2026-04-25 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_import_data", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImportAuditLog",
        ),
    ]
