# Generated by Django 5.2.10 on 2026-07-12 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_import_data", "0003_importbatch_tenant"),
        ("vs_schools", "0004_require_school_tenant"),
        ("vs_tenants", "0004_backfill_business_tenants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="importbatch",
            name="vs_import_d_school__f81fa8_idx",
        ),
        migrations.RemoveIndex(
            model_name="importbatch",
            name="vs_import_d_school__c45910_idx",
        ),
        migrations.RemoveField(
            model_name="importbatch",
            name="school",
        ),
        migrations.AlterField(
            model_name="importbatch",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="import_batches",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["tenant", "status"], name="vs_import_d_tenant__a029f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["tenant", "dataset_type"], name="vs_import_d_tenant__cc3a36_idx"
            ),
        ),
    ]
