# Generated by Django 5.2.13 on 2026-05-22 17:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_import_data", "0003_remove_detected_columns_from_importbatch"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImportRowCorrection",
        ),
    ]
