# Generated by Django 5.2.13 on 2026-05-23 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_import_data", "0004_remove_importrowcorrection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importbatch",
            name="dataset_type",
            field=models.CharField(
                blank=True,
                choices=[("schools", "Schools"), ("branches", "Branches")],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="import_batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="import_jobs",
                to="vs_import_data.importbatch",
            ),
        ),
        migrations.AlterField(
            model_name="importtemplate",
            name="dataset_type",
            field=models.CharField(
                choices=[("schools", "Schools"), ("branches", "Branches")],
                max_length=30,
            ),
        ),
    ]
