# Generated by Django 5.2.13 on 2026-05-24 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_import_data", "0005_importjob_onetoonefield_to_foreignkey"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="importtemplate",
            options={"ordering": ["dataset_type", "name"]},
        ),
        migrations.RemoveField(
            model_name="importtemplate",
            name="version",
        ),
    ]
