# Generated by Django 5.2.10 on 2026-08-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_import_data", "0006_retarget_branch_to_vs_tenants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importtemplatecolumn",
            name="reference_model",
            field=models.CharField(
                blank=True,
                help_text="Example: Staff, Branch, ClassRoom",
                max_length=255,
            ),
        ),
    ]
