# Generated by Django 5.2.10 on 2026-08-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_import_data", "0007_alter_importtemplatecolumn_reference_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("uploaded", "Uploaded"),
                    ("detecting", "Detecting Dataset Type"),
                    ("mapping_required", "Mapping Required"),
                    ("validating", "Validating"),
                    ("validation_failed", "Validation Failed"),
                    ("ready_to_import", "Ready To Import"),
                    ("import_queued", "Import Queued"),
                    ("import_running", "Import Running"),
                    ("import_partial", "Import Partial"),
                    ("import_succeeded", "Import Succeeded"),
                    ("import_failed", "Import Failed"),
                    ("rolled_back", "Rolled Back"),
                    ("partially_rolled_back", "Partially Rolled Back"),
                    ("cancelled", "Cancelled"),
                ],
                default="uploaded",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("rolled_back", "Rolled Back"),
                    ("partially_rolled_back", "Partially Rolled Back"),
                ],
                default="queued",
                max_length=30,
            ),
        ),
    ]
