# Generated by Django 5.2.10 on 2026-06-11 13:17

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_import_data", "0007_fix_stale_school_branch_all_tables"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="importbatch",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelManagers(
            name="importbatch",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
