# Generated by Django 5.2.10 on 2026-07-14 16:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("metric", models.CharField(blank=True, default="", max_length=120)),
                ("target", models.CharField(blank=True, default="", max_length=120)),
                ("deadline", models.DateField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        max_length=8,
                    ),
                ),
                (
                    "department",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("is_done", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "vs_todo_task",
                "ordering": ["is_done", "deadline", "-priority"],
            },
        ),
    ]
