# Generated by Django 5.2.13 on 2026-06-11 19:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("metric", models.CharField(blank=True, default="", max_length=120)),
                ("target", models.CharField(blank=True, default="", max_length=120)),
                ("deadline", models.DateField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        max_length=8,
                    ),
                ),
                (
                    "department",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("is_done", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="todo_tasks_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todo_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "vs_todo_task",
                "ordering": ["is_done", "deadline", "-priority"],
                "indexes": [
                    models.Index(
                        fields=["assignee", "is_done"],
                        name="vs_todo_tas_assigne_5cae5e_idx",
                    ),
                    models.Index(
                        fields=["assignee", "deadline"],
                        name="vs_todo_tas_assigne_d3f973_idx",
                    ),
                    models.Index(
                        fields=["assigned_by"], name="vs_todo_tas_assigne_6c2904_idx"
                    ),
                    models.Index(
                        fields=["is_done", "deadline"],
                        name="vs_todo_tas_is_done_929ed8_idx",
                    ),
                ],
            },
        ),
    ]
