# Generated by Django 5.2.10 on 2026-07-14 16:09

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vs_finance", "0001_initial"),
        ("vs_schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Value tied to this milestone, in kobo."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("MISSED", "Missed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("line_no", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["contract", "line_no", "due_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="GoodsReceivedNoteLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "accepted_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "rejected_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "unit_price",
                    vs_finance.money.MoneyField(
                        help_text="Price per unit, in kobo (from the PO)."
                    ),
                ),
                (
                    "value_amount",
                    vs_finance.money.MoneyField(
                        help_text="accepted_qty × unit_price, in kobo."
                    ),
                ),
                ("line_no", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["grn", "line_no", "id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("order_date", models.DateField()),
                ("expected_date", models.DateField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                (
                    "subtotal",
                    vs_finance.money.MoneyField(help_text="Net of tax, in kobo."),
                ),
                (
                    "tax_total",
                    vs_finance.money.MoneyField(help_text="Total tax, in kobo."),
                ),
                (
                    "total",
                    vs_finance.money.MoneyField(
                        help_text="subtotal + tax_total, in kobo."
                    ),
                ),
                (
                    "approval_state",
                    models.CharField(
                        choices=[
                            ("NOT_SUBMITTED", "Not submitted"),
                            ("PENDING", "Pending approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="NOT_SUBMITTED",
                        help_text="Spend-approval state driven by vs_workflow (overlay; not the ledger status).",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=1, max_digits=14),
                ),
                (
                    "unit_price",
                    vs_finance.money.MoneyField(
                        help_text="Agreed price per unit, in kobo."
                    ),
                ),
                (
                    "net_amount",
                    vs_finance.money.MoneyField(
                        help_text="quantity × unit_price, in kobo."
                    ),
                ),
                (
                    "tax_amount",
                    vs_finance.money.MoneyField(help_text="Tax on the net, in kobo."),
                ),
                (
                    "received_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "invoiced_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("line_no", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["purchase_order", "line_no", "id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("request_date", models.DateField()),
                ("needed_by", models.DateField(blank=True, null=True)),
                (
                    "justification",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "estimated_total",
                    vs_finance.money.MoneyField(
                        help_text="Rolled-up estimate from the lines, in kobo."
                    ),
                ),
                (
                    "approval_state",
                    models.CharField(
                        choices=[
                            ("NOT_SUBMITTED", "Not submitted"),
                            ("PENDING", "Pending approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="NOT_SUBMITTED",
                        help_text="Spend-approval state driven by vs_workflow (overlay; not the ledger status).",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequisitionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=1, max_digits=14),
                ),
                (
                    "estimated_unit_price",
                    vs_finance.money.MoneyField(
                        help_text="Estimated price per unit, in kobo."
                    ),
                ),
                ("line_no", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["requisition", "line_no", "id"],
            },
        ),
        migrations.CreateModel(
            name="RequestForQuotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                (
                    "rfq_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ISSUED", "Issued"),
                            ("AWARDED", "Awarded"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("issue_date", models.DateField()),
                (
                    "response_due_date",
                    models.DateField(
                        blank=True,
                        help_text="Closing date for vendor responses.",
                        null=True,
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RfqLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=1, max_digits=14),
                ),
                ("line_no", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["rfq", "line_no", "id"],
            },
        ),
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Stock code, unique within the entity.", max_length=40
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "unit_of_measure",
                    models.CharField(blank=True, default="each", max_length=24),
                ),
                (
                    "reorder_level",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="On-hand at/below which the item is flagged for reorder.",
                        max_digits=14,
                    ),
                ),
                (
                    "reorder_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Suggested quantity to reorder when low.",
                        max_digits=14,
                    ),
                ),
                (
                    "on_hand_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Live quantity on hand (maintained by the stock ledger).",
                        max_digits=16,
                    ),
                ),
                (
                    "stock_value",
                    vs_finance.money.MoneyField(
                        help_text="Total value of on-hand stock, in kobo (weighted-average basis)."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["entity", "code"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("RECEIPT", "Receipt"),
                            ("ISSUE", "Issue"),
                            ("ADJUSTMENT", "Adjustment"),
                        ],
                        max_length=16,
                    ),
                ),
                ("movement_date", models.DateField()),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Signed quantity change (+ receipt, − issue).",
                        max_digits=16,
                    ),
                ),
                (
                    "value_amount",
                    models.BigIntegerField(
                        help_text="Signed value change in kobo (+ in, − out)."
                    ),
                ),
                (
                    "balance_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="On-hand quantity after this movement.",
                        max_digits=16,
                    ),
                ),
                (
                    "balance_value",
                    vs_finance.money.MoneyField(
                        help_text="Stock value (kobo) after this movement."
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "ordering": ["-movement_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Vendor code, unique within the entity.",
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
                ("address", models.TextField(blank=True, default="")),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="TIN / tax identifier.",
                        max_length=32,
                    ),
                ),
                ("bank_name", models.CharField(blank=True, default="", max_length=120)),
                (
                    "bank_account_number",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "bank_account_name",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("NET_0", "Due on receipt"),
                            ("NET_7", "Net 7 days"),
                            ("NET_14", "Net 14 days"),
                            ("NET_30", "Net 30 days"),
                            ("NET_60", "Net 60 days"),
                            ("NET_90", "Net 90 days"),
                        ],
                        default="NET_30",
                        max_length=8,
                    ),
                ),
                (
                    "kyc_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=8,
                    ),
                ),
                (
                    "risk",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="LOW",
                        max_length=6,
                    ),
                ),
                (
                    "on_hold",
                    models.BooleanField(
                        default=False, help_text="Block new POs/payments while True."
                    ),
                ),
                (
                    "opening_balance",
                    vs_finance.money.MoneyField(
                        help_text="Opening AP balance in kobo (informational)."
                    ),
                ),
                (
                    "source_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("source_id", models.CharField(blank=True, default="", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["entity", "code"],
            },
        ),
        migrations.CreateModel(
            name="VendorCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique within the entity.", max_length=32
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "vendor categories",
                "ordering": ["entity", "code"],
            },
        ),
        migrations.CreateModel(
            name="VendorContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        help_text="Contract reference, unique within the entity.",
                        max_length=64,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("TERMINATED", "Terminated"),
                            ("RENEWED", "Renewed"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "contract_value",
                    vs_finance.money.MoneyField(
                        help_text="Total committed value over the term, in kobo."
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("NET_0", "Due on receipt"),
                            ("NET_7", "Net 7 days"),
                            ("NET_14", "Net 14 days"),
                            ("NET_30", "Net 30 days"),
                            ("NET_60", "Net 60 days"),
                            ("NET_90", "Net 90 days"),
                        ],
                        default="NET_30",
                        max_length=8,
                    ),
                ),
                ("auto_renew", models.BooleanField(default=False)),
                (
                    "renewal_notice_days",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="Days before end_date to flag the contract for renewal.",
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "ordering": ["entity", "-end_date", "reference"],
            },
        ),
        migrations.CreateModel(
            name="VendorInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("invoice_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "vendor_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The vendor's own invoice number.",
                        max_length=64,
                    ),
                ),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                (
                    "subtotal",
                    vs_finance.money.MoneyField(help_text="Net of tax, in kobo."),
                ),
                (
                    "tax_total",
                    vs_finance.money.MoneyField(help_text="Total tax, in kobo."),
                ),
                (
                    "total",
                    vs_finance.money.MoneyField(
                        help_text="subtotal + tax_total, in kobo."
                    ),
                ),
                (
                    "amount_paid",
                    vs_finance.money.MoneyField(
                        help_text="Cash allocated to this bill, in kobo."
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "Unpaid"),
                            ("PARTIAL", "Partially Paid"),
                            ("PAID", "Paid"),
                        ],
                        default="UNPAID",
                        max_length=8,
                    ),
                ),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("NOT_MATCHED", "Not matched"),
                            ("AUTO_MATCHED", "Auto-matched"),
                            ("UNDER_RECEIVED", "Under received"),
                            ("OVER_BILLED", "Over billed"),
                            ("PRICE_VARIANCE", "Price variance"),
                        ],
                        default="NOT_MATCHED",
                        max_length=16,
                    ),
                ),
                (
                    "approval_state",
                    models.CharField(
                        choices=[
                            ("NOT_SUBMITTED", "Not submitted"),
                            ("PENDING", "Pending approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="NOT_SUBMITTED",
                        help_text="Spend-approval state driven by vs_workflow (overlay; not the ledger status).",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VendorInvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=1, max_digits=14),
                ),
                (
                    "unit_price",
                    vs_finance.money.MoneyField(
                        help_text="Price per unit billed, in kobo."
                    ),
                ),
                (
                    "net_amount",
                    vs_finance.money.MoneyField(
                        help_text="quantity × unit_price, in kobo."
                    ),
                ),
                (
                    "tax_amount",
                    vs_finance.money.MoneyField(help_text="Tax on the net, in kobo."),
                ),
                ("line_no", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["vendor_invoice", "line_no", "id"],
            },
        ),
        migrations.CreateModel(
            name="VendorPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CARD", "Card"),
                            ("CHEQUE", "Cheque"),
                            ("ONLINE", "Online / Gateway"),
                            ("OTHER", "Other"),
                        ],
                        default="BANK_TRANSFER",
                        max_length=16,
                    ),
                ),
                (
                    "gross_amount",
                    vs_finance.money.MoneyField(
                        help_text="Total liability settled (Dr AP), in kobo."
                    ),
                ),
                (
                    "wht_amount",
                    vs_finance.money.MoneyField(
                        help_text="Withholding tax retained (Cr WHT payable), in kobo."
                    ),
                ),
                (
                    "net_amount",
                    vs_finance.money.MoneyField(
                        help_text="Cash actually paid out (Cr bank) = gross − WHT, in kobo."
                    ),
                ),
                (
                    "allocated_amount",
                    vs_finance.money.MoneyField(
                        help_text="Gross applied to bills, in kobo."
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VendorPaymentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Gross applied to this bill, in kobo."
                    ),
                ),
            ],
            options={
                "ordering": ["payment", "id"],
            },
        ),
        migrations.CreateModel(
            name="VendorQuotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "quotation_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("AWARDED", "Awarded"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("quote_date", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "lead_time_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Promised delivery lead time in days.",
                        null=True,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "subtotal",
                    vs_finance.money.MoneyField(help_text="Net of tax, in kobo."),
                ),
                (
                    "tax_total",
                    vs_finance.money.MoneyField(help_text="Total tax, in kobo."),
                ),
                (
                    "total",
                    vs_finance.money.MoneyField(
                        help_text="subtotal + tax_total, in kobo."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VendorQuotationLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=1, max_digits=14),
                ),
                (
                    "unit_price",
                    vs_finance.money.MoneyField(
                        help_text="Quoted price per unit, in kobo."
                    ),
                ),
                (
                    "net_amount",
                    vs_finance.money.MoneyField(
                        help_text="quantity × unit_price, in kobo."
                    ),
                ),
                (
                    "tax_amount",
                    vs_finance.money.MoneyField(help_text="Tax on the net, in kobo."),
                ),
                ("line_no", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["quotation", "line_no", "id"],
            },
        ),
        migrations.CreateModel(
            name="CatalogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Item code, unique within the entity.", max_length=40
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        blank=True,
                        default="each",
                        help_text="e.g. 'each', 'box', 'hour'.",
                        max_length=24,
                    ),
                ),
                (
                    "lead_time_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Typical delivery lead time, in days.",
                        null=True,
                    ),
                ),
                (
                    "standard_unit_price",
                    vs_finance.money.MoneyField(
                        help_text="Indicative price per unit, in kobo."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "default_expense_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="GL account the cost lands in (seeds purchase lines).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_items",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "default_tax_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_items",
                        to="vs_finance.taxcode",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_items",
                        to="vs_finance.ledgerentity",
                    ),
                ),
            ],
            options={
                "ordering": ["entity", "code"],
            },
        ),
        migrations.CreateModel(
            name="GoodsReceivedNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("received_date", models.DateField()),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                (
                    "total_value",
                    vs_finance.money.MoneyField(
                        help_text="Accepted value (ex-tax), in kobo."
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_schools.branch",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
