# Generated by Django 5.2.10 on 2026-06-06 19:15

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vs_finance", "0008_alter_financeauditlog_action"),
        ("vs_schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("order_date", models.DateField()),
                ("expected_date", models.DateField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                (
                    "subtotal",
                    vs_finance.money.MoneyField(help_text="Net of tax, in kobo."),
                ),
                (
                    "tax_total",
                    vs_finance.money.MoneyField(help_text="Total tax, in kobo."),
                ),
                (
                    "total",
                    vs_finance.money.MoneyField(
                        help_text="subtotal + tax_total, in kobo."
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="vs_finance.currency",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_finance.ledgerentity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GoodsReceivedNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("received_date", models.DateField()),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                (
                    "total_value",
                    vs_finance.money.MoneyField(
                        help_text="Accepted value (ex-tax), in kobo."
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grns",
                        to="vs_finance.journalentry",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipts",
                        to="vs_procurement.purchaseorder",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=1, max_digits=14),
                ),
                (
                    "unit_price",
                    vs_finance.money.MoneyField(
                        help_text="Agreed price per unit, in kobo."
                    ),
                ),
                (
                    "net_amount",
                    vs_finance.money.MoneyField(
                        help_text="quantity × unit_price, in kobo."
                    ),
                ),
                (
                    "tax_amount",
                    vs_finance.money.MoneyField(help_text="Tax on the net, in kobo."),
                ),
                (
                    "received_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "invoiced_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("line_no", models.PositiveSmallIntegerField(default=0)),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="po_lines",
                        to="vs_finance.costcenter",
                    ),
                ),
                (
                    "expense_account",
                    models.ForeignKey(
                        help_text="GL account the cost lands in when goods are received.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="po_lines",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="vs_procurement.purchaseorder",
                    ),
                ),
                (
                    "tax_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="po_lines",
                        to="vs_finance.taxcode",
                    ),
                ),
            ],
            options={
                "ordering": ["purchase_order", "line_no", "id"],
            },
        ),
        migrations.CreateModel(
            name="GoodsReceivedNoteLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "accepted_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "rejected_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "unit_price",
                    vs_finance.money.MoneyField(
                        help_text="Price per unit, in kobo (from the PO)."
                    ),
                ),
                (
                    "value_amount",
                    vs_finance.money.MoneyField(
                        help_text="accepted_qty × unit_price, in kobo."
                    ),
                ),
                ("line_no", models.PositiveSmallIntegerField(default=0)),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grn_lines",
                        to="vs_finance.costcenter",
                    ),
                ),
                (
                    "expense_account",
                    models.ForeignKey(
                        help_text="GL account debited for the accepted value.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grn_lines",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "grn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="vs_procurement.goodsreceivednote",
                    ),
                ),
                (
                    "po_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grn_lines",
                        to="vs_procurement.purchaseorderline",
                    ),
                ),
            ],
            options={
                "ordering": ["grn", "line_no", "id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("request_date", models.DateField()),
                ("needed_by", models.DateField(blank=True, null=True)),
                (
                    "justification",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "estimated_total",
                    vs_finance.money.MoneyField(
                        help_text="Rolled-up estimate from the lines, in kobo."
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_requisitions",
                        to="vs_finance.costcenter",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_requisitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="requisition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="vs_procurement.purchaserequisition",
            ),
        ),
        migrations.CreateModel(
            name="PurchaseRequisitionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=1, max_digits=14),
                ),
                (
                    "estimated_unit_price",
                    vs_finance.money.MoneyField(
                        help_text="Estimated price per unit, in kobo."
                    ),
                ),
                ("line_no", models.PositiveSmallIntegerField(default=0)),
                (
                    "expense_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requisition_lines",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="vs_procurement.purchaserequisition",
                    ),
                ),
                (
                    "tax_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requisition_lines",
                        to="vs_finance.taxcode",
                    ),
                ),
            ],
            options={
                "ordering": ["requisition", "line_no", "id"],
            },
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="requisition_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="po_lines",
                to="vs_procurement.purchaserequisitionline",
            ),
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Vendor code, unique within the entity.",
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
                ("address", models.TextField(blank=True, default="")),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="TIN / tax identifier.",
                        max_length=32,
                    ),
                ),
                ("bank_name", models.CharField(blank=True, default="", max_length=120)),
                (
                    "bank_account_number",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "bank_account_name",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("NET_0", "Due on receipt"),
                            ("NET_7", "Net 7 days"),
                            ("NET_14", "Net 14 days"),
                            ("NET_30", "Net 30 days"),
                            ("NET_60", "Net 60 days"),
                            ("NET_90", "Net 90 days"),
                        ],
                        default="NET_30",
                        max_length=8,
                    ),
                ),
                (
                    "kyc_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=8,
                    ),
                ),
                (
                    "risk",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="LOW",
                        max_length=6,
                    ),
                ),
                (
                    "on_hold",
                    models.BooleanField(
                        default=False, help_text="Block new POs/payments while True."
                    ),
                ),
                (
                    "opening_balance",
                    vs_finance.money.MoneyField(
                        help_text="Opening AP balance in kobo (informational)."
                    ),
                ),
                (
                    "source_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("source_id", models.CharField(blank=True, default="", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendors",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "default_expense_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="default_vendors",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "default_wht_tax_code",
                    models.ForeignKey(
                        blank=True,
                        help_text="Withholding-tax code applied to this vendor's payments.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wht_vendors",
                        to="vs_finance.taxcode",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendors",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "payable_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="AP control account this vendor's balance rolls into.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ap_vendors",
                        to="vs_finance.account",
                    ),
                ),
            ],
            options={
                "ordering": ["entity", "code"],
            },
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="vs_procurement.vendor",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceivednote",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="goods_receipts",
                to="vs_procurement.vendor",
            ),
        ),
        migrations.CreateModel(
            name="VendorCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique within the entity.", max_length=32
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "default_expense_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_categories",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_categories",
                        to="vs_finance.ledgerentity",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "vendor categories",
                "ordering": ["entity", "code"],
            },
        ),
        migrations.AddField(
            model_name="vendor",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vendors",
                to="vs_procurement.vendorcategory",
            ),
        ),
        migrations.CreateModel(
            name="VendorInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("invoice_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "vendor_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The vendor's own invoice number.",
                        max_length=64,
                    ),
                ),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                (
                    "subtotal",
                    vs_finance.money.MoneyField(help_text="Net of tax, in kobo."),
                ),
                (
                    "tax_total",
                    vs_finance.money.MoneyField(help_text="Total tax, in kobo."),
                ),
                (
                    "total",
                    vs_finance.money.MoneyField(
                        help_text="subtotal + tax_total, in kobo."
                    ),
                ),
                (
                    "amount_paid",
                    vs_finance.money.MoneyField(
                        help_text="Cash allocated to this bill, in kobo."
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "Unpaid"),
                            ("PARTIAL", "Partially Paid"),
                            ("PAID", "Paid"),
                        ],
                        default="UNPAID",
                        max_length=8,
                    ),
                ),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("NOT_MATCHED", "Not matched"),
                            ("AUTO_MATCHED", "Auto-matched"),
                            ("UNDER_RECEIVED", "Under received"),
                            ("OVER_BILLED", "Over billed"),
                            ("PRICE_VARIANCE", "Price variance"),
                        ],
                        default="NOT_MATCHED",
                        max_length=16,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_invoices",
                        to="vs_finance.currency",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ap_invoices",
                        to="vs_finance.journalentry",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_invoices",
                        to="vs_procurement.purchaseorder",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="vs_procurement.vendor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VendorInvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=1, max_digits=14),
                ),
                (
                    "unit_price",
                    vs_finance.money.MoneyField(
                        help_text="Price per unit billed, in kobo."
                    ),
                ),
                (
                    "net_amount",
                    vs_finance.money.MoneyField(
                        help_text="quantity × unit_price, in kobo."
                    ),
                ),
                (
                    "tax_amount",
                    vs_finance.money.MoneyField(help_text="Tax on the net, in kobo."),
                ),
                ("line_no", models.PositiveSmallIntegerField(default=0)),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_invoice_lines",
                        to="vs_finance.costcenter",
                    ),
                ),
                (
                    "expense_account",
                    models.ForeignKey(
                        help_text="GL expense account (used directly for non-PO bills).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_invoice_lines",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "grn_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_invoice_lines",
                        to="vs_procurement.goodsreceivednoteline",
                    ),
                ),
                (
                    "po_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_invoice_lines",
                        to="vs_procurement.purchaseorderline",
                    ),
                ),
                (
                    "tax_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_invoice_lines",
                        to="vs_finance.taxcode",
                    ),
                ),
                (
                    "vendor_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="vs_procurement.vendorinvoice",
                    ),
                ),
            ],
            options={
                "ordering": ["vendor_invoice", "line_no", "id"],
            },
        ),
        migrations.CreateModel(
            name="VendorPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CARD", "Card"),
                            ("CHEQUE", "Cheque"),
                            ("ONLINE", "Online / Gateway"),
                            ("OTHER", "Other"),
                        ],
                        default="BANK_TRANSFER",
                        max_length=16,
                    ),
                ),
                (
                    "gross_amount",
                    vs_finance.money.MoneyField(
                        help_text="Total liability settled (Dr AP), in kobo."
                    ),
                ),
                (
                    "wht_amount",
                    vs_finance.money.MoneyField(
                        help_text="Withholding tax retained (Cr WHT payable), in kobo."
                    ),
                ),
                (
                    "net_amount",
                    vs_finance.money.MoneyField(
                        help_text="Cash actually paid out (Cr bank) = gross − WHT, in kobo."
                    ),
                ),
                (
                    "allocated_amount",
                    vs_finance.money.MoneyField(
                        help_text="Gross applied to bills, in kobo."
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_payments",
                        to="vs_finance.currency",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ap_payments",
                        to="vs_finance.journalentry",
                    ),
                ),
                (
                    "payment_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bank/cash account credited (where the money left).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_payments",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="vs_procurement.vendor",
                    ),
                ),
                (
                    "wht_tax_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_payments_wht",
                        to="vs_finance.taxcode",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VendorPaymentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Gross applied to this bill, in kobo."
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="vs_procurement.vendorpayment",
                    ),
                ),
                (
                    "vendor_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="vs_procurement.vendorinvoice",
                    ),
                ),
            ],
            options={
                "ordering": ["payment", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="goodsreceivednoteline",
            index=models.Index(fields=["grn"], name="vs_procurem_grn_id_76f04d_idx"),
        ),
        migrations.AddIndex(
            model_name="goodsreceivednoteline",
            index=models.Index(
                fields=["po_line"], name="vs_procurem_po_line_f7bb5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaserequisition",
            index=models.Index(
                fields=["entity", "status"], name="vs_procurem_entity__a9e528_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaserequisition",
            index=models.Index(
                fields=["entity", "request_date"], name="vs_procurem_entity__572df3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaserequisition",
            constraint=models.UniqueConstraint(
                fields=("entity", "document_number"),
                name="uniq_vs_procurement_purchaserequisition_entity_docnum",
            ),
        ),
        migrations.AddIndex(
            model_name="purchaserequisitionline",
            index=models.Index(
                fields=["requisition"], name="vs_procurem_requisi_773d1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorderline",
            index=models.Index(
                fields=["purchase_order"], name="vs_procurem_purchas_ca50ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorderline",
            index=models.Index(
                fields=["expense_account"], name="vs_procurem_expense_ad2817_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["entity", "status"], name="vs_procurem_entity__fe9b1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["vendor"], name="vs_procurem_vendor__35473c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["entity", "order_date"], name="vs_procurem_entity__84c117_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorder",
            constraint=models.UniqueConstraint(
                fields=("entity", "document_number"),
                name="uniq_vs_procurement_purchaseorder_entity_docnum",
            ),
        ),
        migrations.AddIndex(
            model_name="goodsreceivednote",
            index=models.Index(
                fields=["entity", "status"], name="vs_procurem_entity__f79391_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goodsreceivednote",
            index=models.Index(
                fields=["vendor"], name="vs_procurem_vendor__5907a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goodsreceivednote",
            index=models.Index(
                fields=["entity", "received_date"],
                name="vs_procurem_entity__2d263c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="goodsreceivednote",
            constraint=models.UniqueConstraint(
                fields=("entity", "document_number"),
                name="uniq_vs_procurement_goodsreceivednote_entity_docnum",
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorcategory",
            constraint=models.UniqueConstraint(
                fields=("entity", "code"), name="uniq_proc_vendorcat_entity_code"
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["entity", "is_active"], name="vs_procurem_entity__8e1dc9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["entity", "on_hold"], name="vs_procurem_entity__178cfc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["source_type", "source_id"],
                name="vs_procurem_source__56d3b1_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="vendor",
            constraint=models.UniqueConstraint(
                fields=("entity", "code"), name="uniq_proc_vendor_entity_code"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorinvoice",
            index=models.Index(
                fields=["entity", "status"], name="vs_procurem_entity__6629c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorinvoice",
            index=models.Index(
                fields=["entity", "payment_status"],
                name="vs_procurem_entity__5c3ea2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vendorinvoice",
            index=models.Index(
                fields=["vendor"], name="vs_procurem_vendor__4d4cbf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorinvoice",
            index=models.Index(
                fields=["entity", "invoice_date"], name="vs_procurem_entity__68ec96_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorinvoice",
            constraint=models.UniqueConstraint(
                fields=("entity", "document_number"),
                name="uniq_vs_procurement_vendorinvoice_entity_docnum",
            ),
        ),
        migrations.AddIndex(
            model_name="vendorinvoiceline",
            index=models.Index(
                fields=["vendor_invoice"], name="vs_procurem_vendor__7ef4f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorinvoiceline",
            index=models.Index(
                fields=["expense_account"], name="vs_procurem_expense_d03160_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorpayment",
            index=models.Index(
                fields=["entity", "status"], name="vs_procurem_entity__8ac083_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorpayment",
            index=models.Index(
                fields=["vendor"], name="vs_procurem_vendor__ba978a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorpayment",
            index=models.Index(
                fields=["entity", "payment_date"], name="vs_procurem_entity__d19322_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorpayment",
            constraint=models.UniqueConstraint(
                fields=("entity", "document_number"),
                name="uniq_vs_procurement_vendorpayment_entity_docnum",
            ),
        ),
        migrations.AddIndex(
            model_name="vendorpaymentallocation",
            index=models.Index(
                fields=["vendor_invoice"], name="vs_procurem_vendor__d27fab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorpaymentallocation",
            index=models.Index(
                fields=["payment"], name="vs_procurem_payment_4453c7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorpaymentallocation",
            constraint=models.UniqueConstraint(
                fields=("payment", "vendor_invoice"),
                name="uniq_proc_alloc_payment_invoice",
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorpaymentallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="ck_proc_alloc_non_negative",
            ),
        ),
    ]
