# Generated by Django 5.2.10 on 2026-06-07 16:55

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0013_alter_documentsequence_doc_type_and_more"),
        ("vs_procurement", "0001_initial"),
        ("vs_schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestForQuotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                (
                    "rfq_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ISSUED", "Issued"),
                            ("AWARDED", "Awarded"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("issue_date", models.DateField()),
                (
                    "response_due_date",
                    models.DateField(
                        blank=True,
                        help_text="Closing date for vendor responses.",
                        null=True,
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rfqs",
                        to="vs_procurement.purchaserequisition",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RfqLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=1, max_digits=14),
                ),
                ("line_no", models.PositiveSmallIntegerField(default=0)),
                (
                    "expense_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rfq_lines",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "requisition_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rfq_lines",
                        to="vs_procurement.purchaserequisitionline",
                    ),
                ),
                (
                    "rfq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="vs_procurement.requestforquotation",
                    ),
                ),
                (
                    "tax_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rfq_lines",
                        to="vs_finance.taxcode",
                    ),
                ),
            ],
            options={
                "ordering": ["rfq", "line_no", "id"],
            },
        ),
        migrations.CreateModel(
            name="VendorQuotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "quotation_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("AWARDED", "Awarded"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("quote_date", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "lead_time_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Promised delivery lead time in days.",
                        null=True,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "subtotal",
                    vs_finance.money.MoneyField(help_text="Net of tax, in kobo."),
                ),
                (
                    "tax_total",
                    vs_finance.money.MoneyField(help_text="Total tax, in kobo."),
                ),
                (
                    "total",
                    vs_finance.money.MoneyField(
                        help_text="subtotal + tax_total, in kobo."
                    ),
                ),
                (
                    "awarded_po",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_quotation",
                        to="vs_procurement.purchaseorder",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotations",
                        to="vs_finance.currency",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "rfq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotations",
                        to="vs_procurement.requestforquotation",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotations",
                        to="vs_procurement.vendor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VendorQuotationLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=1, max_digits=14),
                ),
                (
                    "unit_price",
                    vs_finance.money.MoneyField(
                        help_text="Quoted price per unit, in kobo."
                    ),
                ),
                (
                    "net_amount",
                    vs_finance.money.MoneyField(
                        help_text="quantity × unit_price, in kobo."
                    ),
                ),
                (
                    "tax_amount",
                    vs_finance.money.MoneyField(help_text="Tax on the net, in kobo."),
                ),
                ("line_no", models.PositiveSmallIntegerField(default=0)),
                (
                    "expense_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="GL account the cost lands in once received (carried onto the PO line).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotation_lines",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="vs_procurement.vendorquotation",
                    ),
                ),
                (
                    "rfq_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotation_lines",
                        to="vs_procurement.rfqline",
                    ),
                ),
                (
                    "tax_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotation_lines",
                        to="vs_finance.taxcode",
                    ),
                ),
            ],
            options={
                "ordering": ["quotation", "line_no", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="requestforquotation",
            index=models.Index(
                fields=["entity", "rfq_status"], name="vs_procurem_entity__7b8ddf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="requestforquotation",
            index=models.Index(
                fields=["entity", "issue_date"], name="vs_procurem_entity__111947_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="requestforquotation",
            constraint=models.UniqueConstraint(
                fields=("entity", "document_number"),
                name="uniq_vs_procurement_requestforquotation_entity_docnum",
            ),
        ),
        migrations.AddIndex(
            model_name="rfqline",
            index=models.Index(fields=["rfq"], name="vs_procurem_rfq_id_ce31c8_idx"),
        ),
        migrations.AddIndex(
            model_name="vendorquotation",
            index=models.Index(
                fields=["entity", "quotation_status"],
                name="vs_procurem_entity__7bd443_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vendorquotation",
            index=models.Index(fields=["rfq"], name="vs_procurem_rfq_id_68dd15_idx"),
        ),
        migrations.AddIndex(
            model_name="vendorquotation",
            index=models.Index(
                fields=["vendor"], name="vs_procurem_vendor__6f30b0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorquotation",
            constraint=models.UniqueConstraint(
                fields=("entity", "document_number"),
                name="uniq_vs_procurement_vendorquotation_entity_docnum",
            ),
        ),
        migrations.AddIndex(
            model_name="vendorquotationline",
            index=models.Index(
                fields=["quotation"], name="vs_procurem_quotati_131f02_idx"
            ),
        ),
    ]
