# Generated by Django 5.2.10 on 2026-06-07 17:06

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0013_alter_documentsequence_doc_type_and_more"),
        ("vs_procurement", "0002_requestforquotation_rfqline_vendorquotation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Item code, unique within the entity.", max_length=40
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        blank=True,
                        default="each",
                        help_text="e.g. 'each', 'box', 'hour'.",
                        max_length=24,
                    ),
                ),
                (
                    "lead_time_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Typical delivery lead time, in days.",
                        null=True,
                    ),
                ),
                (
                    "standard_unit_price",
                    vs_finance.money.MoneyField(
                        help_text="Indicative price per unit, in kobo."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "default_expense_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="GL account the cost lands in (seeds purchase lines).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_items",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "default_tax_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_items",
                        to="vs_finance.taxcode",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_items",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "preferred_vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="catalog_items",
                        to="vs_procurement.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["entity", "code"],
                "indexes": [
                    models.Index(
                        fields=["entity", "is_active"],
                        name="vs_procurem_entity__5b17b2_idx",
                    ),
                    models.Index(
                        fields=["preferred_vendor"],
                        name="vs_procurem_preferr_7235be_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entity", "code"),
                        name="uniq_proc_catalogitem_entity_code",
                    )
                ],
            },
        ),
    ]
