# Generated by Django 5.2.10 on 2026-06-07 17:24

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0014_alter_financeauditlog_action"),
        ("vs_procurement", "0003_catalogitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        help_text="Contract reference, unique within the entity.",
                        max_length=64,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("TERMINATED", "Terminated"),
                            ("RENEWED", "Renewed"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "contract_value",
                    vs_finance.money.MoneyField(
                        help_text="Total committed value over the term, in kobo."
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("NET_0", "Due on receipt"),
                            ("NET_7", "Net 7 days"),
                            ("NET_14", "Net 14 days"),
                            ("NET_30", "Net 30 days"),
                            ("NET_60", "Net 60 days"),
                            ("NET_90", "Net 90 days"),
                        ],
                        default="NET_30",
                        max_length=8,
                    ),
                ),
                ("auto_renew", models.BooleanField(default=False)),
                (
                    "renewal_notice_days",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="Days before end_date to flag the contract for renewal.",
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_contracts",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "renews",
                    models.ForeignKey(
                        blank=True,
                        help_text="The prior contract this one renews/replaces.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="renewed_by",
                        to="vs_procurement.vendorcontract",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="vs_procurement.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["entity", "-end_date", "reference"],
            },
        ),
        migrations.CreateModel(
            name="ContractMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Value tied to this milestone, in kobo."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("MISSED", "Missed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("line_no", models.PositiveSmallIntegerField(default=0)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="vs_procurement.vendorcontract",
                    ),
                ),
            ],
            options={
                "ordering": ["contract", "line_no", "due_date", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="vendorcontract",
            index=models.Index(
                fields=["entity", "status"], name="vs_procurem_entity__f3f2c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorcontract",
            index=models.Index(
                fields=["entity", "end_date"], name="vs_procurem_entity__5681bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorcontract",
            index=models.Index(
                fields=["vendor"], name="vs_procurem_vendor__1fe25f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorcontract",
            constraint=models.UniqueConstraint(
                fields=("entity", "reference"), name="uniq_proc_contract_entity_ref"
            ),
        ),
        migrations.AddIndex(
            model_name="contractmilestone",
            index=models.Index(
                fields=["contract"], name="vs_procurem_contrac_53ec64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractmilestone",
            index=models.Index(
                fields=["status", "due_date"], name="vs_procurem_status_bb400e_idx"
            ),
        ),
    ]
