# Generated by Django 5.2.10 on 2026-06-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_procurement", "0004_vendorcontract_contractmilestone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="approval_state",
            field=models.CharField(
                choices=[
                    ("NOT_SUBMITTED", "Not submitted"),
                    ("PENDING", "Pending approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="NOT_SUBMITTED",
                help_text="Spend-approval state driven by vs_workflow (overlay; not the ledger status).",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="purchaserequisition",
            name="approval_state",
            field=models.CharField(
                choices=[
                    ("NOT_SUBMITTED", "Not submitted"),
                    ("PENDING", "Pending approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="NOT_SUBMITTED",
                help_text="Spend-approval state driven by vs_workflow (overlay; not the ledger status).",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="vendorinvoice",
            name="approval_state",
            field=models.CharField(
                choices=[
                    ("NOT_SUBMITTED", "Not submitted"),
                    ("PENDING", "Pending approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="NOT_SUBMITTED",
                help_text="Spend-approval state driven by vs_workflow (overlay; not the ledger status).",
                max_length=16,
            ),
        ),
    ]
