# Generated by Django 5.2.10 on 2026-06-07 21:06

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0016_alter_financeauditlog_action"),
        ("vs_procurement", "0005_purchaseorder_approval_state_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsreceivednoteline",
            name="expense_account",
            field=models.ForeignKey(
                help_text="GL account debited for the accepted value (non-stock lines).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grn_lines",
                to="vs_finance.account",
            ),
        ),
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Stock code, unique within the entity.", max_length=40
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "unit_of_measure",
                    models.CharField(blank=True, default="each", max_length=24),
                ),
                (
                    "reorder_level",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="On-hand at/below which the item is flagged for reorder.",
                        max_digits=14,
                    ),
                ),
                (
                    "reorder_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Suggested quantity to reorder when low.",
                        max_digits=14,
                    ),
                ),
                (
                    "on_hand_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Live quantity on hand (maintained by the stock ledger).",
                        max_digits=16,
                    ),
                ),
                (
                    "stock_value",
                    vs_finance.money.MoneyField(
                        help_text="Total value of on-hand stock, in kobo (weighted-average basis)."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "catalog_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to the buying-defaults catalog entry for this good.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_items",
                        to="vs_procurement.catalogitem",
                    ),
                ),
                (
                    "default_expense_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default account debited when stock is issued (e.g. Cost of Sales).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_items_expense",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_items",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "inventory_account",
                    models.ForeignKey(
                        help_text="Balance-sheet asset account this item's value is carried in.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_items",
                        to="vs_finance.account",
                    ),
                ),
            ],
            options={
                "ordering": ["entity", "code"],
            },
        ),
        migrations.AddField(
            model_name="goodsreceivednoteline",
            name="stock_item",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, the receipt is capitalised to inventory (perpetual stock).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grn_lines",
                to="vs_procurement.stockitem",
            ),
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("RECEIPT", "Receipt"),
                            ("ISSUE", "Issue"),
                            ("ADJUSTMENT", "Adjustment"),
                        ],
                        max_length=16,
                    ),
                ),
                ("movement_date", models.DateField()),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Signed quantity change (+ receipt, − issue).",
                        max_digits=16,
                    ),
                ),
                (
                    "value_amount",
                    models.BigIntegerField(
                        help_text="Signed value change in kobo (+ in, − out)."
                    ),
                ),
                (
                    "balance_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="On-hand quantity after this movement.",
                        max_digits=16,
                    ),
                ),
                (
                    "balance_value",
                    vs_finance.money.MoneyField(
                        help_text="Stock value (kobo) after this movement."
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "grn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="vs_procurement.goodsreceivednote",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="vs_finance.journalentry",
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="vs_procurement.stockitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-movement_date", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="stockitem",
            index=models.Index(
                fields=["entity", "is_active"], name="vs_procurem_entity__89a68d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockitem",
            index=models.Index(
                fields=["catalog_item"], name="vs_procurem_catalog_13d837_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockitem",
            constraint=models.UniqueConstraint(
                fields=("entity", "code"), name="uniq_proc_stockitem_entity_code"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["entity", "movement_date"],
                name="vs_procurem_entity__93f455_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["stock_item", "movement_date"],
                name="vs_procurem_stock_i_4db3f0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["movement_type"], name="vs_procurem_movemen_1be560_idx"
            ),
        ),
    ]
