# Generated by Django 5.2.10 on 2026-07-18 13:58

import django.db.models.functions.text
from django.db import migrations, models
import re


def normalize_vendor_identifiers(apps, schema_editor):
    """Canonicalize existing identifiers before the race-safe constraints are installed."""
    Vendor = apps.get_model("vs_procurement", "Vendor")
    seen_codes = set()
    seen_tax_ids = set()
    for vendor in Vendor.objects.order_by("entity_id", "id"):
        code = str(vendor.code or "").strip().upper()
        tax_id = str(vendor.tax_id or "").strip().upper()
        tax_id_normalized = re.sub(r"[^A-Z0-9]", "", tax_id)
        code_key = (vendor.entity_id, code)
        tax_key = (vendor.entity_id, tax_id_normalized)
        if code_key in seen_codes:
            raise RuntimeError(f"Duplicate vendor code after normalization: entity={vendor.entity_id}, code={code}")
        if tax_id_normalized and tax_key in seen_tax_ids:
            raise RuntimeError(
                f"Duplicate vendor tax identifier after normalization in entity={vendor.entity_id}."
            )
        seen_codes.add(code_key)
        if tax_id_normalized:
            seen_tax_ids.add(tax_key)
        Vendor.objects.filter(pk=vendor.pk).update(
            code=code, tax_id=tax_id, tax_id_normalized=tax_id_normalized,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0007_alter_documentsequence_doc_type_and_more"),
        ("vs_procurement", "0007_vendor_payment_approval"),
        ("vs_schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="tax_id_normalized",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="Canonical tax identifier used only for entity-scoped duplicate detection.",
                max_length=32,
            ),
        ),
        migrations.RunPython(normalize_vendor_identifiers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="vendor",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"),
                models.F("entity"),
                name="uniq_proc_vendor_entity_code_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="vendor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tax_id_normalized", ""), _negated=True),
                fields=("entity", "tax_id_normalized"),
                name="uniq_proc_vendor_entity_tax_id_norm",
            ),
        ),
    ]
