# Generated by Django 5.2.10 on 2026-07-18

import django.db.models.functions.text
from django.db import migrations, models


def normalize_category_codes(apps, schema_editor):
    """Canonicalize codes before installing the case-insensitive constraint."""
    VendorCategory = apps.get_model("vs_procurement", "VendorCategory")
    seen = set()
    for category in VendorCategory.objects.order_by("entity_id", "id"):
        code = str(category.code or "").strip().upper()
        key = (category.entity_id, code)
        if key in seen:
            raise RuntimeError(
                f"Duplicate vendor category code after normalization: entity={category.entity_id}, code={code}"
            )
        seen.add(key)
        VendorCategory.objects.filter(pk=category.pk).update(code=code)


class Migration(migrations.Migration):
    dependencies = [
        ("vs_procurement", "0008_vendor_tax_id_normalized_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_category_codes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="vendorcategory",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"),
                models.F("entity"),
                name="uniq_proc_vendorcat_entity_code_ci",
            ),
        ),
    ]
