# Generated by Django 5.2.10 on 2026-07-18 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0007_alter_documentsequence_doc_type_and_more"),
        ("vs_procurement", "0009_vendorcategory_code_ci"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional parent category; API governance caps the tree at three levels.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="vs_procurement.vendorcategory",
            ),
        ),
        migrations.AddIndex(
            model_name="vendorcategory",
            index=models.Index(
                fields=["entity", "parent"], name="proc_vcat_entity_parent_idx"
            ),
        ),
    ]
