# Generated by Django 5.2.10 on 2026-07-21 04:07

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_procurement", "0011_catalogitem_category_and_code_ci"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestforquotation",
            name="budget_estimate",
            field=vs_finance.money.MoneyField(
                blank=True,
                help_text="Optional buyer budget ceiling, in kobo.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="RfqInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rfq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="vs_procurement.requestforquotation",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rfq_invitations",
                        to="vs_procurement.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["rfq", "id"],
                "indexes": [
                    models.Index(fields=["rfq"], name="vs_procurem_rfq_id_be6f04_idx")
                ],
                "unique_together": {("rfq", "vendor")},
            },
        ),
    ]
