# Generated by Django 5.2.10 on 2026-07-21 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_procurement", "0012_requestforquotation_budget_estimate_rfqinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                help_text="Explicit call-off link to the vendor contract this PO is raised against. SET_NULL so a contract deletion never blocks the order; optional so requisition-/award-spawned POs stay unlinked. The Contracts 'Linked POs' tab falls back to a vendor+term association only for POs where this is null.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders",
                to="vs_procurement.vendorcontract",
            ),
        ),
    ]
