# Generated by Django 5.2.10 on 2026-08-08 14:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0013_alter_financeauditlog_action_financeaccountmapping"),
        ("vs_procurement", "0015_vendorinvoice_reference_ci"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorinvoice",
            name="match_status",
            field=models.CharField(
                choices=[
                    ("NOT_MATCHED", "Not matched"),
                    ("AUTO_MATCHED", "Auto-matched"),
                    ("UNDER_RECEIVED", "Under received"),
                    ("OVER_BILLED", "Over billed"),
                    ("PRICE_VARIANCE", "Price variance"),
                    ("NON_PO_BLOCKED", "Non-PO invoice blocked"),
                ],
                default="NOT_MATCHED",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="ProcurementSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_payment_terms",
                    models.CharField(
                        choices=[
                            ("NET_0", "Due on receipt"),
                            ("NET_7", "Net 7 days"),
                            ("NET_14", "Net 14 days"),
                            ("NET_30", "Net 30 days"),
                            ("NET_60", "Net 60 days"),
                            ("NET_90", "Net 90 days"),
                        ],
                        default="NET_30",
                        max_length=8,
                    ),
                ),
                ("default_delivery_address", models.TextField(blank=True, default="")),
                (
                    "quantity_tolerance_bps",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Allowed ordered/received quantity overage in basis points.",
                        validators=[django.core.validators.MaxValueValidator(10000)],
                    ),
                ),
                (
                    "price_tolerance_bps",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Allowed unit-price variance in basis points.",
                        validators=[django.core.validators.MaxValueValidator(10000)],
                    ),
                ),
                ("allow_non_po_invoices", models.BooleanField(default=True)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procurement_settings",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procurement_settings_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
