# Generated by Django 5.2.10 on 2026-08-08 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_procurement", "0016_alter_vendorinvoice_match_status_procurementsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="procurementsettings",
            name="contract_renewal_notice_days",
            field=models.PositiveSmallIntegerField(
                default=30, validators=[django.core.validators.MaxValueValidator(365)]
            ),
        ),
        migrations.AddField(
            model_name="procurementsettings",
            name="default_requisition_lead_days",
            field=models.PositiveSmallIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(365)]
            ),
        ),
        migrations.AddField(
            model_name="procurementsettings",
            name="require_purchase_order_for_receipts",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="procurementsettings",
            name="vendor_purchase_kyc_requirement",
            field=models.CharField(
                choices=[
                    ("PENDING_OR_VERIFIED", "Pending or verified"),
                    ("VERIFIED_ONLY", "Verified only"),
                ],
                default="PENDING_OR_VERIFIED",
                max_length=20,
            ),
        ),
    ]
