# Generated by Django 5.2.10 on 2026-08-08 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "vs_procurement",
            "0017_procurementsettings_contract_renewal_notice_days_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="procurementsettings",
            name="default_rfq_response_days",
            field=models.PositiveSmallIntegerField(
                default=14,
                help_text="Default number of days allowed for responses to a new RFQ.",
                validators=[django.core.validators.MaxValueValidator(365)],
            ),
        ),
        migrations.AddField(
            model_name="procurementsettings",
            name="rfq_closing_soon_days",
            field=models.PositiveSmallIntegerField(
                default=7,
                help_text="Horizon used by the RFQ closing-soon summary.",
                validators=[django.core.validators.MaxValueValidator(365)],
            ),
        ),
    ]
