# Generated by Django 5.2.10 on 2026-08-11 10:03

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import vs_procurement.models
from django.conf import settings
from django.db import migrations, models


def backfill_vendor_contacts_and_deadlines(apps, schema_editor):
    """Adopt existing vendor emails and date-only deadlines without data loss."""
    Vendor = apps.get_model("vs_procurement", "Vendor")
    VendorContact = apps.get_model("vs_procurement", "VendorContact")
    RequestForQuotation = apps.get_model("vs_procurement", "RequestForQuotation")
    for vendor in Vendor.objects.exclude(email="").iterator():
        VendorContact.objects.get_or_create(
            vendor_id=vendor.pk,
            email=vendor.email,
            defaults={"name": vendor.name, "is_primary": True, "receives_rfqs": True},
        )
    for rfq in RequestForQuotation.objects.filter(
        response_due_date__isnull=False, response_due_at__isnull=True,
    ).iterator():
        rfq.response_due_at = django.utils.timezone.make_aware(
            django.utils.timezone.datetime.combine(
                rfq.response_due_date,
                django.utils.timezone.datetime.max.time().replace(microsecond=0),
            ),
            django.utils.timezone.get_default_timezone(),
        )
        rfq.save(update_fields=["response_due_at"])


def seed_procurement_notification_events(apps, schema_editor):
    """Install the must-send email events used immediately after RFQ issue."""
    Event = apps.get_model("vs_notifications", "NotificationEventType")
    Template = apps.get_model("vs_notifications", "NotificationTemplate")
    events = {
        "procurement.rfq_invitation": (
            "Vendor RFQ invitation", "Quotation requested: {{ rfq_number }}",
            "Hello {{ recipient_name }},\n\n{{ issuer_name }} invited {{ vendor_name }} to quote for {{ rfq_number }}: {{ rfq_title }}.\n\nDeadline: {{ deadline }}\n\n{{ invitation_url }}",
        ),
        "procurement.rfq_verification_code": (
            "Vendor RFQ verification code", "Your quotation verification code",
            "Your verification code for {{ rfq_number }} is {{ verification_code }}. It expires in {{ expiry_minutes }} minutes.",
        ),
        "procurement.rfq_reminder": (
            "Vendor RFQ reminder", "Reminder: quotation due for {{ rfq_number }}",
            "Hello {{ recipient_name }}, your quotation for {{ rfq_number }} is due {{ deadline }}.\n\n{{ invitation_url }}",
        ),
        "procurement.quotation_receipt": (
            "Vendor quotation receipt", "Quotation received: {{ quotation_number }}",
            "Revision {{ revision }} for {{ rfq_number }} was received at {{ submitted_at }}.\n\n{{ invitation_url }}",
        ),
        "procurement.rfq_amended": (
            "Vendor RFQ amendment", "RFQ amended: {{ rfq_number }} version {{ rfq_version }}",
            "{{ rfq_number }} was amended. {{ amendment_summary }} Response required: {{ response_required }}.\n\n{{ invitation_url }}",
        ),
        "procurement.rfq_deadline_extended": (
            "Vendor RFQ deadline extension", "Quotation deadline extended: {{ rfq_number }}",
            "The deadline for {{ vendor_name }} to respond to {{ rfq_number }} is now {{ deadline }}.\n\n{{ invitation_url }}",
        ),
    }
    for key, (label, subject, body) in events.items():
        event, _ = Event.objects.update_or_create(
            key=key,
            defaults={
                "label": label, "description": label, "source_module": "vs_procurement",
                "supported_channels": ["email"], "default_enabled": True,
                "is_transactional": True, "is_active": True,
            },
        )
        Template.objects.get_or_create(
            event_type=event, channel="email",
            defaults={"subject": subject, "body": body, "html_body": "", "is_active": True},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("vs_procurement", "0019_procurementsettings_competitive_bidding"),
        ("vs_notifications", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="requestforquotation",
            name="response_due_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Exact UTC closing instant. Date-only RFQs default to 23:59:59 local time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="requestforquotation",
            name="version",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="rfqinvitation",
            name="acknowledged_version",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="rfqinvitation",
            name="decline_reason",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="rfqinvitation",
            name="declined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rfqinvitation",
            name="draft_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rfqinvitation",
            name="extended_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rfqinvitation",
            name="last_reminder_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rfqinvitation",
            name="opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rfqinvitation",
            name="reminder_stage",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rfqinvitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SENT", "Sent"),
                    ("OPENED", "Opened"),
                    ("DRAFTING", "Drafting"),
                    ("SUBMITTED", "Submitted"),
                    ("DECLINED", "Declined"),
                    ("EXPIRED", "Expired"),
                    ("BOUNCED", "Bounced"),
                    ("REVOKED", "Revoked"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="rfqinvitation",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rfqinvitation",
            name="token_version",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="rfqline",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="rfqline",
            name="version",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="vendorquotationline",
            name="alternative_for",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alternative_quotation_lines",
                to="vs_procurement.rfqline",
            ),
        ),
        migrations.AddField(
            model_name="vendorquotation",
            name="vendor_managed",
            field=models.BooleanField(
                default=False,
                help_text="True when the external vendor portal owns the draft content.",
            ),
        ),
        migrations.AddField(
            model_name="vendorquotationline",
            name="response_type",
            field=models.CharField(
                choices=[
                    ("QUOTED", "Quoted"),
                    ("ALTERNATIVE", "Alternative offered"),
                    ("NO_BID", "Not available or no-bid"),
                ],
                default="QUOTED",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="VendorContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, default="", max_length=160)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
                ("is_primary", models.BooleanField(default=False)),
                ("receives_rfqs", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="vs_procurement.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["vendor", "-is_primary", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="RfqInvitationRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, default="", max_length=160)),
                ("email", models.EmailField(max_length=254)),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="vs_procurement.rfqinvitation",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitation_recipients",
                        to="vs_procurement.vendorcontact",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="VendorQuotationAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveSmallIntegerField(default=1)),
                (
                    "file",
                    models.FileField(
                        upload_to=vs_procurement.models.quotation_attachment_upload_to
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=120)),
                ("size", models.PositiveIntegerField()),
                (
                    "uploaded_by_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="vs_procurement.vendorquotation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendorQuotationSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveSmallIntegerField()),
                ("rfq_version", models.PositiveSmallIntegerField()),
                ("submitted_at", models.DateTimeField()),
                ("submitted_by_email", models.EmailField(max_length=254)),
                ("snapshot", models.JSONField()),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="vs_procurement.vendorquotation",
                    ),
                ),
            ],
            options={
                "ordering": ["quotation", "-revision"],
            },
        ),
        migrations.CreateModel(
            name="RfqAmendment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveSmallIntegerField()),
                ("summary", models.CharField(max_length=500)),
                ("response_required", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_rfq_amendments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rfq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="amendments",
                        to="vs_procurement.requestforquotation",
                    ),
                ),
            ],
            options={
                "ordering": ["rfq", "version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("rfq", "version"),
                        name="uniq_proc_rfq_amendment_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RfqInvitationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="vs_procurement.rfqinvitation",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["invitation", "expires_at"],
                        name="vs_procurem_invitat_21f057_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RfqInvitationVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254)),
                ("code_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_codes",
                        to="vs_procurement.rfqinvitation",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["invitation", "email", "expires_at"],
                        name="vs_procurem_invitat_15315e_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="vendorcontact",
            index=models.Index(
                fields=["vendor", "is_active", "receives_rfqs"],
                name="vs_procurem_vendor__d339cc_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorcontact",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                models.F("vendor"),
                name="uniq_proc_vendor_contact_email_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="rfqinvitationrecipient",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                models.F("invitation"),
                name="uniq_proc_rfq_invite_recipient_email_ci",
            ),
        ),
        migrations.AddIndex(
            model_name="vendorquotationattachment",
            index=models.Index(
                fields=["quotation", "revision"], name="vs_procurem_quotati_d99a00_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorquotationsubmission",
            constraint=models.UniqueConstraint(
                fields=("quotation", "revision"),
                name="uniq_proc_quotation_submission_revision",
            ),
        ),
        migrations.RunPython(
            backfill_vendor_contacts_and_deadlines,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            seed_procurement_notification_events,
            migrations.RunPython.noop,
        ),
    ]
