# Generated by Django 5.2.10 on 2026-08-11 11:46

import django.db.models.deletion
import django.utils.timezone
import vs_procurement.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_procurement", "0021_vendorinvoice_creation_idempotency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrderVendorDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(choices=[("AUTOMATIC", "Automatic after approval"), ("MANUAL", "Manual"), ("RETRY", "Retry")], max_length=16)),
                ("status", models.CharField(choices=[("AWAITING_APPROVAL", "Awaiting approval"), ("PENDING", "Pending"), ("SENT", "Sent"), ("FAILED", "Failed"), ("CANCELLED", "Cancelled")], max_length=24)),
                ("workflow_instance_id", models.CharField(blank=True, default="", max_length=64)),
                ("buyer_message", models.TextField(blank=True, default="")),
                ("recipients", models.JSONField(default=list)),
                ("cc", models.JSONField(default=list)),
                ("notification_ids", models.JSONField(default=list)),
                ("pdf_file", models.FileField(blank=True, upload_to=vs_procurement.models.purchase_order_vendor_pdf_path)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True, default="")),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AddField(
            model_name="vendorcontact",
            name="receives_purchase_orders",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="vendorcontact",
            index=models.Index(fields=["vendor", "is_active", "receives_purchase_orders"], name="vs_procurem_vendor__a86067_idx"),
        ),
        migrations.AddField(
            model_name="purchaseordervendordelivery",
            name="parent",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="retries", to="vs_procurement.purchaseordervendordelivery"),
        ),
        migrations.AddField(
            model_name="purchaseordervendordelivery",
            name="purchase_order",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="vendor_deliveries", to="vs_procurement.purchaseorder"),
        ),
        migrations.AddField(
            model_name="purchaseordervendordelivery",
            name="requested_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="requested_purchase_order_vendor_deliveries", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name="purchaseordervendordelivery",
            index=models.Index(fields=["purchase_order", "-created_at"], name="vs_procurem_purchas_1d87fb_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaseordervendordelivery",
            index=models.Index(fields=["status", "created_at"], name="vs_procurem_status_0e07cb_idx"),
        ),
        migrations.AddConstraint(
            model_name="purchaseordervendordelivery",
            constraint=models.UniqueConstraint(condition=models.Q(("status", "AWAITING_APPROVAL")), fields=("purchase_order",), name="uniq_proc_po_active_email_intent"),
        ),
    ]
