# Generated by Django 5.2.10 on 2026-08-11 21:13

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("vs_finance", "0018_alter_financeauditlog_action"),
        ("vs_procurement", "0023_procurement_stages_never_auto_skip"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document_object_id", models.PositiveBigIntegerField()),
                ("document_type", models.CharField(db_index=True, max_length=100)),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reference as it read when released; the document may be renumbered.",
                        max_length=48,
                    ),
                ),
                (
                    "workflow_instance_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("stage_code", models.CharField(blank=True, default="", max_length=64)),
                ("stage_attempt", models.PositiveIntegerField(default=1)),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="The document's approval amount when released, in kobo."
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="The actor's own words, stored verbatim and never editable."
                    ),
                ),
                (
                    "document_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        help_text="Ledger entity of the released document; the tenant isolation boundary.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procurement_approval_overrides",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "overridden_by",
                    models.ForeignKey(
                        help_text="The human accountable for the release. Never null: the override is the human.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procurement_approval_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["entity", "-created_at"],
                        name="vs_procurem_entity__b6d900_idx",
                    ),
                    models.Index(
                        fields=["document_content_type", "document_object_id"],
                        name="vs_procurem_documen_0fde17_idx",
                    ),
                ],
            },
        ),
    ]
