"""Turn off non-PO bills by default, and close the door on existing tenants too.

A bill with no purchase order has nothing to three-way match against: no ordered
quantity, no receipt, no agreed price. Approval is its only control, so a ₦3,000,000
invoice for goods nobody ordered and nobody recorded arriving posts to accounts payable
on one person's say-so. Allowing that by default was the wrong way round.

Changing the model default alone would only affect settings rows created from now on,
which means the tenants that exist today - the only ones the change is meant to protect
- would keep the permissive behaviour and the fix would do nothing. So this also flips
existing rows.

That does overwrite an administrator who deliberately switched it on, which is why it
is a migration rather than a quiet default change: it is visible, it is reversible, and
the setting is exposed on the procurement settings API, so a tenant that genuinely bills
without purchase orders turns it back on in one call.

Reverse: restores ``allow_non_po_invoices=True`` on every row. It is a true inverse, so
rolling back re-opens non-PO billing for everyone, which is stated here so the choice is
visible at rollback time.
"""
# Generated by Django 5.2.10 on 2026-08-14 04:28

from django.db import migrations, models




def _set_allow_non_po(apps, value):
    ProcurementSettings = apps.get_model("vs_procurement", "ProcurementSettings")
    ProcurementSettings.objects.exclude(
        allow_non_po_invoices=value,
    ).update(allow_non_po_invoices=value)


def close_non_po_billing(apps, schema_editor):
    """Require a purchase order on every existing tenant's bills."""
    _set_allow_non_po(apps, False)


def reopen_non_po_billing(apps, schema_editor):
    """Restore the permissive setting. Re-opens un-matched billing everywhere."""
    _set_allow_non_po(apps, True)


class Migration(migrations.Migration):

    dependencies = [
        ("vs_procurement", "0026_vendor_advance_allocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procurementsettings",
            name="allow_non_po_invoices",
            field=models.BooleanField(
                default=False,
                help_text="Allow bills with no purchase order. Off by default: a non-PO bill has no three-way match, so approval is its only control.",
            ),
        ),
        migrations.RunPython(close_non_po_billing, reopen_non_po_billing),
    ]
