"""Give stock a location, and attribute everything that already exists to one.

Stock was one pool per entity. The pool knew a thousand units existed; it could not
know that seven hundred stood at one campus and three hundred at the other, so an issue
at the smaller site drew against stock it did not have and the availability check
allowed it. Quieter and just as wrong: one blended average meant a site that bought
dearer and a site that bought cheaper both relieved inventory at the middle, so each
one's expense was off in opposite directions.

This adds :class:`StockLocation` and :class:`StockBalance`, and a location on every
movement. The item's own ``on_hand_qty`` and ``stock_value`` stay exactly as they are
and become the roll-up across locations, which is what lets every existing report,
serializer and reorder rule keep reading the same numbers.

What the data step does, and what it deliberately does not:

* every entity that holds stock items gets one location, ``MAIN``, marked default;
* each item carrying quantity or value gets one balance row at ``MAIN`` holding its
  current totals verbatim, so no value is created or destroyed;
* every existing movement is attributed to ``MAIN``.

Attributing all history to one location is the honest answer, not a convenient one: the
old data records no location, so any split across campuses would be invented. A school
that has been running two campuses should create its second location and transfer the
opening balances deliberately, where the transfer is visible, rather than have this
migration guess.

Reverse drops the balances and locations and clears the movement links. The item totals
are never touched in either direction, so the reverse is lossless.
"""
# Generated by Django 5.2.10 on 2026-08-14 07:26

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.db import migrations, models




DEFAULT_CODE = "MAIN"
DEFAULT_NAME = "Main store"


def open_default_locations(apps, schema_editor):
    """Create MAIN per stock-holding entity, then attribute balances and history."""
    StockItem = apps.get_model("vs_procurement", "StockItem")
    StockLocation = apps.get_model("vs_procurement", "StockLocation")
    StockBalance = apps.get_model("vs_procurement", "StockBalance")
    StockMovement = apps.get_model("vs_procurement", "StockMovement")

    entity_ids = set(StockItem.objects.values_list("entity_id", flat=True))
    entity_ids |= set(StockMovement.objects.values_list("entity_id", flat=True))

    locations = {}
    for entity_id in sorted(entity_ids):
        location, _ = StockLocation.objects.get_or_create(
            entity_id=entity_id, code=DEFAULT_CODE,
            defaults={
                "name": DEFAULT_NAME,
                "description": "Created when stock gained a location dimension.",
                "is_default": True,
                "is_active": True,
            },
        )
        locations[entity_id] = location

    # Only items that actually hold something get a balance row. Creating one per
    # item would leave a table full of permanent zeroes.
    for item in StockItem.objects.exclude(on_hand_qty=0, stock_value=0):
        StockBalance.objects.get_or_create(
            stock_item=item, location=locations[item.entity_id],
            defaults={
                "on_hand_qty": item.on_hand_qty,
                "stock_value": item.stock_value,
            },
        )

    for entity_id, location in locations.items():
        StockMovement.objects.filter(
            entity_id=entity_id, location__isnull=True,
        ).update(location=location)


def close_default_locations(apps, schema_editor):
    """Unpick the attribution. The item totals were never touched, so nothing is lost."""
    StockLocation = apps.get_model("vs_procurement", "StockLocation")
    StockBalance = apps.get_model("vs_procurement", "StockBalance")
    StockMovement = apps.get_model("vs_procurement", "StockMovement")

    StockMovement.objects.filter(location__isnull=False).update(location=None)
    StockBalance.objects.all().delete()
    StockLocation.objects.filter(code=DEFAULT_CODE).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("vs_finance", "0020_alter_financeaccountmapping_key"),
        ("vs_procurement", "0027_non_po_invoices_off_by_default"),
        ("vs_schools", "0003_branch_tenant"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Location code, unique within the entity.",
                        max_length=40,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="The location used when a caller names none. One per entity.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Campus this store belongs to. Blank for an entity-wide store.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_locations",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_locations",
                        to="vs_finance.ledgerentity",
                    ),
                ),
            ],
            options={
                "ordering": ["entity", "code"],
            },
        ),
        migrations.CreateModel(
            name="StockBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "on_hand_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Live quantity at this location (maintained by the stock ledger).",
                        max_digits=16,
                    ),
                ),
                (
                    "stock_value",
                    vs_finance.money.MoneyField(
                        help_text="Value of stock at this location, in kobo (weighted-average basis)."
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balances",
                        to="vs_procurement.stockitem",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balances",
                        to="vs_procurement.stocklocation",
                    ),
                ),
            ],
            options={
                "ordering": ["stock_item", "location"],
            },
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Where the stock moved. Set on every movement written after 0028.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="vs_procurement.stocklocation",
            ),
        ),
        migrations.AddIndex(
            model_name="stocklocation",
            index=models.Index(
                fields=["entity", "is_active"], name="vs_procurem_entity__59a5d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocklocation",
            index=models.Index(
                fields=["entity", "branch"], name="vs_procurem_entity__d28c6c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklocation",
            constraint=models.UniqueConstraint(
                fields=("entity", "code"), name="uniq_proc_stocklocation_entity_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("entity",),
                name="uniq_proc_stocklocation_one_default",
            ),
        ),
        migrations.AddIndex(
            model_name="stockbalance",
            index=models.Index(
                fields=["location", "stock_item"], name="vs_procurem_locatio_28e64a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbalance",
            constraint=models.UniqueConstraint(
                fields=("stock_item", "location"),
                name="uniq_proc_stockbalance_item_location",
            ),
        ),
        migrations.RunPython(open_default_locations, close_default_locations),
    ]
