# Generated by Django 5.2.10 on 2026-08-15 07:06

import django.db.models.deletion
import django.utils.timezone
import vs_procurement.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_procurement", "0028_stock_locations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorInvoiceAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=vs_procurement.models.vendor_invoice_attachment_path
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=120)),
                ("size", models.PositiveIntegerField()),
                ("caption", models.CharField(blank=True, default="", max_length=255)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_invoice_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="vs_procurement.vendorinvoice",
                    ),
                ),
            ],
            options={
                "ordering": ["vendor_invoice", "id"],
                "indexes": [
                    models.Index(
                        fields=["vendor_invoice"], name="vs_procurem_vendor__03f0ca_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VendorPaymentAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=vs_procurement.models.vendor_payment_attachment_path
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=120)),
                ("size", models.PositiveIntegerField()),
                ("caption", models.CharField(blank=True, default="", max_length=255)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="vs_procurement.vendorpayment",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_payment_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["payment", "id"],
                "indexes": [
                    models.Index(
                        fields=["payment"], name="vs_procurem_payment_c14498_idx"
                    )
                ],
            },
        ),
    ]
