# Generated by Django 5.2.10 on 2026-08-20 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_procurement", "0031_vendor_delivery_cc_to_bcc"),
        ("vs_tenants", "0008_alter_branch_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocklocation",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Branch this store belongs to. Blank for an entity-wide store.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_locations",
                to="vs_tenants.branch",
            ),
        ),
    ]
