# Generated by Django 5.2.10 on 2026-08-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_procurement", "0032_alter_stocklocation_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="bank_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Provider bank code used for verified electronic disbursements.",
                max_length=20,
            ),
        ),
    ]
