# Generated by Django 5.2.10 on 2026-09-26 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_procurement", "0034_approver_groups_nobody_asked_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="procurementsettings",
            name="non_po_spend_limit_pct",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="Share of spend the school accepts on bills raised without a purchase order.",
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
    ]
