# Generated by Django 5.2.10 on 2026-09-26 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0030_document_settings_collection_target"),
        ("vs_procurement", "0035_non_po_spend_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                help_text="Who the stock was issued to, when an issue names one.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="vs_finance.costcenter",
            ),
        ),
    ]
