# Generated by Django 5.2.10 on 2026-09-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_procurement", "0036_stock_issue_cost_center"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorpayment",
            name="wht_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMPUTED", "Computed from the tax code"),
                    ("ENTERED", "Entered by hand"),
                ],
                default="",
                help_text="Whether wht_amount was computed from the tax code or entered by hand.",
                max_length=8,
            ),
        ),
    ]
