# Generated by Django 5.2.10 on 2026-09-30 02:42

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0035_tax_returns_declare_source_lines"),
        ("vs_procurement", "0038_backfill_vendor_quotation_media_tenant"),
        ("vs_tenants", "0010_remove_branch__type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceivednoteline",
            name="returned_qty",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Accepted quantity sent back to the vendor by posted goods returns.",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="vendorinvoice",
            name="amount_credited",
            field=vs_finance.money.MoneyField(
                help_text="Vendor credit notes applied to this bill, in kobo."
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("RECEIPT", "Receipt"),
                    ("ISSUE", "Issue"),
                    ("ADJUSTMENT", "Adjustment"),
                    ("RETURN", "Return to vendor"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="GoodsReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("return_date", models.DateField()),
                ("reason", models.CharField(max_length=255)),
                (
                    "total_value",
                    vs_finance.money.MoneyField(
                        help_text="Value taken back out of GR/IR (ex-tax), in kobo."
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_tenants.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "grn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="vs_procurement.goodsreceivednote",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_returns",
                        to="vs_finance.journalentry",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_returns",
                        to="vs_procurement.vendor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GoodsReturnLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "value_amount",
                    vs_finance.money.MoneyField(
                        help_text="quantity × receipt unit price, in kobo."
                    ),
                ),
                ("line_no", models.PositiveSmallIntegerField(default=0)),
                (
                    "goods_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="vs_procurement.goodsreturn",
                    ),
                ),
                (
                    "grn_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_lines",
                        to="vs_procurement.goodsreceivednoteline",
                    ),
                ),
            ],
            options={
                "ordering": ["goods_return", "line_no", "id"],
            },
        ),
        migrations.CreateModel(
            name="VendorCreditNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("note_date", models.DateField()),
                (
                    "vendor_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The vendor's own credit memo number.",
                        max_length=64,
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                (
                    "subtotal",
                    vs_finance.money.MoneyField(help_text="Net of tax, in kobo."),
                ),
                (
                    "tax_total",
                    vs_finance.money.MoneyField(
                        help_text="Input tax reversed, in kobo."
                    ),
                ),
                (
                    "total",
                    vs_finance.money.MoneyField(
                        help_text="subtotal + tax_total, in kobo."
                    ),
                ),
                (
                    "allocated_amount",
                    vs_finance.money.MoneyField(
                        help_text="Credit applied to bills, in kobo."
                    ),
                ),
                (
                    "approval_state",
                    models.CharField(
                        choices=[
                            ("NOT_SUBMITTED", "Not submitted"),
                            ("PENDING", "Pending approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="NOT_SUBMITTED",
                        help_text="Approval state driven by vs_workflow (overlay; not the ledger status).",
                        max_length=16,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_tenants.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_credit_notes",
                        to="vs_finance.currency",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_credit_notes",
                        to="vs_finance.journalentry",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_notes",
                        to="vs_procurement.vendor",
                    ),
                ),
                (
                    "vendor_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_notes",
                        to="vs_procurement.vendorinvoice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VendorCreditAllocationJournal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Vendor credit reclassified to AP, in kobo."
                    ),
                ),
                (
                    "journal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_credit_allocation",
                        to="vs_finance.journalentry",
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocation_journals",
                        to="vs_procurement.vendorcreditnote",
                    ),
                ),
            ],
            options={
                "ordering": ["journal_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="VendorCreditNoteAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Credit applied to this bill, in kobo."
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        help_text="Accounting date of the journal that debited AP for this settlement."
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="vs_procurement.vendorcreditnote",
                    ),
                ),
                (
                    "vendor_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_allocations",
                        to="vs_procurement.vendorinvoice",
                    ),
                ),
            ],
            options={
                "ordering": ["note", "id"],
            },
        ),
        migrations.CreateModel(
            name="VendorCreditNoteLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Units credited; zero for a price allowance that moves value only.",
                        max_digits=14,
                    ),
                ),
                (
                    "net_amount",
                    vs_finance.money.MoneyField(help_text="Net credited, in kobo."),
                ),
                (
                    "tax_amount",
                    vs_finance.money.MoneyField(
                        help_text="Input tax reversed, in kobo."
                    ),
                ),
                ("line_no", models.PositiveSmallIntegerField(default=0)),
                (
                    "credit_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="vs_procurement.vendorcreditnote",
                    ),
                ),
                (
                    "invoice_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_note_lines",
                        to="vs_procurement.vendorinvoiceline",
                    ),
                ),
            ],
            options={
                "ordering": ["credit_note", "line_no", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="goodsreturn",
            index=models.Index(
                fields=["entity", "return_date"], name="vs_procurem_entity__2d0392_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goodsreturn",
            index=models.Index(fields=["grn"], name="vs_procurem_grn_id_8d19a4_idx"),
        ),
        migrations.AddConstraint(
            model_name="goodsreturn",
            constraint=models.UniqueConstraint(
                fields=("entity", "document_number"),
                name="uniq_vs_procurement_goodsreturn_entity_docnum",
            ),
        ),
        migrations.AddIndex(
            model_name="goodsreturnline",
            index=models.Index(
                fields=["grn_line"], name="vs_procurem_grn_lin_f69d8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorcreditnote",
            index=models.Index(
                fields=["entity", "status"], name="vs_procurem_entity__37a6c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorcreditnote",
            index=models.Index(
                fields=["vendor"], name="vs_procurem_vendor__414620_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorcreditnote",
            index=models.Index(
                fields=["vendor_invoice"], name="vs_procurem_vendor__eef3be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorcreditnote",
            index=models.Index(
                fields=["entity", "note_date"], name="vs_procurem_entity__c84404_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorcreditnote",
            constraint=models.UniqueConstraint(
                fields=("entity", "document_number"),
                name="uniq_vs_procurement_vendorcreditnote_entity_docnum",
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorcreditnote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("allocated_amount__gte", 0),
                    ("allocated_amount__lte", models.F("total")),
                ),
                name="ck_proc_vcn_alloc_within_total",
            ),
        ),
        migrations.AddIndex(
            model_name="vendorcreditnoteallocation",
            index=models.Index(
                fields=["vendor_invoice"], name="vs_procurem_vendor__4a7f26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorcreditnoteallocation",
            index=models.Index(fields=["note"], name="vs_procurem_note_id_f07240_idx"),
        ),
        migrations.AddConstraint(
            model_name="vendorcreditnoteallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="ck_proc_vcn_alloc_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorcreditnoteline",
            index=models.Index(
                fields=["invoice_line"], name="vs_procurem_invoice_7e197f_idx"
            ),
        ),
    ]
