# Generated by Django 5.2.10 on 2026-09-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_procurement", "0040_vendor_credit_note_approval_routes"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorinvoice",
            name="is_opening",
            field=models.BooleanField(
                default=False,
                help_text="An unpaid bill carried in from before these books began (opening balance).",
            ),
        ),
    ]
