# Generated by Django 5.2.10 on 2026-10-01 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0052_inter_branch_transfers"),
        ("vs_procurement", "0042_vendor_assessment_date_no_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="inter_branch_transfer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="vs_finance.interbranchtransfer",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="paired_movement",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paired_with",
                to="vs_procurement.stockmovement",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("RECEIPT", "Receipt"),
                    ("ISSUE", "Issue"),
                    ("ADJUSTMENT", "Adjustment"),
                    ("RETURN", "Return to vendor"),
                    ("TRANSFER", "Transfer between stores"),
                ],
                max_length=16,
            ),
        ),
    ]
