# Generated by Django 5.2.10 on 2026-08-29 18:53

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.manager
import django.utils.timezone
import schools.vs_students.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0006_backfill_storedfile_bindings"),
        ("vs_academics", "0008_a_level_says_whether_it_ends"),
        ("vs_tenants", "0008_alter_branch_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=32)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "occupation",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("address", models.TextField(blank=True, default="")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guardians",
                        to="vs_tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guardian_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student_number",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("FEMALE", "Female"), ("MALE", "Male")], max_length=10
                    ),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "state_of_origin",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("address", models.TextField(blank=True, default="")),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "previous_school",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "photo",
                    models.FileField(
                        blank=True,
                        upload_to=schools.vs_students.models.student_photo_path,
                    ),
                ),
                ("blood_group", models.CharField(blank=True, default="", max_length=4)),
                ("allergies", models.CharField(blank=True, default="", max_length=200)),
                (
                    "conditions",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLICANT", "Applicant"),
                            ("ENROLLED", "Enrolled"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("GRADUATED", "Graduated"),
                            ("TRANSFERRED", "Transferred"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="APPLICANT",
                        max_length=12,
                    ),
                ),
                (
                    "enrolment_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("applied_on", models.DateField(blank=True, null=True)),
                (
                    "applied_for",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vs_academics.level",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="vs_tenants.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ClassEnrolment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "effective_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PARENT_REQUEST", "Parent request"),
                            ("STREAM_CHANGE", "Stream change"),
                            ("CLASS_BALANCING", "Class balancing"),
                            ("BEHAVIOUR", "Behaviour"),
                            ("ACADEMIC_PLACEMENT", "Academic placement"),
                            ("OTHER", "Other"),
                        ],
                        default="",
                        max_length=24,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("CURRENT", "Current"),
                            ("PROMOTED", "Promoted"),
                            ("REPEATED", "Repeated"),
                            ("GRADUATED", "Graduated"),
                            ("TRANSFERRED", "Transferred"),
                            ("ENDED", "Ended"),
                        ],
                        default="CURRENT",
                        max_length=12,
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrolments",
                        to="vs_academics.schoolclass",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrolments",
                        to="vs_academics.academicsession",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="class_enrolments",
                        to="vs_tenants.tenant",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolments",
                        to="vs_students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_at"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="StudentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("BIRTH_CERTIFICATE", "Birth certificate"),
                            ("REPORT_CARD", "Previous report card"),
                            ("PASSPORT_PHOTO", "Passport photograph"),
                            ("TRANSFER_CERTIFICATE", "Transfer certificate"),
                            ("IMMUNISATION", "Immunisation record"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=schools.vs_students.models.student_document_path
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("size", models.PositiveIntegerField(default=0)),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="vs_students.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_documents",
                        to="vs_tenants.tenant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["document_type"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="StudentGuardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("MOTHER", "Mother"),
                            ("FATHER", "Father"),
                            ("UNCLE", "Uncle"),
                            ("AUNT", "Aunt"),
                            ("GRANDPARENT", "Grandparent"),
                            ("LEGAL_GUARDIAN", "Legal guardian"),
                            ("SIBLING", "Sibling"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_links",
                        to="vs_students.guardian",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardian_links",
                        to="vs_students.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "id"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="StudentPromotionBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total", models.PositiveIntegerField(default=0)),
                ("promoted", models.PositiveIntegerField(default=0)),
                ("repeated", models.PositiveIntegerField(default=0)),
                ("graduated", models.PositiveIntegerField(default=0)),
                ("held", models.PositiveIntegerField(default=0)),
                ("excluded", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                (
                    "background_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.backgroundjob",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vs_tenants.branch",
                    ),
                ),
                (
                    "from_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vs_academics.academicsession",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vs_tenants.tenant",
                    ),
                ),
                (
                    "to_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vs_academics.academicsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="StudentStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("APPLICANT", "Applicant"),
                            ("ENROLLED", "Enrolled"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("GRADUATED", "Graduated"),
                            ("TRANSFERRED", "Transferred"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="",
                        max_length=12,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("APPLICANT", "Applicant"),
                            ("ENROLLED", "Enrolled"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("GRADUATED", "Graduated"),
                            ("TRANSFERRED", "Transferred"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=12,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=200)),
                (
                    "effective_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "destination_school",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="vs_students.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="guardian",
            index=models.Index(
                fields=["tenant", "phone"], name="vs_students_tenant__1eb8ee_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="guardian",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                models.F("tenant"),
                condition=models.Q(("email", ""), _negated=True),
                name="uq_guardian_tenant_email_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="guardian",
            constraint=models.UniqueConstraint(
                models.F("tenant"),
                models.F("user"),
                condition=models.Q(("user__isnull", False)),
                name="uq_guardian_tenant_user",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["tenant", "branch", "status"],
                name="vs_students_tenant__f5fb99_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["tenant", "status"], name="vs_students_tenant__c8aa33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["tenant", "last_name", "first_name"],
                name="vs_students_tenant__550365_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("student_number"),
                models.F("tenant"),
                condition=models.Q(("student_number", ""), _negated=True),
                name="uq_student_tenant_number_ci",
            ),
        ),
        migrations.AddIndex(
            model_name="classenrolment",
            index=models.Index(
                fields=["school_class", "is_active"],
                name="vs_students_school__2975df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classenrolment",
            index=models.Index(
                fields=["tenant", "session", "is_active"],
                name="vs_students_tenant__0485ee_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="classenrolment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("student", "session"),
                name="uq_enrolment_one_active_per_session",
            ),
        ),
        migrations.AddIndex(
            model_name="studentdocument",
            index=models.Index(
                fields=["tenant", "student"], name="vs_students_tenant__604c5f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentdocument",
            constraint=models.UniqueConstraint(
                fields=("student", "document_type"), name="uq_student_document_type"
            ),
        ),
        migrations.AddIndex(
            model_name="studentguardian",
            index=models.Index(
                fields=["tenant", "guardian"], name="vs_students_tenant__ebdd26_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentguardian",
            constraint=models.UniqueConstraint(
                fields=("student", "guardian"), name="uq_studentguardian_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentguardian",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("student",),
                name="uq_studentguardian_one_primary",
            ),
        ),
        migrations.AddIndex(
            model_name="studentpromotionbatch",
            index=models.Index(
                fields=["tenant", "from_session"], name="vs_students_tenant__989196_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentstatuslog",
            index=models.Index(
                fields=["student", "changed_at"], name="vs_students_student_26a2aa_idx"
            ),
        ),
    ]
