# Generated by Django 5.2.10 on 2026-09-03 20:07

import schools.vs_students.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_students", "0002_bind_student_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardian",
            name="photo",
            field=models.FileField(
                blank=True, upload_to=schools.vs_students.models.guardian_photo_path
            ),
        ),
    ]
