# Generated by Django 5.2.10 on 2026-07-14 16:09

import django.db.models.manager
import django.utils.timezone
import vs_tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ticket_number",
                    models.CharField(editable=False, max_length=32, unique=True),
                ),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BUG", "Bug report"),
                            ("SUPPORT", "Support request"),
                            ("HELP", "Help"),
                            ("ACCOUNT", "Account"),
                            ("BILLING", "Billing"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="SUPPORT",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        db_index=True,
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_PROGRESS", "In progress"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("INTERNAL", "Internal"), ("CUSTOMER", "Customer")],
                        db_index=True,
                        default="CUSTOMER",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "vs_tickets_ticket",
                "ordering": ["-created_at"],
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TicketAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=vs_tickets.models.ticket_attachment_upload_to
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("size", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "vs_tickets_attachment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("UPDATED", "Updated"),
                            ("ASSIGNED", "Assigned"),
                            ("STATUS_CHANGED", "Status changed"),
                            ("COMMENTED", "Commented"),
                            ("INTERNAL_NOTE_ADDED", "Internal note added"),
                            ("ATTACHMENT_ADDED", "Attachment added"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("summary", models.TextField(blank=True, default="")),
                ("before_data", models.JSONField(blank=True, default=dict)),
                ("after_data", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
            options={
                "db_table": "vs_tickets_audit_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField()),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PUBLIC", "Public"), ("INTERNAL", "Internal")],
                        db_index=True,
                        default="PUBLIC",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "vs_tickets_comment",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "vs_tickets_sequence",
            },
        ),
    ]
