# Generated by Django 5.2.10 on 2026-07-14 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vs_schools", "0001_initial"),
        ("vs_tenants", "0001_initial"),
        ("vs_tickets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="vs_schools.branch",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requested_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="ticketattachment",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="vs_tickets.ticket",
            ),
        ),
        migrations.AddField(
            model_name="ticketattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ticket_attachments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticketauditlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ticket_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticketauditlog",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="vs_tickets.ticket",
            ),
        ),
        migrations.AddField(
            model_name="ticketcomment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ticket_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticketcomment",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="vs_tickets.ticket",
            ),
        ),
        migrations.AddField(
            model_name="ticketattachment",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="vs_tickets.ticketcomment",
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["status", "priority"], name="vs_tickets__status_3e2aa6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["requester", "status"], name="vs_tickets__request_692da4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["assignee", "status"], name="vs_tickets__assigne_b4fa53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["tenant", "status"], name="vs_tickets__tenant__4a2939_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["category", "created_at"], name="vs_tickets__categor_653520_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["created_at"], name="vs_tickets__created_ad766f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketauditlog",
            index=models.Index(
                fields=["ticket", "created_at"], name="vs_tickets__ticket__2fdd99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketauditlog",
            index=models.Index(
                fields=["action", "created_at"], name="vs_tickets__action_9329fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketcomment",
            index=models.Index(
                fields=["ticket", "visibility"], name="vs_tickets__ticket__249f36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketcomment",
            index=models.Index(
                fields=["author", "created_at"], name="vs_tickets__author__8c53ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketattachment",
            index=models.Index(
                fields=["ticket", "created_at"], name="vs_tickets__ticket__972eb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketattachment",
            index=models.Index(
                fields=["uploaded_by", "created_at"],
                name="vs_tickets__uploade_b5b4bd_idx",
            ),
        ),
    ]
