# Generated by Django 5.2.10 on 2026-07-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_tickets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "vs_tickets_sequence",
            },
        ),
    ]
