# Generated by Django 5.2.10 on 2026-07-12 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "vs_tenants",
            "0003_rename_vs_tenants_kind_status_idx_vs_tenants__kind_580eca_idx",
        ),
        ("vs_tickets", "0002_ticketsequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="vs_tenants.tenant",
            ),
        ),
    ]
