# Generated by Django 5.2.10 on 2026-07-12 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_schools", "0004_require_school_tenant"),
        ("vs_tenants", "0004_backfill_business_tenants"),
        ("vs_tickets", "0003_ticket_tenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ticket",
            name="vs_tickets__school__1b7dff_idx",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="school",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["tenant", "status"], name="vs_tickets__tenant__4a2939_idx"
            ),
        ),
    ]
