# Generated by Django 5.2.10 on 2026-09-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_tickets", "0008_ticket_escalated_at_ticket_escalated_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("UPDATED", "Updated"),
                    ("ASSIGNED", "Assigned"),
                    ("STATUS_CHANGED", "Status changed"),
                    ("COMMENTED", "Commented"),
                    ("INTERNAL_NOTE_ADDED", "Internal note added"),
                    ("ATTACHMENT_ADDED", "Attachment added"),
                    ("ESCALATED", "Escalated to CodeX"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
