# Generated by Django 5.2.10 on 2026-08-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_schools", "0006_school_operates_branches"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("PENDING", "Pending"),
                    ("SUSPENDED", "Suspended"),
                ],
                db_index=True,
                default="PENDING",
                max_length=16,
            ),
        ),
    ]
