# Generated by Django 5.2.10 on 2026-09-06 08:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_schools", "0011_drop_declared_seat_capacities"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="packageplan",
            name="max_admins",
        ),
        migrations.RemoveField(
            model_name="packageplan",
            name="max_branch",
        ),
        migrations.RemoveField(
            model_name="packageplan",
            name="max_students",
        ),
        migrations.RemoveField(
            model_name="packageplan",
            name="max_teachers",
        ),
        migrations.AddField(
            model_name="packageplan",
            name="default_depth",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(10, "Core"), (20, "Plus"), (30, "Advanced")],
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="PackagePlanModuleDepth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("capability_key", models.SlugField(max_length=100)),
                (
                    "depth",
                    models.PositiveSmallIntegerField(
                        choices=[(10, "Core"), (20, "Plus"), (30, "Advanced")]
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_depths",
                        to="vs_schools.packageplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Package Plan Module Depth",
                "verbose_name_plural": "Package Plan Module Depths",
                "ordering": ["capability_key"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plan", "capability_key"), name="uniq_plan_module_depth"
                    )
                ],
            },
        ),
    ]
