"""Seed vs_workflow permission keys and grant them to platform roles (idempotent).

Run order:
    python manage.py seed_actions                 # adds submit, cancel, reverse
    python manage.py create_superuser             # ensures xvs_super_admin + xvs_platform_admin
    python manage.py seed_workflow_permissions

Safe to re-run — all operations use get_or_create.
"""
from django.core.management.base import BaseCommand
from django.db import transaction


# (resource_name, resource_description, [(action_name, description, is_restricted), ...])
WORKFLOW_RESOURCES = [
    (
        "template",
        "Workflow template definitions",
        [
            ("manage", "Create, update, and publish workflow templates",      True),
            ("view",   "View workflow templates (read-only)",                 False),
        ],
    ),
    (
        "instance",
        "Workflow approval instances",
        [
            ("submit", "Submit a document for workflow approval",             False),
            ("view",   "View workflow instances and their stage history",     False),
            ("cancel", "Cancel a workflow instance (admin override)",         True),
        ],
    ),
    (
        "action",
        "Workflow stage actions",
        [
            ("reverse", "Reverse a recorded approver action (admin override)", True),
        ],
    ),
]

PLATFORM_ROLE_IDS = ["xvs_super_admin", "xvs_platform_admin"]


class Command(BaseCommand):
    help = "Seed vs_workflow permission keys and grant them to platform admin roles."

    @transaction.atomic
    def handle(self, *args, **options):
        from vs_rbac.models import (
            Permission,
            PermissionAction,
            PermissionModule,
            PermissionResource,
            PlatformRolePermission,
            PlatformRoleTemplate,
        )

        self.stdout.write(self.style.MIGRATE_HEADING("\n  Seeding workflow permissions...\n"))

        module, created = PermissionModule.objects.get_or_create(
            name="workflow",
            defaults={"description": "Approval workflow engine permissions", "is_active": True},
        )
        if created:
            self.stdout.write("  Created module: workflow")

        created_count = 0
        all_perms = []

        for resource_name, resource_desc, actions in WORKFLOW_RESOURCES:
            resource, _ = PermissionResource.objects.get_or_create(
                module=module,
                name=resource_name,
                defaults={"description": resource_desc, "is_active": True},
            )

            for action_name, description, is_restricted in actions:
                action = PermissionAction.objects.filter(name=action_name).first()
                if not action:
                    self.stdout.write(self.style.WARNING(
                        f"  ⚠  Action '{action_name}' not found — run seed_actions first."
                    ))
                    continue

                # Key is auto-generated by Permission.save() as module.resource.action
                expected_key = f"workflow.{resource_name}.{action_name}"

                perm = Permission.objects.filter(key=expected_key).first()
                if perm:
                    self.stdout.write(f"    {expected_key} (exists)")
                else:
                    perm = Permission(
                        module=module,
                        resource=resource,
                        action=action,
                        description=description,
                        is_restricted=is_restricted,
                        sensitivity_level="SENSITIVE" if is_restricted else "NORMAL",
                        is_active=True,
                    )
                    perm.save()
                    created_count += 1
                    self.stdout.write(f"  + {perm.key}")

                all_perms.append(perm)

        # ── Grant to platform roles ────────────────────────────────────────────

        self.stdout.write(self.style.MIGRATE_HEADING("\n  Granting to platform roles...\n"))

        for role_id in PLATFORM_ROLE_IDS:
            try:
                role = PlatformRoleTemplate.objects.get(id=role_id)
            except PlatformRoleTemplate.DoesNotExist:
                self.stdout.write(self.style.WARNING(
                    f"  ⚠  Role '{role_id}' not found — run create_superuser first."
                ))
                continue

            granted = 0
            for perm in all_perms:
                _, link_created = PlatformRolePermission.objects.get_or_create(
                    role=role,
                    permission=perm,
                    defaults={"granted": True, "granted_by": None},
                )
                if link_created:
                    granted += 1

            self.stdout.write(
                self.style.SUCCESS(f"  {role_id}: granted {granted} new permission(s).")
                if granted else
                f"  {role_id}: all permissions already assigned."
            )

        self.stdout.write(self.style.SUCCESS(
            f"\n  Done. {created_count} new permission(s) created, "
            f"{len(all_perms)} total workflow keys registered.\n"
        ))
