# Generated by Django 5.2.10 on 2026-06-12 06:29

import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "unregistered_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Used only when recipient is null (unregistered recipient path). Stores the email address for the Celery task to dispatch to.",
                        max_length=254,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("in_app", "In-App"), ("email", "Email")],
                        help_text="Which delivery channel this record represents.",
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Rendered subject line (email only). Stored at dispatch time.",
                        max_length=500,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Rendered body after variable substitution. Stored at dispatch time."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        help_text="Delivery status. IN_APP: always SENT on creation. EMAIL: PENDING → SENT or FAILED via Celery task.",
                        max_length=20,
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Populated on FAILED. Stores the last Celery task exception message or a sentinel value (e.g. NO_EMAIL_ADDRESS) for pre-flight failures.",
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of dispatch attempts made by the Celery task.",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="In-app channel only. True once the recipient marks the notification as read.",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when is_read was set to True.",
                        null=True,
                    ),
                ),
                (
                    "dispatched_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the first successful dispatch.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="NotificationEventType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Dot-notation identifier. e.g. billing.invoice_issued. Never changes after creation — other modules depend on this string.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable name displayed in School Admin notification settings.",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Explains when this event fires. Shown in the settings UI.",
                    ),
                ),
                (
                    "source_module",
                    models.CharField(
                        help_text="The vs_* Django app that owns this event type. e.g. vs_billing.",
                        max_length=100,
                    ),
                ),
                (
                    "supported_channels",
                    models.JSONField(
                        default=list,
                        help_text='List of channel strings this event supports. e.g. ["in_app", "email"]. Only channels listed here will be dispatched.',
                    ),
                ),
                (
                    "default_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this event type is enabled by default when a new school is seeded. Does not retroactively affect existing school settings.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Platform-level kill switch. Inactive event types are never dispatched regardless of school settings. Use this to retire an event type.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification event type",
                "verbose_name_plural": "Notification event types",
                "ordering": ["source_module", "key"],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("in_app", "In-App"), ("email", "Email")],
                        help_text="The delivery channel this template renders for.",
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Email subject line. Supports {{ variable }} substitution. Not used for in-app channel.",
                        max_length=500,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Notification body. Supports {{ variable }} substitution using Django template syntax. Stored rendered at dispatch time."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive templates cause the channel to be silently skipped at dispatch time. Existing Notification records are unaffected.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification template",
                "verbose_name_plural": "Notification templates",
                "ordering": ["event_type__source_module", "event_type__key", "channel"],
            },
        ),
        migrations.CreateModel(
            name="SchoolNotificationSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("in_app", "In-App"), ("email", "Email")],
                        help_text="The channel being configured.",
                        max_length=20,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this (event_type, channel) fires for this school. School Admins toggle this. IN_APP cannot be set to False.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "School notification setting",
                "verbose_name_plural": "School notification settings",
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
