# Generated by Django 5.2.10 on 2026-07-14 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vs_notifications", "0001_initial"),
        ("vs_tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                help_text="The target User. Null only for unregistered recipients (e.g. user.invited before the account is created).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notifications",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="event_type",
            field=models.ForeignKey(
                help_text="The event type that triggered this notification.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notifications",
                to="vs_notifications.notificationeventtype",
            ),
        ),
        migrations.AddField(
            model_name="notificationsetting",
            name="event_type",
            field=models.ForeignKey(
                help_text="The event type being configured.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to="vs_notifications.notificationeventtype",
            ),
        ),
        migrations.AddField(
            model_name="notificationsetting",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Null only for platform-wide defaults.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notification_settings",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="notificationsetting",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The admin who last changed this setting.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notification_settings_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Vision Staff user who created this template.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notification_templates_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="event_type",
            field=models.ForeignKey(
                help_text="The event type this template belongs to.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="templates",
                to="vs_notifications.notificationeventtype",
            ),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Vision Staff user who last edited this template.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notification_templates_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "channel", "is_read", "-created_at"],
                name="vs_notifica_recipie_5e0240_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["tenant", "event_type", "status"],
                name="vs_notifica_tenant__fe9682_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["tenant", "channel", "status", "-created_at"],
                name="vs_notifica_tenant__354928_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["status", "channel", "-created_at"],
                name="vs_notifica_status_6569cc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationsetting",
            index=models.Index(
                fields=["event_type", "channel", "tenant"],
                name="vs_notifica_event_t_f6ece7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationsetting",
            index=models.Index(
                fields=["tenant", "channel", "is_enabled"],
                name="vs_notifica_tenant__9440a9_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationsetting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tenant__isnull", False)),
                fields=("tenant", "event_type", "channel"),
                name="uq_notif_setting_tenant_scoped",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationsetting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tenant__isnull", True)),
                fields=("event_type", "channel"),
                name="uq_notif_setting_platform",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notificationtemplate",
            unique_together={("event_type", "channel")},
        ),
    ]
