# Generated by Django 5.2.10 on 2026-06-12 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vs_notifications", "0001_initial"),
        ("vs_schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                help_text="The target User. Null only for unregistered recipients (e.g. user.invited before the account is created).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="school",
            field=models.ForeignKey(
                help_text="School of the recipient. Scoping anchor — never null.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notifications",
                to="vs_schools.school",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="event_type",
            field=models.ForeignKey(
                help_text="The event type that triggered this notification.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notifications",
                to="vs_notifications.notificationeventtype",
            ),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Vision Staff user who created this template.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notification_templates_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="event_type",
            field=models.ForeignKey(
                help_text="The event type this template belongs to.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="templates",
                to="vs_notifications.notificationeventtype",
            ),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Vision Staff user who last edited this template.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notification_templates_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="schoolnotificationsetting",
            name="event_type",
            field=models.ForeignKey(
                help_text="The event type being configured.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="school_settings",
                to="vs_notifications.notificationeventtype",
            ),
        ),
        migrations.AddField(
            model_name="schoolnotificationsetting",
            name="school",
            field=models.ForeignKey(
                help_text="The school these settings apply to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_settings",
                to="vs_schools.school",
            ),
        ),
        migrations.AddField(
            model_name="schoolnotificationsetting",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The admin who last changed this setting.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notification_settings_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "channel", "is_read", "-created_at"],
                name="vs_notifica_recipie_5e0240_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["school", "event_type", "status"],
                name="vs_notifica_school__4c6df0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["school", "channel", "status", "-created_at"],
                name="vs_notifica_school__8cb79f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["status", "channel", "-created_at"],
                name="vs_notifica_status_6569cc_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notificationtemplate",
            unique_together={("event_type", "channel")},
        ),
        migrations.AddIndex(
            model_name="schoolnotificationsetting",
            index=models.Index(
                fields=["school", "event_type"], name="vs_notifica_school__f6014f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolnotificationsetting",
            index=models.Index(
                fields=["school", "channel", "is_enabled"],
                name="vs_notifica_school__70317f_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="schoolnotificationsetting",
            unique_together={("school", "event_type", "channel")},
        ),
    ]
