# Generated by Django 5.2.10 on 2026-06-11 18:33

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_notifications", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
                "ordering": ["-created_at"],
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.AlterModelOptions(
            name="schoolnotificationsetting",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
                "verbose_name": "School notification setting",
                "verbose_name_plural": "School notification settings",
            },
        ),
        migrations.AlterModelManagers(
            name="notification",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="schoolnotificationsetting",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
