# Generated by Django 5.2.10 on 2026-06-12 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_notifications", "0002_initial"),
        ("vs_schools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="school",
            field=models.ForeignKey(
                blank=True,
                help_text="School of the recipient — the tenant scoping anchor. Null only for platform-level notifications to CX staff (e.g. background-task completion alerts).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notifications",
                to="vs_schools.school",
            ),
        ),
    ]
