# Generated by Django 5.2.10 on 2026-07-12 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_notifications", "0004_notification_overhaul"),
        (
            "vs_tenants",
            "0003_rename_vs_tenants_kind_status_idx_vs_tenants__kind_580eca_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notifications",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="notificationsetting",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Null only for platform-wide defaults.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_settings",
                to="vs_tenants.tenant",
            ),
        ),
    ]
