# Generated by Django 5.2.10 on 2026-07-12 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_notifications", "0005_notification_tenant_notificationsetting_tenant"),
        ("vs_tenants", "0004_backfill_business_tenants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notificationsetting",
            name="uq_notif_setting_school_scoped",
        ),
        migrations.RemoveConstraint(
            model_name="notificationsetting",
            name="uq_notif_setting_platform",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="vs_notifica_school__4c6df0_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="vs_notifica_school__8cb79f_idx",
        ),
        migrations.RemoveIndex(
            model_name="notificationsetting",
            name="vs_notifica_event_t_c986ff_idx",
        ),
        migrations.RemoveIndex(
            model_name="notificationsetting",
            name="vs_notifica_school__f46d44_idx",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="school",
        ),
        migrations.RemoveField(
            model_name="notificationsetting",
            name="school",
        ),
        migrations.AlterField(
            model_name="notification",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notifications",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["tenant", "event_type", "status"],
                name="vs_notifica_tenant__fe9682_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["tenant", "channel", "status", "-created_at"],
                name="vs_notifica_tenant__354928_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationsetting",
            index=models.Index(
                fields=["event_type", "channel", "tenant"],
                name="vs_notifica_event_t_f6ece7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationsetting",
            index=models.Index(
                fields=["tenant", "channel", "is_enabled"],
                name="vs_notifica_tenant__9440a9_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationsetting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tenant__isnull", False)),
                fields=("tenant", "event_type", "channel"),
                name="uq_notif_setting_tenant_scoped",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationsetting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tenant__isnull", True)),
                fields=("event_type", "channel"),
                name="uq_notif_setting_platform",
            ),
        ),
    ]
