# Generated by Django 5.2.10 on 2026-07-12 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "vs_notifications",
            "0006_remove_notificationsetting_uq_notif_setting_school_scoped_and_more",
        ),
        ("vs_tenants", "0004_backfill_business_tenants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationsetting",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Null only for platform-wide defaults.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notification_settings",
                to="vs_tenants.tenant",
            ),
        ),
    ]
