# Generated by Django 5.2.10 on 2026-03-05 19:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["email"], name="vs_institut_email_f9f8a2_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe unique institution identifier. Lowercase, hyphen-separated.",
                        max_length=80,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Slug must be lowercase letters/numbers separated by single hyphens.",
                                regex="^[a-z0-9]+(?:-[a-z0-9]+)*$",
                            )
                        ],
                    ),
                ),
                ("_type", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="Active",
                        max_length=16,
                    ),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["slug"], name="vs_institut_slug_8dec92_idx"),
                    models.Index(
                        fields=["status", "created_at"],
                        name="vs_institut_status_33aa2b_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("slug", ""), _negated=True),
                        name="slug_not_empty",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Branch display name, e.g., 'Lekki Campus'",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.PositiveIntegerField(
                        db_index=True,
                        editable=False,
                        help_text="Branch code unique per institution (1..N).",
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False,
                        help_text="Marks the primary/main branch for this institution.",
                    ),
                ),
                ("category", models.CharField(max_length=80)),
                (
                    "plan_tier",
                    models.CharField(
                        choices=[
                            ("STARTER", "Starter"),
                            ("PRO", "Pro"),
                            ("ENTERPRISE", "Enterprise"),
                        ],
                        default="STARTER",
                        max_length=80,
                    ),
                ),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("website", models.URLField(blank=True, default="")),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=15),
                ),
                ("country", models.CharField(default="Nigeria", max_length=80)),
                ("state", models.CharField(blank=True, default="", max_length=120)),
                ("city", models.CharField(blank=True, default="", max_length=120)),
                ("timezone", models.CharField(blank=True, default="", max_length=64)),
                ("currency", models.CharField(blank=True, default="", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Pending", "Pending Activation"),
                            ("Suspended", "Suspended"),
                            ("Inactive", "Inactive"),
                            ("Closed", "Closed"),
                        ],
                        db_index=True,
                        default="Pending",
                        max_length=16,
                    ),
                ),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="vs_institutions.institution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("actor_id", models.CharField(max_length=120)),
                ("action", models.CharField(max_length=120)),
                ("resource_type", models.CharField(max_length=80)),
                ("resource_slug", models.CharField(max_length=64)),
                ("before_change", models.TextField(blank=True, default="")),
                ("diff_change", models.TextField(blank=True, default="")),
                (
                    "outcome",
                    models.CharField(
                        choices=[("SUCCEEDED", "Succeeded"), ("FAILED", "Failed")],
                        max_length=16,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="vs_institutions.institution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstitutionBranding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="institution_logos/"
                    ),
                ),
                (
                    "institution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branding",
                        to="vs_institutions.institution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InstitutionModuleSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("module_key", models.CharField(max_length=80)),
                ("enabled", models.BooleanField(default=False)),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                (
                    "changed_by_actor_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_settings",
                        to="vs_institutions.institution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BranchLifecycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_state",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Pending", "Pending Activation"),
                            ("Suspended", "Suspended"),
                            ("Inactive", "Inactive"),
                            ("Closed", "Closed"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "to_state",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Pending", "Pending Activation"),
                            ("Suspended", "Suspended"),
                            ("Inactive", "Inactive"),
                            ("Closed", "Closed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("actor_id", models.CharField(max_length=120)),
                ("reason", models.TextField(blank=True, default=None)),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lifecycle_events",
                        to="vs_institutions.branch",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["branch", "occurred_at"],
                        name="vs_institut_branch__ca228d_idx",
                    ),
                    models.Index(
                        fields=["branch", "to_state"],
                        name="vs_institut_branch__87f012_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BranchPrimaryAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role_label",
                    models.CharField(blank=True, default="BR_AD", max_length=80),
                ),
                (
                    "invite_status",
                    models.CharField(
                        choices=[
                            ("Queued", "Queued"),
                            ("Sent", "Sent"),
                            ("Failed", "Failed"),
                        ],
                        db_index=True,
                        default="Queued",
                        max_length=16,
                    ),
                ),
                ("invite_queued_at", models.DateTimeField(blank=True, null=True)),
                ("invite_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_admin",
                        to="vs_institutions.branch",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_admin_for_branches",
                        to="vs_institutions.contactinfo",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["branch", "invite_status"],
                        name="vs_institut_branch__79b886_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["institution", "is_main"], name="vs_institut_institu_27eec8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["institution", "status"], name="vs_institut_institu_df45d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["institution", "code"], name="vs_institut_institu_b38af6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code", 0), _negated=True),
                fields=("institution", "code"),
                name="uniq_branch_code_per_institution_when_present",
            ),
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_main", True)),
                fields=("institution",),
                name="uniq_one_main_branch_per_institution",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["institution", "occurred_at"],
                name="vs_institut_institu_724c96_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["action", "occurred_at"], name="vs_institut_action_a7b267_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["resource_type", "resource_slug"],
                name="vs_institut_resourc_b4a44c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="institutionmodulesetting",
            index=models.Index(
                fields=["institution", "module_key"],
                name="vs_institut_institu_9ac7b9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="institutionmodulesetting",
            index=models.Index(
                fields=["institution", "enabled"], name="vs_institut_institu_1dcef3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="institutionmodulesetting",
            constraint=models.UniqueConstraint(
                fields=("institution", "module_key"),
                name="uniq_module_key_per_institution",
            ),
        ),
    ]
