# Generated by Django 5.2.8 on 2026-02-06 21:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'db_table': 'contact_info',
                'indexes': [models.Index(fields=['email'], name='contact_inf_email_978a65_idx')],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_name', models.CharField(max_length=255)),
                ('institution_slug', models.SlugField(help_text='URL-safe unique institution identifier. Lowercase, hyphen-separated.', max_length=80, unique=True, validators=[django.core.validators.RegexValidator(message='Slug must be lowercase letters/numbers separated by single hyphens.', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('institution_group', models.CharField(blank=True, default='', max_length=80)),
                ('category', models.CharField(max_length=80)),
                ('institution_type', models.CharField(max_length=80)),
                ('plan_tier', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=80)),
                ('region', models.CharField(max_length=120)),
                ('timezone', models.CharField(blank=True, default='', max_length=64)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('primary_contact_name', models.CharField(blank=True, default='', max_length=120)),
                ('primary_contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('primary_contact_phone', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('CONFIGURING', 'Configuring'), ('DATA_IMPORTING', 'Data Importing'), ('READY', 'Ready'), ('LIVE', 'Live'), ('SUSPENDED', 'Suspended'), ('DELETED_SOFT', 'Soft Deleted'), ('LOCKED', 'Locked (Intervention Required)')], db_index=True, default='CREATED', max_length=32)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'institution',
                'indexes': [models.Index(fields=['institution_slug'], name='institution_institu_ff3082_idx'), models.Index(fields=['status', 'created_at'], name='institution_status_464b88_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('institution_slug', ''), _negated=True), name='institution_slug_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='InstitutionBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institution_logos/')),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='vs_institutions.institution')),
            ],
            options={
                'db_table': 'institution_branding',
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_id', models.CharField(max_length=120)),
                ('action', models.CharField(max_length=120)),
                ('resource_type', models.CharField(max_length=80)),
                ('resource_id', models.CharField(max_length=64)),
                ('before_hash', models.CharField(blank=True, default='', max_length=128)),
                ('after_hash', models.CharField(blank=True, default='', max_length=128)),
                ('outcome', models.CharField(choices=[('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], max_length=16)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='vs_institutions.institution')),
            ],
            options={
                'db_table': 'audit_event',
                'indexes': [models.Index(fields=['institution', 'occurred_at'], name='audit_event_institu_03bfa0_idx'), models.Index(fields=['action', 'occurred_at'], name='audit_event_action_01e02e_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_event_resourc_ee3581_idx')],
            },
        ),
        migrations.CreateModel(
            name='InstitutionLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_state', models.CharField(choices=[('CREATED', 'Created'), ('CONFIGURING', 'Configuring'), ('DATA_IMPORTING', 'Data Importing'), ('READY', 'Ready'), ('LIVE', 'Live'), ('SUSPENDED', 'Suspended'), ('DELETED_SOFT', 'Soft Deleted'), ('LOCKED', 'Locked (Intervention Required)')], max_length=32)),
                ('to_state', models.CharField(choices=[('CREATED', 'Created'), ('CONFIGURING', 'Configuring'), ('DATA_IMPORTING', 'Data Importing'), ('READY', 'Ready'), ('LIVE', 'Live'), ('SUSPENDED', 'Suspended'), ('DELETED_SOFT', 'Soft Deleted'), ('LOCKED', 'Locked (Intervention Required)')], max_length=32)),
                ('actor_id', models.CharField(max_length=120)),
                ('reason', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='vs_institutions.institution')),
            ],
            options={
                'db_table': 'institution_lifecycle_event',
                'indexes': [models.Index(fields=['institution', 'occurred_at'], name='institution_institu_263361_idx'), models.Index(fields=['institution', 'to_state'], name='institution_institu_492a03_idx')],
            },
        ),
        migrations.CreateModel(
            name='InstitutionModuleSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_key', models.CharField(max_length=80)),
                ('enabled', models.BooleanField(default=False)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('changed_by_actor_id', models.CharField(blank=True, default='', max_length=120)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_settings', to='vs_institutions.institution')),
            ],
            options={
                'db_table': 'institution_module_setting',
                'indexes': [models.Index(fields=['institution', 'module_key'], name='institution_institu_3b314d_idx'), models.Index(fields=['institution', 'enabled'], name='institution_institu_69b809_idx')],
                'constraints': [models.UniqueConstraint(fields=('institution', 'module_key'), name='uniq_module_key_per_institution')],
            },
        ),
        migrations.CreateModel(
            name='InstitutionOperationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_type', models.CharField(choices=[('SUSPEND', 'Suspend'), ('REACTIVATE', 'Reactivate'), ('SOFT_DELETE', 'Soft Delete'), ('HARD_DELETE', 'Hard Delete'), ('RESET', 'Reset Config')], max_length=16)),
                ('actor_id', models.CharField(max_length=120)),
                ('reason', models.TextField(blank=True, default='')),
                ('confirmation_token', models.CharField(blank=True, default='', help_text='Stores typed confirmation phrase/token or hash reference (never store raw secrets).', max_length=128)),
                ('outcome', models.CharField(choices=[('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], max_length=16)),
                ('error_code', models.CharField(blank=True, default='', max_length=80)),
                ('error_message', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_events', to='vs_institutions.institution')),
            ],
            options={
                'db_table': 'institution_operation_event',
                'indexes': [models.Index(fields=['institution', 'operation_type', 'occurred_at'], name='institution_institu_6559af_idx')],
            },
        ),
        migrations.CreateModel(
            name='InstitutionPrimaryAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_label', models.CharField(blank=True, default='', max_length=80)),
                ('invite_status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=16)),
                ('invite_queued_at', models.DateTimeField(blank=True, null=True)),
                ('invite_sent_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_admin_for_institutions', to='vs_institutions.contactinfo')),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='primary_admin_link', to='vs_institutions.institution')),
            ],
            options={
                'db_table': 'institution_primary_admin',
                'indexes': [models.Index(fields=['institution', 'invite_status'], name='institution_institu_9b67bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProvisioningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provisioning_status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('ROLLED_BACK', 'Rolled Back'), ('ROLLBACK_FAILED', 'Rollback Failed')], db_index=True, default='QUEUED', max_length=32)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=80)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rollback_status', models.CharField(blank=True, choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('ROLLED_BACK', 'Rolled Back'), ('ROLLBACK_FAILED', 'Rollback Failed')], default='', help_text='Optional status reflecting rollback outcome if provisioning failed.', max_length=32)),
                ('rollback_completed_at', models.DateTimeField(blank=True, null=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning', to='vs_institutions.institution')),
            ],
            options={
                'db_table': 'provisioning_record',
                'indexes': [models.Index(fields=['institution', 'provisioning_status'], name='provisionin_institu_193003_idx')],
            },
        ),
    ]
