# Generated by Django 5.2.10 on 2026-03-02 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_institutions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutionprimaryadmin",
            name="institution",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primary_admin",
                to="vs_institutions.institution",
            ),
        ),
    ]
