# Generated by Django 5.2.10 on 2026-03-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_institutions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="institution",
            name="country",
            field=models.CharField(default="Nigeria", max_length=80),
        ),
    ]
