# Generated by Django 5.2.10 on 2026-04-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_institutions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="branch",
            old_name="deleted_at",
            new_name="deactivated_at",
        ),
        migrations.RenameField(
            model_name="institution",
            old_name="deleted_at",
            new_name="deactivated_at",
        ),
        migrations.AlterField(
            model_name="institution",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("PENDING", "Pending"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=16,
            ),
        ),
    ]
