# Generated by Django 5.2.10 on 2026-01-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_institutions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institutionbranding",
            name="accent_color",
        ),
        migrations.RemoveField(
            model_name="institutionbranding",
            name="background_color",
        ),
        migrations.RemoveField(
            model_name="institutionbranding",
            name="logo_asset_ref",
        ),
        migrations.RemoveField(
            model_name="institutionbranding",
            name="primary_color",
        ),
        migrations.RemoveField(
            model_name="institutionbranding",
            name="secondary_color",
        ),
        migrations.RemoveField(
            model_name="institutionbranding",
            name="text_color",
        ),
        migrations.RemoveField(
            model_name="institutionbranding",
            name="theme_pack_key",
        ),
        migrations.AddField(
            model_name="institution",
            name="institution_group",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="institutionbranding",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="institution_logos/"
            ),
        ),
    ]
