# Generated by Django 5.2.10 on 2026-03-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_institutions", "0002_institution_address_alter_institution_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institutionoperationevent",
            name="institution",
        ),
        migrations.RemoveIndex(
            model_name="auditevent",
            name="vs_institut_resourc_63e014_idx",
        ),
        migrations.RenameField(
            model_name="auditevent",
            old_name="resource_id",
            new_name="resource_slug",
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["resource_type", "resource_slug"],
                name="vs_institut_resourc_b4a44c_idx",
            ),
        ),
        migrations.DeleteModel(
            name="InstitutionOperationEvent",
        ),
    ]
