# Generated by Django 5.2.13 on 2026-05-24 14:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vs_schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchFeatureFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("flag_key", models.CharField(db_index=True, max_length=200)),
                ("is_enabled", models.BooleanField(default=False)),
                ("set_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Branch Feature Flag",
                "verbose_name_plural": "Branch Feature Flags",
            },
        ),
        migrations.CreateModel(
            name="ConfigurationChangeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("GLOBAL_CONFIG", "Global Config"),
                            ("FEATURE_FLAG", "Feature Flag"),
                            ("BRANCH_OVERRIDE", "Branch Override"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("target_key", models.CharField(db_index=True, max_length=200)),
                ("previous_value", models.TextField(blank=True, default="")),
                ("new_value", models.TextField()),
                ("changed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("reason", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Configuration Change Log",
                "verbose_name_plural": "Configuration Change Logs",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="ConfigurationKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=200, unique=True)),
                ("value", models.TextField()),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable explanation of what this key controls. Required."
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuration Key",
                "verbose_name_plural": "Configuration Keys",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="BranchConfigOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=200)),
                ("value", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_overrides",
                        to="vs_schools.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch Config Override",
                "verbose_name_plural": "Branch Config Overrides",
            },
        ),
    ]
