# Generated by Django 5.2.13 on 2026-05-05 04:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vs_schools", "0002_remove_mariadb_unsupported_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigurationKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=200, unique=True)),
                ("value", models.TextField()),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable explanation of what this key controls. Required."
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="config_keys_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration Key",
                "verbose_name_plural": "Configuration Keys",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="BranchConfigOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=200)),
                ("value", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_overrides",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="config_overrides_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch Config Override",
                "verbose_name_plural": "Branch Config Overrides",
                "indexes": [
                    models.Index(
                        fields=["branch", "key"], name="vs_config_b_branch__6d0f35_idx"
                    )
                ],
                "unique_together": {("branch", "key")},
            },
        ),
        migrations.CreateModel(
            name="BranchFeatureFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("flag_key", models.CharField(db_index=True, max_length=200)),
                ("is_enabled", models.BooleanField(default=False)),
                ("set_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_flags",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "set_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feature_flags_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch Feature Flag",
                "verbose_name_plural": "Branch Feature Flags",
                "indexes": [
                    models.Index(
                        fields=["branch", "is_enabled"],
                        name="vs_config_b_branch__ce4889_idx",
                    ),
                    models.Index(
                        fields=["branch", "flag_key"],
                        name="vs_config_b_branch__84c898_idx",
                    ),
                ],
                "unique_together": {("branch", "flag_key")},
            },
        ),
        migrations.CreateModel(
            name="ConfigurationChangeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("GLOBAL_CONFIG", "Global Config"),
                            ("FEATURE_FLAG", "Feature Flag"),
                            ("BRANCH_OVERRIDE", "Branch Override"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("target_key", models.CharField(db_index=True, max_length=200)),
                ("previous_value", models.TextField(blank=True, default="")),
                ("new_value", models.TextField()),
                ("changed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_change_logs",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="config_changes_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_change_logs",
                        to="vs_schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration Change Log",
                "verbose_name_plural": "Configuration Change Logs",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["institution", "change_type", "-changed_at"],
                        name="vs_config_c_institu_7c2b46_idx",
                    ),
                    models.Index(
                        fields=["target_key", "-changed_at"],
                        name="vs_config_c_target__afe464_idx",
                    ),
                    models.Index(
                        fields=["changed_by", "-changed_at"],
                        name="vs_config_c_changed_4995d9_idx",
                    ),
                ],
            },
        ),
    ]
