# Generated by Django 5.2.13 on 2026-05-24 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vs_config", "0001_initial"),
        ("vs_schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="branchconfigoverride",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="config_overrides_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="branchfeatureflag",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_flags",
                to="vs_schools.branch",
            ),
        ),
        migrations.AddField(
            model_name="branchfeatureflag",
            name="set_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feature_flags_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="configurationchangelog",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="config_change_logs",
                to="vs_schools.branch",
            ),
        ),
        migrations.AddField(
            model_name="configurationchangelog",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="config_changes_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="configurationchangelog",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="config_change_logs",
                to="vs_schools.school",
            ),
        ),
        migrations.AddField(
            model_name="configurationkey",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="config_keys_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="branchconfigoverride",
            index=models.Index(
                fields=["branch", "key"], name="vs_config_b_branch__6d0f35_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="branchconfigoverride",
            unique_together={("branch", "key")},
        ),
        migrations.AddIndex(
            model_name="branchfeatureflag",
            index=models.Index(
                fields=["branch", "is_enabled"], name="vs_config_b_branch__ce4889_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branchfeatureflag",
            index=models.Index(
                fields=["branch", "flag_key"], name="vs_config_b_branch__84c898_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="branchfeatureflag",
            unique_together={("branch", "flag_key")},
        ),
        migrations.AddIndex(
            model_name="configurationchangelog",
            index=models.Index(
                fields=["institution", "change_type", "-changed_at"],
                name="vs_config_c_institu_7c2b46_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="configurationchangelog",
            index=models.Index(
                fields=["target_key", "-changed_at"],
                name="vs_config_c_target__afe464_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="configurationchangelog",
            index=models.Index(
                fields=["changed_by", "-changed_at"],
                name="vs_config_c_changed_4995d9_idx",
            ),
        ),
    ]
