# Generated by Django 5.2.10 on 2026-07-14 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vs_config", "0001_initial"),
        ("vs_schools", "0001_initial"),
        ("vs_tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="capabilityentitlement",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="capability_entitlements_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="capabilityoverride",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="vs_schools.branch",
            ),
        ),
        migrations.AddField(
            model_name="capabilityoverride",
            name="capability",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="overrides",
                to="vs_config.capability",
            ),
        ),
        migrations.AddField(
            model_name="capabilityoverride",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="capabilityoverride",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="capability_overrides_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="configurationauditevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="configuration_audit_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="configurationauditevent",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="vs_schools.branch",
            ),
        ),
        migrations.AddField(
            model_name="configurationauditevent",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="configurationdefinition",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="configuration_definitions_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="configurationvalue",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="vs_schools.branch",
            ),
        ),
        migrations.AddField(
            model_name="configurationvalue",
            name="definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="vs_config.configurationdefinition",
            ),
        ),
        migrations.AddField(
            model_name="configurationvalue",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="configurationvalue",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="configuration_values_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="capabilitydependency",
            constraint=models.UniqueConstraint(
                fields=("capability", "requires"), name="uniq_capability_dependency"
            ),
        ),
        migrations.AddConstraint(
            model_name="capabilitydependency",
            constraint=models.CheckConstraint(
                condition=models.Q(("capability", models.F("requires")), _negated=True),
                name="capability_cannot_require_itself",
            ),
        ),
        migrations.AddConstraint(
            model_name="capabilityentitlement",
            constraint=models.UniqueConstraint(
                fields=("capability", "scope_key"),
                name="uniq_capability_entitlement_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="capabilityoverride",
            constraint=models.UniqueConstraint(
                fields=("capability", "scope_key"),
                name="uniq_capability_override_scope",
            ),
        ),
        migrations.AddIndex(
            model_name="configurationauditevent",
            index=models.Index(
                fields=["tenant", "branch", "-created_at"],
                name="vs_config_c_tenant__78c756_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="configurationvalue",
            index=models.Index(
                fields=["tenant", "branch"], name="vs_config_c_tenant__2edffb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="configurationvalue",
            constraint=models.UniqueConstraint(
                fields=("definition", "scope_key"), name="uniq_config_value_scope"
            ),
        ),
    ]
