# Generated by Django 5.2.10 on 2026-07-10 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_config", "0004_migrate_legacy_configuration"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BranchConfigOverride",
        ),
        migrations.DeleteModel(
            name="BranchFeatureFlag",
        ),
        migrations.DeleteModel(
            name="ConfigurationChangeLog",
        ),
        migrations.DeleteModel(
            name="ConfigurationKey",
        ),
    ]
