# Generated by Django 5.2.10 on 2026-07-13 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_config", "0006_configuration_audit_immutability"),
        ("vs_tenants", "0004_backfill_business_tenants"),
    ]

    operations = [
        migrations.AddField(
            model_name="capabilityentitlement",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="capability_entitlements",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="capabilityoverride",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="configurationauditevent",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="configurationvalue",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="vs_tenants.tenant",
            ),
        ),
    ]
