# Generated by Django 5.2.5 on 2026-08-09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vs_config", "0006_enable_scoped_security_overrides"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vs_schools", "0001_initial"),
        ("vs_tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="capabilityentitlement",
            index=models.Index(
                fields=["state", "ends_at"], name="config_ent_state_end_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="capabilityentitlement",
            index=models.Index(
                fields=["state", "starts_at"], name="config_ent_state_start_idx",
            ),
        ),
        migrations.CreateModel(
            name="ConfigurationAuditSavedView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False,
                    ),
                ),
                ("scope_key", models.CharField(db_index=True, editable=False, max_length=80)),
                ("name", models.CharField(max_length=80)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuration_audit_saved_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "updated_at"],
                        name="config_saved_owner_time_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "name"),
                        name="uniq_config_audit_saved_view_owner_name",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ConfigurationAuditExportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False,
                    ),
                ),
                ("scope_key", models.CharField(db_index=True, editable=False, max_length=80)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("client_key", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="QUEUED",
                        max_length=12,
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("storage_name", models.CharField(blank=True, max_length=500)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("failure_message", models.CharField(blank=True, max_length=500)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("available_until", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configuration_audit_export_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["requested_by", "-requested_at"],
                        name="config_job_request_time_idx",
                    ),
                    models.Index(
                        fields=["scope_key", "-requested_at"],
                        name="config_job_scope_time_idx",
                    ),
                    models.Index(fields=["client_key"], name="config_job_client_idx"),
                ],
            },
        ),
    ]
