# Generated by Django 5.2.10 on 2026-07-13 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_config", "0008_backfill_tenant_scope"),
        ("vs_schools", "0004_require_school_tenant"),
        ("vs_tenants", "0004_backfill_business_tenants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="configurationauditevent",
            name="vs_config_c_school__23621f_idx",
        ),
        migrations.RemoveIndex(
            model_name="configurationvalue",
            name="vs_config_c_school__1aab3b_idx",
        ),
        migrations.RemoveField(
            model_name="capabilityentitlement",
            name="school",
        ),
        migrations.RemoveField(
            model_name="capabilityoverride",
            name="school",
        ),
        migrations.RemoveField(
            model_name="configurationauditevent",
            name="school",
        ),
        migrations.RemoveField(
            model_name="configurationvalue",
            name="school",
        ),
        migrations.AddIndex(
            model_name="configurationauditevent",
            index=models.Index(
                fields=["tenant", "branch", "-created_at"],
                name="vs_config_c_tenant__78c756_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="configurationvalue",
            index=models.Index(
                fields=["tenant", "branch"], name="vs_config_c_tenant__2edffb_idx"
            ),
        ),
    ]
