# Generated by Django 5.2.10 on 2026-09-06 08:38

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_config", "0009_seed_payroll_scope"),
        ("vs_tenants", "0008_alter_branch_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CapabilityDepthGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "depth",
                    models.PositiveSmallIntegerField(
                        choices=[(10, "Core"), (20, "Plus"), (30, "Advanced")]
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("PACKAGE", "Package"),
                            ("PLATFORM", "Platform"),
                            ("MANUAL", "Manual"),
                            ("IMPORT", "Import"),
                        ],
                        default="MANUAL",
                        max_length=12,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="capability",
            name="depth",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(10, "Core"), (20, "Plus"), (30, "Advanced")],
                db_index=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="capability",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bands",
                to="vs_config.capability",
            ),
        ),
        migrations.AddField(
            model_name="capabilityentitlement",
            name="depth",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(10, "Core"), (20, "Plus"), (30, "Advanced")],
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="capability",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("depth__isnull", True), ("parent__isnull", True)),
                    models.Q(("depth__isnull", False), ("parent__isnull", False)),
                    _connector="OR",
                ),
                name="capability_band_has_parent_and_depth",
            ),
        ),
        migrations.AddField(
            model_name="capabilitydepthgrant",
            name="capability",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="depth_grants",
                to="vs_config.capability",
            ),
        ),
        migrations.AddField(
            model_name="capabilitydepthgrant",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="capability_depth_grants",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="capabilitydepthgrant",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="capability_depth_grants_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="capabilitydepthgrant",
            index=models.Index(
                fields=["tenant", "ends_at"], name="config_depth_tenant_end_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="capabilitydepthgrant",
            constraint=models.UniqueConstraint(
                fields=("capability", "tenant"), name="uniq_capability_depth_grant"
            ),
        ),
    ]
