# Generated by Django 5.2.10 on 2026-03-03 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vs_admin_console", "0001_initial"),
        ("vs_institutions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="adminactionlog",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="admin_console_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="adminactionlog",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                help_text="Some actions can be global, so institution can be empty.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="admin_console_actions",
                to="vs_institutions.institution",
            ),
        ),
        migrations.AddField(
            model_name="featureflag",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_flags",
                to="vs_institutions.institution",
            ),
        ),
        migrations.AddField(
            model_name="featureflag",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="feature_flags_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="impersonationsession",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="impersonation_sessions",
                to="vs_institutions.institution",
            ),
        ),
        migrations.AddField(
            model_name="impersonationsession",
            name="staff_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="impersonation_sessions_started",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="impersonationsession",
            name="target_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="impersonation_sessions_as_target",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="importjoblog",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="import_job_logs",
                to="vs_institutions.institution",
            ),
        ),
        migrations.AddField(
            model_name="provisioningevent",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provisioning_events",
                to="vs_institutions.institution",
            ),
        ),
        migrations.AddConstraint(
            model_name="featureflag",
            constraint=models.UniqueConstraint(
                fields=("institution", "key"), name="uq_feature_flag_per_institution"
            ),
        ),
    ]
