# Generated by Django 5.2.10 on 2026-07-12 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_admin_console", "0002_initial"),
        (
            "vs_tenants",
            "0003_rename_vs_tenants_kind_status_idx_vs_tenants__kind_580eca_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="impersonationsession",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="impersonation_sessions",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="impersonationsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("ENDED", "Ended"),
                    ("EXPIRED", "Expired"),
                ],
                default="ACTIVE",
                max_length=10,
            ),
        ),
    ]
