# Generated by Django 5.2.10 on 2026-07-12 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_admin_console", "0005_require_impersonation_tenant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="impersonationsession",
            name="school",
        ),
    ]
