# Generated by Django 5.2.10 on 2026-08-27 05:37

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vs_academics", "0007_subject_is_catalogue"),
        ("vs_tenants", "0008_alter_branch_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("HOLIDAY", "Public holiday"),
                            ("MIDTERM_BREAK", "Mid-term break"),
                            ("EXAM_PERIOD", "Exam period"),
                            ("SCHOOL_EVENT", "School event"),
                            ("PTA", "PTA"),
                            ("SPORTS", "Sports day"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("closes_school", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calendar_events",
                        to="vs_tenants.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calendar_events",
                        to="vs_academics.academicsession",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calendar_events",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date", "name"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CalendarEventAudience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audience",
                        to="vs_calendar.calendarevent",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_event_audiences",
                        to="vs_academics.level",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_event_audiences",
                        to="vs_academics.schoolclass",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calendar_event_audiences",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ClassTimetable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                        db_index=True,
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timetables",
                        to="vs_academics.schoolclass",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="class_timetables",
                        to="vs_academics.academicsession",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="class_timetables",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["school_class"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                        db_index=True,
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "calendar_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exams",
                        to="vs_calendar.calendarevent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exams",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["calendar_event", "name"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ],
                        db_index=True,
                        null=True,
                    ),
                ),
                ("order_index", models.PositiveSmallIntegerField()),
                ("label", models.CharField(max_length=40)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("LESSON", "Lesson"),
                            ("BREAK", "Break"),
                            ("LUNCH", "Lunch"),
                            ("ASSEMBLY", "Assembly"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="periods",
                        to="vs_tenants.branch",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="periods",
                        to="vs_academics.academicsession",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="periods",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["day_of_week", "order_index"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("code", models.CharField(blank=True, default="", max_length=20)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("CLASSROOM", "Classroom"),
                            ("LABORATORY", "Laboratory"),
                            ("HALL", "Hall"),
                            ("LIBRARY", "Library"),
                            ("SPORTS", "Sports"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("capacity", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rooms",
                        to="vs_tenants.branch",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rooms",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["branch", "name"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ExamSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("exam_date", models.DateField()),
                (
                    "sitting",
                    models.CharField(
                        choices=[("MORNING", "Morning"), ("AFTERNOON", "Afternoon")],
                        max_length=12,
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="vs_calendar.exam",
                    ),
                ),
                (
                    "invigilator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_slots",
                        to="vs_academics.schoolclass",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_slots",
                        to="vs_academics.subject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_slots",
                        to="vs_tenants.tenant",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_slots",
                        to="vs_calendar.room",
                    ),
                ),
            ],
            options={
                "ordering": ["exam_date", "sitting"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TimetableSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ]
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="slots",
                        to="vs_calendar.period",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="slots",
                        to="vs_calendar.room",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timetable_slots",
                        to="vs_academics.schoolclass",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timetable_slots",
                        to="vs_academics.academicsession",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timetable_slots",
                        to="vs_academics.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timetable_slots",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["day_of_week", "period"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(
                fields=["tenant", "session", "start_date"],
                name="vs_calendar_tenant__72a45e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(
                fields=["tenant", "session", "event_type"],
                name="vs_calendar_tenant__d4c919_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="ck_calendar_event_dates",
            ),
        ),
        migrations.AddIndex(
            model_name="calendareventaudience",
            index=models.Index(
                fields=["tenant", "event"], name="vs_calendar_tenant__eb6356_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="calendareventaudience",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("level__isnull", False), ("school_class__isnull", True)),
                    models.Q(("level__isnull", True), ("school_class__isnull", False)),
                    _connector="OR",
                ),
                name="ck_event_audience_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="calendareventaudience",
            constraint=models.UniqueConstraint(
                condition=models.Q(("level__isnull", False)),
                fields=("event", "level"),
                name="uq_event_audience_level",
            ),
        ),
        migrations.AddConstraint(
            model_name="calendareventaudience",
            constraint=models.UniqueConstraint(
                condition=models.Q(("school_class__isnull", False)),
                fields=("event", "school_class"),
                name="uq_event_audience_class",
            ),
        ),
        migrations.AddIndex(
            model_name="classtimetable",
            index=models.Index(
                fields=["tenant", "session", "status"],
                name="vs_calendar_tenant__d8347c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="classtimetable",
            constraint=models.UniqueConstraint(
                fields=("session", "school_class"),
                name="uq_class_timetable_session_class",
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["tenant", "calendar_event"],
                name="vs_calendar_tenant__0dec06_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="period",
            index=models.Index(
                fields=["tenant", "session", "branch", "day_of_week", "order_index"],
                name="vs_calendar_tenant__afaa8d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="period",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="ck_period_times",
            ),
        ),
        migrations.AddConstraint(
            model_name="period",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("branch__isnull", False), ("day_of_week__isnull", False)
                ),
                fields=("tenant", "session", "branch", "day_of_week", "order_index"),
                name="uq_period_order_branch_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="period",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("branch__isnull", True), ("day_of_week__isnull", True)
                ),
                fields=("tenant", "session", "order_index"),
                name="uq_period_order_shared_everyday",
            ),
        ),
        migrations.AddConstraint(
            model_name="period",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("branch__isnull", False), ("day_of_week__isnull", True)
                ),
                fields=("tenant", "session", "branch", "order_index"),
                name="uq_period_order_branch_everyday",
            ),
        ),
        migrations.AddConstraint(
            model_name="period",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("branch__isnull", True), ("day_of_week__isnull", False)
                ),
                fields=("tenant", "session", "day_of_week", "order_index"),
                name="uq_period_order_shared_day",
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["tenant", "branch", "is_active"],
                name="vs_calendar_tenant__dec24a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("branch"),
                name="uq_room_branch_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"),
                models.F("tenant"),
                condition=models.Q(("code", ""), _negated=True),
                name="uq_room_tenant_code",
            ),
        ),
        migrations.AddIndex(
            model_name="examslot",
            index=models.Index(
                fields=["tenant", "exam", "exam_date"],
                name="vs_calendar_tenant__9628b8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="examslot",
            index=models.Index(
                fields=["tenant", "exam", "room", "exam_date"],
                name="vs_calendar_tenant__79dbc9_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="examslot",
            constraint=models.UniqueConstraint(
                fields=("exam", "school_class", "exam_date", "sitting"),
                name="uq_examslot_class_sitting",
            ),
        ),
        migrations.AddConstraint(
            model_name="examslot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("start_time__isnull", True),
                    ("end_time__isnull", True),
                    ("end_time__gt", models.F("start_time")),
                    _connector="OR",
                ),
                name="ck_examslot_times",
            ),
        ),
        migrations.AddIndex(
            model_name="timetableslot",
            index=models.Index(
                fields=["tenant", "session", "teacher", "day_of_week"],
                name="vs_calendar_tenant__1fe4ec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timetableslot",
            index=models.Index(
                fields=["tenant", "session", "room", "day_of_week"],
                name="vs_calendar_tenant__36218f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timetableslot",
            index=models.Index(
                fields=["tenant", "session", "school_class"],
                name="vs_calendar_tenant__c5f218_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="timetableslot",
            constraint=models.UniqueConstraint(
                fields=("session", "school_class", "day_of_week", "period"),
                name="uq_slot_class_day_period",
            ),
        ),
    ]
