# Generated by Django 5.2.4 on 2026-07-22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vs_tenants", "0002_seed_platform_tenant"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantDocumentSequence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("document_code", models.CharField(max_length=16)),
                ("date", models.DateField()),
                ("last_number", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="document_sequences", to="vs_tenants.tenant")),
            ],
            options={
                "indexes": [models.Index(fields=["tenant", "date"], name="tenant_docseq_tenant_date_idx")],
                "constraints": [models.UniqueConstraint(fields=("tenant", "document_code", "date"), name="uniq_tenant_docseq_code_date")],
            },
        ),
    ]
