# Generated by Django 5.2.10 on 2026-07-12 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_tenants", "0002_backfill_tenants"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tenant",
            new_name="vs_tenants__kind_580eca_idx",
            old_name="vs_tenants_kind_status_idx",
        ),
    ]
