# Generated by Django 5.2.10 on 2026-08-17 08:10

from django.db import migrations, models


def backfill_pending_since(apps, schema_editor):
    """Give every tenant that is already PENDING a defensible start date.

    ``created_at`` is the only evidence there is for a tenant that has been
    pending since before the column existed, and for such a tenant it is also
    the truth: it has been pending since it was made. Tenants in any other
    status keep NULL, because the column describes the spell a tenant is in
    now and they are not in one.

    A school that is already past the expiry window will therefore be swept on
    the first run after deployment, which is the intended behaviour: it has
    genuinely been abandoned for that long.
    """
    Tenant = apps.get_model("vs_tenants", "Tenant")
    Tenant.objects.filter(status="PENDING", pending_since__isnull=True).update(
        pending_since=models.F("created_at"),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("vs_tenants", "0004_move_branch_from_vs_schools"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="pending_since",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(
            backfill_pending_since,
            # Reversing drops a derived value and nothing else: the column goes
            # with the AddField above it.
            migrations.RunPython.noop,
        ),
    ]
