# Generated by Django 5.2.10 on 2026-08-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_tenants", "0005_tenant_pending_since"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="expiry_warned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
