# Generated by Django 5.2.10 on 2026-08-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_tenants", "0006_tenant_expiry_warned_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="_type",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AlterField(
            model_name="branchlifecycle",
            name="actor_id",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="branchlifecycle",
            name="from_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACTIVE", "Active"),
                    ("PENDING", "Pending Activation"),
                    ("SUSPENDED", "Suspended"),
                    ("INACTIVE", "Inactive"),
                    ("CLOSED", "Closed"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
