# Generated by Django 5.2.10 on 2026-08-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_tenants", "0007_branch_type_and_lifecycle_blanks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="name",
            field=models.CharField(
                help_text="Branch display name, e.g., 'Lekki Branch'", max_length=255
            ),
        ),
    ]
