# Generated by Django 5.2.10 on 2026-09-09 07:17

"""Drop the branch descriptor nothing read and nothing could have got right.

``Branch._type`` was a free-text column with no choices, no validation and no
reader: no query filtered on it, no report grouped by it, no rule consulted it.
Across every branch on the platform it held two values, "Primary" and
"Secondary", both written by seed data rather than chosen by anybody. The
console's create-branch form nonetheless made it mandatory, so an operator had
to type something unguided into a field that was never read back.

It was also the wrong shape for what it claimed to record. A site does not have
one type: a school runs Nursery, Primary and both Secondary stages school-wide
and Vocational at one branch only. What a branch teaches is
:class:`schools.vs_academics.Program`, which is branch-aware and plural and says
this correctly. The single descriptor could only ever be a lossy summary of it,
and in practice said "Secondary" for a site running four stages.

Data is dropped with the column. Nothing derived anything from it, so there is
nothing to carry across, and the two values it held are recoverable from the
programmes at each site.
"""
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_tenants", "0009_a_site_is_a_branch_not_a_campus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="_type",
        ),
    ]
