# Generated by Django 5.2.10 on 2026-06-12 06:29

import django.db.models.deletion
import django.db.models.manager
import vs_workflow.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("vs_schools", "0001_initial"),
        ("vs_user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowStage",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=vs_workflow.models._short_id,
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.SlugField(max_length=80)),
                ("label", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[("APPROVAL", "Approval"), ("BRANCH", "Branch")],
                        default="APPROVAL",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "approver_source",
                    models.CharField(
                        choices=[
                            ("RBAC_PERMISSION", "RBAC permission holders (default)"),
                            ("ORGANOGRAM", "Organogram (relative to requester)"),
                        ],
                        default="RBAC_PERMISSION",
                        max_length=20,
                    ),
                ),
                (
                    "approver_permission_key",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "approver_scope",
                    models.CharField(
                        choices=[
                            ("BRANCH", "Branch-scoped"),
                            ("SCHOOL", "School-scoped"),
                            ("PLATFORM", "Platform-scoped"),
                        ],
                        default="SCHOOL",
                        max_length=20,
                    ),
                ),
                (
                    "organogram_target",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DIRECT_MANAGER", "Requester's direct manager"),
                            ("N_LEVELS_UP", "N levels up the reporting chain"),
                            ("DEPARTMENT_HEAD", "Head of requester's department"),
                            ("SPECIFIC_POSITION", "Holder(s) of a specific position"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("organogram_levels", models.PositiveSmallIntegerField(default=1)),
                (
                    "advance_rule",
                    models.CharField(
                        choices=[
                            ("UNANIMOUS", "Unanimous (all must approve)"),
                            ("QUORUM", "Quorum (N of M must approve)"),
                            ("ANY", "Any one approver"),
                        ],
                        default="UNANIMOUS",
                        max_length=20,
                    ),
                ),
                ("quorum_count", models.PositiveIntegerField(default=0)),
                (
                    "on_rejection",
                    models.CharField(
                        choices=[
                            ("TERMINAL", "Rejection terminates the workflow"),
                            ("RETURN_TO_REQUESTER", "Rejection returns to requester"),
                        ],
                        default="TERMINAL",
                        max_length=30,
                    ),
                ),
                ("skip_if_no_approvers", models.BooleanField(default=True)),
                ("inclusion_condition", models.JSONField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organogram_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_stages",
                        to="vs_user.position",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowInstance",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=vs_workflow.models._short_id,
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_object_id", models.CharField(db_index=True, max_length=64)),
                ("document_type", models.CharField(db_index=True, max_length=100)),
                ("document_summary", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RETURNED", "Returned to Requester"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("CANCELLED", "Cancelled (Admin)"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("state_version", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_instances",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "document_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_workflow_instances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_instances",
                        to="vs_schools.school",
                    ),
                ),
                (
                    "current_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vs_workflow.workflowstage",
                    ),
                ),
            ],
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowStageInstance",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=vs_workflow.models._short_id,
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("RETURNED", "Returned to Requester"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "skip_reason",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("attempt", models.PositiveIntegerField(default=1)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_instances",
                        to="vs_workflow.workflowinstance",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vs_workflow.workflowstage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowStageApprover",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=vs_workflow.models._short_id,
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempt", models.PositiveIntegerField(default=1)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "on_behalf_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stage_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligible_approvers",
                        to="vs_workflow.workflowstageinstance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowStageAction",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=vs_workflow.models._short_id,
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("RETURNED", "Returned to Requester"),
                            ("WITHDRAWN", "Withdrawn by Requester"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("attempt", models.PositiveIntegerField(default=1)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("reversal_reason", models.TextField(blank=True, default="")),
                ("acted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "is_reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="vs_workflow.workflowstageaction",
                    ),
                ),
                (
                    "on_behalf_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stage_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="vs_workflow.workflowstageinstance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowAuditLog",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=vs_workflow.models._short_id,
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("INSTANCE_SUBMITTED", "Instance submitted"),
                            ("INSTANCE_WITHDRAWN", "Instance withdrawn by requester"),
                            ("INSTANCE_CANCELLED", "Instance cancelled by admin"),
                            ("INSTANCE_APPROVED", "Instance fully approved"),
                            ("INSTANCE_REJECTED", "Instance terminally rejected"),
                            ("INSTANCE_RETURNED", "Instance returned to requester"),
                            (
                                "INSTANCE_RESUBMITTED",
                                "Instance resubmitted after return",
                            ),
                            ("STAGE_ACTIVATED", "Stage became active"),
                            ("STAGE_APPROVED", "Stage approved"),
                            ("STAGE_REJECTED", "Stage rejected"),
                            (
                                "STAGE_SKIPPED_NO_APPROVER",
                                "Stage auto-skipped (no eligible approvers)",
                            ),
                            (
                                "STAGE_SKIPPED_CONDITION",
                                "Stage skipped (conditional branch)",
                            ),
                            ("APPROVER_ACTED", "An approver recorded a vote"),
                            ("ACTION_REVERSED", "Admin reversed an approver action"),
                            ("ROUTE_EVALUATED", "Route recomputed at stage transition"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("context", models.JSONField(blank=True, default=dict)),
                ("message", models.TextField(blank=True, default="")),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to="vs_workflow.workflowinstance",
                    ),
                ),
                (
                    "stage_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vs_workflow.workflowstageinstance",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowTemplate",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=vs_workflow.models._short_id,
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_type", models.CharField(db_index=True, max_length=100)),
                ("code", models.SlugField(max_length=100)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("notification_events", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_templates",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_templates",
                        to="vs_schools.school",
                    ),
                ),
            ],
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="workflowstage",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stages",
                to="vs_workflow.workflowtemplate",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowRoutePath",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=vs_workflow.models._short_id,
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("condition", models.JSONField(blank=True, null=True)),
                (
                    "from_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbound_routes",
                        to="vs_workflow.workflowstage",
                    ),
                ),
                (
                    "to_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbound_routes",
                        to="vs_workflow.workflowstage",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="vs_workflow.workflowtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["from_stage_id", "order"],
            },
        ),
        migrations.AddField(
            model_name="workflowinstance",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="instances",
                to="vs_workflow.workflowtemplate",
            ),
        ),
        migrations.CreateModel(
            name="ApprovalDelegation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=vs_workflow.models._short_id,
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "document_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "exclusive",
                    models.BooleanField(
                        default=False,
                        help_text="If True, delegator is excluded from eligibility for the duration.",
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delegate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delegator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_delegations",
                        to="vs_schools.school",
                    ),
                ),
            ],
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["delegator", "starts_at", "ends_at"],
                        name="vs_workflow_delegat_56ff30_idx",
                    ),
                    models.Index(
                        fields=["delegate", "starts_at", "ends_at"],
                        name="vs_workflow_delegat_0e2a5f_idx",
                    ),
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="workflowstageinstance",
            index=models.Index(
                fields=["instance", "status"], name="vs_workflow_instanc_2e095e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowstageapprover",
            index=models.Index(
                fields=["stage_instance", "attempt"],
                name="vs_workflow_stage_i_2f6bf6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowstageaction",
            index=models.Index(
                fields=["stage_instance", "attempt"],
                name="vs_workflow_stage_i_42abc8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowstageaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_reversal_of__isnull", True)),
                fields=("stage_instance", "actor", "attempt"),
                name="uniq_live_action_per_actor_per_attempt",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowauditlog",
            index=models.Index(
                fields=["instance", "occurred_at"],
                name="vs_workflow_instanc_a5f151_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowauditlog",
            index=models.Index(
                fields=["instance", "event_type"], name="vs_workflow_instanc_c67a36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtemplate",
            index=models.Index(
                fields=["school", "branch", "document_type"],
                name="vs_workflow_school__54835e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowtemplate",
            constraint=models.UniqueConstraint(
                fields=("school", "branch", "document_type", "code"),
                name="uniq_workflow_template",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowstage",
            constraint=models.UniqueConstraint(
                fields=("template", "code"), name="uniq_stage_code_per_template"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(
                fields=["school", "document_type", "status"],
                name="vs_workflow_school__61c836_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(
                fields=["document_content_type", "document_object_id"],
                name="vs_workflow_documen_a0b92a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(
                fields=["requested_by", "status"], name="vs_workflow_request_1deaf6_idx"
            ),
        ),
    ]
