# Generated by Django 5.2.13 on 2026-05-28 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_workflow", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="workflowtemplate",
            new_name="vs_workflow_school__54835e_idx",
            old_name="vs_workflow_school__4ba373_idx",
        ),
    ]
