# Generated by Django 5.2.10 on 2026-08-12 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vs_rbac", "0003_userpermissionoverride"),
        ("vs_workflow", "0002_seed_platform_user_creation_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstage",
            name="approver_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workflow_stages",
                to="vs_rbac.tenantroletemplate",
            ),
        ),
        migrations.AlterField(
            model_name="workflowstage",
            name="approver_source",
            field=models.CharField(
                choices=[
                    ("RBAC_PERMISSION", "RBAC permission holders (default)"),
                    ("ORGANOGRAM", "Organogram (relative to requester)"),
                    ("ROLE", "Tenant role holders"),
                ],
                default="RBAC_PERMISSION",
                max_length=20,
            ),
        ),
    ]
