# Generated by Django 5.2.10 on 2026-07-12 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("vs_schools", "0004_require_school_tenant"),
        ("vs_tenants", "0004_backfill_business_tenants"),
        (
            "vs_workflow",
            "0002_approvaldelegation_tenant_workflowinstance_tenant_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="workflowtemplate",
            name="uniq_workflow_template",
        ),
        migrations.RemoveIndex(
            model_name="workflowinstance",
            name="vs_workflow_school__61c836_idx",
        ),
        migrations.RemoveIndex(
            model_name="workflowtemplate",
            name="vs_workflow_school__54835e_idx",
        ),
        migrations.RemoveField(
            model_name="approvaldelegation",
            name="school",
        ),
        migrations.RemoveField(
            model_name="workflowinstance",
            name="school",
        ),
        migrations.RemoveField(
            model_name="workflowtemplate",
            name="school",
        ),
        migrations.AlterField(
            model_name="approvaldelegation",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approval_delegations",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="workflowinstance",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workflow_instances",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(
                fields=["tenant", "document_type", "status"],
                name="vs_workflow_tenant__a77602_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtemplate",
            index=models.Index(
                fields=["tenant", "branch", "document_type"],
                name="vs_workflow_tenant__2004bb_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowtemplate",
            constraint=models.UniqueConstraint(
                fields=("tenant", "branch", "document_type", "code"),
                name="uniq_workflow_template",
            ),
        ),
    ]
