# Generated by Django 5.2.10 on 2026-08-12 17:40

import django.db.models.deletion
import django.db.models.manager
import vs_workflow.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vs_rbac", "0003_userpermissionoverride"),
        ("vs_schools", "0001_initial"),
        ("vs_tenants", "0003_tenantdocumentsequence"),
        ("vs_user", "0004_protect_orgnode_parent"),
        ("vs_workflow", "0003_workflowstage_approver_role_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowstage",
            name="approver_source",
            field=models.CharField(
                choices=[
                    ("RBAC_PERMISSION", "RBAC permission holders (default)"),
                    ("ORGANOGRAM", "Organogram (relative to requester)"),
                    ("ROLE", "Tenant role holders"),
                    ("WORKFLOW_GROUP", "Workflow approver group"),
                ],
                default="RBAC_PERMISSION",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="WorkflowApproverGroup",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=vs_workflow.models._short_id,
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.SlugField(max_length=100)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_approver_groups",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_approver_groups",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="workflowstage",
            name="approver_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workflow_stages",
                to="vs_workflow.workflowapprovergroup",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowApproverGroupMember",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=vs_workflow.models._short_id,
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("USER", "Specific person"),
                            ("ROLE", "Role holders"),
                            ("POSITION", "Position holders"),
                        ],
                        max_length=20,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="vs_workflow.workflowapprovergroup",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approver_group_members",
                        to="vs_user.position",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approver_group_members",
                        to="vs_rbac.tenantroletemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "added_at"],
            },
        ),
        migrations.AddIndex(
            model_name="workflowapprovergroup",
            index=models.Index(
                fields=["tenant", "is_active"], name="vs_workflow_tenant__6afbdc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowapprovergroup",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uniq_approver_group_code"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowapprovergroupmember",
            index=models.Index(
                fields=["group", "kind"], name="vs_workflow_group_i_31c044_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowapprovergroupmember",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kind", "USER"),
                        ("position__isnull", True),
                        ("role__isnull", True),
                        ("user__isnull", False),
                    ),
                    models.Q(
                        ("kind", "ROLE"),
                        ("position__isnull", True),
                        ("role__isnull", False),
                        ("user__isnull", True),
                    ),
                    models.Q(
                        ("kind", "POSITION"),
                        ("position__isnull", False),
                        ("role__isnull", True),
                        ("user__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ck_group_member_target_matches_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowapprovergroupmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "USER")),
                fields=("group", "user"),
                name="uniq_group_member_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowapprovergroupmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "ROLE")),
                fields=("group", "role"),
                name="uniq_group_member_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowapprovergroupmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "POSITION")),
                fields=("group", "position"),
                name="uniq_group_member_position",
            ),
        ),
    ]
