# Generated by Django 5.2.10 on 2026-08-12 19:02

import django.db.models.deletion
import vs_workflow.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vs_rbac", "0003_userpermissionoverride"),
        ("vs_workflow", "0004_alter_workflowstage_approver_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowstage",
            name="approver_source",
            field=models.CharField(
                choices=[
                    ("RBAC_PERMISSION", "RBAC permission holders (default)"),
                    ("ORGANOGRAM", "Organogram (relative to requester)"),
                    ("ROLE", "Tenant role holders"),
                    ("WORKFLOW_GROUP", "Workflow approver group"),
                    ("DYNAMIC_ROLE", "Role chosen by the document"),
                ],
                default="RBAC_PERMISSION",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="WorkflowStageDynamicRule",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=vs_workflow.models._short_id,
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("condition", models.JSONField(blank=True, null=True)),
                ("label", models.CharField(blank=True, default="", max_length=150)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_dynamic_rules",
                        to="vs_rbac.tenantroletemplate",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dynamic_rules",
                        to="vs_workflow.workflowstage",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "indexes": [
                    models.Index(
                        fields=["stage", "order"], name="vs_workflow_stage_i_7c2efd_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("stage", "order"), name="uniq_dynamic_rule_order"
                    )
                ],
            },
        ),
    ]
