# Generated by Django 5.2.13 on 2026-06-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_workflow", "0004_workflowstage_retired_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowstageinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACTIVE", "Active"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("RETURNED", "Returned to Requester"),
                    ("SKIPPED", "Skipped"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
