# Generated by Django 5.2.10 on 2026-08-12 20:18

import django.db.models.deletion
import django.db.models.manager
import vs_workflow.models
from django.conf import settings
from django.db import migrations, models


# Central templates cannot be resolved by querying a tenant's roles, so the
# keys the platform itself shipped are mapped explicitly.
CENTRAL_KEY_TO_ROLE = {
    "platform.team.create": "xvs_platform_admin",
    "procurement.approval.approve": "procurement-approver",
    "procurement.approval.approve_senior": "procurement-senior-approver",
}


def convert_permission_keys_to_role_keys(apps, schema_editor):
    """Repoint every RBAC_PERMISSION stage at a role key.

    Permission keys already resolved through roles: a key was granted to roles,
    and roles were assigned to people. So for each stage the equivalent role is
    whichever role in that template's tenant grants the key.

      * exactly one such role  -> the stage names that role's key
      * more than one          -> the alphabetically first is used and the rest
                                  are reported, because a stage names one role
                                  and picking silently would hide the choice
      * none, or a central     -> the permission key is slugified into a role
        (tenant-less) template    key so the intent survives and is visible

    Anything in the last group resolves to nobody until an admin acts, which is
    what ``workflow_role_coverage`` is for. Deliberately not silent: this prints
    every stage it could not resolve confidently.
    """
    WorkflowStage = apps.get_model("vs_workflow", "WorkflowStage")
    TenantRolePermission = apps.get_model("vs_rbac", "TenantRolePermission")
    GroupPermission = apps.get_model("vs_rbac", "GroupPermission")
    TenantRoleGroup = apps.get_model("vs_rbac", "TenantRoleGroup")

    unresolved, ambiguous = [], []

    stages = WorkflowStage.objects.filter(
        approver_source="RBAC_PERMISSION",
    ).select_related("template")

    for stage in stages:
        key = (stage.approver_permission_key or "").strip()
        tenant_id = stage.template.tenant_id
        chosen = None

        if key and tenant_id:
            # Roles granting the key directly, or through a permission group,
            # minus any role that explicitly denies it - the same set the old
            # resolver computed.
            direct = set(TenantRolePermission.objects.filter(
                permission_id=key, granted=True,
            ).values_list("role_id", flat=True))
            group_ids = GroupPermission.objects.filter(
                permission_id=key).values_list("group_id", flat=True)
            via_group = set(TenantRoleGroup.objects.filter(
                group_id__in=group_ids).values_list("role_id", flat=True))
            denied = set(TenantRolePermission.objects.filter(
                permission_id=key, granted=False,
            ).values_list("role_id", flat=True))

            candidates = sorted(
                (direct | via_group) - denied,
                key=lambda rid: str(rid),
            )
            candidates = [
                r for r in candidates
                if TenantRolePermission.objects.filter(role_id=r).exists()
                or TenantRoleGroup.objects.filter(role_id=r).exists()
            ]
            roles = list(
                apps.get_model("vs_rbac", "TenantRoleTemplate").objects.filter(
                    pk__in=candidates, tenant_id=tenant_id, status="ACTIVE",
                ).order_by("key")
            )
            if len(roles) == 1:
                chosen = roles[0]
            elif len(roles) > 1:
                chosen = roles[0]
                ambiguous.append(
                    f"{stage.template.code}:{stage.code} -> {chosen.key} "
                    f"(also matched: {', '.join(r.key for r in roles[1:])})")

        if chosen is not None:
            stage.approver_role_key = chosen.key
            stage.approver_role_id = chosen.pk
        elif key in CENTRAL_KEY_TO_ROLE:
            # A key the platform shipped: its role is known by name.
            stage.approver_role_key = CENTRAL_KEY_TO_ROLE[key]
        else:
            # Keep the intent visible rather than blanking the stage.
            fallback = key.replace(".", "-").replace("_", "-").lower()[:120]
            stage.approver_role_key = fallback
            if fallback:
                unresolved.append(f"{stage.template.code}:{stage.code} -> {fallback}")

        stage.approver_source = "ROLE"
        stage.save(update_fields=[
            "approver_source", "approver_role_key", "approver_role"])

    if ambiguous:
        print("\n  Stages whose permission key matched more than one role:")
        for line in ambiguous:
            print(f"    {line}")
    if unresolved:
        print("\n  Stages whose permission key matched no role - these resolve to")
        print("  nobody until the role exists and is assigned:")
        for line in unresolved:
            print(f"    {line}")
    if ambiguous or unresolved:
        print("\n  Run: python manage.py workflow_role_coverage\n")


class Migration(migrations.Migration):

    # The data pass below UPDATEs every converted stage, and the RemoveField at
    # the end ALTERs that same table. Postgres refuses to ALTER a table that
    # still has pending trigger events from writes in the open transaction
    # ("cannot ALTER TABLE ... because it has pending trigger events"), so this
    # migration cannot run as one transaction on any database that actually has
    # stages to convert. Running non-atomically commits the conversion before
    # the column is dropped. Same operations, same name: no history rewrite.
    atomic = False

    dependencies = [
        ("vs_rbac", "0003_userpermissionoverride"),
        ("vs_tenants", "0003_tenantdocumentsequence"),
        ("vs_workflow", "0005_alter_workflowstage_approver_source_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstage",
            name="approver_role_key",
            field=models.SlugField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="workflowstagedynamicrule",
            name="role_key",
            field=models.SlugField(default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="workflowstage",
            name="approver_source",
            field=models.CharField(
                choices=[
                    ("ROLE", "Role holders (default)"),
                    ("WORKFLOW_GROUP", "Workflow approver group"),
                    ("DYNAMIC_ROLE", "Role chosen by the document"),
                    ("ORGANOGRAM", "Organogram (relative to requester)"),
                ],
                default="ROLE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workflowstagedynamicrule",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workflow_dynamic_rules",
                to="vs_rbac.tenantroletemplate",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowStageApproverOverride",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=vs_workflow.models._short_id,
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "approver_source",
                    models.CharField(
                        choices=[
                            ("ROLE", "Role holders (default)"),
                            ("WORKFLOW_GROUP", "Workflow approver group"),
                            ("DYNAMIC_ROLE", "Role chosen by the document"),
                            ("ORGANOGRAM", "Organogram (relative to requester)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "approver_role_key",
                    models.SlugField(blank=True, default="", max_length=120),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_overrides",
                        to="vs_workflow.workflowapprovergroup",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_overrides",
                        to="vs_workflow.workflowstage",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_stage_approver_overrides",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["tenant", "stage"],
                        name="vs_workflow_tenant__f9df18_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "stage"),
                        name="uniq_stage_override_per_tenant",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("approver_group__isnull", True),
                                ("approver_source", "ROLE"),
                                models.Q(("approver_role_key", ""), _negated=True),
                            ),
                            models.Q(
                                ("approver_group__isnull", False),
                                ("approver_role_key", ""),
                                ("approver_source", "WORKFLOW_GROUP"),
                            ),
                            _connector="OR",
                        ),
                        name="ck_stage_override_source_target",
                    ),
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunPython(
            convert_permission_keys_to_role_keys,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="workflowstage",
            name="approver_permission_key",
        ),
    ]
