# Generated by Django 5.2.13 on 2026-06-09 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "vs_user",
            "0007_department_matrixreport_position_positionassignment_and_more",
        ),
        ("vs_workflow", "0005_alter_workflowstageinstance_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstage",
            name="approver_source",
            field=models.CharField(
                choices=[
                    ("RBAC_PERMISSION", "RBAC permission holders (default)"),
                    ("ORGANOGRAM", "Organogram (relative to requester)"),
                ],
                default="RBAC_PERMISSION",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workflowstage",
            name="organogram_levels",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="workflowstage",
            name="organogram_position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_stages",
                to="vs_user.position",
            ),
        ),
        migrations.AddField(
            model_name="workflowstage",
            name="organogram_target",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DIRECT_MANAGER", "Requester's direct manager"),
                    ("N_LEVELS_UP", "N levels up the reporting chain"),
                    ("DEPARTMENT_HEAD", "Head of requester's department"),
                    ("SPECIFIC_POSITION", "Holder(s) of a specific position"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
