# Generated by Django 5.2.10 on 2026-08-13 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_schools", "0003_branch_tenant"),
        ("vs_tenants", "0003_tenantdocumentsequence"),
        ("vs_workflow", "0006_remove_workflowstage_approver_permission_key_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowtemplate",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="workflowtemplate",
            index=models.Index(
                fields=["document_type", "code", "tenant", "is_active"],
                name="vs_workflow_documen_b2f503_idx",
            ),
        ),
    ]
