# Generated by Django 5.2.10 on 2026-09-09 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Narrow the live-action uniqueness rule to exclude reversed votes.

    The partial index covered every row that was not itself a reversal, so a
    reversed vote still occupied its actor's slot on the stage attempt and the
    approver could not vote again: the re-vote failed on the database
    constraint rather than being recorded. Adding ``reversed_at IS NULL``
    matches the constraint to its own name.

    The new index covers a subset of the old one's rows, so it cannot conflict
    with anything already stored.
    """

    dependencies = [
        ("vs_workflow", "0013_the_approver_roles_a_list_missed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="workflowstageaction",
            name="uniq_live_action_per_actor_per_attempt",
        ),
        migrations.AddConstraint(
            model_name="workflowstageaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_reversal_of__isnull", True), ("reversed_at__isnull", True)
                ),
                fields=("stage_instance", "actor", "attempt"),
                name="uniq_live_action_per_actor_per_attempt",
            ),
        ),
    ]
