"""Named Dynamic Roles: reusable rules that decide who approves.

A Dynamic Role is built once on the Approvers screen and picked by name in any
stage, the way an approver group is. Its rules read the document and the person
who raised it, and each sends to a role's holders, a person or an approver
group.

Additive only. Stages keep their own dynamic rules, and a stage without a named
Dynamic Role resolves through them exactly as before, so nothing already
published changes until it is republished. The approver-source label is a
choices change with no effect on the database.
"""
# Generated by Django 5.2.10 on 2026-09-11 10:20

import django.db.models.deletion
import django.db.models.manager
import vs_workflow.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_rbac", "0019_ticket_assignment_is_the_desks_own"),
        ("vs_tenants", "0010_remove_branch__type"),
        ("vs_workflow", "0015_a_role_change_is_decided_by_a_ladder"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowstage",
            name="approver_source",
            field=models.CharField(
                choices=[
                    ("ROLE", "Role holders (default)"),
                    ("WORKFLOW_GROUP", "Workflow approver group"),
                    ("DYNAMIC_ROLE", "Dynamic Role"),
                    ("ORGANOGRAM", "Organogram (relative to requester)"),
                ],
                default="ROLE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workflowstageapproveroverride",
            name="approver_source",
            field=models.CharField(
                choices=[
                    ("ROLE", "Role holders (default)"),
                    ("WORKFLOW_GROUP", "Workflow approver group"),
                    ("DYNAMIC_ROLE", "Dynamic Role"),
                    ("ORGANOGRAM", "Organogram (relative to requester)"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="WorkflowDynamicRole",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=vs_workflow.models._short_id,
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.SlugField(max_length=100)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, default="")),
                ("document_types", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_dynamic_roles",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="workflowstage",
            name="dynamic_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workflow_stages",
                to="vs_workflow.workflowdynamicrole",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowDynamicRoleRule",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=vs_workflow.models._short_id,
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("condition", models.JSONField(blank=True, null=True)),
                (
                    "target_kind",
                    models.CharField(
                        choices=[
                            ("ROLE", "Role holders"),
                            ("USER", "Specific person"),
                            ("GROUP", "Approver group"),
                        ],
                        max_length=20,
                    ),
                ),
                ("role_key", models.SlugField(blank=True, default="", max_length=120)),
                ("label", models.CharField(blank=True, default="", max_length=150)),
                (
                    "dynamic_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="vs_workflow.workflowdynamicrole",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dynamic_role_rules",
                        to="vs_workflow.workflowapprovergroup",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_dynamic_role_rules",
                        to="vs_rbac.tenantroletemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="workflowdynamicrole",
            index=models.Index(
                fields=["tenant", "is_active"], name="vs_workflow_tenant__344aeb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowdynamicrole",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uniq_dynamic_role_code"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowdynamicrolerule",
            index=models.Index(
                fields=["dynamic_role", "order"], name="vs_workflow_dynamic_85a2f3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowdynamicrolerule",
            constraint=models.UniqueConstraint(
                fields=("dynamic_role", "order"), name="uniq_dynamic_role_rule_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowdynamicrolerule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("group__isnull", True),
                        ("role__isnull", False),
                        ("target_kind", "ROLE"),
                        ("user__isnull", True),
                        models.Q(("role_key", ""), _negated=True),
                    ),
                    models.Q(
                        ("group__isnull", True),
                        ("role__isnull", True),
                        ("role_key", ""),
                        ("target_kind", "USER"),
                        ("user__isnull", False),
                    ),
                    models.Q(
                        ("group__isnull", False),
                        ("role__isnull", True),
                        ("role_key", ""),
                        ("target_kind", "GROUP"),
                        ("user__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ck_dynamic_role_rule_target_matches_kind",
            ),
        ),
    ]
