"""A stage or an approver group can name a post on the tenant's own organogram.

A SPECIFIC_POSITION stage and a POSITION group member gain a plain id column
beside the CX chart's foreign key, for a post on the owning tenant's chart. The
constraints keep one post per row: a stage never names both, and a POSITION
member names exactly one.

Additive only. Every existing row names a CX seat or nothing, leaves the new
columns empty, and satisfies the rewritten check as it satisfied the old one.
Reversing drops the columns, which is safe only while no row uses them.
"""
# Generated by Django 5.2.10 on 2026-09-27 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_rbac", "0029_a_restricted_grant_waits_for_approval"),
        ("vs_user", "0015_retire_auth_event_log"),
        ("vs_workflow", "0018_a_restricted_role_grant_is_decided_by_a_ladder"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="workflowapprovergroupmember",
            name="ck_group_member_target_matches_kind",
        ),
        migrations.AddField(
            model_name="workflowapprovergroupmember",
            name="tenant_position_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workflowstage",
            name="organogram_tenant_position_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="workflowapprovergroupmember",
            index=models.Index(
                condition=models.Q(("tenant_position_id__isnull", False)),
                fields=["tenant_position_id"],
                name="wf_member_tenant_pos_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowstage",
            index=models.Index(
                condition=models.Q(("organogram_tenant_position_id__isnull", False)),
                fields=["organogram_tenant_position_id"],
                name="wf_stage_tenant_pos_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowapprovergroupmember",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kind", "USER"),
                        ("position__isnull", True),
                        ("role__isnull", True),
                        ("tenant_position_id__isnull", True),
                        ("user__isnull", False),
                    ),
                    models.Q(
                        ("kind", "ROLE"),
                        ("position__isnull", True),
                        ("role__isnull", False),
                        ("tenant_position_id__isnull", True),
                        ("user__isnull", True),
                    ),
                    models.Q(
                        ("kind", "POSITION"),
                        ("position__isnull", False),
                        ("role__isnull", True),
                        ("tenant_position_id__isnull", True),
                        ("user__isnull", True),
                    ),
                    models.Q(
                        ("kind", "POSITION"),
                        ("position__isnull", True),
                        ("role__isnull", True),
                        ("tenant_position_id__isnull", False),
                        ("user__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ck_group_member_target_matches_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowapprovergroupmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("kind", "POSITION"), ("tenant_position_id__isnull", False)
                ),
                fields=("group", "tenant_position_id"),
                name="uniq_group_member_tenant_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowstage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("organogram_position__isnull", True),
                    ("organogram_tenant_position_id__isnull", True),
                    _connector="OR",
                ),
                name="ck_stage_one_organogram_position",
            ),
        ),
    ]
