# Generated by Django 5.2.10 on 2026-09-05 06:03

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import schools.vs_staff.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vs_academics", "0008_a_level_says_whether_it_ends"),
        ("vs_tenants", "0008_alter_branch_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff_number",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("job_title", models.CharField(blank=True, default="", max_length=150)),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FULL_TIME", "Full-time"),
                            ("PART_TIME", "Part-time"),
                            ("CONTRACT", "Contract"),
                            ("VOLUNTEER", "Volunteer"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("INVITED", "Invited"),
                            ("ACTIVE", "Active"),
                            ("ON_LEAVE", "On Leave"),
                            ("SUSPENDED", "Suspended"),
                            ("RESIGNED", "Resigned"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="INVITED",
                        max_length=16,
                    ),
                ),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("exit_date", models.DateField(blank=True, null=True)),
                (
                    "middle_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=schools.vs_staff.models.staff_photo_path,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_profiles",
                        to="vs_tenants.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_staff_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_profiles",
                        to="vs_tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="StaffEmploymentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INVITED", "Invited"),
                            ("ACTIVE", "Active"),
                            ("ON_LEAVE", "On Leave"),
                            ("SUSPENDED", "Suspended"),
                            ("RESIGNED", "Resigned"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("INVITED", "Invited"),
                            ("ACTIVE", "Active"),
                            ("ON_LEAVE", "On Leave"),
                            ("SUSPENDED", "Suspended"),
                            ("RESIGNED", "Resigned"),
                            ("TERMINATED", "Terminated"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=200)),
                ("effective_date", models.DateField()),
                ("last_working_day", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_employment_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_employment_events",
                        to="vs_tenants.tenant",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employment_events",
                        to="vs_staff.staffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="StaffDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CV", "CV"),
                            ("DEGREE_CERTIFICATE", "Degree certificate"),
                            ("PROFESSIONAL_CERTIFICATE", "Professional certificate"),
                            ("IDENTIFICATION", "National ID"),
                            ("OTHER", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "file",
                    models.FileField(
                        upload_to=schools.vs_staff.models.staff_document_path
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_documents",
                        to="vs_tenants.tenant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_staff_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="vs_staff.staffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("ANNUAL", "Annual"),
                            ("SICK", "Sick"),
                            ("MATERNITY", "Maternity"),
                            ("PATERNITY", "Paternity"),
                            ("STUDY", "Study"),
                            ("COMPASSIONATE", "Compassionate"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("days", models.PositiveSmallIntegerField()),
                ("note", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_leave",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_leave_requests",
                        to="vs_tenants.tenant",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_requests",
                        to="vs_staff.staffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-id"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="StaffQualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("qualification", models.CharField(max_length=200)),
                (
                    "institution",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "year_obtained",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_staff_qualifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifications",
                        to="vs_staff.staffprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_qualifications",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-year_obtained", "qualification"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TeachingAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "part",
                    models.CharField(
                        choices=[("LEAD", "Lead"), ("ASSISTANT", "Assistant")],
                        default="LEAD",
                        max_length=10,
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="made_teaching_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teaching_assignments",
                        to="vs_academics.schoolclass",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teaching_assignments",
                        to="vs_academics.academicsession",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teaching_assignments",
                        to="vs_staff.staffprofile",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teaching_assignments",
                        to="vs_academics.subject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teaching_assignments",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["subject__name", "school_class__name"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="staffprofile",
            index=models.Index(
                fields=["tenant", "employment_status"],
                name="vs_staff_st_tenant__52622e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="staffprofile",
            index=models.Index(
                fields=["tenant", "branch"], name="vs_staff_st_tenant__1c0012_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffprofile",
            index=models.Index(
                fields=["tenant", "staff_number"], name="vs_staff_st_tenant__f8f0ed_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="staffprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("staff_number", ""), _negated=True),
                fields=("tenant", "staff_number"),
                name="uq_staff_number_per_tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="staffemploymentevent",
            index=models.Index(
                fields=["tenant", "staff", "-created_at"],
                name="vs_staff_st_tenant__4cfa1e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="staffdocument",
            index=models.Index(
                fields=["tenant", "staff", "document_type"],
                name="vs_staff_st_tenant__471d54_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["tenant", "staff", "start_date"],
                name="vs_staff_le_tenant__d3f356_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["tenant", "start_date", "end_date"],
                name="vs_staff_le_tenant__5ef6b0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["tenant", "status"], name="vs_staff_le_tenant__4d09a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffqualification",
            index=models.Index(
                fields=["tenant", "staff"], name="vs_staff_st_tenant__fb8f0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teachingassignment",
            index=models.Index(
                fields=["tenant", "session", "staff"],
                name="vs_staff_te_tenant__9cf23b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teachingassignment",
            index=models.Index(
                fields=["tenant", "session", "school_class"],
                name="vs_staff_te_tenant__1b0863_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teachingassignment",
            index=models.Index(
                fields=["tenant", "session", "subject"],
                name="vs_staff_te_tenant__5ef1d4_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="teachingassignment",
            constraint=models.UniqueConstraint(
                fields=("tenant", "session", "school_class", "subject", "staff"),
                name="uq_teaching_assignment",
            ),
        ),
        migrations.AddConstraint(
            model_name="teachingassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("part", "LEAD")),
                fields=("tenant", "session", "school_class", "subject"),
                name="uq_teaching_lead",
            ),
        ),
    ]
