# Generated by Django 5.2.10 on 2026-09-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_staff", "0003_on_leave_is_read_not_written"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teachingassignment",
            name="part",
            field=models.CharField(
                choices=[("LEAD", "Main teacher"), ("ASSISTANT", "Assisting")],
                default="LEAD",
                max_length=10,
            ),
        ),
    ]
