# Generated by Django 5.2.10 on 2026-06-07 00:06

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vs_finance", "0009_alter_documentsequence_doc_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayoutInstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("OPAY", "OPay"),
                            ("PAYSTACK", "Paystack"),
                            ("FAKE", "Fake (testing)"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Our merchant reference / idempotency key for this payout.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "provider_reference",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Amount to disburse, in kobo."
                    ),
                ),
                ("beneficiary_name", models.CharField(max_length=200)),
                ("beneficiary_account_number", models.CharField(max_length=20)),
                (
                    "beneficiary_bank_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "recipient_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Provider-side transfer recipient id (e.g. Paystack recipient_code).",
                        max_length=128,
                    ),
                ),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                (
                    "vendor_source_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "vendor_source_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("vendor_payment_id", models.IntegerField(blank=True, null=True)),
                (
                    "failure_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payout_instructions",
                        to="vs_finance.currency",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payout_instructions",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "source_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bank/cash GL account the booked payout credits.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payout_instructions",
                        to="vs_finance.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="VirtualAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("OPAY", "OPay"),
                            ("PAYSTACK", "Paystack"),
                            ("FAKE", "Fake (testing)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("account_number", models.CharField(max_length=20)),
                ("bank_name", models.CharField(blank=True, default="", max_length=120)),
                (
                    "account_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "provider_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The provider's id for this account (e.g. dedicated_account id).",
                        max_length=128,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="virtual_accounts",
                        to="vs_finance.currency",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="virtual_accounts",
                        to="vs_finance.customer",
                    ),
                ),
                (
                    "deposit_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bank/cash GL account credited collections into this NUBAN land in.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="virtual_accounts",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="virtual_accounts",
                        to="vs_finance.ledgerentity",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="CollectionIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("OPAY", "OPay"),
                            ("PAYSTACK", "Paystack"),
                            ("FAKE", "Fake (testing)"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("CHECKOUT", "Hosted checkout / redirect"),
                            ("VIRTUAL_ACCOUNT", "Dedicated virtual account (NUBAN)"),
                            ("CARD", "Card"),
                            ("BANK_TRANSFER", "Bank transfer"),
                            ("USSD", "USSD"),
                        ],
                        default="CHECKOUT",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Our merchant reference / idempotency key for this collection.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "provider_reference",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Amount to collect, in kobo."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("ABANDONED", "Abandoned"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                (
                    "payer_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "payer_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                (
                    "checkout_url",
                    models.URLField(blank=True, default="", max_length=600),
                ),
                (
                    "authorization_code",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collection_intents",
                        to="vs_finance.currency",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collection_intents",
                        to="vs_finance.customer",
                    ),
                ),
                (
                    "deposit_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bank/cash GL account the booked receipt debits.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collection_intents",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collection_intents",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional invoice this collection settles (auto-allocated on confirm).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collection_intents",
                        to="vs_finance.invoice",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        help_text="The customer receipt booked when this collection settled.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collection_intents",
                        to="vs_finance.payment",
                    ),
                ),
                (
                    "virtual_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collection_intents",
                        to="vs_payments.virtualaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("OPAY", "OPay"),
                            ("PAYSTACK", "Paystack"),
                            ("FAKE", "Fake (testing)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("event_type", models.CharField(blank=True, default="", max_length=64)),
                (
                    "provider_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The transaction/transfer reference this event concerns.",
                        max_length=128,
                    ),
                ),
                (
                    "dedupe_key",
                    models.CharField(
                        help_text="Stable idempotency key (provider event id, else a body hash).",
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("signature", models.CharField(blank=True, default="", max_length=256)),
                ("verified", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("PROCESSED", "Processed"),
                            ("IGNORED", "Ignored"),
                            ("FAILED", "Failed"),
                        ],
                        default="RECEIVED",
                        max_length=12,
                    ),
                ),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("raw_body", models.TextField(blank=True, default="")),
                ("error", models.CharField(blank=True, default="", max_length=255)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_events",
                        to="vs_payments.collectionintent",
                    ),
                ),
                (
                    "payout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_events",
                        to="vs_payments.payoutinstruction",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OPAY", "OPay"),
                            ("PAYSTACK", "Paystack"),
                            ("FAKE", "Fake (testing)"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("COLLECTION_INITIATED", "Collection initiated"),
                            ("COLLECTION_CONFIRMED", "Collection confirmed"),
                            ("COLLECTION_FAILED", "Collection failed"),
                            ("VIRTUAL_ACCOUNT_CREATED", "Virtual account created"),
                            ("PAYOUT_INITIATED", "Payout initiated"),
                            ("PAYOUT_CONFIRMED", "Payout confirmed"),
                            ("PAYOUT_FAILED", "Payout failed"),
                            ("WEBHOOK_RECEIVED", "Webhook received"),
                            ("WEBHOOK_REJECTED", "Webhook rejected"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                ("succeeded", models.BooleanField(default=True)),
                ("message", models.CharField(blank=True, default="", max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_events",
                        to="vs_finance.ledgerentity",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["entity", "action"],
                        name="vs_payments_entity__0dc6f5_idx",
                    ),
                    models.Index(
                        fields=["reference"], name="vs_payments_referen_f35504_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="payoutinstruction",
            index=models.Index(
                fields=["entity", "status"], name="vs_payments_entity__807fb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payoutinstruction",
            index=models.Index(
                fields=["provider", "provider_reference"],
                name="vs_payments_provide_523db1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="virtualaccount",
            index=models.Index(
                fields=["entity", "provider"], name="vs_payments_entity__2c29d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="virtualaccount",
            index=models.Index(
                fields=["customer"], name="vs_payments_custome_ba8be9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="virtualaccount",
            constraint=models.UniqueConstraint(
                fields=("provider", "account_number"),
                name="uniq_payments_va_provider_account",
            ),
        ),
        migrations.AddIndex(
            model_name="collectionintent",
            index=models.Index(
                fields=["entity", "status"], name="vs_payments_entity__d92f8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collectionintent",
            index=models.Index(
                fields=["provider", "provider_reference"],
                name="vs_payments_provide_85b79c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="collectionintent",
            index=models.Index(
                fields=["customer"], name="vs_payments_custome_2307d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["provider", "event_type"], name="vs_payments_provide_f94764_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["provider_reference"], name="vs_payments_provide_56c85c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(fields=["status"], name="vs_payments_status_288332_idx"),
        ),
    ]
