# Generated by Django 5.2.10 on 2026-06-12 06:29

import django.utils.timezone
import vs_finance.money
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CollectionIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("OPAY", "OPay"),
                            ("PAYSTACK", "Paystack"),
                            ("FAKE", "Fake (testing)"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("CHECKOUT", "Hosted checkout / redirect"),
                            ("VIRTUAL_ACCOUNT", "Dedicated virtual account (NUBAN)"),
                            ("CARD", "Card"),
                            ("BANK_TRANSFER", "Bank transfer"),
                            ("USSD", "USSD"),
                        ],
                        default="CHECKOUT",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Our merchant reference / idempotency key for this collection.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "provider_reference",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Amount to collect, in kobo."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("ABANDONED", "Abandoned"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                (
                    "payer_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "payer_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                (
                    "checkout_url",
                    models.URLField(blank=True, default="", max_length=600),
                ),
                (
                    "authorization_code",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OPAY", "OPay"),
                            ("PAYSTACK", "Paystack"),
                            ("FAKE", "Fake (testing)"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("COLLECTION_INITIATED", "Collection initiated"),
                            ("COLLECTION_CONFIRMED", "Collection confirmed"),
                            ("COLLECTION_FAILED", "Collection failed"),
                            ("VIRTUAL_ACCOUNT_CREATED", "Virtual account created"),
                            ("PAYOUT_INITIATED", "Payout initiated"),
                            ("PAYOUT_CONFIRMED", "Payout confirmed"),
                            ("PAYOUT_FAILED", "Payout failed"),
                            ("PAYOUT_BATCH_CREATED", "Payout batch created"),
                            ("PAYOUT_BATCH_SUBMITTED", "Payout batch submitted"),
                            ("WEBHOOK_RECEIVED", "Webhook received"),
                            ("WEBHOOK_REJECTED", "Webhook rejected"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                ("succeeded", models.BooleanField(default=True)),
                ("message", models.CharField(blank=True, default="", max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="PayoutBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("OPAY", "OPay"),
                            ("PAYSTACK", "Paystack"),
                            ("FAKE", "Fake (testing)"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Our reference / idempotency key for this batch.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("PARTIALLY_COMPLETED", "Partially completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    vs_finance.money.MoneyField(
                        help_text="Sum of child instruction amounts, in kobo."
                    ),
                ),
                ("item_count", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="PayoutInstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("OPAY", "OPay"),
                            ("PAYSTACK", "Paystack"),
                            ("FAKE", "Fake (testing)"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Our merchant reference / idempotency key for this payout.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "provider_reference",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Amount to disburse, in kobo."
                    ),
                ),
                ("beneficiary_name", models.CharField(max_length=200)),
                ("beneficiary_account_number", models.CharField(max_length=20)),
                (
                    "beneficiary_bank_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "recipient_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Provider-side transfer recipient id (e.g. Paystack recipient_code).",
                        max_length=128,
                    ),
                ),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                (
                    "vendor_source_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "vendor_source_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("vendor_payment_id", models.IntegerField(blank=True, null=True)),
                (
                    "failure_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="VirtualAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("OPAY", "OPay"),
                            ("PAYSTACK", "Paystack"),
                            ("FAKE", "Fake (testing)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("account_number", models.CharField(max_length=20)),
                ("bank_name", models.CharField(blank=True, default="", max_length=120)),
                (
                    "account_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "provider_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The provider's id for this account (e.g. dedicated_account id).",
                        max_length=128,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                ("raw", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("OPAY", "OPay"),
                            ("PAYSTACK", "Paystack"),
                            ("FAKE", "Fake (testing)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("event_type", models.CharField(blank=True, default="", max_length=64)),
                (
                    "provider_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The transaction/transfer reference this event concerns.",
                        max_length=128,
                    ),
                ),
                (
                    "dedupe_key",
                    models.CharField(
                        help_text="Stable idempotency key (provider event id, else a body hash).",
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("signature", models.CharField(blank=True, default="", max_length=256)),
                ("verified", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("PROCESSED", "Processed"),
                            ("IGNORED", "Ignored"),
                            ("FAILED", "Failed"),
                        ],
                        default="RECEIVED",
                        max_length=12,
                    ),
                ),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("raw_body", models.TextField(blank=True, default="")),
                ("error", models.CharField(blank=True, default="", max_length=255)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
