# Generated by Django 5.2.10 on 2026-07-14 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vs_finance", "0002_initial"),
        ("vs_payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionintent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="collectionintent",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="collection_intents",
                to="vs_finance.currency",
            ),
        ),
        migrations.AddField(
            model_name="collectionintent",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="collection_intents",
                to="vs_finance.customer",
            ),
        ),
        migrations.AddField(
            model_name="collectionintent",
            name="deposit_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Bank/cash GL account the booked receipt debits.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="collection_intents",
                to="vs_finance.account",
            ),
        ),
        migrations.AddField(
            model_name="collectionintent",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="collection_intents",
                to="vs_finance.ledgerentity",
            ),
        ),
        migrations.AddField(
            model_name="collectionintent",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional invoice this collection settles (auto-allocated on confirm).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="collection_intents",
                to="vs_finance.invoice",
            ),
        ),
        migrations.AddField(
            model_name="collectionintent",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                help_text="The customer receipt booked when this collection settled.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="collection_intents",
                to="vs_finance.payment",
            ),
        ),
        migrations.AddField(
            model_name="paymentevent",
            name="actor_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentevent",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_events",
                to="vs_finance.ledgerentity",
            ),
        ),
        migrations.AddField(
            model_name="payoutbatch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payoutbatch",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payout_batches",
                to="vs_finance.currency",
            ),
        ),
        migrations.AddField(
            model_name="payoutbatch",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payout_batches",
                to="vs_finance.ledgerentity",
            ),
        ),
        migrations.AddField(
            model_name="payoutbatch",
            name="source_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Default bank/cash GL account the booked payouts credit.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payout_batches",
                to="vs_finance.account",
            ),
        ),
        migrations.AddField(
            model_name="payoutinstruction",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                help_text="The bulk batch this instruction belongs to, if any.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="instructions",
                to="vs_payments.payoutbatch",
            ),
        ),
        migrations.AddField(
            model_name="payoutinstruction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payoutinstruction",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payout_instructions",
                to="vs_finance.currency",
            ),
        ),
        migrations.AddField(
            model_name="payoutinstruction",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payout_instructions",
                to="vs_finance.ledgerentity",
            ),
        ),
        migrations.AddField(
            model_name="payoutinstruction",
            name="source_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Bank/cash GL account the booked payout credits.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payout_instructions",
                to="vs_finance.account",
            ),
        ),
        migrations.AddField(
            model_name="virtualaccount",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="virtual_accounts",
                to="vs_finance.currency",
            ),
        ),
        migrations.AddField(
            model_name="virtualaccount",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="virtual_accounts",
                to="vs_finance.customer",
            ),
        ),
        migrations.AddField(
            model_name="virtualaccount",
            name="deposit_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Bank/cash GL account credited collections into this NUBAN land in.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="virtual_accounts",
                to="vs_finance.account",
            ),
        ),
        migrations.AddField(
            model_name="virtualaccount",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="virtual_accounts",
                to="vs_finance.ledgerentity",
            ),
        ),
        migrations.AddField(
            model_name="collectionintent",
            name="virtual_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="collection_intents",
                to="vs_payments.virtualaccount",
            ),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="webhook_events",
                to="vs_payments.collectionintent",
            ),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="payout",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="webhook_events",
                to="vs_payments.payoutinstruction",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentevent",
            index=models.Index(
                fields=["entity", "action"], name="vs_payments_entity__0dc6f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentevent",
            index=models.Index(
                fields=["reference"], name="vs_payments_referen_f35504_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payoutbatch",
            index=models.Index(
                fields=["entity", "status"], name="vs_payments_entity__30780f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payoutbatch",
            index=models.Index(
                fields=["provider"], name="vs_payments_provide_79ee04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payoutinstruction",
            index=models.Index(
                fields=["entity", "status"], name="vs_payments_entity__807fb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payoutinstruction",
            index=models.Index(
                fields=["provider", "provider_reference"],
                name="vs_payments_provide_523db1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="virtualaccount",
            index=models.Index(
                fields=["entity", "provider"], name="vs_payments_entity__2c29d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="virtualaccount",
            index=models.Index(
                fields=["customer"], name="vs_payments_custome_ba8be9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="virtualaccount",
            constraint=models.UniqueConstraint(
                fields=("provider", "account_number"),
                name="uniq_payments_va_provider_account",
            ),
        ),
        migrations.AddConstraint(
            model_name="virtualaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("customer__isnull", False), ("status", "ACTIVE")),
                fields=("entity", "provider", "customer"),
                name="uniq_payments_va_active_customer_provider",
            ),
        ),
        migrations.AddIndex(
            model_name="collectionintent",
            index=models.Index(
                fields=["entity", "status"], name="vs_payments_entity__d92f8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collectionintent",
            index=models.Index(
                fields=["provider", "provider_reference"],
                name="vs_payments_provide_85b79c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="collectionintent",
            index=models.Index(
                fields=["customer"], name="vs_payments_custome_2307d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["provider", "event_type"], name="vs_payments_provide_f94764_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["provider_reference"], name="vs_payments_provide_56c85c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(fields=["status"], name="vs_payments_status_288332_idx"),
        ),
    ]
