# Generated by Django 5.2.10 on 2026-06-08 05:40

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0019_account_ifrs_line"),
        ("vs_payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("COLLECTION_INITIATED", "Collection initiated"),
                    ("COLLECTION_CONFIRMED", "Collection confirmed"),
                    ("COLLECTION_FAILED", "Collection failed"),
                    ("VIRTUAL_ACCOUNT_CREATED", "Virtual account created"),
                    ("PAYOUT_INITIATED", "Payout initiated"),
                    ("PAYOUT_CONFIRMED", "Payout confirmed"),
                    ("PAYOUT_FAILED", "Payout failed"),
                    ("PAYOUT_BATCH_CREATED", "Payout batch created"),
                    ("PAYOUT_BATCH_SUBMITTED", "Payout batch submitted"),
                    ("WEBHOOK_RECEIVED", "Webhook received"),
                    ("WEBHOOK_REJECTED", "Webhook rejected"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="PayoutBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("OPAY", "OPay"),
                            ("PAYSTACK", "Paystack"),
                            ("FAKE", "Fake (testing)"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Our reference / idempotency key for this batch.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("PARTIALLY_COMPLETED", "Partially completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    vs_finance.money.MoneyField(
                        help_text="Sum of child instruction amounts, in kobo."
                    ),
                ),
                ("item_count", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payout_batches",
                        to="vs_finance.currency",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payout_batches",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "source_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default bank/cash GL account the booked payouts credit.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payout_batches",
                        to="vs_finance.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="payoutinstruction",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                help_text="The bulk batch this instruction belongs to, if any.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="instructions",
                to="vs_payments.payoutbatch",
            ),
        ),
        migrations.AddIndex(
            model_name="payoutbatch",
            index=models.Index(
                fields=["entity", "status"], name="vs_payments_entity__30780f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payoutbatch",
            index=models.Index(
                fields=["provider"], name="vs_payments_provide_79ee04_idx"
            ),
        ),
    ]
