# Generated by Django 5.2.10 on 2026-07-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_payments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionintent",
            name="provider",
            field=models.CharField(
                choices=[("PAYSTACK", "Paystack"), ("FAKE", "Fake (testing)")],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="paymentevent",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[("PAYSTACK", "Paystack"), ("FAKE", "Fake (testing)")],
                default="",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="payoutbatch",
            name="provider",
            field=models.CharField(
                choices=[("PAYSTACK", "Paystack"), ("FAKE", "Fake (testing)")],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="payoutinstruction",
            name="provider",
            field=models.CharField(
                choices=[("PAYSTACK", "Paystack"), ("FAKE", "Fake (testing)")],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="virtualaccount",
            name="provider",
            field=models.CharField(
                choices=[("PAYSTACK", "Paystack"), ("FAKE", "Fake (testing)")],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="provider",
            field=models.CharField(
                choices=[("PAYSTACK", "Paystack"), ("FAKE", "Fake (testing)")],
                max_length=16,
            ),
        ),
    ]
