# Generated by Django 5.2.10 on 2026-07-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0027_alter_financeauditlog_action"),
        ("vs_payments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("COLLECTION_INITIATED", "Collection initiated"),
                    ("COLLECTION_CONFIRMED", "Collection confirmed"),
                    ("COLLECTION_FAILED", "Collection failed"),
                    ("VIRTUAL_ACCOUNT_CREATED", "Virtual account created"),
                    (
                        "VIRTUAL_ACCOUNT_STATUS_CHANGED",
                        "Virtual account status changed",
                    ),
                    ("PAYOUT_INITIATED", "Payout initiated"),
                    ("PAYOUT_CONFIRMED", "Payout confirmed"),
                    ("PAYOUT_FAILED", "Payout failed"),
                    ("PAYOUT_BATCH_CREATED", "Payout batch created"),
                    ("PAYOUT_BATCH_SUBMITTED", "Payout batch submitted"),
                    ("WEBHOOK_RECEIVED", "Webhook received"),
                    ("WEBHOOK_REJECTED", "Webhook rejected"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="virtualaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("customer__isnull", False), ("status", "ACTIVE")),
                fields=("entity", "provider", "customer"),
                name="uniq_payments_va_active_customer_provider",
            ),
        ),
    ]
