# Generated by Django 5.2.10 on 2026-08-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_payments", "0003_alter_collectionintent_provider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payoutbatch",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Caller-supplied key that deduplicates batch creation within an entity.",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="payoutbatch",
            name="request_fingerprint",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA-256 of the normalized request bound to the idempotency key.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="payoutbatch",
            name="reference",
            field=models.CharField(
                help_text="Our stable provider reference for this batch.",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="payoutbatch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("entity", "idempotency_key"),
                name="uniq_payments_pbatch_entity_idem_key",
            ),
        ),
    ]
