# Generated by Django 5.2.10 on 2026-06-05 22:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vs_schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LedgerEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                (
                    "code",
                    models.CharField(
                        help_text="Short uppercase code used inside document numbers; e.g. LEKKI, CODEX.",
                        max_length=16,
                        unique=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PLATFORM", "Platform (Codex)"),
                            ("TENANT", "Tenant"),
                            ("PRODUCT", "Product"),
                            ("OTHER", "Other"),
                        ],
                        default="TENANT",
                        max_length=12,
                    ),
                ),
                (
                    "base_currency",
                    models.CharField(
                        default="NGN",
                        help_text="Primary ledger currency (ISO 4217). Phase 1 promotes to a Currency FK.",
                        max_length=3,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_school",
                    models.ForeignKey(
                        blank=True,
                        help_text="Originating tenant; NULL for platform/product entities. A tenant may own several entities (non-unique).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entities",
                        to="vs_schools.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("JNL", "Journal Entry"),
                            ("INV", "Sales / AR Invoice"),
                            ("RCP", "Receipt"),
                            ("PAY", "Payment"),
                            ("CRN", "Credit Note"),
                            ("PR", "Purchase Requisition"),
                            ("RFQ", "Request for Quotation"),
                            ("PO", "Purchase Order"),
                            ("GRN", "Goods Received Note"),
                            ("VIN", "Vendor Invoice"),
                            ("VPY", "Vendor Payment"),
                            ("EXP", "Expense Claim"),
                        ],
                        max_length=8,
                    ),
                ),
                ("fiscal_year", models.PositiveIntegerField()),
                ("last_number", models.PositiveIntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_doc_sequences",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doc_sequences",
                        to="vs_finance.ledgerentity",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="ledgerentity",
            index=models.Index(
                fields=["kind", "is_active"], name="vs_finance__kind_dbc630_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentity",
            index=models.Index(
                fields=["source_school"], name="vs_finance__source__6adc88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentsequence",
            index=models.Index(
                fields=["entity", "doc_type", "fiscal_year"],
                name="vs_finance__entity__e0aef8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsequence",
            constraint=models.UniqueConstraint(
                fields=("entity", "branch", "doc_type", "fiscal_year"),
                name="uniq_finance_docseq_scope",
            ),
        ),
    ]
