# Generated by Django 5.2.10 on 2026-06-05 22:44

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0002_seed_platform_entity"),
        ("vs_schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 4217 alphabetic code, e.g. NGN, USD.",
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("symbol", models.CharField(default="", max_length=8)),
                (
                    "minor_unit",
                    models.PositiveSmallIntegerField(
                        default=2, help_text="Decimal places; 2 for NGN, 0 for JPY."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "currencies",
                "ordering": ["code"],
            },
        ),
        migrations.AlterField(
            model_name="ledgerentity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("PLATFORM", "Platform (CodeX)"),
                    ("TENANT", "Tenant"),
                    ("PRODUCT", "Product"),
                    ("OTHER", "Other"),
                ],
                default="TENANT",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="CoA code, unique within the entity, e.g. 1000.",
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("ASSET", "Asset"),
                            ("LIABILITY", "Liability"),
                            ("EQUITY", "Equity"),
                            ("INCOME", "Income"),
                            ("EXPENSE", "Expense"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "normal_balance",
                    models.CharField(
                        choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")], max_length=6
                    ),
                ),
                (
                    "is_contra",
                    models.BooleanField(
                        default=False,
                        help_text="Carries the opposite of its type's natural balance (e.g. accumulated depreciation).",
                    ),
                ),
                (
                    "is_postable",
                    models.BooleanField(
                        default=True,
                        help_text="Leaf accounts accept postings; header accounts (False) only aggregate.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave null to use the entity's base currency.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="vs_finance.currency",
                    ),
                ),
            ],
            options={
                "ordering": ["entity", "code"],
            },
        ),
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=160)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_centers",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="vs_finance.costcenter",
                    ),
                ),
            ],
            options={
                "ordering": ["entity", "code"],
            },
        ),
        migrations.CreateModel(
            name="Dimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Axis key used inside line ``dimensions`` JSON, e.g. FUND.",
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dimensions",
                        to="vs_finance.ledgerentity",
                    ),
                ),
            ],
            options={
                "ordering": ["entity", "code"],
            },
        ),
        migrations.CreateModel(
            name="FiscalPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period_no",
                    models.PositiveSmallIntegerField(
                        help_text="1–12 for monthly periods (13+ for adjustment periods)."
                    ),
                ),
                ("name", models.CharField(help_text="e.g. 'Jan 2026'.", max_length=40)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("SOFT_CLOSED", "Soft Closed"),
                            ("CLOSED", "Closed"),
                            ("LOCKED", "Locked"),
                        ],
                        default="OPEN",
                        max_length=12,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_periods_closed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fiscal_periods",
                        to="vs_finance.ledgerentity",
                    ),
                ),
            ],
            options={
                "ordering": ["entity", "fiscal_year", "period_no"],
            },
        ),
        migrations.CreateModel(
            name="AccountBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "opening_debit",
                    vs_finance.money.MoneyField(
                        help_text="Amount in minor units (kobo); integer, never float."
                    ),
                ),
                (
                    "opening_credit",
                    vs_finance.money.MoneyField(
                        help_text="Amount in minor units (kobo); integer, never float."
                    ),
                ),
                (
                    "debit_total",
                    vs_finance.money.MoneyField(
                        help_text="Amount in minor units (kobo); integer, never float."
                    ),
                ),
                (
                    "credit_total",
                    vs_finance.money.MoneyField(
                        help_text="Amount in minor units (kobo); integer, never float."
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balances",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="account_balances",
                        to="vs_finance.fiscalperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["period", "account"],
            },
        ),
        migrations.CreateModel(
            name="FiscalYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="Label, e.g. 2026; used in document numbers."
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("SOFT_CLOSED", "Soft Closed"),
                            ("CLOSED", "Closed"),
                            ("LOCKED", "Locked"),
                        ],
                        default="OPEN",
                        max_length=12,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fiscal_years",
                        to="vs_finance.ledgerentity",
                    ),
                ),
            ],
            options={
                "ordering": ["entity", "-year"],
            },
        ),
        migrations.AddField(
            model_name="fiscalperiod",
            name="fiscal_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="periods",
                to="vs_finance.fiscalyear",
            ),
        ),
        migrations.CreateModel(
            name="FxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=10,
                        help_text="1 unit of base = <rate> units of quote.",
                        max_digits=20,
                    ),
                ),
                ("as_of", models.DateField()),
                (
                    "source",
                    models.CharField(
                        default="",
                        help_text="Feed/source, e.g. CBN, ECB.",
                        max_length=32,
                    ),
                ),
                (
                    "base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fx_rates_from",
                        to="vs_finance.currency",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fx_rates_to",
                        to="vs_finance.currency",
                    ),
                ),
            ],
            options={
                "ordering": ["-as_of"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Accounting date; determines the period it posts to."
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("SALES", "Sales / AR"),
                            ("PURCHASE", "Purchase / AP"),
                            ("BANK", "Bank / Cash"),
                            ("PAYROLL", "Payroll"),
                            ("CLOSING", "Period Close"),
                            ("OPENING", "Opening Balance"),
                            ("FX", "FX Revaluation"),
                            ("SYSTEM", "System"),
                        ],
                        default="MANUAL",
                        max_length=12,
                    ),
                ),
                (
                    "fx_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        help_text="Rate to base currency at posting; null for base-currency entries.",
                        max_digits=20,
                        null=True,
                    ),
                ),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="External reference (cheque no., supplier ref, etc.).",
                        max_length=64,
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        help_text="Defaults to the entity base currency.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_entries",
                        to="vs_finance.currency",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_entries",
                        to="vs_finance.fiscalperiod",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_journals_posted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reverses",
                    models.OneToOneField(
                        blank=True,
                        help_text="Set on a reversing entry; points at the journal it cancels.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="vs_finance.journalentry",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "journal entries",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JournalLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "debit",
                    vs_finance.money.MoneyField(
                        help_text="Debit amount in kobo (0 if this is a credit line)."
                    ),
                ),
                (
                    "credit",
                    vs_finance.money.MoneyField(
                        help_text="Credit amount in kobo (0 if this is a debit line)."
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "dimensions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Analytical values keyed by Dimension.code, e.g. {'FUND': 'GRANT-A'}.",
                    ),
                ),
                ("line_no", models.PositiveSmallIntegerField(default=0)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_lines",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_lines",
                        to="vs_finance.costcenter",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="vs_finance.journalentry",
                    ),
                ),
            ],
            options={
                "ordering": ["entry", "line_no", "id"],
            },
        ),
        migrations.CreateModel(
            name="TaxCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(help_text="e.g. VAT, WHT-5, PAYE.", max_length=20),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "rate_bps",
                    models.PositiveIntegerField(
                        help_text="Rate in basis points; 750 = 7.5%. Integer-exact, never a float."
                    ),
                ),
                (
                    "is_recoverable",
                    models.BooleanField(
                        default=True,
                        help_text="Input tax recoverable against output tax (e.g. VAT).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "collected_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Output/payable control account.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tax_codes_collected",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tax_codes",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "paid_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Input/recoverable control account.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tax_codes_paid",
                        to="vs_finance.account",
                    ),
                ),
            ],
            options={
                "ordering": ["entity", "code"],
            },
        ),
        migrations.AddConstraint(
            model_name="costcenter",
            constraint=models.UniqueConstraint(
                fields=("entity", "code"), name="uniq_finance_costcenter_entity_code"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["entity", "account_type"], name="vs_finance__entity__c2df1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["entity", "is_postable", "is_active"],
                name="vs_finance__entity__2d1552_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("entity", "code"), name="uniq_finance_account_entity_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="dimension",
            constraint=models.UniqueConstraint(
                fields=("entity", "code"), name="uniq_finance_dimension_entity_code"
            ),
        ),
        migrations.AddIndex(
            model_name="accountbalance",
            index=models.Index(
                fields=["period"], name="vs_finance__period__e2dcf5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="accountbalance",
            constraint=models.UniqueConstraint(
                fields=("account", "period"), name="uniq_finance_balance_account_period"
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalyear",
            constraint=models.UniqueConstraint(
                fields=("entity", "year"), name="uniq_finance_fiscalyear_entity_year"
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalperiod",
            index=models.Index(
                fields=["entity", "status"], name="vs_finance__entity__b39f38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalperiod",
            index=models.Index(
                fields=["entity", "start_date", "end_date"],
                name="vs_finance__entity__8c2cfc_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalperiod",
            constraint=models.UniqueConstraint(
                fields=("fiscal_year", "period_no"), name="uniq_finance_period_year_no"
            ),
        ),
        migrations.AddIndex(
            model_name="fxrate",
            index=models.Index(
                fields=["base", "quote", "as_of"], name="vs_finance__base_id_84440c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fxrate",
            constraint=models.UniqueConstraint(
                fields=("base", "quote", "as_of", "source"), name="uniq_finance_fxrate"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["entity", "date"], name="vs_finance__entity__76fad0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["entity", "status"], name="vs_finance__entity__153fed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["period"], name="vs_finance__period__f82c76_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.UniqueConstraint(
                fields=("entity", "document_number"),
                name="uniq_vs_finance_journalentry_entity_docnum",
            ),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(
                fields=["account"], name="vs_finance__account_6a06a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(fields=["entry"], name="vs_finance__entry_i_6291ca_idx"),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                condition=models.Q(("debit", 0), ("credit", 0), _connector="OR"),
                name="ck_finance_line_one_sided",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                condition=models.Q(("debit__gte", 0), ("credit__gte", 0)),
                name="ck_finance_line_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="taxcode",
            constraint=models.UniqueConstraint(
                fields=("entity", "code"), name="uniq_finance_taxcode_entity_code"
            ),
        ),
    ]
