# Generated by Django 5.2.10 on 2026-06-15 20:59

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vs_finance', '0004_seed_platform_entity'),
        ('vs_schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Unique within the entity.', max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('term', models.CharField(blank=True, default='', help_text="Applicability tag, e.g. '2026/T1'.", max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_fee_structures', to='vs_schools.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_fee_structures_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='vs_finance.ledgerentity')),
            ],
            options={
                'ordering': ['entity', 'code'],
            },
        ),
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', vs_finance.money.MoneyField(help_text='Charge amount per customer, in kobo (net of tax).')),
                ('line_no', models.PositiveSmallIntegerField(default=0)),
                ('revenue_account', models.ForeignKey(help_text='GL revenue account this fee credits when billed.', on_delete=django.db.models.deletion.PROTECT, related_name='fee_items', to='vs_finance.account')),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_items', to='vs_finance.taxcode')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vs_finance.feestructure')),
            ],
            options={
                'ordering': ['structure', 'line_no', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['entity', 'is_active'], name='vs_finance__entity__ab93cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(fields=('entity', 'code'), name='uniq_finance_feestructure_entity_code'),
        ),
        migrations.AddIndex(
            model_name='feeitem',
            index=models.Index(fields=['structure'], name='vs_finance__structu_c9867c_idx'),
        ),
    ]
