# Generated by Django 5.2.10 on 2026-06-06 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0004_seed_currencies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgerentity",
            name="base_currency",
            field=models.ForeignKey(
                default="NGN",
                help_text="Primary ledger (reporting) currency. FK to Currency; defaults to NGN.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entities",
                to="vs_finance.currency",
            ),
        ),
    ]
