# Generated by Django 5.2.10 on 2026-06-06 18:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0005_alter_ledgerentity_base_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("JOURNAL_POSTED", "Journal posted"),
                            ("JOURNAL_REVERSED", "Journal reversed"),
                            ("JOURNAL_POST_REJECTED", "Journal posting rejected"),
                            ("PERIOD_CLOSED", "Period closed"),
                            ("PERIOD_REOPENED", "Period re-opened"),
                            ("ACCOUNT_CREATED", "Account created"),
                            ("ACCOUNT_UPDATED", "Account updated"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILED", "Failed")],
                        default="SUCCESS",
                        max_length=8,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Model of the thing acted on, e.g. 'JournalEntry'.",
                        max_length=64,
                    ),
                ),
                ("target_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "document_number",
                    models.CharField(blank=True, default="", max_length=48),
                ),
                ("message", models.CharField(blank=True, default="", max_length=255)),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who acted; null for system/automated actions.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_audit_logs",
                        to="vs_finance.ledgerentity",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["entity", "action"],
                        name="vs_finance__entity__80f643_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="vs_finance__target__1a16f3_idx",
                    ),
                    models.Index(
                        fields=["entity", "created_at"],
                        name="vs_finance__entity__07891d_idx",
                    ),
                ],
            },
        ),
    ]
