# Generated by Django 5.2.10 on 2026-06-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0005_feestructure_feeitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="subtype",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional sub-classification shown in the chart (e.g. 'Current asset', 'Operating revenue').",
                max_length=40,
            ),
        ),
    ]
