# Generated by Django 5.2.10 on 2026-06-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0006_account_subtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dunningnotice",
            name="channel",
            field=models.CharField(
                default="EMAIL",
                help_text="Snapshot of the stage's channel(s), comma-separated.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="dunningstage",
            name="channel",
            field=models.CharField(
                default="EMAIL",
                help_text="One or more DunningChannel values, comma-separated (e.g. 'EMAIL,IN_APP').",
                max_length=32,
            ),
        ),
    ]
