# Generated by Django 5.2.10 on 2026-07-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0006_ledgerentity_number_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentsequence",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("JN", "Journal Entry"),
                    ("IV", "Sales / AR Invoice"),
                    ("RC", "Receipt"),
                    ("PY", "Payment"),
                    ("CN", "Credit Note"),
                    ("DN", "Debit Note"),
                    ("RF", "Customer Refund"),
                    ("PP", "Installment Payment Plan"),
                    ("CC", "Concession / Discount / Waiver"),
                    ("WO", "Bad-debt Write-off"),
                    ("DU", "Dunning / Payment Reminder"),
                    ("PR", "Purchase Requisition"),
                    ("RQ", "Request for Quotation"),
                    ("QT", "Vendor Quotation"),
                    ("PO", "Purchase Order"),
                    ("GN", "Goods Received Note"),
                    ("VI", "Vendor Invoice"),
                    ("VP", "Vendor Payment"),
                    ("EX", "Expense Claim"),
                    ("PC", "Petty Cash Voucher"),
                    ("PL", "Payroll Run"),
                    ("FA", "Fixed Asset"),
                    ("TX", "Tax Filing / Remittance"),
                    ("BG", "Budget"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentity",
            name="code",
            field=models.CharField(
                help_text="Short uppercase code identifying the entity; e.g. LEKKI, CODEX.",
                max_length=16,
                unique=True,
            ),
        ),
    ]
