# Generated by Django 5.2.10 on 2026-06-06 18:45

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0006_financeauditlog"),
        ("vs_schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="financeauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("JOURNAL_POSTED", "Journal posted"),
                    ("JOURNAL_REVERSED", "Journal reversed"),
                    ("JOURNAL_POST_REJECTED", "Journal posting rejected"),
                    ("INVOICE_POSTED", "Invoice posted"),
                    ("INVOICE_CANCELLED", "Invoice cancelled"),
                    ("PAYMENT_POSTED", "Payment posted"),
                    ("PAYMENT_ALLOCATED", "Payment allocated"),
                    ("PERIOD_CLOSED", "Period closed"),
                    ("PERIOD_REOPENED", "Period re-opened"),
                    ("ACCOUNT_CREATED", "Account created"),
                    ("ACCOUNT_UPDATED", "Account updated"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Customer code, unique within the entity.",
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "billing_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "billing_phone",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("billing_address", models.TextField(blank=True, default="")),
                (
                    "opening_balance",
                    vs_finance.money.MoneyField(
                        help_text="Opening AR balance in kobo (informational; not auto-posted)."
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Loose reference to the originating domain record's model, e.g. 'vs_schools.Student'.",
                        max_length=64,
                    ),
                ),
                ("source_id", models.CharField(blank=True, default="", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_customers",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customers",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "receivable_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="AR control account this customer's balance rolls into.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ar_customers",
                        to="vs_finance.account",
                    ),
                ),
            ],
            options={
                "ordering": ["entity", "code"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("invoice_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("FEE_BILLING", "Fee Billing"),
                            ("SUBSCRIPTION", "Subscription"),
                            ("API", "API"),
                        ],
                        default="MANUAL",
                        max_length=16,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                (
                    "subtotal",
                    vs_finance.money.MoneyField(help_text="Net of tax, in kobo."),
                ),
                (
                    "tax_total",
                    vs_finance.money.MoneyField(help_text="Total tax, in kobo."),
                ),
                (
                    "total",
                    vs_finance.money.MoneyField(
                        help_text="subtotal + tax_total, in kobo."
                    ),
                ),
                (
                    "amount_paid",
                    vs_finance.money.MoneyField(
                        help_text="Cash allocated to this invoice, in kobo."
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "Unpaid"),
                            ("PARTIAL", "Partially Paid"),
                            ("PAID", "Paid"),
                        ],
                        default="UNPAID",
                        max_length=8,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="vs_finance.currency",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="vs_finance.customer",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        help_text="The AR journal raised when this invoice posted.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ar_invoices",
                        to="vs_finance.journalentry",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=1, max_digits=14),
                ),
                (
                    "unit_price",
                    vs_finance.money.MoneyField(help_text="Price per unit in kobo."),
                ),
                (
                    "net_amount",
                    vs_finance.money.MoneyField(
                        help_text="quantity × unit_price, in kobo."
                    ),
                ),
                (
                    "tax_amount",
                    vs_finance.money.MoneyField(help_text="Tax on the net, in kobo."),
                ),
                ("dimensions", models.JSONField(blank=True, default=dict)),
                ("line_no", models.PositiveSmallIntegerField(default=0)),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_lines",
                        to="vs_finance.costcenter",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="vs_finance.invoice",
                    ),
                ),
                (
                    "revenue_account",
                    models.ForeignKey(
                        help_text="GL revenue account credited for this line's net.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_lines",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "tax_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_lines",
                        to="vs_finance.taxcode",
                    ),
                ),
            ],
            options={
                "ordering": ["invoice", "line_no", "id"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CARD", "Card"),
                            ("CHEQUE", "Cheque"),
                            ("ONLINE", "Online / Gateway"),
                            ("OTHER", "Other"),
                        ],
                        default="BANK_TRANSFER",
                        max_length=16,
                    ),
                ),
                (
                    "amount",
                    vs_finance.money.MoneyField(help_text="Total received, in kobo."),
                ),
                (
                    "allocated_amount",
                    vs_finance.money.MoneyField(
                        help_text="Portion allocated to invoices, in kobo."
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="vs_finance.currency",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="vs_finance.customer",
                    ),
                ),
                (
                    "deposit_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bank/cash account debited (where the money landed).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_payments",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ar_payments",
                        to="vs_finance.journalentry",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Amount of the payment applied to this invoice, in kobo."
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="vs_finance.invoice",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="vs_finance.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["payment", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["entity", "is_active"], name="vs_finance__entity__93555c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["source_type", "source_id"],
                name="vs_finance__source__14b6da_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("entity", "code"), name="uniq_finance_customer_entity_code"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["entity", "status"], name="vs_finance__entity__0bd524_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["entity", "payment_status"],
                name="vs_finance__entity__27a172_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["customer"], name="vs_finance__custome_bd0e0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["entity", "invoice_date"], name="vs_finance__entity__8916b7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("entity", "document_number"),
                name="uniq_vs_finance_invoice_entity_docnum",
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceline",
            index=models.Index(
                fields=["invoice"], name="vs_finance__invoice_474996_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceline",
            index=models.Index(
                fields=["revenue_account"], name="vs_finance__revenue_b03123_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["entity", "status"], name="vs_finance__entity__54b9de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["customer"], name="vs_finance__custome_2d42a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["entity", "payment_date"], name="vs_finance__entity__f97f1c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("entity", "document_number"),
                name="uniq_vs_finance_payment_entity_docnum",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(
                fields=["invoice"], name="vs_finance__invoice_4e49c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(
                fields=["payment"], name="vs_finance__payment_9e8451_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentallocation",
            constraint=models.UniqueConstraint(
                fields=("payment", "invoice"), name="uniq_finance_alloc_payment_invoice"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="ck_finance_alloc_non_negative",
            ),
        ),
    ]
