# Generated by Django 5.2.10 on 2026-06-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0007_alter_dunningnotice_channel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feestructure",
            name="term",
        ),
        migrations.AddField(
            model_name="feestructure",
            name="applies_to",
            field=models.CharField(
                choices=[
                    ("CUSTOMER", "Customer"),
                    ("VENDOR", "Vendor"),
                    ("STAFF", "Staff"),
                    ("GENERAL", "General"),
                ],
                default="CUSTOMER",
                help_text="Counterparty type this template bills (customer / vendor / staff / general).",
                max_length=16,
            ),
        ),
    ]
