# Generated by Django 5.2.10 on 2026-06-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0008_remove_feestructure_term_feestructure_applies_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeitem",
            name="code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional short fee code/category, e.g. 'TUITION', 'BOARDING'.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="feeitem",
            name="is_optional",
            field=models.BooleanField(
                default=False,
                help_text="An opt-in charge (vs a required line). Informational for now — generation bills every line.",
            ),
        ),
    ]
