# Generated by Django 5.2.10 on 2026-06-06 19:51

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0008_alter_financeauditlog_action"),
        ("vs_schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentsequence",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("JNL", "Journal Entry"),
                    ("INV", "Sales / AR Invoice"),
                    ("RCP", "Receipt"),
                    ("PAY", "Payment"),
                    ("CRN", "Credit Note"),
                    ("PR", "Purchase Requisition"),
                    ("RFQ", "Request for Quotation"),
                    ("PO", "Purchase Order"),
                    ("GRN", "Goods Received Note"),
                    ("VIN", "Vendor Invoice"),
                    ("VPY", "Vendor Payment"),
                    ("EXP", "Expense Claim"),
                    ("PYR", "Payroll Run"),
                    ("FA", "Fixed Asset"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="financeauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("JOURNAL_POSTED", "Journal posted"),
                    ("JOURNAL_REVERSED", "Journal reversed"),
                    ("JOURNAL_POST_REJECTED", "Journal posting rejected"),
                    ("INVOICE_POSTED", "Invoice posted"),
                    ("INVOICE_CANCELLED", "Invoice cancelled"),
                    ("PAYMENT_POSTED", "Payment posted"),
                    ("PAYMENT_ALLOCATED", "Payment allocated"),
                    ("PERIOD_CLOSED", "Period closed"),
                    ("PERIOD_REOPENED", "Period re-opened"),
                    ("ACCOUNT_CREATED", "Account created"),
                    ("ACCOUNT_UPDATED", "Account updated"),
                    ("REQUISITION_APPROVED", "Requisition approved"),
                    ("PURCHASE_ORDER_APPROVED", "Purchase order approved"),
                    ("GRN_POSTED", "Goods receipt posted"),
                    ("GRN_POST_REJECTED", "Goods receipt posting rejected"),
                    ("VENDOR_INVOICE_MATCHED", "Vendor invoice matched"),
                    ("VENDOR_INVOICE_POSTED", "Vendor invoice posted"),
                    ("VENDOR_INVOICE_POST_REJECTED", "Vendor invoice posting rejected"),
                    ("VENDOR_PAYMENT_POSTED", "Vendor payment posted"),
                    ("VENDOR_PAYMENT_POST_REJECTED", "Vendor payment posting rejected"),
                    ("VENDOR_PAYMENT_ALLOCATED", "Vendor payment allocated"),
                    ("BANK_RECONCILED", "Bank statement reconciled"),
                    ("BANK_CHARGE_POSTED", "Bank charge posted"),
                    ("EXPENSE_CLAIM_POSTED", "Expense claim posted"),
                    ("EXPENSE_CLAIM_POST_REJECTED", "Expense claim posting rejected"),
                    ("EXPENSE_CLAIM_SETTLED", "Expense claim settled"),
                    ("PAYROLL_POSTED", "Payroll run posted"),
                    ("PAYROLL_POST_REJECTED", "Payroll run posting rejected"),
                    ("PAYROLL_PAID", "Payroll run disbursed"),
                    ("BUDGET_APPROVED", "Budget approved"),
                    ("ASSET_ACQUIRED", "Fixed asset acquired"),
                    ("DEPRECIATION_POSTED", "Depreciation posted"),
                    ("PERIOD_LOCKED", "Period locked"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly label, e.g. 'GTBank Operations'.",
                        max_length=160,
                    ),
                ),
                ("bank_name", models.CharField(blank=True, default="", max_length=120)),
                (
                    "account_number",
                    models.CharField(blank=True, default="", max_length=34),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_bank_accounts",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        help_text="Defaults to the entity base currency.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_accounts",
                        to="vs_finance.currency",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_accounts",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "gl_account",
                    models.OneToOneField(
                        help_text="The cash/bank GL account this maps to (1:1). All movement posts here.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_account",
                        to="vs_finance.account",
                    ),
                ),
            ],
            options={
                "ordering": ["entity", "name"],
            },
        ),
        migrations.CreateModel(
            name="BankStatementLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "txn_date",
                    models.DateField(
                        help_text="Value/transaction date on the statement."
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Signed kobo: +inflow (GL debit), -outflow (GL credit)."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNMATCHED", "Unmatched"),
                            ("MATCHED", "Matched"),
                            ("IGNORED", "Ignored"),
                        ],
                        default="UNMATCHED",
                        max_length=10,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Bank/provider line id, used to de-duplicate on import.",
                        max_length=128,
                    ),
                ),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "adjusting_journal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Journal raised to book an unrecorded charge/credit before matching.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_adjustments",
                        to="vs_finance.journalentry",
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statement_lines",
                        to="vs_finance.bankaccount",
                    ),
                ),
                (
                    "matched_line",
                    models.ForeignKey(
                        blank=True,
                        help_text="The cash-account journal line this statement line reconciles to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_statement_lines",
                        to="vs_finance.journalline",
                    ),
                ),
            ],
            options={
                "ordering": ["bank_account", "txn_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPROVED", "Approved"),
                            ("LOCKED", "Locked"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_budgets_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budgets",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budgets",
                        to="vs_finance.fiscalyear",
                    ),
                ),
            ],
            options={
                "ordering": ["entity", "-fiscal_year__year", "name"],
            },
        ),
        migrations.CreateModel(
            name="BudgetLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period_no",
                    models.PositiveSmallIntegerField(
                        help_text="1–12; the fiscal period within the year."
                    ),
                ),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Budgeted amount for this cell, in kobo."
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budget_lines",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="vs_finance.budget",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budget_lines",
                        to="vs_finance.costcenter",
                    ),
                ),
            ],
            options={
                "ordering": ["budget", "account", "period_no"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "claimant_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Free-text name when the claimant isn't a platform user.",
                        max_length=160,
                    ),
                ),
                ("claim_date", models.DateField()),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                (
                    "subtotal",
                    vs_finance.money.MoneyField(help_text="Net of tax, in kobo."),
                ),
                (
                    "tax_total",
                    vs_finance.money.MoneyField(
                        help_text="Recoverable input tax, in kobo."
                    ),
                ),
                (
                    "total",
                    vs_finance.money.MoneyField(
                        help_text="subtotal + tax_total, in kobo."
                    ),
                ),
                (
                    "amount_paid",
                    vs_finance.money.MoneyField(
                        help_text="Reimbursed so far, in kobo."
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "Unpaid"),
                            ("PARTIAL", "Partially Paid"),
                            ("PAID", "Paid"),
                        ],
                        default="UNPAID",
                        max_length=8,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "claimant",
                    models.ForeignKey(
                        blank=True,
                        help_text="The employee being reimbursed.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_expense_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expense_claims",
                        to="vs_finance.currency",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expense_claims",
                        to="vs_finance.journalentry",
                    ),
                ),
                (
                    "reimbursement_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Liability credited (accrued reimbursement). Defaults to 2400.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expense_claims",
                        to="vs_finance.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExpenseClaimLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=1, max_digits=14),
                ),
                (
                    "unit_price",
                    vs_finance.money.MoneyField(help_text="Price per unit in kobo."),
                ),
                (
                    "net_amount",
                    vs_finance.money.MoneyField(
                        help_text="quantity × unit_price, in kobo."
                    ),
                ),
                (
                    "tax_amount",
                    vs_finance.money.MoneyField(
                        help_text="Recoverable tax on the net, in kobo."
                    ),
                ),
                ("line_no", models.PositiveSmallIntegerField(default=0)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="vs_finance.expenseclaim",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expense_claim_lines",
                        to="vs_finance.costcenter",
                    ),
                ),
                (
                    "expense_account",
                    models.ForeignKey(
                        help_text="GL expense account debited for this line's net.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expense_claim_lines",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "tax_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expense_claim_lines",
                        to="vs_finance.taxcode",
                    ),
                ),
            ],
            options={
                "ordering": ["claim", "line_no", "id"],
            },
        ),
        migrations.CreateModel(
            name="FixedAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "asset_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional tag/serial.",
                        max_length=40,
                    ),
                ),
                ("acquisition_date", models.DateField()),
                (
                    "cost",
                    vs_finance.money.MoneyField(help_text="Capitalised cost in kobo."),
                ),
                (
                    "salvage_value",
                    vs_finance.money.MoneyField(
                        help_text="Residual value at end of life, in kobo."
                    ),
                ),
                (
                    "useful_life_months",
                    models.PositiveIntegerField(
                        help_text="Depreciable life in months."
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("STRAIGHT_LINE", "Straight line")],
                        default="STRAIGHT_LINE",
                        max_length=16,
                    ),
                ),
                (
                    "asset_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("FULLY_DEPRECIATED", "Fully depreciated"),
                            ("DISPOSED", "Disposed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "accumulated_depreciation",
                    vs_finance.money.MoneyField(
                        help_text="Total depreciation booked to date, in kobo."
                    ),
                ),
                (
                    "accumulated_depreciation_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contra-asset. Defaults to 1900.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_assets_accum_dep",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "acquisition_journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_acquisitions",
                        to="vs_finance.journalentry",
                    ),
                ),
                (
                    "asset_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Capitalised cost account. Defaults to 1500 PP&E.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_assets",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "depreciation_expense_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Expense account. Defaults to 5400.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_assets_dep_expense",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_finance.ledgerentity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DepreciationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seq",
                    models.PositiveSmallIntegerField(
                        help_text="1-based month index in the asset's life."
                    ),
                ),
                (
                    "depreciation_date",
                    models.DateField(help_text="Date this charge posts on."),
                ),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Depreciation for this period, in kobo."
                    ),
                ),
                ("is_posted", models.BooleanField(default=False)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="depreciation_charges",
                        to="vs_finance.journalentry",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="vs_finance.fixedasset",
                    ),
                ),
            ],
            options={
                "ordering": ["asset", "seq"],
            },
        ),
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "pay_date",
                    models.DateField(help_text="Date the run is accounted/posted on."),
                ),
                (
                    "period_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. 'January 2026'.",
                        max_length=40,
                    ),
                ),
                (
                    "run_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted (accrued)"),
                            ("PAID", "Paid (disbursed)"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                (
                    "gross_total",
                    vs_finance.money.MoneyField(
                        help_text="Amount in minor units (kobo); integer, never float."
                    ),
                ),
                (
                    "paye_total",
                    vs_finance.money.MoneyField(
                        help_text="Amount in minor units (kobo); integer, never float."
                    ),
                ),
                (
                    "pension_total",
                    vs_finance.money.MoneyField(
                        help_text="Amount in minor units (kobo); integer, never float."
                    ),
                ),
                (
                    "net_total",
                    vs_finance.money.MoneyField(
                        help_text="Amount in minor units (kobo); integer, never float."
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cash account disbursed from at pay time.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_runs",
                        to="vs_finance.bankaccount",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_runs",
                        to="vs_finance.currency",
                    ),
                ),
                (
                    "disbursement_journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_disbursements",
                        to="vs_finance.journalentry",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_accruals",
                        to="vs_finance.journalentry",
                    ),
                ),
                (
                    "net_payable_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Defaults to 2330 Net Wages Payable.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_net_runs",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "paye_payable_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Defaults to 2310 PAYE Payable.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_paye_runs",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "pension_payable_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Defaults to 2320 Pension Payable.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_pension_runs",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "salary_expense_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Defaults to 5200 Salaries & Wages.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_salary_runs",
                        to="vs_finance.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PayrollLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee_name",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "gross_amount",
                    vs_finance.money.MoneyField(help_text="Gross pay in kobo."),
                ),
                (
                    "paye_amount",
                    vs_finance.money.MoneyField(
                        help_text="PAYE (employee income tax) withheld, in kobo."
                    ),
                ),
                (
                    "pension_amount",
                    vs_finance.money.MoneyField(
                        help_text="Employee pension contribution withheld, in kobo."
                    ),
                ),
                (
                    "net_amount",
                    vs_finance.money.MoneyField(
                        help_text="Take-home: gross - paye - pension, in kobo."
                    ),
                ),
                ("line_no", models.PositiveSmallIntegerField(default=0)),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_lines",
                        to="vs_finance.costcenter",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_payroll_lines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="vs_finance.payrollrun",
                    ),
                ),
            ],
            options={
                "ordering": ["run", "line_no", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(
                fields=["entity", "is_active"], name="vs_finance__entity__841588_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.UniqueConstraint(
                fields=("entity", "name"), name="uniq_finance_bank_entity_name"
            ),
        ),
        migrations.AddIndex(
            model_name="bankstatementline",
            index=models.Index(
                fields=["bank_account", "status"], name="vs_finance__bank_ac_f25f2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bankstatementline",
            index=models.Index(
                fields=["bank_account", "txn_date"],
                name="vs_finance__bank_ac_729a01_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="bankstatementline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id__gt", "")),
                fields=("bank_account", "external_id"),
                name="uniq_finance_bankline_external",
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["entity", "status"], name="vs_finance__entity__6b9dc0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(
                fields=("entity", "fiscal_year", "name"),
                name="uniq_finance_budget_entity_year_name",
            ),
        ),
        migrations.AddIndex(
            model_name="budgetline",
            index=models.Index(
                fields=["budget", "account"], name="vs_finance__budget__e08da9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="budgetline",
            constraint=models.UniqueConstraint(
                fields=("budget", "account", "cost_center", "period_no"),
                name="uniq_finance_budgetline_cell",
            ),
        ),
        migrations.AddIndex(
            model_name="expenseclaim",
            index=models.Index(
                fields=["entity", "status"], name="vs_finance__entity__9d466e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expenseclaim",
            index=models.Index(
                fields=["entity", "payment_status"],
                name="vs_finance__entity__9a38d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expenseclaim",
            index=models.Index(
                fields=["claimant"], name="vs_finance__claiman_e447ea_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="expenseclaim",
            constraint=models.UniqueConstraint(
                fields=("entity", "document_number"),
                name="uniq_vs_finance_expenseclaim_entity_docnum",
            ),
        ),
        migrations.AddIndex(
            model_name="expenseclaimline",
            index=models.Index(fields=["claim"], name="vs_finance__claim_i_48fb58_idx"),
        ),
        migrations.AddIndex(
            model_name="expenseclaimline",
            index=models.Index(
                fields=["expense_account"], name="vs_finance__expense_ad5180_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fixedasset",
            index=models.Index(
                fields=["entity", "asset_status"], name="vs_finance__entity__6567e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fixedasset",
            index=models.Index(
                fields=["entity", "acquisition_date"],
                name="vs_finance__entity__0fd797_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="fixedasset",
            constraint=models.UniqueConstraint(
                fields=("entity", "document_number"),
                name="uniq_vs_finance_fixedasset_entity_docnum",
            ),
        ),
        migrations.AddIndex(
            model_name="depreciationschedule",
            index=models.Index(
                fields=["asset", "is_posted"], name="vs_finance__asset_i_429a83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="depreciationschedule",
            index=models.Index(
                fields=["depreciation_date"], name="vs_finance__depreci_219de4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="depreciationschedule",
            constraint=models.UniqueConstraint(
                fields=("asset", "seq"), name="uniq_finance_depschedule_asset_seq"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollrun",
            index=models.Index(
                fields=["entity", "run_status"], name="vs_finance__entity__e896c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollrun",
            index=models.Index(
                fields=["entity", "pay_date"], name="vs_finance__entity__ea5f2b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollrun",
            constraint=models.UniqueConstraint(
                fields=("entity", "document_number"),
                name="uniq_vs_finance_payrollrun_entity_docnum",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollline",
            index=models.Index(fields=["run"], name="vs_finance__run_id_bdab9b_idx"),
        ),
        migrations.AddIndex(
            model_name="payrollline",
            index=models.Index(
                fields=["employee"], name="vs_finance__employe_1593c7_idx"
            ),
        ),
    ]
