# Generated by Django 5.2.10 on 2026-07-28 13:37

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0008_alter_financeauditlog_action"),
        ("vs_import_data", "0004_alter_importbatch_dataset_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankStatementImportContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "statement_date",
                    models.DateField(
                        help_text="Closing date reported by the bank statement."
                    ),
                ),
                (
                    "period_label",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "opening_balance",
                    vs_finance.money.MoneyField(
                        help_text="Bank-reported opening balance in minor units."
                    ),
                ),
                (
                    "closing_balance",
                    vs_finance.money.MoneyField(
                        help_text="Bank-reported closing balance in minor units."
                    ),
                ),
                (
                    "source_file_hash",
                    models.CharField(
                        help_text="SHA-256 of the uploaded file, used to block accidental re-publish.",
                        max_length=64,
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="statement_import_contexts",
                        to="vs_finance.bankaccount",
                    ),
                ),
                (
                    "import_batch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_statement_context",
                        to="vs_import_data.importbatch",
                    ),
                ),
                (
                    "published_statement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_context",
                        to="vs_finance.bankstatement",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["bank_account", "source_file_hash"],
                        name="vs_finance__bank_ac_745c45_idx",
                    )
                ],
            },
        ),
    ]
