# Generated by Django 5.2.10 on 2026-06-21 14:35

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0009_feeitem_code_feeitem_is_optional"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="The entity's main operating account (at most one).",
            ),
        ),
        migrations.CreateModel(
            name="BankStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "statement_date",
                    models.DateField(help_text="Closing date of the statement period."),
                ),
                (
                    "period_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human label for the period, e.g. 'Apr 2026' or 'May 1–15'.",
                        max_length=120,
                    ),
                ),
                (
                    "opening_balance",
                    vs_finance.money.MoneyField(
                        help_text="Bank-reported opening balance, kobo."
                    ),
                ),
                (
                    "closing_balance",
                    vs_finance.money.MoneyField(
                        help_text="Bank-reported closing balance, kobo."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("RECONCILED", "Reconciled"),
                        ],
                        default="UPLOADED",
                        max_length=12,
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statements",
                        to="vs_finance.bankaccount",
                    ),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_statements_imported",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-statement_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BankReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("as_of_date", models.DateField()),
                (
                    "book_balance",
                    vs_finance.money.MoneyField(
                        help_text="GL cash-account balance, kobo."
                    ),
                ),
                (
                    "statement_balance",
                    vs_finance.money.MoneyField(
                        help_text="Bank-reported balance, kobo."
                    ),
                ),
                (
                    "difference",
                    vs_finance.money.MoneyField(
                        help_text="book − statement (signed kobo)."
                    ),
                ),
                ("matched_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BALANCED", "Balanced"),
                            ("OUT_OF_BALANCE", "Out of balance"),
                        ],
                        default="BALANCED",
                        max_length=16,
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliations",
                        to="vs_finance.bankaccount",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciliations",
                        to="vs_finance.bankstatement",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="bankstatementline",
            name="statement",
            field=models.ForeignKey(
                blank=True,
                help_text="The imported statement batch this line belongs to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lines",
                to="vs_finance.bankstatement",
            ),
        ),
        migrations.AddIndex(
            model_name="bankstatement",
            index=models.Index(
                fields=["bank_account", "statement_date"],
                name="vs_finance__bank_ac_a9066b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bankreconciliation",
            index=models.Index(
                fields=["bank_account", "created_at"],
                name="vs_finance__bank_ac_619409_idx",
            ),
        ),
    ]
