# Generated by Django 5.2.10 on 2026-06-07 15:58

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0010_invoice_amount_credited_and_more"),
        ("vs_schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentsequence",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("JNL", "Journal Entry"),
                    ("INV", "Sales / AR Invoice"),
                    ("RCP", "Receipt"),
                    ("PAY", "Payment"),
                    ("CRN", "Credit Note"),
                    ("DRN", "Debit Note"),
                    ("RFD", "Customer Refund"),
                    ("PPL", "Installment Payment Plan"),
                    ("CNC", "Concession / Discount / Waiver"),
                    ("PR", "Purchase Requisition"),
                    ("RFQ", "Request for Quotation"),
                    ("PO", "Purchase Order"),
                    ("GRN", "Goods Received Note"),
                    ("VIN", "Vendor Invoice"),
                    ("VPY", "Vendor Payment"),
                    ("EXP", "Expense Claim"),
                    ("PYR", "Payroll Run"),
                    ("FA", "Fixed Asset"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="financeauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("JOURNAL_POSTED", "Journal posted"),
                    ("JOURNAL_REVERSED", "Journal reversed"),
                    ("JOURNAL_POST_REJECTED", "Journal posting rejected"),
                    ("INVOICE_POSTED", "Invoice posted"),
                    ("INVOICE_CANCELLED", "Invoice cancelled"),
                    ("INVOICE_WRITTEN_OFF", "Invoice written off (bad debt)"),
                    ("PAYMENT_POSTED", "Payment posted"),
                    ("PAYMENT_ALLOCATED", "Payment allocated"),
                    ("CREDIT_NOTE_POSTED", "Credit note posted"),
                    ("CREDIT_NOTE_ALLOCATED", "Credit note allocated"),
                    ("DEBIT_NOTE_POSTED", "Debit note posted"),
                    ("REFUND_POSTED", "Customer refund posted"),
                    ("PAYMENT_PLAN_ACTIVATED", "Installment plan activated"),
                    ("PAYMENT_PLAN_COMPLETED", "Installment plan completed"),
                    ("PAYMENT_PLAN_CANCELLED", "Installment plan cancelled"),
                    ("CONCESSION_POSTED", "Concession / discount / waiver posted"),
                    ("PERIOD_CLOSED", "Period closed"),
                    ("PERIOD_REOPENED", "Period re-opened"),
                    ("ACCOUNT_CREATED", "Account created"),
                    ("ACCOUNT_UPDATED", "Account updated"),
                    ("REQUISITION_APPROVED", "Requisition approved"),
                    ("PURCHASE_ORDER_APPROVED", "Purchase order approved"),
                    ("GRN_POSTED", "Goods receipt posted"),
                    ("GRN_POST_REJECTED", "Goods receipt posting rejected"),
                    ("VENDOR_INVOICE_MATCHED", "Vendor invoice matched"),
                    ("VENDOR_INVOICE_POSTED", "Vendor invoice posted"),
                    ("VENDOR_INVOICE_POST_REJECTED", "Vendor invoice posting rejected"),
                    ("VENDOR_PAYMENT_POSTED", "Vendor payment posted"),
                    ("VENDOR_PAYMENT_POST_REJECTED", "Vendor payment posting rejected"),
                    ("VENDOR_PAYMENT_ALLOCATED", "Vendor payment allocated"),
                    ("BANK_RECONCILED", "Bank statement reconciled"),
                    ("BANK_CHARGE_POSTED", "Bank charge posted"),
                    ("EXPENSE_CLAIM_POSTED", "Expense claim posted"),
                    ("EXPENSE_CLAIM_POST_REJECTED", "Expense claim posting rejected"),
                    ("EXPENSE_CLAIM_SETTLED", "Expense claim settled"),
                    ("PAYROLL_POSTED", "Payroll run posted"),
                    ("PAYROLL_POST_REJECTED", "Payroll run posting rejected"),
                    ("PAYROLL_PAID", "Payroll run disbursed"),
                    ("BUDGET_APPROVED", "Budget approved"),
                    ("ASSET_ACQUIRED", "Fixed asset acquired"),
                    ("DEPRECIATION_POSTED", "Depreciation posted"),
                    ("PERIOD_LOCKED", "Period locked"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="PaymentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "plan_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="Due date of the first installment."),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("WEEKLY", "Weekly"),
                            ("FORTNIGHTLY", "Fortnightly (every 2 weeks)"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                        ],
                        default="MONTHLY",
                        max_length=12,
                    ),
                ),
                ("installment_count", models.PositiveSmallIntegerField(default=1)),
                (
                    "total_amount",
                    vs_finance.money.MoneyField(
                        help_text="Total amount being spread, in kobo."
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_plans",
                        to="vs_finance.customer",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        help_text="The invoice this plan settles (optional for a standalone plan).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_plans",
                        to="vs_finance.invoice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentPlanInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seq_no",
                    models.PositiveSmallIntegerField(
                        help_text="1-based position in the schedule."
                    ),
                ),
                ("due_date", models.DateField()),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Amount due for this installment, in kobo."
                    ),
                ),
                (
                    "amount_settled",
                    vs_finance.money.MoneyField(
                        help_text="Amount settled against this installment, in kobo."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PARTIAL", "Partially settled"),
                            ("PAID", "Settled"),
                        ],
                        default="PENDING",
                        max_length=8,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="vs_finance.paymentplan",
                    ),
                ),
            ],
            options={
                "ordering": ["plan", "seq_no", "id"],
            },
        ),
        migrations.CreateModel(
            name="Concession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("DISCOUNT", "Discount"),
                            ("WAIVER", "Waiver"),
                            ("SCHOLARSHIP", "Scholarship / bursary"),
                        ],
                        default="DISCOUNT",
                        max_length=12,
                    ),
                ),
                ("concession_date", models.DateField()),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Amount of the receivable forgiven/discounted, in kobo."
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                (
                    "allowance_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contra-revenue/expense account debited. Defaults to 4910 Discounts & Concessions Allowed.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="concessions",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="concessions",
                        to="vs_finance.customer",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="The invoice whose balance this concession reduces.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="concessions",
                        to="vs_finance.invoice",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="concessions",
                        to="vs_finance.journalentry",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["entity", "status"],
                        name="vs_finance__entity__3ae1a5_idx",
                    ),
                    models.Index(
                        fields=["entity", "kind"], name="vs_finance__entity__e357a4_idx"
                    ),
                    models.Index(
                        fields=["customer"], name="vs_finance__custome_b2db93_idx"
                    ),
                    models.Index(
                        fields=["invoice"], name="vs_finance__invoice_cb39e3_idx"
                    ),
                    models.Index(
                        fields=["entity", "concession_date"],
                        name="vs_finance__entity__166d7b_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entity", "document_number"),
                        name="uniq_vs_finance_concession_entity_docnum",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="paymentplan",
            index=models.Index(
                fields=["entity", "plan_status"], name="vs_finance__entity__4a9ebf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentplan",
            index=models.Index(
                fields=["customer"], name="vs_finance__custome_ec16c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentplan",
            index=models.Index(
                fields=["invoice"], name="vs_finance__invoice_1e2cfd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentplan",
            index=models.Index(
                fields=["entity", "start_date"], name="vs_finance__entity__efea64_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentplan",
            constraint=models.UniqueConstraint(
                fields=("entity", "document_number"),
                name="uniq_vs_finance_paymentplan_entity_docnum",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentplaninstallment",
            index=models.Index(fields=["plan"], name="vs_finance__plan_id_57ecfb_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentplaninstallment",
            index=models.Index(
                fields=["due_date", "status"], name="vs_finance__due_dat_0f976f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentplaninstallment",
            constraint=models.UniqueConstraint(
                fields=("plan", "seq_no"), name="uniq_finance_installment_plan_seq"
            ),
        ),
    ]
