# Generated by Django 5.2.10 on 2026-06-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0010_bankaccount_is_primary_bankstatement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankstatementline",
            name="match_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AUTO", "Auto"),
                    ("MANUAL", "Manual"),
                    ("ADJUSTMENT", "Adjustment"),
                ],
                default="",
                help_text="How it was matched: auto, manual, or via an adjusting entry.",
                max_length=12,
            ),
        ),
    ]
