# Generated by Django 5.2.10 on 2026-06-07 16:31

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0011_alter_documentsequence_doc_type_and_more"),
        ("vs_schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentsequence",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("JNL", "Journal Entry"),
                    ("INV", "Sales / AR Invoice"),
                    ("RCP", "Receipt"),
                    ("PAY", "Payment"),
                    ("CRN", "Credit Note"),
                    ("DRN", "Debit Note"),
                    ("RFD", "Customer Refund"),
                    ("PPL", "Installment Payment Plan"),
                    ("CNC", "Concession / Discount / Waiver"),
                    ("DUN", "Dunning / Payment Reminder"),
                    ("PR", "Purchase Requisition"),
                    ("RFQ", "Request for Quotation"),
                    ("PO", "Purchase Order"),
                    ("GRN", "Goods Received Note"),
                    ("VIN", "Vendor Invoice"),
                    ("VPY", "Vendor Payment"),
                    ("EXP", "Expense Claim"),
                    ("PYR", "Payroll Run"),
                    ("FA", "Fixed Asset"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="financeauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("JOURNAL_POSTED", "Journal posted"),
                    ("JOURNAL_REVERSED", "Journal reversed"),
                    ("JOURNAL_POST_REJECTED", "Journal posting rejected"),
                    ("INVOICE_POSTED", "Invoice posted"),
                    ("INVOICE_CANCELLED", "Invoice cancelled"),
                    ("INVOICE_WRITTEN_OFF", "Invoice written off (bad debt)"),
                    ("PAYMENT_POSTED", "Payment posted"),
                    ("PAYMENT_ALLOCATED", "Payment allocated"),
                    ("CREDIT_NOTE_POSTED", "Credit note posted"),
                    ("CREDIT_NOTE_ALLOCATED", "Credit note allocated"),
                    ("DEBIT_NOTE_POSTED", "Debit note posted"),
                    ("REFUND_POSTED", "Customer refund posted"),
                    ("PAYMENT_PLAN_ACTIVATED", "Installment plan activated"),
                    ("PAYMENT_PLAN_COMPLETED", "Installment plan completed"),
                    ("PAYMENT_PLAN_CANCELLED", "Installment plan cancelled"),
                    ("CONCESSION_POSTED", "Concession / discount / waiver posted"),
                    ("DUNNING_RUN_GENERATED", "Dunning run generated"),
                    ("DUNNING_NOTICE_SENT", "Dunning notice marked sent"),
                    ("DUNNING_NOTICE_CANCELLED", "Dunning notice cancelled"),
                    ("PERIOD_CLOSED", "Period closed"),
                    ("PERIOD_REOPENED", "Period re-opened"),
                    ("ACCOUNT_CREATED", "Account created"),
                    ("ACCOUNT_UPDATED", "Account updated"),
                    ("REQUISITION_APPROVED", "Requisition approved"),
                    ("PURCHASE_ORDER_APPROVED", "Purchase order approved"),
                    ("GRN_POSTED", "Goods receipt posted"),
                    ("GRN_POST_REJECTED", "Goods receipt posting rejected"),
                    ("VENDOR_INVOICE_MATCHED", "Vendor invoice matched"),
                    ("VENDOR_INVOICE_POSTED", "Vendor invoice posted"),
                    ("VENDOR_INVOICE_POST_REJECTED", "Vendor invoice posting rejected"),
                    ("VENDOR_PAYMENT_POSTED", "Vendor payment posted"),
                    ("VENDOR_PAYMENT_POST_REJECTED", "Vendor payment posting rejected"),
                    ("VENDOR_PAYMENT_ALLOCATED", "Vendor payment allocated"),
                    ("BANK_RECONCILED", "Bank statement reconciled"),
                    ("BANK_CHARGE_POSTED", "Bank charge posted"),
                    ("EXPENSE_CLAIM_POSTED", "Expense claim posted"),
                    ("EXPENSE_CLAIM_POST_REJECTED", "Expense claim posting rejected"),
                    ("EXPENSE_CLAIM_SETTLED", "Expense claim settled"),
                    ("PAYROLL_POSTED", "Payroll run posted"),
                    ("PAYROLL_POST_REJECTED", "Payroll run posting rejected"),
                    ("PAYROLL_PAID", "Payroll run disbursed"),
                    ("BUDGET_APPROVED", "Budget approved"),
                    ("ASSET_ACQUIRED", "Fixed asset acquired"),
                    ("DEPRECIATION_POSTED", "Depreciation posted"),
                    ("PERIOD_LOCKED", "Period locked"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="DunningPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="The policy a dunning run uses when none is named. At most one per entity.",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dunning_policies",
                        to="vs_finance.ledgerentity",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "dunning policies",
                "ordering": ["entity", "name"],
            },
        ),
        migrations.CreateModel(
            name="DunningStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        help_text="1-based escalation order."
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'First reminder', 'Final notice'.",
                        max_length=80,
                    ),
                ),
                (
                    "min_days_overdue",
                    models.PositiveSmallIntegerField(
                        help_text="Days past due an invoice must be before this stage applies."
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("LETTER", "Letter"),
                            ("IN_APP", "In-app"),
                        ],
                        default="EMAIL",
                        max_length=8,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Reminder text/template copied onto each notice raised at this stage.",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="vs_finance.dunningpolicy",
                    ),
                ),
            ],
            options={
                "ordering": ["policy", "level"],
            },
        ),
        migrations.CreateModel(
            name="DunningNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        help_text="Escalation level this notice fired at."
                    ),
                ),
                (
                    "notice_date",
                    models.DateField(
                        help_text="The 'as at' date the run was generated for."
                    ),
                ),
                ("days_overdue", models.PositiveSmallIntegerField(default=0)),
                (
                    "amount_due",
                    vs_finance.money.MoneyField(
                        help_text="Invoice balance outstanding when generated, in kobo."
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("LETTER", "Letter"),
                            ("IN_APP", "In-app"),
                        ],
                        default="EMAIL",
                        max_length=8,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                (
                    "notice_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("RESOLVED", "Resolved"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dunning_notices",
                        to="vs_finance.customer",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dunning_notices",
                        to="vs_finance.invoice",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notices",
                        to="vs_finance.dunningpolicy",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notices",
                        to="vs_finance.dunningstage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="dunningpolicy",
            index=models.Index(
                fields=["entity", "is_active"], name="vs_finance__entity__6280e9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dunningpolicy",
            constraint=models.UniqueConstraint(
                fields=("entity", "name"), name="uniq_finance_dunning_policy_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="dunningpolicy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("entity",),
                name="uniq_finance_dunning_policy_default",
            ),
        ),
        migrations.AddIndex(
            model_name="dunningstage",
            index=models.Index(
                fields=["policy", "min_days_overdue"],
                name="vs_finance__policy__e201b3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="dunningstage",
            constraint=models.UniqueConstraint(
                fields=("policy", "level"), name="uniq_finance_dunning_stage_level"
            ),
        ),
        migrations.AddIndex(
            model_name="dunningnotice",
            index=models.Index(
                fields=["entity", "notice_status"],
                name="vs_finance__entity__b7ceb3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dunningnotice",
            index=models.Index(
                fields=["customer"], name="vs_finance__custome_5fa79d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dunningnotice",
            index=models.Index(
                fields=["invoice"], name="vs_finance__invoice_d0c6ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dunningnotice",
            index=models.Index(
                fields=["entity", "notice_date"], name="vs_finance__entity__c167d1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dunningnotice",
            constraint=models.UniqueConstraint(
                fields=("entity", "document_number"),
                name="uniq_vs_finance_dunningnotice_entity_docnum",
            ),
        ),
        migrations.AddConstraint(
            model_name="dunningnotice",
            constraint=models.UniqueConstraint(
                fields=("invoice", "level"),
                name="uniq_finance_dunning_notice_invoice_level",
            ),
        ),
    ]
