# Generated by Django 5.2.10 on 2026-06-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0011_bankstatementline_match_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenseclaimline",
            name="receipt",
            field=models.FileField(
                blank=True,
                help_text="Supporting receipt (DB-backed storage). PDF or image.",
                null=True,
                upload_to="expense-receipts/",
            ),
        ),
    ]
