# Generated by Django 5.2.10 on 2026-06-22 08:09

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0012_expenseclaimline_receipt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeSalary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Employee name.", max_length=160)),
                (
                    "gross_amount",
                    vs_finance.money.MoneyField(
                        help_text="Standard monthly gross pay, in kobo."
                    ),
                ),
                (
                    "paye_amount",
                    vs_finance.money.MoneyField(
                        help_text="Standard PAYE withheld, in kobo."
                    ),
                ),
                (
                    "pension_amount",
                    vs_finance.money.MoneyField(
                        help_text="Standard pension withheld, in kobo."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_salaries",
                        to="vs_finance.costcenter",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_employee_salaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_salaries",
                        to="vs_finance.ledgerentity",
                    ),
                ),
            ],
            options={
                "ordering": ["entity", "name"],
                "indexes": [
                    models.Index(
                        fields=["entity", "is_active"],
                        name="vs_finance__entity__965a4f_idx",
                    )
                ],
            },
        ),
    ]
