# Generated by Django 5.2.10 on 2026-06-22 10:56

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0013_employeesalary"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollline",
            name="components",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Payslip breakdown snapshot copied from the salary structure at generation: [{name, kind, statutory_type, amount}]. Empty in flat mode.",
            ),
        ),
        migrations.AlterField(
            model_name="employeesalary",
            name="paye_amount",
            field=vs_finance.money.MoneyField(
                help_text="Manual PAYE withheld (flat mode, no structure), in kobo."
            ),
        ),
        migrations.AlterField(
            model_name="employeesalary",
            name="pension_amount",
            field=vs_finance.money.MoneyField(
                help_text="Manual pension withheld (flat mode, no structure), in kobo."
            ),
        ),
        migrations.CreateModel(
            name="SalaryStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="e.g. 'Senior staff'.", max_length=120),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salary_structures",
                        to="vs_finance.ledgerentity",
                    ),
                ),
            ],
            options={
                "ordering": ["entity", "name"],
            },
        ),
        migrations.CreateModel(
            name="SalaryComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Basic', 'Housing', 'PAYE'.", max_length=80
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("EARNING", "Earning"), ("DEDUCTION", "Deduction")],
                        default="EARNING",
                        max_length=10,
                    ),
                ),
                (
                    "calc_method",
                    models.CharField(
                        choices=[
                            ("FIXED", "Fixed amount"),
                            ("PERCENT_OF_GROSS", "Percent of gross"),
                            ("PERCENT_OF_BASIC", "Percent of basic"),
                        ],
                        default="PERCENT_OF_GROSS",
                        max_length=20,
                    ),
                ),
                (
                    "rate_bps",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Rate in basis points for the percent methods (4000 = 40%).",
                    ),
                ),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Fixed amount in kobo, for the FIXED method."
                    ),
                ),
                (
                    "is_basic",
                    models.BooleanField(
                        default=False,
                        help_text="Earnings flagged basic form the base for '% of basic' components.",
                    ),
                ),
                (
                    "statutory_type",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("PAYE", "PAYE"),
                            ("PENSION", "Pension"),
                        ],
                        default="NONE",
                        help_text="For deductions: routes the amount to PAYE/pension payable + the return.",
                        max_length=10,
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField(default=0)),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="vs_finance.salarystructure",
                    ),
                ),
            ],
            options={
                "ordering": ["structure", "sequence", "id"],
            },
        ),
        migrations.AddField(
            model_name="employeesalary",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, PAYE/pension/net are derived from the structure applied to gross; the manual paye/pension fields below are then ignored.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employee_salaries",
                to="vs_finance.salarystructure",
            ),
        ),
        migrations.AddConstraint(
            model_name="salarystructure",
            constraint=models.UniqueConstraint(
                fields=("entity", "name"), name="uniq_salary_structure_name_per_entity"
            ),
        ),
        migrations.AddIndex(
            model_name="salarycomponent",
            index=models.Index(
                fields=["structure"], name="vs_finance__structu_c1e564_idx"
            ),
        ),
    ]
