# Generated by Django 5.2.10 on 2026-06-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0014_payrollline_components_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Auto-allocated reference, e.g. CFX-CODEX-BDG-2026-00001.",
                max_length=48,
            ),
        ),
        migrations.AlterField(
            model_name="documentsequence",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("JNL", "Journal Entry"),
                    ("INV", "Sales / AR Invoice"),
                    ("RCP", "Receipt"),
                    ("PAY", "Payment"),
                    ("CRN", "Credit Note"),
                    ("DRN", "Debit Note"),
                    ("RFD", "Customer Refund"),
                    ("PPL", "Installment Payment Plan"),
                    ("CNC", "Concession / Discount / Waiver"),
                    ("DUN", "Dunning / Payment Reminder"),
                    ("PR", "Purchase Requisition"),
                    ("RFQ", "Request for Quotation"),
                    ("QUO", "Vendor Quotation"),
                    ("PO", "Purchase Order"),
                    ("GRN", "Goods Received Note"),
                    ("VIN", "Vendor Invoice"),
                    ("VPY", "Vendor Payment"),
                    ("EXP", "Expense Claim"),
                    ("PCV", "Petty Cash Voucher"),
                    ("PYR", "Payroll Run"),
                    ("FA", "Fixed Asset"),
                    ("TXF", "Tax Filing / Remittance"),
                    ("BDG", "Budget"),
                ],
                max_length=8,
            ),
        ),
    ]
