# Generated by Django 5.2.10 on 2026-06-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0016_fixedasset_category_fixedasset_disposal_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixedasset",
            name="method",
            field=models.CharField(
                choices=[
                    ("STRAIGHT_LINE", "Straight line"),
                    ("DECLINING_BALANCE", "Declining balance"),
                ],
                default="STRAIGHT_LINE",
                max_length=20,
            ),
        ),
    ]
