# Generated by Django 5.2.10 on 2026-06-07 21:27

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0016_alter_financeauditlog_action"),
        ("vs_schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentsequence",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("JNL", "Journal Entry"),
                    ("INV", "Sales / AR Invoice"),
                    ("RCP", "Receipt"),
                    ("PAY", "Payment"),
                    ("CRN", "Credit Note"),
                    ("DRN", "Debit Note"),
                    ("RFD", "Customer Refund"),
                    ("PPL", "Installment Payment Plan"),
                    ("CNC", "Concession / Discount / Waiver"),
                    ("DUN", "Dunning / Payment Reminder"),
                    ("PR", "Purchase Requisition"),
                    ("RFQ", "Request for Quotation"),
                    ("QUO", "Vendor Quotation"),
                    ("PO", "Purchase Order"),
                    ("GRN", "Goods Received Note"),
                    ("VIN", "Vendor Invoice"),
                    ("VPY", "Vendor Payment"),
                    ("EXP", "Expense Claim"),
                    ("PCV", "Petty Cash Voucher"),
                    ("PYR", "Payroll Run"),
                    ("FA", "Fixed Asset"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="financeauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("JOURNAL_POSTED", "Journal posted"),
                    ("JOURNAL_REVERSED", "Journal reversed"),
                    ("JOURNAL_POST_REJECTED", "Journal posting rejected"),
                    ("INVOICE_POSTED", "Invoice posted"),
                    ("INVOICE_CANCELLED", "Invoice cancelled"),
                    ("INVOICE_WRITTEN_OFF", "Invoice written off (bad debt)"),
                    ("PAYMENT_POSTED", "Payment posted"),
                    ("PAYMENT_ALLOCATED", "Payment allocated"),
                    ("CREDIT_NOTE_POSTED", "Credit note posted"),
                    ("CREDIT_NOTE_ALLOCATED", "Credit note allocated"),
                    ("DEBIT_NOTE_POSTED", "Debit note posted"),
                    ("REFUND_POSTED", "Customer refund posted"),
                    ("PAYMENT_PLAN_ACTIVATED", "Installment plan activated"),
                    ("PAYMENT_PLAN_COMPLETED", "Installment plan completed"),
                    ("PAYMENT_PLAN_CANCELLED", "Installment plan cancelled"),
                    ("CONCESSION_POSTED", "Concession / discount / waiver posted"),
                    ("DUNNING_RUN_GENERATED", "Dunning run generated"),
                    ("DUNNING_NOTICE_SENT", "Dunning notice marked sent"),
                    ("DUNNING_NOTICE_CANCELLED", "Dunning notice cancelled"),
                    ("PERIOD_CLOSED", "Period closed"),
                    ("PERIOD_REOPENED", "Period re-opened"),
                    ("ACCOUNT_CREATED", "Account created"),
                    ("ACCOUNT_UPDATED", "Account updated"),
                    ("REQUISITION_APPROVED", "Requisition approved"),
                    ("RFQ_ISSUED", "Request for quotation issued"),
                    ("RFQ_CANCELLED", "Request for quotation cancelled"),
                    ("QUOTATION_SUBMITTED", "Vendor quotation submitted"),
                    ("QUOTATION_AWARDED", "Vendor quotation awarded → PO"),
                    ("VENDOR_CONTRACT_ACTIVATED", "Vendor contract activated"),
                    ("VENDOR_CONTRACT_RENEWED", "Vendor contract renewed"),
                    ("VENDOR_CONTRACT_TERMINATED", "Vendor contract terminated"),
                    ("CONTRACT_MILESTONE_COMPLETED", "Contract milestone completed"),
                    ("PURCHASE_ORDER_APPROVED", "Purchase order approved"),
                    ("GRN_POSTED", "Goods receipt posted"),
                    ("GRN_POST_REJECTED", "Goods receipt posting rejected"),
                    ("VENDOR_INVOICE_MATCHED", "Vendor invoice matched"),
                    ("VENDOR_INVOICE_APPROVED", "Vendor invoice approved (workflow)"),
                    ("VENDOR_INVOICE_POSTED", "Vendor invoice posted"),
                    ("VENDOR_INVOICE_POST_REJECTED", "Vendor invoice posting rejected"),
                    ("VENDOR_PAYMENT_POSTED", "Vendor payment posted"),
                    ("VENDOR_PAYMENT_POST_REJECTED", "Vendor payment posting rejected"),
                    ("VENDOR_PAYMENT_ALLOCATED", "Vendor payment allocated"),
                    ("STOCK_RECEIVED", "Stock received (perpetual inventory)"),
                    ("STOCK_ISSUED", "Stock issued"),
                    ("STOCK_ISSUE_REJECTED", "Stock issue rejected"),
                    ("STOCK_ADJUSTED", "Stock adjusted"),
                    ("STOCK_ADJUST_REJECTED", "Stock adjustment rejected"),
                    ("BANK_RECONCILED", "Bank statement reconciled"),
                    ("BANK_CHARGE_POSTED", "Bank charge posted"),
                    ("EXPENSE_CLAIM_POSTED", "Expense claim posted"),
                    ("EXPENSE_CLAIM_POST_REJECTED", "Expense claim posting rejected"),
                    ("EXPENSE_CLAIM_SETTLED", "Expense claim settled"),
                    (
                        "PETTY_CASH_ESTABLISHED",
                        "Petty cash fund established / topped up",
                    ),
                    ("PETTY_CASH_VOUCHER_POSTED", "Petty cash voucher posted"),
                    ("PETTY_CASH_VOUCHER_REJECTED", "Petty cash voucher rejected"),
                    ("PETTY_CASH_REPLENISHED", "Petty cash fund replenished"),
                    ("PAYROLL_POSTED", "Payroll run posted"),
                    ("PAYROLL_POST_REJECTED", "Payroll run posting rejected"),
                    ("PAYROLL_PAID", "Payroll run disbursed"),
                    ("BUDGET_APPROVED", "Budget approved"),
                    ("ASSET_ACQUIRED", "Fixed asset acquired"),
                    ("DEPRECIATION_POSTED", "Depreciation posted"),
                    ("PERIOD_LOCKED", "Period locked"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="PettyCashFund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly label, e.g. 'Front-desk float'.",
                        max_length=160,
                    ),
                ),
                (
                    "custodian_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Free-text custodian when not a platform user.",
                        max_length=160,
                    ),
                ),
                (
                    "float_amount",
                    vs_finance.money.MoneyField(
                        help_text="The imprest/float the fund is restored to on replenishment, in kobo."
                    ),
                ),
                (
                    "current_balance",
                    vs_finance.money.MoneyField(
                        help_text="Live cash on hand, in kobo (maintained by the petty-cash ledger)."
                    ),
                ),
                ("last_replenished_at", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_petty_cash_funds",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        help_text="Defaults to the entity base currency.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="petty_cash_funds",
                        to="vs_finance.currency",
                    ),
                ),
                (
                    "custodian",
                    models.ForeignKey(
                        blank=True,
                        help_text="The person accountable for the cash tin.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="petty_cash_funds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="petty_cash_funds",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "gl_account",
                    models.OneToOneField(
                        help_text="The petty-cash GL account this float maps to (1:1). All movement posts here.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="petty_cash_fund",
                        to="vs_finance.account",
                    ),
                ),
            ],
            options={
                "ordering": ["entity", "name"],
            },
        ),
        migrations.CreateModel(
            name="PettyCashVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("voucher_date", models.DateField()),
                (
                    "payee",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Who the cash was paid to.",
                        max_length=160,
                    ),
                ),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                (
                    "subtotal",
                    vs_finance.money.MoneyField(help_text="Net of tax, in kobo."),
                ),
                (
                    "tax_total",
                    vs_finance.money.MoneyField(
                        help_text="Recoverable input tax, in kobo."
                    ),
                ),
                (
                    "total",
                    vs_finance.money.MoneyField(
                        help_text="subtotal + tax_total, in kobo (the cash paid out)."
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="petty_cash_vouchers",
                        to="vs_finance.currency",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vouchers",
                        to="vs_finance.pettycashfund",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="petty_cash_vouchers",
                        to="vs_finance.journalentry",
                    ),
                ),
                (
                    "spent_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The staff member who incurred the spend.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="petty_cash_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PettyCashVoucherLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=1, max_digits=14),
                ),
                (
                    "unit_price",
                    vs_finance.money.MoneyField(help_text="Price per unit in kobo."),
                ),
                (
                    "net_amount",
                    vs_finance.money.MoneyField(
                        help_text="quantity × unit_price, in kobo."
                    ),
                ),
                (
                    "tax_amount",
                    vs_finance.money.MoneyField(
                        help_text="Recoverable tax on the net, in kobo."
                    ),
                ),
                ("line_no", models.PositiveSmallIntegerField(default=0)),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="petty_cash_voucher_lines",
                        to="vs_finance.costcenter",
                    ),
                ),
                (
                    "expense_account",
                    models.ForeignKey(
                        help_text="GL expense account debited for this line's net.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="petty_cash_voucher_lines",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "tax_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="petty_cash_voucher_lines",
                        to="vs_finance.taxcode",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="vs_finance.pettycashvoucher",
                    ),
                ),
            ],
            options={
                "ordering": ["voucher", "line_no", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="pettycashfund",
            index=models.Index(
                fields=["entity", "is_active"], name="vs_finance__entity__50f54e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pettycashfund",
            constraint=models.UniqueConstraint(
                fields=("entity", "name"), name="uniq_finance_pettycash_entity_name"
            ),
        ),
        migrations.AddIndex(
            model_name="pettycashvoucher",
            index=models.Index(
                fields=["entity", "status"], name="vs_finance__entity__e211f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pettycashvoucher",
            index=models.Index(fields=["fund"], name="vs_finance__fund_id_dd1d2e_idx"),
        ),
        migrations.AddConstraint(
            model_name="pettycashvoucher",
            constraint=models.UniqueConstraint(
                fields=("entity", "document_number"),
                name="uniq_vs_finance_pettycashvoucher_entity_docnum",
            ),
        ),
        migrations.AddIndex(
            model_name="pettycashvoucherline",
            index=models.Index(
                fields=["voucher"], name="vs_finance__voucher_5dc117_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pettycashvoucherline",
            index=models.Index(
                fields=["expense_account"], name="vs_finance__expense_9da792_idx"
            ),
        ),
    ]
