# Generated by Django 5.2.10 on 2026-06-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0017_alter_fixedasset_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="source",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("FEE_BILLING", "Fee Billing"),
                    ("SUBSCRIPTION", "Subscription"),
                    ("API", "API"),
                    ("OPENING", "Opening Balance"),
                ],
                default="MANUAL",
                max_length=16,
            ),
        ),
    ]
