# Generated by Django 5.2.10 on 2026-06-07 21:53

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0017_alter_documentsequence_doc_type_and_more"),
        ("vs_schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentsequence",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("JNL", "Journal Entry"),
                    ("INV", "Sales / AR Invoice"),
                    ("RCP", "Receipt"),
                    ("PAY", "Payment"),
                    ("CRN", "Credit Note"),
                    ("DRN", "Debit Note"),
                    ("RFD", "Customer Refund"),
                    ("PPL", "Installment Payment Plan"),
                    ("CNC", "Concession / Discount / Waiver"),
                    ("DUN", "Dunning / Payment Reminder"),
                    ("PR", "Purchase Requisition"),
                    ("RFQ", "Request for Quotation"),
                    ("QUO", "Vendor Quotation"),
                    ("PO", "Purchase Order"),
                    ("GRN", "Goods Received Note"),
                    ("VIN", "Vendor Invoice"),
                    ("VPY", "Vendor Payment"),
                    ("EXP", "Expense Claim"),
                    ("PCV", "Petty Cash Voucher"),
                    ("PYR", "Payroll Run"),
                    ("FA", "Fixed Asset"),
                    ("TXF", "Tax Filing / Remittance"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="financeauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("JOURNAL_POSTED", "Journal posted"),
                    ("JOURNAL_REVERSED", "Journal reversed"),
                    ("JOURNAL_POST_REJECTED", "Journal posting rejected"),
                    ("INVOICE_POSTED", "Invoice posted"),
                    ("INVOICE_CANCELLED", "Invoice cancelled"),
                    ("INVOICE_WRITTEN_OFF", "Invoice written off (bad debt)"),
                    ("PAYMENT_POSTED", "Payment posted"),
                    ("PAYMENT_ALLOCATED", "Payment allocated"),
                    ("CREDIT_NOTE_POSTED", "Credit note posted"),
                    ("CREDIT_NOTE_ALLOCATED", "Credit note allocated"),
                    ("DEBIT_NOTE_POSTED", "Debit note posted"),
                    ("REFUND_POSTED", "Customer refund posted"),
                    ("PAYMENT_PLAN_ACTIVATED", "Installment plan activated"),
                    ("PAYMENT_PLAN_COMPLETED", "Installment plan completed"),
                    ("PAYMENT_PLAN_CANCELLED", "Installment plan cancelled"),
                    ("CONCESSION_POSTED", "Concession / discount / waiver posted"),
                    ("DUNNING_RUN_GENERATED", "Dunning run generated"),
                    ("DUNNING_NOTICE_SENT", "Dunning notice marked sent"),
                    ("DUNNING_NOTICE_CANCELLED", "Dunning notice cancelled"),
                    ("PERIOD_CLOSED", "Period closed"),
                    ("PERIOD_REOPENED", "Period re-opened"),
                    ("ACCOUNT_CREATED", "Account created"),
                    ("ACCOUNT_UPDATED", "Account updated"),
                    ("REQUISITION_APPROVED", "Requisition approved"),
                    ("RFQ_ISSUED", "Request for quotation issued"),
                    ("RFQ_CANCELLED", "Request for quotation cancelled"),
                    ("QUOTATION_SUBMITTED", "Vendor quotation submitted"),
                    ("QUOTATION_AWARDED", "Vendor quotation awarded → PO"),
                    ("VENDOR_CONTRACT_ACTIVATED", "Vendor contract activated"),
                    ("VENDOR_CONTRACT_RENEWED", "Vendor contract renewed"),
                    ("VENDOR_CONTRACT_TERMINATED", "Vendor contract terminated"),
                    ("CONTRACT_MILESTONE_COMPLETED", "Contract milestone completed"),
                    ("PURCHASE_ORDER_APPROVED", "Purchase order approved"),
                    ("GRN_POSTED", "Goods receipt posted"),
                    ("GRN_POST_REJECTED", "Goods receipt posting rejected"),
                    ("VENDOR_INVOICE_MATCHED", "Vendor invoice matched"),
                    ("VENDOR_INVOICE_APPROVED", "Vendor invoice approved (workflow)"),
                    ("VENDOR_INVOICE_POSTED", "Vendor invoice posted"),
                    ("VENDOR_INVOICE_POST_REJECTED", "Vendor invoice posting rejected"),
                    ("VENDOR_PAYMENT_POSTED", "Vendor payment posted"),
                    ("VENDOR_PAYMENT_POST_REJECTED", "Vendor payment posting rejected"),
                    ("VENDOR_PAYMENT_ALLOCATED", "Vendor payment allocated"),
                    ("STOCK_RECEIVED", "Stock received (perpetual inventory)"),
                    ("STOCK_ISSUED", "Stock issued"),
                    ("STOCK_ISSUE_REJECTED", "Stock issue rejected"),
                    ("STOCK_ADJUSTED", "Stock adjusted"),
                    ("STOCK_ADJUST_REJECTED", "Stock adjustment rejected"),
                    ("BANK_RECONCILED", "Bank statement reconciled"),
                    ("BANK_CHARGE_POSTED", "Bank charge posted"),
                    ("EXPENSE_CLAIM_POSTED", "Expense claim posted"),
                    ("EXPENSE_CLAIM_POST_REJECTED", "Expense claim posting rejected"),
                    ("EXPENSE_CLAIM_SETTLED", "Expense claim settled"),
                    (
                        "PETTY_CASH_ESTABLISHED",
                        "Petty cash fund established / topped up",
                    ),
                    ("PETTY_CASH_VOUCHER_POSTED", "Petty cash voucher posted"),
                    ("PETTY_CASH_VOUCHER_REJECTED", "Petty cash voucher rejected"),
                    ("PETTY_CASH_REPLENISHED", "Petty cash fund replenished"),
                    ("PAYROLL_POSTED", "Payroll run posted"),
                    ("PAYROLL_POST_REJECTED", "Payroll run posting rejected"),
                    ("PAYROLL_PAID", "Payroll run disbursed"),
                    ("BUDGET_APPROVED", "Budget approved"),
                    ("ASSET_ACQUIRED", "Fixed asset acquired"),
                    ("DEPRECIATION_POSTED", "Depreciation posted"),
                    ("PERIOD_LOCKED", "Period locked"),
                    ("TAX_FILING_PREPARED", "Tax filing prepared"),
                    ("TAX_FILING_FILED", "Tax filing submitted to authority"),
                    ("TAX_FILING_PAID", "Tax filing paid / remitted"),
                    ("TAX_FILING_REJECTED", "Tax filing action rejected"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="TaxObligation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Short slug, e.g. 'VAT', 'WHT', 'PAYE'.",
                        max_length=24,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "obligation_type",
                    models.CharField(
                        choices=[
                            ("VAT", "Value Added Tax"),
                            ("WHT", "Withholding Tax"),
                            ("PAYE", "Pay-As-You-Earn (employee income tax)"),
                            ("PENSION", "Pension contribution"),
                            ("OTHER", "Other statutory levy"),
                        ],
                        help_text="Which statutory tax this obligation covers.",
                        max_length=12,
                    ),
                ),
                (
                    "authority_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Who the tax is paid to, e.g. 'FIRS', 'Lagos State IRS', a PFA.",
                        max_length=160,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUAL", "Annual"),
                        ],
                        default="MONTHLY",
                        max_length=12,
                    ),
                ),
                (
                    "filing_day",
                    models.PositiveSmallIntegerField(
                        default=21,
                        help_text="Day of the month after period end the return is due (e.g. 21 for VAT).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tax_obligations",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "liability_account",
                    models.ForeignKey(
                        help_text="Liability control account whose balance is remitted (Dr on payment).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tax_obligations",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "recoverable_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Recoverable input account netted off at filing (VAT only). Usually 1300.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tax_obligations_recoverable",
                        to="vs_finance.account",
                    ),
                ),
            ],
            options={
                "ordering": ["entity", "code"],
            },
        ),
        migrations.CreateModel(
            name="TaxFiling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "filing_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft / prepared"),
                            ("FILED", "Filed with authority"),
                            ("PAID", "Paid / remitted"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                (
                    "gross_liability",
                    vs_finance.money.MoneyField(
                        help_text="Output/payable accrued in the period, in kobo."
                    ),
                ),
                (
                    "recoverable_amount",
                    vs_finance.money.MoneyField(
                        help_text="Recoverable input netted off (VAT), in kobo."
                    ),
                ),
                (
                    "adjustment_amount",
                    vs_finance.money.MoneyField(
                        help_text="Penalty / interest added at filing (increases amount due), in kobo."
                    ),
                ),
                (
                    "amount_due",
                    vs_finance.money.MoneyField(
                        help_text="gross_liability − recoverable_amount + adjustment, in kobo."
                    ),
                ),
                (
                    "amount_paid",
                    vs_finance.money.MoneyField(help_text="Remitted so far, in kobo."),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "Unpaid"),
                            ("PARTIAL", "Partially Paid"),
                            ("PAID", "Paid"),
                        ],
                        default="UNPAID",
                        max_length=8,
                    ),
                ),
                (
                    "filing_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Authority's return/receipt number once filed.",
                        max_length=64,
                    ),
                ),
                ("filed_at", models.DateField(blank=True, null=True)),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                (
                    "adjustment_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Expense account debited for a penalty/interest adjustment.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tax_filing_adjustments",
                        to="vs_finance.account",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tax_filings",
                        to="vs_finance.currency",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "filing_journal",
                    models.ForeignKey(
                        blank=True,
                        help_text="The netting/penalty journal posted at filing (if any).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tax_filing_postings",
                        to="vs_finance.journalentry",
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="filings",
                        to="vs_finance.taxobligation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="taxobligation",
            index=models.Index(
                fields=["entity", "is_active"], name="vs_finance__entity__79169a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="taxobligation",
            constraint=models.UniqueConstraint(
                fields=("entity", "code"), name="uniq_finance_taxobligation_entity_code"
            ),
        ),
        migrations.AddIndex(
            model_name="taxfiling",
            index=models.Index(
                fields=["entity", "filing_status"],
                name="vs_finance__entity__b551d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taxfiling",
            index=models.Index(
                fields=["obligation"], name="vs_finance__obligat_794007_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="taxfiling",
            constraint=models.UniqueConstraint(
                fields=("entity", "document_number"),
                name="uniq_vs_finance_taxfiling_entity_docnum",
            ),
        ),
    ]
