# Generated by Django 5.2.13 on 2026-06-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0018_alter_documentsequence_doc_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="ifrs_line",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PPE", "Property, plant and equipment"),
                    ("INTANGIBLES", "Intangible assets"),
                    ("INVESTMENTS", "Investments"),
                    ("INVENTORIES", "Inventories"),
                    ("TRADE_RECEIVABLES", "Trade and other receivables"),
                    ("CURRENT_TAX_ASSET", "Current tax assets"),
                    ("CASH", "Cash and cash equivalents"),
                    ("OTHER_CURRENT_ASSETS", "Other current assets"),
                    ("SHARE_CAPITAL", "Share capital"),
                    ("RETAINED_EARNINGS", "Retained earnings"),
                    ("OTHER_RESERVES", "Other reserves"),
                    ("LONG_TERM_BORROWINGS", "Long-term borrowings"),
                    ("TRADE_PAYABLES", "Trade and other payables"),
                    ("CURRENT_TAX_PAYABLE", "Current tax payable"),
                    ("EMPLOYEE_PAYABLES", "Employee benefit obligations"),
                    ("SHORT_TERM_BORROWINGS", "Short-term borrowings"),
                    ("REVENUE", "Revenue"),
                    ("COST_OF_SALES", "Cost of sales"),
                    ("OTHER_INCOME", "Other income"),
                    ("DISTRIBUTION_COSTS", "Distribution costs"),
                    ("ADMIN_EXPENSES", "Administrative expenses"),
                    ("OTHER_EXPENSES", "Other expenses"),
                    ("FINANCE_COSTS", "Finance costs"),
                    ("TAX_EXPENSE", "Income tax expense"),
                ],
                default="",
                help_text="IFRS-for-SMEs statutory presentation line; blank falls back to the type default.",
                max_length=32,
            ),
        ),
    ]
