# Generated by Django 5.2.10 on 2026-07-01 11:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0019_dimension_allowed_values"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankLineMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "journal_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_line_matches",
                        to="vs_finance.journalline",
                    ),
                ),
                (
                    "statement_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_matches",
                        to="vs_finance.bankstatementline",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["journal_line"], name="vs_finance__journal_1f63a5_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("statement_line", "journal_line"),
                        name="uniq_finance_bank_line_match",
                    )
                ],
            },
        ),
    ]
