# Generated by Django 5.2.10 on 2026-09-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0024_employeesalary_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="pay_token_version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Bumped to invalidate every public pay link already issued for this invoice. The version is signed into the token, so raising it kills the links in circulation for this invoice and no other.",
            ),
        ),
    ]
