# Generated by Django 5.2.10 on 2026-07-03 13:36

from django.db import migrations, models

# No data migration is needed: BudgetStatus.LOCKED was never written to any Budget row
# (approval sets APPROVED, never LOCKED), so dropping the choice only narrows the field's
# validation set — there are no existing "LOCKED" values to backfill or remap.


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0025_financeauditlog_immutability_triggers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("APPROVED", "Approved")],
                default="DRAFT",
                max_length=10,
            ),
        ),
    ]
