# Generated by Django 5.2.10 on 2026-07-05 22:41

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0027_alter_financeauditlog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditnote",
            name="amount_paid",
            field=vs_finance.money.MoneyField(
                help_text="Cash allocated to this DEBIT note, in kobo."
            ),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="settlement_status",
            field=models.CharField(
                choices=[
                    ("UNPAID", "Unpaid"),
                    ("PARTIAL", "Partially Paid"),
                    ("PAID", "Paid"),
                ],
                default="UNPAID",
                help_text="How much of a DEBIT note has been settled by receipts.",
                max_length=8,
            ),
        ),
        migrations.CreateModel(
            name="DebitNoteAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Amount of the payment applied to this debit note, in kobo."
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="vs_finance.creditnote",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debit_note_allocations",
                        to="vs_finance.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["payment", "id"],
                "indexes": [
                    models.Index(
                        fields=["note"], name="vs_finance__note_id_f1d622_idx"
                    ),
                    models.Index(
                        fields=["payment"], name="vs_finance__payment_f5a067_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("payment", "note"),
                        name="uniq_finance_dnalloc_payment_note",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", 0)),
                        name="ck_finance_dnalloc_non_negative",
                    ),
                ],
            },
        ),
    ]
