# Generated by Django 5.2.10 on 2026-09-26 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0028_approver_groups_nobody_asked_for"),
        ("vs_tenants", "0010_remove_branch__type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="budget",
            name="uniq_finance_budget_entity_year_name",
        ),
        migrations.AddField(
            model_name="budget",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="finance_budgets",
                to="vs_tenants.branch",
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(
                condition=models.Q(("branch__isnull", True)),
                fields=("entity", "fiscal_year", "name"),
                name="uniq_finance_budget_entity_year_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(
                condition=models.Q(("branch__isnull", False)),
                fields=("entity", "fiscal_year", "branch", "name"),
                name="uniq_finance_budget_branch_year_name",
            ),
        ),
    ]
