# Generated by Django 5.2.10 on 2026-07-05 23:16

import vs_finance.money
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "vs_finance",
            "0028_creditnote_amount_paid_creditnote_settlement_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentplan",
            name="baseline_settled",
            field=vs_finance.money.MoneyField(
                help_text="Invoice settlement (cash + non-cash credits) already applied when the plan was activated. Excluded from installment progress so pre-plan credits/waivers aren't miscounted as installment payments."
            ),
        ),
    ]
