# Generated by Django 5.2.10 on 2026-07-07 08:33

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0029_paymentplan_baseline_settled"),
        ("vs_schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentsequence",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("JNL", "Journal Entry"),
                    ("INV", "Sales / AR Invoice"),
                    ("RCP", "Receipt"),
                    ("PAY", "Payment"),
                    ("CRN", "Credit Note"),
                    ("DRN", "Debit Note"),
                    ("RFD", "Customer Refund"),
                    ("PPL", "Installment Payment Plan"),
                    ("CNC", "Concession / Discount / Waiver"),
                    ("WOF", "Bad-debt Write-off"),
                    ("DUN", "Dunning / Payment Reminder"),
                    ("PR", "Purchase Requisition"),
                    ("RFQ", "Request for Quotation"),
                    ("QUO", "Vendor Quotation"),
                    ("PO", "Purchase Order"),
                    ("GRN", "Goods Received Note"),
                    ("VIN", "Vendor Invoice"),
                    ("VPY", "Vendor Payment"),
                    ("EXP", "Expense Claim"),
                    ("PCV", "Petty Cash Voucher"),
                    ("PYR", "Payroll Run"),
                    ("FA", "Fixed Asset"),
                    ("TXF", "Tax Filing / Remittance"),
                    ("BDG", "Budget"),
                ],
                max_length=8,
            ),
        ),
        migrations.CreateModel(
            name="WriteOffRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Amount to write off, in kobo."
                    ),
                ),
                ("write_off_date", models.DateField(blank=True, null=True)),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="write_off_requests",
                        to="vs_finance.invoice",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="write_off_requests",
                        to="vs_finance.journalentry",
                    ),
                ),
                (
                    "write_off_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Expense account debited; defaults to the entity's bad-debt account.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="write_off_requests",
                        to="vs_finance.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["entity", "status"],
                        name="vs_finance__entity__78047a_idx",
                    ),
                    models.Index(
                        fields=["invoice"], name="vs_finance__invoice_4ed1f0_idx"
                    ),
                    models.Index(
                        fields=["entity", "write_off_date"],
                        name="vs_finance__entity__b069a6_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entity", "document_number"),
                        name="uniq_vs_finance_writeoffrequest_entity_docnum",
                    )
                ],
            },
        ),
    ]
