# Generated by Django 5.2.10 on 2026-09-26 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0029_budget_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="financedocumentsettings",
            name="term_collection_target_pct",
            field=models.PositiveSmallIntegerField(
                default=90,
                help_text="Share of a billing period's fees the owner aims to collect by its end, drawn as the target on the collection curve.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
