# Generated by Django 5.2.10 on 2026-07-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0030_alter_documentsequence_doc_type_writeoffrequest"),
        ("vs_schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="is_primary_collection",
            field=models.BooleanField(
                default=False,
                help_text="The entity's primary fee-collection account — the one printed as 'pay to' on customer invoices/receipts. At most one per entity.",
            ),
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary_collection", True)),
                fields=("entity",),
                name="uniq_finance_primary_collection_per_entity",
            ),
        ),
    ]
