# Generated by Django 5.2.10 on 2026-07-12 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0032_alter_financeauditlog_action"),
        ("vs_schools", "0003_school_tenant"),
        (
            "vs_tenants",
            "0003_rename_vs_tenants_kind_status_idx_vs_tenants__kind_580eca_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgerentity",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Canonical owner; temporarily nullable during data backfill.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entities",
                to="vs_tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentity",
            index=models.Index(
                fields=["tenant", "is_active"], name="vs_finance__tenant__424f6e_idx"
            ),
        ),
    ]
