# Generated by Django 5.2.10 on 2026-07-14 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0035_require_ledger_tenant"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ledgerentity",
            name="vs_finance__source__6adc88_idx",
        ),
        migrations.RemoveField(
            model_name="ledgerentity",
            name="source_school",
        ),
    ]
