# Generated by Django 5.2.10 on 2026-09-30 02:52

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0038_bank_transfers"),
        ("vs_tenants", "0010_remove_branch__type"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollline",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="finance_payroll_lines",
                to="vs_tenants.branch",
            ),
        ),
        migrations.CreateModel(
            name="PayrollRunBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gross_total",
                    vs_finance.money.MoneyField(
                        help_text="Amount in minor units (kobo); integer, never float."
                    ),
                ),
                (
                    "paye_total",
                    vs_finance.money.MoneyField(
                        help_text="Amount in minor units (kobo); integer, never float."
                    ),
                ),
                (
                    "pension_total",
                    vs_finance.money.MoneyField(
                        help_text="Amount in minor units (kobo); integer, never float."
                    ),
                ),
                (
                    "net_total",
                    vs_finance.money.MoneyField(
                        help_text="Amount in minor units (kobo); integer, never float."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted (accrued)"),
                            ("PAID", "Paid (disbursed)"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="POSTED",
                        max_length=10,
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_run_shares",
                        to="vs_finance.bankaccount",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_run_shares",
                        to="vs_tenants.branch",
                    ),
                ),
                (
                    "disbursement_journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_branch_disbursements",
                        to="vs_finance.journalentry",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_branch_accruals",
                        to="vs_finance.journalentry",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_shares",
                        to="vs_finance.payrollrun",
                    ),
                ),
            ],
            options={
                "ordering": ["run", "branch__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "branch"), name="uniq_finance_payroll_run_branch"
                    )
                ],
            },
        ),
    ]
