# Generated by Django 5.2.10 on 2026-09-30 14:08

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import vs_finance.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0039_payroll_journal_per_branch"),
        ("vs_tenants", "0010_remove_branch__type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerCreditTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("transfer_date", models.DateField()),
                (
                    "amount",
                    vs_finance.money.MoneyField(help_text="Credit moved, in kobo."),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerCreditTransferDraw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Amount drawn from this lot, in kobo."
                    ),
                ),
            ],
            options={
                "ordering": ["transfer", "id"],
            },
        ),
        migrations.CreateModel(
            name="FeeItemAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["item", "customer"],
            },
        ),
        migrations.AddField(
            model_name="creditnote",
            name="transferred_amount",
            field=vs_finance.money.MoneyField(
                help_text="Portion of a CREDIT note's unapplied value moved to another customer by an approved credit transfer, in kobo. Maintained by CustomerCreditTransferDraw."
            ),
        ),
        migrations.AddField(
            model_name="financedocumentsettings",
            name="auto_apply_customer_credit",
            field=models.BooleanField(
                default=True,
                help_text="Apply a customer's unapplied credit (advance payments, overpayments, credit notes) to every new invoice of theirs as it posts, oldest credit first. Off, credit waits until somebody allocates it.",
            ),
        ),
        migrations.AddField(
            model_name="financedocumentsettings",
            name="concession_second_person_threshold",
            field=models.PositiveBigIntegerField(
                default=1000000,
                help_text="Kobo above which a concession, counted with the other reductions of the same bill and billing period, must be posted by somebody other than the person who raised it.",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="billing_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="What a fee run billed: 'FEE:<structure code>', with '@<period>' when the run named a billing period. Unique per customer among live invoices.",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="billing_period",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Opaque key of the billing period the owner layer placed this invoice in. Fixed once posted.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="billing_period_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The billing period's name as it read when the invoice was raised.",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="transferred_amount",
            field=vs_finance.money.MoneyField(
                help_text="Portion of this receipt's unapplied cash moved to another customer by an approved credit transfer, in kobo. Maintained by CustomerCreditTransferDraw."
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="An inactive customer is billed by no fee run and by no 'bill all active' selection, and keeps its debt, its documents and its place in debtor lists.",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="opening_balance",
            field=vs_finance.money.MoneyField(
                help_text="Opening AR balance in kobo, posted once as an opening invoice when the customer is created. Fixed afterwards: a correction is a credit or debit note."
            ),
        ),
        migrations.AlterField(
            model_name="documentsequence",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("JN", "Journal Entry"),
                    ("IV", "Sales / AR Invoice"),
                    ("RC", "Receipt"),
                    ("PY", "Payment"),
                    ("CN", "Credit Note"),
                    ("DN", "Debit Note"),
                    ("RF", "Customer Refund"),
                    ("PP", "Installment Payment Plan"),
                    ("CC", "Concession / Discount / Waiver"),
                    ("WO", "Bad-debt Write-off"),
                    ("DU", "Dunning / Payment Reminder"),
                    ("PR", "Purchase Requisition"),
                    ("RQ", "Request for Quotation"),
                    ("QT", "Vendor Quotation"),
                    ("PO", "Purchase Order"),
                    ("GN", "Goods Received Note"),
                    ("VI", "Vendor Invoice"),
                    ("VP", "Vendor Payment"),
                    ("EX", "Expense Claim"),
                    ("PC", "Petty Cash Voucher"),
                    ("PL", "Payroll Run"),
                    ("FA", "Fixed Asset"),
                    ("TX", "Tax Filing / Remittance"),
                    ("BG", "Budget"),
                    ("BT", "Bank Transaction"),
                    ("BX", "Transfer Between Own Accounts"),
                    ("CT", "Customer Credit Transfer"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="feeitem",
            name="is_optional",
            field=models.BooleanField(
                default=False,
                help_text="An opt-in charge: billed only to the customers assigned to it (FeeItemAssignment). A required line bills every customer the run bills.",
            ),
        ),
        migrations.AlterField(
            model_name="financeauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("JOURNAL_POSTED", "Journal posted"),
                    ("JOURNAL_REVERSED", "Journal reversed"),
                    ("JOURNAL_POST_REJECTED", "Journal posting rejected"),
                    ("INVOICE_POSTED", "Invoice posted"),
                    ("INVOICE_CANCELLED", "Invoice cancelled"),
                    ("INVOICE_REVERSED", "Invoice reversed"),
                    ("INVOICE_WRITTEN_OFF", "Invoice written off (bad debt)"),
                    ("INVOICE_PAY_LINK_REVOKED", "Invoice pay link revoked"),
                    ("PAYMENT_POSTED", "Payment posted"),
                    ("PAYMENT_ALLOCATED", "Payment allocated"),
                    ("PAYMENT_REVERSED", "Payment reversed"),
                    ("CREDIT_NOTE_POSTED", "Credit note posted"),
                    ("CREDIT_NOTE_ALLOCATED", "Credit note allocated"),
                    ("DEBIT_NOTE_POSTED", "Debit note posted"),
                    ("CREDIT_NOTE_REVERSED", "Credit/debit note reversed"),
                    ("REFUND_POSTED", "Customer refund posted"),
                    ("REFUND_REVERSED", "Customer refund reversed"),
                    ("PAYMENT_PLAN_ACTIVATED", "Installment plan activated"),
                    ("PAYMENT_PLAN_COMPLETED", "Installment plan completed"),
                    ("PAYMENT_PLAN_CANCELLED", "Installment plan cancelled"),
                    ("CONCESSION_POSTED", "Concession / discount / waiver posted"),
                    ("CONCESSION_REVERSED", "Concession / discount / waiver reversed"),
                    ("CUSTOMER_UPDATED", "Customer updated"),
                    ("CUSTOMER_DEACTIVATED", "Customer deactivated"),
                    ("CUSTOMER_REACTIVATED", "Customer reactivated"),
                    ("CUSTOMER_OPENING_POSTED", "Customer opening invoice posted"),
                    ("CREDIT_TRANSFER_POSTED", "Customer credit transfer posted"),
                    ("CREDIT_TRANSFER_REVERSED", "Customer credit transfer reversed"),
                    ("RECEIPT_PARKED_AS_CREDIT", "Receipt parked as customer credit"),
                    ("DUNNING_RUN_GENERATED", "Dunning run generated"),
                    ("DUNNING_NOTICE_SENT", "Dunning notice marked sent"),
                    ("DUNNING_NOTICE_CANCELLED", "Dunning notice cancelled"),
                    ("PERIOD_CLOSED", "Period closed"),
                    ("PERIOD_REOPENED", "Period re-opened"),
                    ("ACCOUNT_CREATED", "Account created"),
                    ("ACCOUNT_UPDATED", "Account updated"),
                    ("FINANCE_SETTINGS_UPDATED", "Finance settings updated"),
                    (
                        "FIN_DOCUMENT_SETTINGS_UPDATED",
                        "Finance document settings updated",
                    ),
                    ("FIN_BANK_SETTINGS_UPDATED", "Finance banking settings updated"),
                    (
                        "FIN_CALENDAR_SETTINGS_UPDATED",
                        "Finance calendar settings updated",
                    ),
                    ("PROCUREMENT_SETTINGS_UPDATED", "Procurement settings updated"),
                    ("REQUISITION_APPROVED", "Requisition approved"),
                    (
                        "SPEND_APPROVAL_OVERRIDDEN",
                        "Spend approval released by override (no review)",
                    ),
                    ("RFQ_ISSUED", "Request for quotation issued"),
                    ("RFQ_CANCELLED", "Request for quotation cancelled"),
                    ("RFQ_CLOSED", "Request for quotation closed without award"),
                    ("QUOTATION_SUBMITTED", "Vendor quotation submitted"),
                    ("QUOTATION_AWARDED", "Vendor quotation awarded → PO"),
                    ("QUOTATION_REJECTED", "Vendor quotation rejected"),
                    ("VENDOR_CONTRACT_ACTIVATED", "Vendor contract activated"),
                    ("VENDOR_CONTRACT_RENEWED", "Vendor contract renewed"),
                    ("VENDOR_CONTRACT_TERMINATED", "Vendor contract terminated"),
                    ("CONTRACT_MILESTONE_COMPLETED", "Contract milestone completed"),
                    ("PURCHASE_ORDER_APPROVED", "Purchase order approved"),
                    ("PURCHASE_ORDER_CANCELLED", "Purchase order cancelled"),
                    ("PO_EMAIL_SCHEDULED", "Purchase order email scheduled"),
                    ("PO_EMAIL_QUEUED", "Purchase order email queued"),
                    ("PO_EMAIL_SENT", "Purchase order email sent"),
                    ("PO_EMAIL_FAILED", "Purchase order email failed"),
                    ("PO_EMAIL_CANCELLED", "Purchase order email cancelled"),
                    ("DOC_EMAIL_QUEUED", "Customer document email queued"),
                    ("DOC_EMAIL_SENT", "Customer document email sent"),
                    ("DOC_EMAIL_FAILED", "Customer document email failed"),
                    ("GRN_POSTED", "Goods receipt posted"),
                    ("GRN_POST_REJECTED", "Goods receipt posting rejected"),
                    ("VENDOR_INVOICE_MATCHED", "Vendor invoice matched"),
                    ("VENDOR_INVOICE_APPROVED", "Vendor invoice approved (workflow)"),
                    ("VENDOR_INVOICE_POSTED", "Vendor invoice posted"),
                    ("VENDOR_INVOICE_POST_REJECTED", "Vendor invoice posting rejected"),
                    ("VENDOR_PAYMENT_POSTED", "Vendor payment posted"),
                    ("VENDOR_PAYMENT_POST_REJECTED", "Vendor payment posting rejected"),
                    ("VENDOR_PAYMENT_ALLOCATED", "Vendor payment allocated"),
                    ("VENDOR_INVOICE_VOIDED", "Vendor invoice voided"),
                    (
                        "VENDOR_CREDIT_NOTE_APPROVED",
                        "Vendor credit note approved (workflow)",
                    ),
                    ("VENDOR_CREDIT_NOTE_POSTED", "Vendor credit note posted"),
                    ("VENDOR_CREDIT_NOTE_ALLOCATED", "Vendor credit note allocated"),
                    ("VENDOR_CREDIT_NOTE_VOIDED", "Vendor credit note voided"),
                    ("GOODS_RETURNED", "Goods returned to vendor"),
                    ("VENDOR_OPENING_BILL_POSTED", "Vendor opening bill posted"),
                    ("STOCK_RECEIVED", "Stock received (perpetual inventory)"),
                    ("STOCK_ISSUED", "Stock issued"),
                    ("STOCK_ISSUE_REJECTED", "Stock issue rejected"),
                    ("STOCK_ADJUSTED", "Stock adjusted"),
                    ("STOCK_ADJUST_REJECTED", "Stock adjustment rejected"),
                    ("BANK_STATEMENT_CORRECTED", "Bank statement corrected"),
                    ("BANK_RECONCILED", "Bank statement reconciled"),
                    ("BANK_CHARGE_POSTED", "Bank charge posted"),
                    ("BANK_TRANSACTION_POSTED", "Bank transaction posted"),
                    ("BANK_TRANSACTION_VOIDED", "Bank transaction voided"),
                    ("BANK_TRANSFER_POSTED", "Transfer between own accounts posted"),
                    ("BANK_TRANSFER_VOIDED", "Transfer between own accounts voided"),
                    ("EXPENSE_CLAIM_POSTED", "Expense claim posted"),
                    ("EXPENSE_CLAIM_POST_REJECTED", "Expense claim posting rejected"),
                    ("EXPENSE_CLAIM_SETTLED", "Expense claim settled"),
                    ("EXPENSE_CLAIM_VOIDED", "Expense claim voided"),
                    (
                        "PETTY_CASH_ESTABLISHED",
                        "Petty cash fund established / topped up",
                    ),
                    ("PETTY_CASH_VOUCHER_POSTED", "Petty cash voucher posted"),
                    ("PETTY_CASH_VOUCHER_REJECTED", "Petty cash voucher rejected"),
                    ("PETTY_CASH_VOUCHER_VOIDED", "Petty cash voucher voided"),
                    ("PETTY_CASH_REPLENISHED", "Petty cash fund replenished"),
                    ("PAYROLL_POSTED", "Payroll run posted"),
                    ("PAYROLL_POST_REJECTED", "Payroll run posting rejected"),
                    ("PAYROLL_PAID", "Payroll run disbursed"),
                    ("PAYROLL_CANCELLED", "Payroll run cancelled / voided"),
                    ("BUDGET_APPROVED", "Budget approved"),
                    ("BUDGET_DELETED", "Budget deleted"),
                    ("ASSET_ACQUIRED", "Fixed asset acquired"),
                    ("DEPRECIATION_POSTED", "Depreciation posted"),
                    ("ASSET_DISPOSED", "Fixed asset disposed"),
                    ("PERIOD_LOCKED", "Period locked"),
                    ("FISCAL_YEAR_OPENED", "Fiscal year opened"),
                    ("FISCAL_YEAR_CLOSED", "Fiscal year closed"),
                    ("FISCAL_YEAR_REOPENED", "Fiscal year re-opened"),
                    (
                        "FISCAL_CALENDAR_WARNED",
                        "Finance staff warned the fiscal calendar is running out",
                    ),
                    ("TAX_FILING_PREPARED", "Tax filing prepared"),
                    ("TAX_FILING_FILED", "Tax filing submitted to authority"),
                    ("TAX_FILING_UNFILED", "Tax filing un-filed (reverted to draft)"),
                    ("TAX_FILING_PAID", "Tax filing paid / remitted"),
                    ("TAX_FILING_REJECTED", "Tax filing action rejected"),
                    ("TAX_REMITTANCE_REVERSED", "Tax remittance reversed"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("BANK_TRANSFER", "Bank Transfer"),
                    ("CARD", "Card"),
                    ("CHEQUE", "Cheque"),
                    ("ONLINE", "Online / Gateway"),
                    ("OTHER", "Other"),
                    ("CREDIT_TRANSFER", "Customer credit transfer"),
                ],
                default="BANK_TRANSFER",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["entity", "billing_period"],
                name="vs_finance__entity__108e9a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("allocated_amount__gte", 0),
                    ("refunded_amount__gte", 0),
                    ("transferred_amount__gte", 0),
                    ("amount_paid__gte", 0),
                ),
                name="ck_finance_creditnote_spent_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "total__gte",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("allocated_amount"),
                                "+",
                                models.F("refunded_amount"),
                            ),
                            "+",
                            models.F("transferred_amount"),
                        ),
                    )
                ),
                name="ck_finance_creditnote_spent_within_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnote",
            constraint=models.CheckConstraint(
                condition=models.Q(("total__gte", models.F("amount_paid"))),
                name="ck_finance_creditnote_paid_within_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_id", ""), _negated=True),
                fields=("entity", "source_type", "source_id"),
                name="uniq_finance_customer_entity_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("billing_key", ""), _negated=True),
                    models.Q(("status__in", ["REVERSED", "CANCELLED"]), _negated=True),
                ),
                fields=("entity", "customer", "billing_key"),
                name="uniq_finance_invoice_billing_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("amount_paid__gte", 0), ("amount_credited__gte", 0)
                ),
                name="ck_finance_invoice_settled_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "total__gte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("amount_paid"), "+", models.F("amount_credited")
                        ),
                    )
                ),
                name="ck_finance_invoice_settled_within_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("allocated_amount__gte", 0),
                    ("refunded_amount__gte", 0),
                    ("transferred_amount__gte", 0),
                ),
                name="ck_finance_payment_spent_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "amount__gte",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("allocated_amount"),
                                "+",
                                models.F("refunded_amount"),
                            ),
                            "+",
                            models.F("transferred_amount"),
                        ),
                    )
                ),
                name="ck_finance_payment_spent_within_amount",
            ),
        ),
        migrations.AddField(
            model_name="customercredittransfer",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                to="vs_tenants.branch",
            ),
        ),
        migrations.AddField(
            model_name="customercredittransfer",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customercredittransfer",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                to="vs_finance.ledgerentity",
            ),
        ),
        migrations.AddField(
            model_name="customercredittransfer",
            name="from_customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_transfers_out",
                to="vs_finance.customer",
            ),
        ),
        migrations.AddField(
            model_name="customercredittransfer",
            name="receipt",
            field=models.OneToOneField(
                blank=True,
                help_text="The destination's credit-transfer receipt, once posted.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_transfer",
                to="vs_finance.payment",
            ),
        ),
        migrations.AddField(
            model_name="customercredittransfer",
            name="to_customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_transfers_in",
                to="vs_finance.customer",
            ),
        ),
        migrations.AddField(
            model_name="customercredittransferdraw",
            name="note",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_transfer_draws",
                to="vs_finance.creditnote",
            ),
        ),
        migrations.AddField(
            model_name="customercredittransferdraw",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_transfer_draws",
                to="vs_finance.payment",
            ),
        ),
        migrations.AddField(
            model_name="customercredittransferdraw",
            name="transfer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draws",
                to="vs_finance.customercredittransfer",
            ),
        ),
        migrations.AddField(
            model_name="feeitemassignment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="finance_fee_item_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feeitemassignment",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_item_assignments",
                to="vs_finance.customer",
            ),
        ),
        migrations.AddField(
            model_name="feeitemassignment",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="vs_finance.feeitem",
            ),
        ),
        migrations.AddIndex(
            model_name="customercredittransfer",
            index=models.Index(
                fields=["entity", "status"], name="vs_finance__entity__034930_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customercredittransfer",
            index=models.Index(
                fields=["from_customer"], name="vs_finance__from_cu_9e37fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customercredittransfer",
            index=models.Index(
                fields=["to_customer"], name="vs_finance__to_cust_4551ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customercredittransfer",
            index=models.Index(
                fields=["entity", "transfer_date"],
                name="vs_finance__entity__ae8310_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="customercredittransfer",
            constraint=models.UniqueConstraint(
                fields=("entity", "document_number"),
                name="uniq_vs_finance_customercredittransfer_entity_docnum",
            ),
        ),
        migrations.AddConstraint(
            model_name="customercredittransfer",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="ck_finance_credittransfer_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="customercredittransfer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("from_customer", models.F("to_customer")), _negated=True
                ),
                name="ck_finance_credittransfer_two_customers",
            ),
        ),
        migrations.AddIndex(
            model_name="customercredittransferdraw",
            index=models.Index(
                fields=["transfer"], name="vs_finance__transfe_9272f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customercredittransferdraw",
            index=models.Index(
                fields=["payment"], name="vs_finance__payment_4bdd54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customercredittransferdraw",
            index=models.Index(fields=["note"], name="vs_finance__note_id_b6072e_idx"),
        ),
        migrations.AddConstraint(
            model_name="customercredittransferdraw",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="ck_finance_ctdraw_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="customercredittransferdraw",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("note__isnull", True), ("payment__isnull", False)),
                    models.Q(("note__isnull", False), ("payment__isnull", True)),
                    _connector="OR",
                ),
                name="ck_finance_ctdraw_one_source",
            ),
        ),
        migrations.AddIndex(
            model_name="feeitemassignment",
            index=models.Index(
                fields=["customer"], name="vs_finance__custome_144a57_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="feeitemassignment",
            constraint=models.UniqueConstraint(
                fields=("item", "customer"), name="uniq_finance_feeitem_assignment"
            ),
        ),
    ]
