# Generated by Django 5.2.10 on 2026-09-30 19:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import vs_finance.models.accruals
import vs_finance.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0042_finance_audit_branch"),
        ("vs_tenants", "0010_remove_branch__type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerDeposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    vs_finance.money.MoneyField(help_text="Deposit billed, in kobo."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("HELD", "Held"),
                            ("RELEASED", "Returned or set against bills"),
                            ("FORFEITED", "Forfeited as unclaimed"),
                            ("CANCELLED", "Cancelled with its invoice"),
                        ],
                        default="HELD",
                        max_length=12,
                    ),
                ),
                ("claim_opened_on", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["customer", "id"],
            },
        ),
        migrations.CreateModel(
            name="DeferredIncomeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recognition_date", models.DateField()),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="This month's share, in kobo."
                    ),
                ),
                (
                    "unwound_amount",
                    vs_finance.money.MoneyField(
                        help_text="Taken back out before release, in kobo."
                    ),
                ),
                (
                    "released_amount",
                    vs_finance.money.MoneyField(
                        help_text="Moved to revenue by its release, in kobo."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Waiting to be released"),
                            ("RELEASED", "Released to revenue"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
            ],
            options={
                "ordering": ["invoice", "recognition_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="DeferredIncomeRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Deferred income moved to revenue, in kobo."
                    ),
                ),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["entity", "journal_id"],
            },
        ),
        migrations.CreateModel(
            name="DeferredIncomeUnwind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Deferred income taken back, in kobo."
                    ),
                ),
                ("restored", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["entry", "id"],
            },
        ),
        migrations.CreateModel(
            name="DepositForfeiture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Deposits forfeited, in kobo."
                    ),
                ),
            ],
            options={
                "ordering": ["entity", "id"],
            },
        ),
        migrations.CreateModel(
            name="DoubtfulDebtProvision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "as_of",
                    models.DateField(
                        help_text="The date balances are aged to and the journals are dated."
                    ),
                ),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                (
                    "required_total",
                    vs_finance.money.MoneyField(
                        help_text="Allowance the policy requires across branches, in kobo."
                    ),
                ),
                (
                    "movement_total",
                    vs_finance.money.MoneyField(
                        help_text="Absolute change the run makes to the allowance across branches, in kobo."
                    ),
                ),
                (
                    "policy_snapshot",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="The provision bands the figures were worked out with.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DoubtfulDebtProvisionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "required",
                    vs_finance.money.MoneyField(
                        help_text="Allowance required for this branch, in kobo."
                    ),
                ),
                (
                    "current",
                    vs_finance.money.MoneyField(
                        help_text="Allowance already held for this branch, in kobo."
                    ),
                ),
                (
                    "movement",
                    vs_finance.money.MoneyField(
                        help_text="Change posted to the allowance, in kobo."
                    ),
                ),
                (
                    "bands",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Overdue balance and required allowance per band, in kobo.",
                    ),
                ),
            ],
            options={
                "ordering": ["provision", "branch_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="FinanceReceivablesPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "revenue_recognition",
                    models.CharField(
                        choices=[
                            (
                                "SPREAD_MONTHLY",
                                "Spread evenly over each month of the service period",
                            ),
                            (
                                "AT_PERIOD_START",
                                "All in the month the service period starts",
                            ),
                        ],
                        default="SPREAD_MONTHLY",
                        max_length=16,
                    ),
                ),
                (
                    "provision_bands",
                    models.JSONField(
                        blank=True,
                        default=vs_finance.models.accruals.default_provision_bands,
                    ),
                ),
                ("deposits_offset_unpaid_bills", models.BooleanField(default=False)),
                (
                    "unclaimed_deposit_years",
                    models.PositiveSmallIntegerField(
                        default=6,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WriteOffRecovery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Debt reinstated and paid, in kobo."
                    ),
                ),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["write_off", "id"],
            },
        ),
        migrations.AddField(
            model_name="feeitem",
            name="kind",
            field=models.CharField(
                choices=[("CHARGE", "Charge"), ("DEPOSIT", "Refundable deposit")],
                default="CHARGE",
                help_text="CHARGE is income; DEPOSIT is a refundable deposit held for the customer.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="beneficiary",
            field=models.ForeignKey(
                blank=True,
                help_text="The customer this bill pays for, when the customer billed is a payer such as a sponsor or an employer.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices_paid_by_others",
                to="vs_finance.customer",
            ),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="kind",
            field=models.CharField(
                choices=[("CHARGE", "Charge"), ("DEPOSIT", "Refundable deposit")],
                default="CHARGE",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="service_end",
            field=models.DateField(
                blank=True,
                help_text="Last day of the service this line bills for.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="service_start",
            field=models.DateField(
                blank=True,
                help_text="First day of the service this line bills for.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="writeoffrequest",
            name="allowance_used",
            field=vs_finance.money.MoneyField(
                help_text="Part of the write-off charged to the allowance for doubtful debts, in kobo."
            ),
        ),
        migrations.AddField(
            model_name="writeoffrequest",
            name="recovered_amount",
            field=vs_finance.money.MoneyField(
                help_text="Kobo of this write-off since paid and reinstated, in kobo."
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="ifrs_line",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PPE", "Property, plant and equipment"),
                    ("INTANGIBLES", "Intangible assets"),
                    ("INVESTMENTS", "Investments"),
                    ("INVENTORIES", "Inventories"),
                    ("TRADE_RECEIVABLES", "Trade and other receivables"),
                    ("CURRENT_TAX_ASSET", "Current tax assets"),
                    ("CASH", "Cash and cash equivalents"),
                    ("OTHER_CURRENT_ASSETS", "Other current assets"),
                    ("SHARE_CAPITAL", "Share capital"),
                    ("RETAINED_EARNINGS", "Retained earnings"),
                    ("OTHER_RESERVES", "Other reserves"),
                    ("LONG_TERM_BORROWINGS", "Long-term borrowings"),
                    ("TRADE_PAYABLES", "Trade and other payables"),
                    ("DEFERRED_INCOME", "Deferred income"),
                    ("CURRENT_TAX_PAYABLE", "Current tax payable"),
                    ("EMPLOYEE_PAYABLES", "Employee benefit obligations"),
                    ("SHORT_TERM_BORROWINGS", "Short-term borrowings"),
                    ("REVENUE", "Revenue"),
                    ("COST_OF_SALES", "Cost of sales"),
                    ("OTHER_INCOME", "Other income"),
                    ("DISTRIBUTION_COSTS", "Distribution costs"),
                    ("ADMIN_EXPENSES", "Administrative expenses"),
                    ("OTHER_EXPENSES", "Other expenses"),
                    ("FINANCE_COSTS", "Finance costs"),
                    ("TAX_EXPENSE", "Income tax expense"),
                ],
                default="",
                help_text="IFRS-for-SMEs statutory presentation line; blank falls back to the type default.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="documentsequence",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("JN", "Journal Entry"),
                    ("IV", "Sales / AR Invoice"),
                    ("RC", "Receipt"),
                    ("PY", "Payment"),
                    ("CN", "Credit Note"),
                    ("DN", "Debit Note"),
                    ("RF", "Customer Refund"),
                    ("PP", "Installment Payment Plan"),
                    ("CC", "Concession / Discount / Waiver"),
                    ("WO", "Bad-debt Write-off"),
                    ("DU", "Dunning / Payment Reminder"),
                    ("PR", "Purchase Requisition"),
                    ("RQ", "Request for Quotation"),
                    ("QT", "Vendor Quotation"),
                    ("PO", "Purchase Order"),
                    ("GN", "Goods Received Note"),
                    ("VI", "Vendor Invoice"),
                    ("VP", "Vendor Payment"),
                    ("EX", "Expense Claim"),
                    ("PC", "Petty Cash Voucher"),
                    ("PL", "Payroll Run"),
                    ("FA", "Fixed Asset"),
                    ("TX", "Tax Filing / Remittance"),
                    ("BG", "Budget"),
                    ("BT", "Bank Transaction"),
                    ("BX", "Transfer Between Own Accounts"),
                    ("CT", "Customer Credit Transfer"),
                    ("DP", "Doubtful-debt Provision"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="financeaccountmapping",
            name="key",
            field=models.CharField(
                choices=[
                    ("CASH_BANK", "Cash and bank"),
                    ("ACCOUNTS_RECEIVABLE", "Accounts receivable"),
                    ("ACCOUNTS_PAYABLE", "Accounts payable"),
                    ("CUSTOMER_CREDIT", "Customer credit"),
                    ("VENDOR_ADVANCE", "Vendor advances"),
                    ("GRIR_CLEARING", "GR/IR clearing"),
                    ("OUTPUT_VAT", "Output VAT"),
                    ("WHT_PAYABLE", "WHT payable"),
                    ("RETAINED_EARNINGS", "Retained earnings"),
                    ("BAD_DEBT_EXPENSE", "Bad debt expense"),
                    ("BANK_CHARGES", "Bank charges"),
                    ("INVENTORY_ASSET", "Inventory asset"),
                    ("INVENTORY_ADJUSTMENT", "Inventory adjustment"),
                    ("PURCHASE_PRICE_VARIANCE", "Purchase price variance"),
                    ("DEFERRED_INCOME", "Deferred income"),
                    ("DEPOSITS_HELD", "Customer deposits held"),
                    ("DOUBTFUL_DEBT_ALLOWANCE", "Allowance for doubtful debts"),
                    ("BAD_DEBT_RECOVERED", "Bad debts recovered"),
                    ("FORFEITED_DEPOSIT_INCOME", "Forfeited deposits income"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="financeauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("JOURNAL_POSTED", "Journal posted"),
                    ("JOURNAL_REVERSED", "Journal reversed"),
                    ("JOURNAL_POST_REJECTED", "Journal posting rejected"),
                    ("INVOICE_POSTED", "Invoice posted"),
                    ("INVOICE_CANCELLED", "Invoice cancelled"),
                    ("INVOICE_REVERSED", "Invoice reversed"),
                    ("INVOICE_WRITTEN_OFF", "Invoice written off (bad debt)"),
                    ("INVOICE_PAY_LINK_REVOKED", "Invoice pay link revoked"),
                    ("PAYMENT_POSTED", "Payment posted"),
                    ("PAYMENT_ALLOCATED", "Payment allocated"),
                    ("PAYMENT_REVERSED", "Payment reversed"),
                    ("CREDIT_NOTE_POSTED", "Credit note posted"),
                    ("CREDIT_NOTE_ALLOCATED", "Credit note allocated"),
                    ("DEBIT_NOTE_POSTED", "Debit note posted"),
                    ("CREDIT_NOTE_REVERSED", "Credit/debit note reversed"),
                    ("REFUND_POSTED", "Customer refund posted"),
                    ("REFUND_REVERSED", "Customer refund reversed"),
                    ("PAYMENT_PLAN_ACTIVATED", "Installment plan activated"),
                    ("PAYMENT_PLAN_COMPLETED", "Installment plan completed"),
                    ("PAYMENT_PLAN_CANCELLED", "Installment plan cancelled"),
                    ("CONCESSION_POSTED", "Concession / discount / waiver posted"),
                    ("CONCESSION_REVERSED", "Concession / discount / waiver reversed"),
                    ("CUSTOMER_UPDATED", "Customer updated"),
                    ("CUSTOMER_DEACTIVATED", "Customer deactivated"),
                    ("CUSTOMER_REACTIVATED", "Customer reactivated"),
                    ("CUSTOMER_OPENING_POSTED", "Customer opening invoice posted"),
                    ("CREDIT_TRANSFER_POSTED", "Customer credit transfer posted"),
                    ("CREDIT_TRANSFER_REVERSED", "Customer credit transfer reversed"),
                    ("DEFERRED_INCOME_RELEASED", "Deferred income released"),
                    ("DEFERRED_RELEASE_REVERSED", "Deferred income release reversed"),
                    ("PROVISION_POSTED", "Doubtful-debt provision posted"),
                    ("WRITE_OFF_RECOVERED", "Written-off debt recovered"),
                    ("DEPOSIT_RELEASED", "Customer deposit released"),
                    ("DEPOSITS_FORFEITED", "Unclaimed deposits forfeited"),
                    ("RECEIPT_PARKED_AS_CREDIT", "Receipt parked as customer credit"),
                    ("DUNNING_RUN_GENERATED", "Dunning run generated"),
                    ("DUNNING_NOTICE_SENT", "Dunning notice marked sent"),
                    ("DUNNING_NOTICE_CANCELLED", "Dunning notice cancelled"),
                    ("PERIOD_CLOSED", "Period closed"),
                    ("PERIOD_REOPENED", "Period re-opened"),
                    ("ACCOUNT_CREATED", "Account created"),
                    ("ACCOUNT_UPDATED", "Account updated"),
                    ("FINANCE_SETTINGS_UPDATED", "Finance settings updated"),
                    (
                        "FIN_DOCUMENT_SETTINGS_UPDATED",
                        "Finance document settings updated",
                    ),
                    ("FIN_BANK_SETTINGS_UPDATED", "Finance banking settings updated"),
                    (
                        "FIN_CALENDAR_SETTINGS_UPDATED",
                        "Finance calendar settings updated",
                    ),
                    (
                        "FIN_RECEIVABLES_SETTINGS_UPDATED",
                        "Finance receivables settings updated",
                    ),
                    ("PROCUREMENT_SETTINGS_UPDATED", "Procurement settings updated"),
                    ("REQUISITION_APPROVED", "Requisition approved"),
                    (
                        "SPEND_APPROVAL_OVERRIDDEN",
                        "Spend approval released by override (no review)",
                    ),
                    ("RFQ_ISSUED", "Request for quotation issued"),
                    ("RFQ_CANCELLED", "Request for quotation cancelled"),
                    ("RFQ_CLOSED", "Request for quotation closed without award"),
                    ("QUOTATION_SUBMITTED", "Vendor quotation submitted"),
                    ("QUOTATION_AWARDED", "Vendor quotation awarded → PO"),
                    ("QUOTATION_REJECTED", "Vendor quotation rejected"),
                    ("VENDOR_CONTRACT_ACTIVATED", "Vendor contract activated"),
                    ("VENDOR_CONTRACT_RENEWED", "Vendor contract renewed"),
                    ("VENDOR_CONTRACT_TERMINATED", "Vendor contract terminated"),
                    ("CONTRACT_MILESTONE_COMPLETED", "Contract milestone completed"),
                    ("PURCHASE_ORDER_APPROVED", "Purchase order approved"),
                    ("PURCHASE_ORDER_CANCELLED", "Purchase order cancelled"),
                    ("PO_EMAIL_SCHEDULED", "Purchase order email scheduled"),
                    ("PO_EMAIL_QUEUED", "Purchase order email queued"),
                    ("PO_EMAIL_SENT", "Purchase order email sent"),
                    ("PO_EMAIL_FAILED", "Purchase order email failed"),
                    ("PO_EMAIL_CANCELLED", "Purchase order email cancelled"),
                    ("DOC_EMAIL_QUEUED", "Customer document email queued"),
                    ("DOC_EMAIL_SENT", "Customer document email sent"),
                    ("DOC_EMAIL_FAILED", "Customer document email failed"),
                    ("GRN_POSTED", "Goods receipt posted"),
                    ("GRN_POST_REJECTED", "Goods receipt posting rejected"),
                    ("VENDOR_INVOICE_MATCHED", "Vendor invoice matched"),
                    ("VENDOR_INVOICE_APPROVED", "Vendor invoice approved (workflow)"),
                    ("VENDOR_INVOICE_POSTED", "Vendor invoice posted"),
                    ("VENDOR_INVOICE_POST_REJECTED", "Vendor invoice posting rejected"),
                    ("VENDOR_PAYMENT_POSTED", "Vendor payment posted"),
                    ("VENDOR_PAYMENT_POST_REJECTED", "Vendor payment posting rejected"),
                    ("VENDOR_PAYMENT_ALLOCATED", "Vendor payment allocated"),
                    ("VENDOR_INVOICE_VOIDED", "Vendor invoice voided"),
                    (
                        "VENDOR_CREDIT_NOTE_APPROVED",
                        "Vendor credit note approved (workflow)",
                    ),
                    ("VENDOR_CREDIT_NOTE_POSTED", "Vendor credit note posted"),
                    ("VENDOR_CREDIT_NOTE_ALLOCATED", "Vendor credit note allocated"),
                    ("VENDOR_CREDIT_NOTE_VOIDED", "Vendor credit note voided"),
                    ("GOODS_RETURNED", "Goods returned to vendor"),
                    ("VENDOR_OPENING_BILL_POSTED", "Vendor opening bill posted"),
                    ("STOCK_RECEIVED", "Stock received (perpetual inventory)"),
                    ("STOCK_ISSUED", "Stock issued"),
                    ("STOCK_ISSUE_REJECTED", "Stock issue rejected"),
                    ("STOCK_ADJUSTED", "Stock adjusted"),
                    ("STOCK_ADJUST_REJECTED", "Stock adjustment rejected"),
                    ("BANK_STATEMENT_CORRECTED", "Bank statement corrected"),
                    ("BANK_RECONCILED", "Bank statement reconciled"),
                    ("BANK_CHARGE_POSTED", "Bank charge posted"),
                    ("BANK_TRANSACTION_POSTED", "Bank transaction posted"),
                    ("BANK_TRANSACTION_VOIDED", "Bank transaction voided"),
                    ("BANK_TRANSFER_POSTED", "Transfer between own accounts posted"),
                    ("BANK_TRANSFER_VOIDED", "Transfer between own accounts voided"),
                    ("EXPENSE_CLAIM_POSTED", "Expense claim posted"),
                    ("EXPENSE_CLAIM_POST_REJECTED", "Expense claim posting rejected"),
                    ("EXPENSE_CLAIM_SETTLED", "Expense claim settled"),
                    ("EXPENSE_CLAIM_VOIDED", "Expense claim voided"),
                    (
                        "PETTY_CASH_ESTABLISHED",
                        "Petty cash fund established / topped up",
                    ),
                    ("PETTY_CASH_VOUCHER_POSTED", "Petty cash voucher posted"),
                    ("PETTY_CASH_VOUCHER_REJECTED", "Petty cash voucher rejected"),
                    ("PETTY_CASH_VOUCHER_VOIDED", "Petty cash voucher voided"),
                    ("PETTY_CASH_REPLENISHED", "Petty cash fund replenished"),
                    ("PAYROLL_POSTED", "Payroll run posted"),
                    ("PAYROLL_POST_REJECTED", "Payroll run posting rejected"),
                    ("PAYROLL_PAID", "Payroll run disbursed"),
                    ("PAYROLL_CANCELLED", "Payroll run cancelled / voided"),
                    ("BUDGET_APPROVED", "Budget approved"),
                    ("BUDGET_DELETED", "Budget deleted"),
                    ("ASSET_ACQUIRED", "Fixed asset acquired"),
                    ("DEPRECIATION_POSTED", "Depreciation posted"),
                    ("ASSET_DISPOSED", "Fixed asset disposed"),
                    ("PERIOD_LOCKED", "Period locked"),
                    ("FISCAL_YEAR_OPENED", "Fiscal year opened"),
                    ("FISCAL_YEAR_CLOSED", "Fiscal year closed"),
                    ("FISCAL_YEAR_REOPENED", "Fiscal year re-opened"),
                    (
                        "FISCAL_CALENDAR_WARNED",
                        "Finance staff warned the fiscal calendar is running out",
                    ),
                    ("TAX_FILING_PREPARED", "Tax filing prepared"),
                    ("TAX_FILING_FILED", "Tax filing submitted to authority"),
                    ("TAX_FILING_UNFILED", "Tax filing un-filed (reverted to draft)"),
                    ("TAX_FILING_PAID", "Tax filing paid / remitted"),
                    ("TAX_FILING_REJECTED", "Tax filing action rejected"),
                    ("TAX_REMITTANCE_REVERSED", "Tax remittance reversed"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("service_end__isnull", True), ("service_start__isnull", True)
                    ),
                    models.Q(
                        ("service_end__gte", models.F("service_start")),
                        ("service_end__isnull", False),
                        ("service_start__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_finance_invoiceline_service_period",
            ),
        ),
        migrations.AddField(
            model_name="customerdeposit",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_deposits",
                to="vs_tenants.branch",
            ),
        ),
        migrations.AddField(
            model_name="customerdeposit",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deposits",
                to="vs_finance.customer",
            ),
        ),
        migrations.AddField(
            model_name="customerdeposit",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_deposits",
                to="vs_finance.ledgerentity",
            ),
        ),
        migrations.AddField(
            model_name="customerdeposit",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_deposits",
                to="vs_finance.invoice",
            ),
        ),
        migrations.AddField(
            model_name="customerdeposit",
            name="line",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_deposit",
                to="vs_finance.invoiceline",
            ),
        ),
        migrations.AddField(
            model_name="customerdeposit",
            name="release_note",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="released_deposits",
                to="vs_finance.creditnote",
            ),
        ),
        migrations.AddField(
            model_name="deferredincomeentry",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deferred_income_entries",
                to="vs_tenants.branch",
            ),
        ),
        migrations.AddField(
            model_name="deferredincomeentry",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deferred_income_entries",
                to="vs_finance.costcenter",
            ),
        ),
        migrations.AddField(
            model_name="deferredincomeentry",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deferred_income_entries",
                to="vs_finance.ledgerentity",
            ),
        ),
        migrations.AddField(
            model_name="deferredincomeentry",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deferred_income_entries",
                to="vs_finance.invoice",
            ),
        ),
        migrations.AddField(
            model_name="deferredincomeentry",
            name="line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deferred_income_entries",
                to="vs_finance.invoiceline",
            ),
        ),
        migrations.AddField(
            model_name="deferredincomeentry",
            name="revenue_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deferred_income_entries",
                to="vs_finance.account",
            ),
        ),
        migrations.AddField(
            model_name="deferredincomeentry",
            name="void_journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deferred_income_voids",
                to="vs_finance.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="deferredincomerelease",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deferred_income_releases",
                to="vs_tenants.branch",
            ),
        ),
        migrations.AddField(
            model_name="deferredincomerelease",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deferred_income_releases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deferredincomerelease",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deferred_income_releases",
                to="vs_finance.ledgerentity",
            ),
        ),
        migrations.AddField(
            model_name="deferredincomerelease",
            name="journal",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deferred_income_release",
                to="vs_finance.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="deferredincomeentry",
            name="release",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entries",
                to="vs_finance.deferredincomerelease",
            ),
        ),
        migrations.AddField(
            model_name="deferredincomeunwind",
            name="adjustment_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deferred_income_unwinds",
                to="vs_finance.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="deferredincomeunwind",
            name="entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="unwinds",
                to="vs_finance.deferredincomeentry",
            ),
        ),
        migrations.AddField(
            model_name="depositforfeiture",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deposit_forfeitures",
                to="vs_tenants.branch",
            ),
        ),
        migrations.AddField(
            model_name="depositforfeiture",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deposit_forfeitures",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="depositforfeiture",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deposit_forfeitures",
                to="vs_finance.ledgerentity",
            ),
        ),
        migrations.AddField(
            model_name="depositforfeiture",
            name="journal",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deposit_forfeiture",
                to="vs_finance.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="customerdeposit",
            name="forfeiture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deposits",
                to="vs_finance.depositforfeiture",
            ),
        ),
        migrations.AddField(
            model_name="doubtfuldebtprovision",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                to="vs_tenants.branch",
            ),
        ),
        migrations.AddField(
            model_name="doubtfuldebtprovision",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="doubtfuldebtprovision",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                to="vs_finance.ledgerentity",
            ),
        ),
        migrations.AddField(
            model_name="doubtfuldebtprovisionline",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="doubtful_debt_provision_lines",
                to="vs_tenants.branch",
            ),
        ),
        migrations.AddField(
            model_name="doubtfuldebtprovisionline",
            name="journal",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="doubtful_debt_provision_line",
                to="vs_finance.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="doubtfuldebtprovisionline",
            name="provision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="vs_finance.doubtfuldebtprovision",
            ),
        ),
        migrations.AddField(
            model_name="financereceivablespolicy",
            name="entity",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="finance_receivables_policy",
                to="vs_finance.ledgerentity",
            ),
        ),
        migrations.AddField(
            model_name="financereceivablespolicy",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="finance_receivables_policy_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="writeoffrecovery",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="write_off_recoveries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="writeoffrecovery",
            name="journal",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="write_off_recovery",
                to="vs_finance.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="writeoffrecovery",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="write_off_recoveries",
                to="vs_finance.payment",
            ),
        ),
        migrations.AddField(
            model_name="writeoffrecovery",
            name="write_off",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recoveries",
                to="vs_finance.writeoffrequest",
            ),
        ),
        migrations.AddIndex(
            model_name="deferredincomerelease",
            index=models.Index(
                fields=["entity", "reversed_at"], name="vs_finance__entity__52986c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deferredincomeentry",
            index=models.Index(
                fields=["entity", "status", "recognition_date"],
                name="vs_finance__entity__f331db_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deferredincomeentry",
            index=models.Index(
                fields=["invoice", "status"], name="vs_finance__invoice_0a6a8f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="deferredincomeentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("unwound_amount__gte", 0),
                    ("amount__gte", models.F("unwound_amount")),
                ),
                name="ck_finance_deferred_unwound_within_amount",
            ),
        ),
        migrations.AddIndex(
            model_name="deferredincomeunwind",
            index=models.Index(
                fields=["adjustment_entry", "restored"],
                name="vs_finance__adjustm_c0d01c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customerdeposit",
            index=models.Index(
                fields=["entity", "status"], name="vs_finance__entity__c81430_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerdeposit",
            index=models.Index(
                fields=["customer", "status"], name="vs_finance__custome_cdda54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doubtfuldebtprovision",
            index=models.Index(
                fields=["entity", "status"], name="vs_finance__entity__8f26c4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="doubtfuldebtprovision",
            constraint=models.UniqueConstraint(
                fields=("entity", "document_number"),
                name="uniq_vs_finance_doubtfuldebtprovision_entity_docnum",
            ),
        ),
        migrations.AddIndex(
            model_name="writeoffrecovery",
            index=models.Index(
                fields=["write_off", "reversed_at"],
                name="vs_finance__write_o_f705e2_idx",
            ),
        ),
    ]
