"""Statutory payroll: national tax tables, payroll policy, salary history, line items, payslips.

Schema only; the national data and the statutory accounts of existing books are
written by 0049.
"""
# Generated by Django 5.2.10 on 2026-10-01 11:44

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0047_held_custody_accounts"),
        ("vs_tenants", "0011_platform_tenant_lagos_branch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeDeduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Withheld each payroll month, in kobo."
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "total_limit",
                    vs_finance.money.MoneyField(
                        default=None,
                        help_text="Stop once this much is withheld.",
                        null=True,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["salary", "deduction_type__code", "id"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeSalaryVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField()),
                (
                    "gross_amount",
                    vs_finance.money.MoneyField(
                        help_text="Amount in minor units (kobo); integer, never float."
                    ),
                ),
                (
                    "paye_amount",
                    vs_finance.money.MoneyField(
                        help_text="Amount in minor units (kobo); integer, never float."
                    ),
                ),
                (
                    "pension_amount",
                    vs_finance.money.MoneyField(
                        help_text="Amount in minor units (kobo); integer, never float."
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "ordering": ["salary", "effective_from", "id"],
            },
        ),
        migrations.CreateModel(
            name="FinancePayrollSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paye_method",
                    models.CharField(
                        choices=[
                            ("COMPUTED", "Computed from the national tax table"),
                            ("SUPPLIED", "Supplied by the tenant"),
                        ],
                        default="COMPUTED",
                        max_length=10,
                    ),
                ),
                ("tax_country", models.CharField(default="NG", max_length=2)),
                ("employee_pension_enabled", models.BooleanField(default=True)),
                (
                    "employee_pension_rate_bps",
                    models.PositiveIntegerField(
                        default=800,
                        validators=[django.core.validators.MaxValueValidator(10000)],
                    ),
                ),
                ("employer_pension_enabled", models.BooleanField(default=True)),
                (
                    "employer_pension_rate_bps",
                    models.PositiveIntegerField(
                        default=1000,
                        validators=[django.core.validators.MaxValueValidator(10000)],
                    ),
                ),
                ("nhf_enabled", models.BooleanField(default=True)),
                (
                    "nhf_rate_bps",
                    models.PositiveIntegerField(
                        default=250,
                        validators=[django.core.validators.MaxValueValidator(10000)],
                    ),
                ),
                ("nsitf_enabled", models.BooleanField(default=True)),
                (
                    "nsitf_rate_bps",
                    models.PositiveIntegerField(
                        default=100,
                        validators=[django.core.validators.MaxValueValidator(10000)],
                    ),
                ),
                ("itf_enabled", models.BooleanField(default=True)),
                (
                    "itf_rate_bps",
                    models.PositiveIntegerField(
                        default=100,
                        validators=[django.core.validators.MaxValueValidator(10000)],
                    ),
                ),
                ("payslip_in_app", models.BooleanField(default=True)),
                ("payslip_email", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PayeTaxBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveSmallIntegerField(default=0)),
                (
                    "lower",
                    vs_finance.money.MoneyField(
                        help_text="Annual income where the band starts, in kobo."
                    ),
                ),
                (
                    "upper",
                    vs_finance.money.MoneyField(
                        default=None,
                        help_text="Where it ends; empty on the top band.",
                        null=True,
                    ),
                ),
                (
                    "rate_bps",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(10000)]
                    ),
                ),
            ],
            options={
                "ordering": ["table", "sequence", "lower"],
            },
        ),
        migrations.CreateModel(
            name="PayeTaxRelief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveSmallIntegerField(default=0)),
                ("code", models.CharField(max_length=24)),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CONTRIBUTION", "Contribution actually made"),
                            (
                                "PERCENT_CAPPED",
                                "Percentage of a basis, floored and capped",
                            ),
                            ("FIXED", "Fixed amount a year"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("PENSION", "Employee pension contributions"),
                            ("NHF", "National Housing Fund contributions"),
                            ("ANNUAL_RENT", "Annual rent the employee pays"),
                            ("ANNUAL_GROSS", "Annual gross income"),
                        ],
                        default="NONE",
                        max_length=16,
                    ),
                ),
                (
                    "rate_bps",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(10000)],
                    ),
                ),
                (
                    "cap_amount",
                    vs_finance.money.MoneyField(
                        default=None,
                        help_text="Annual cap, in kobo; empty for none.",
                        null=True,
                    ),
                ),
                (
                    "floor_amount",
                    vs_finance.money.MoneyField(help_text="Annual floor, in kobo."),
                ),
            ],
            options={
                "ordering": ["table", "sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="PayeTaxTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("country", models.CharField(default="NG", max_length=2)),
                ("tax_year", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=160)),
                (
                    "source_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "minimum_tax_rate_bps",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(10000)],
                    ),
                ),
                (
                    "exempt_income_threshold",
                    vs_finance.money.MoneyField(
                        help_text="Annual gross at or below which no PAYE is charged, in kobo."
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["country", "-tax_year"],
            },
        ),
        migrations.CreateModel(
            name="PayrollDeductionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=24)),
                ("name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["entity", "code"],
            },
        ),
        migrations.CreateModel(
            name="PayrollLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("DEDUCTION", "Employee deduction"),
                            ("EMPLOYER", "Employer contribution"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("PAYE", "PAYE"),
                            ("PENSION", "Employee pension"),
                            ("NHF", "National Housing Fund"),
                            ("VOLUNTARY", "Voluntary deduction"),
                            ("EMPLOYER_PENSION", "Employer pension"),
                            ("NSITF", "NSITF employee compensation"),
                            ("ITF", "ITF training levy"),
                        ],
                        max_length=16,
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=120)),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Amount in minor units (kobo); integer, never float."
                    ),
                ),
                (
                    "basis_amount",
                    vs_finance.money.MoneyField(
                        help_text="Amount in minor units (kobo); integer, never float."
                    ),
                ),
                ("rate_bps", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["line", "kind", "id"],
            },
        ),
        migrations.CreateModel(
            name="PayrollTaxJurisdiction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("country", models.CharField(default="NG", max_length=2)),
                ("code", models.CharField(max_length=8)),
                ("name", models.CharField(max_length=80)),
                ("authority_name", models.CharField(max_length=160)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["country", "name"],
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pay_date", models.DateField()),
                (
                    "period_label",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email_status",
                    models.CharField(
                        choices=[
                            ("NOT_REQUESTED", "Not emailed (switched off)"),
                            ("PENDING", "Waiting to be sent"),
                            ("QUEUED", "Handed to notifications"),
                            ("NO_ADDRESS", "No email address on file"),
                            ("FAILED", "Could not be queued"),
                        ],
                        default="NOT_REQUESTED",
                        max_length=16,
                    ),
                ),
                (
                    "email_attachment",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("notification_ids", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["-pay_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PensionFundAdministrator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=12, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="salarycomponent",
            options={"ordering": ["structure", "effective_from", "sequence", "id"]},
        ),
        migrations.RemoveIndex(
            model_name="salarycomponent",
            name="vs_finance__structu_c1e564_idx",
        ),
        migrations.AddField(
            model_name="employeesalary",
            name="annual_rent",
            field=vs_finance.money.MoneyField(
                help_text="Annual rent the person pays, for rent relief, in kobo."
            ),
        ),
        migrations.AddField(
            model_name="employeesalary",
            name="paye_override",
            field=vs_finance.money.MoneyField(
                default=None,
                help_text="Monthly PAYE supplied from outside, used instead of the computed figure.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employeesalary",
            name="paye_override_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="employeesalary",
            name="pension_pin",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Retirement savings account PIN.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="employeesalary",
            name="tax_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Tax identification number.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="employer_contributions_amount",
            field=vs_finance.money.MoneyField(
                help_text="Employer pension, NSITF and ITF accrued for this person, in kobo."
            ),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="other_deductions_amount",
            field=vs_finance.money.MoneyField(
                help_text="NHF and voluntary deductions withheld, in kobo."
            ),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="paye_source",
            field=models.CharField(
                choices=[
                    ("COMPUTED", "Computed from the tax table"),
                    ("OVERRIDE", "Overridden on the employee's salary"),
                    ("SUPPLIED", "Supplied by the salary structure or roster"),
                    ("MANUAL", "Typed on a hand-raised run"),
                ],
                default="MANUAL",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="pension_pin",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="salary",
            field=models.ForeignKey(
                blank=True,
                help_text="The roster row this line pays; empty on a hand-typed line.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_lines",
                to="vs_finance.employeesalary",
            ),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="tax_basis",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The inputs and working that produced the PAYE figure.",
            ),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="tax_id",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="taxable_pay",
            field=vs_finance.money.MoneyField(
                help_text="This month's income for PAYE, in kobo."
            ),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="employer_contributions_total",
            field=vs_finance.money.MoneyField(
                help_text="Employer pension, NSITF and ITF the run accrues on top of gross, in kobo."
            ),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="other_deductions_total",
            field=vs_finance.money.MoneyField(
                help_text="NHF and voluntary deductions withheld across the run, in kobo."
            ),
        ),
        migrations.AddField(
            model_name="payrollrunbranch",
            name="employer_contributions_total",
            field=vs_finance.money.MoneyField(
                help_text="Amount in minor units (kobo); integer, never float."
            ),
        ),
        migrations.AddField(
            model_name="payrollrunbranch",
            name="other_deductions_total",
            field=vs_finance.money.MoneyField(
                help_text="Amount in minor units (kobo); integer, never float."
            ),
        ),
        migrations.AddField(
            model_name="salarycomponent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="finance_salary_components",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salarycomponent",
            name="effective_from",
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
        migrations.AddField(
            model_name="salarycomponent",
            name="effective_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salarycomponent",
            name="is_pensionable",
            field=models.BooleanField(
                default=False,
                help_text="Earnings flagged pensionable form the base the pension rates apply to.",
            ),
        ),
        migrations.AddField(
            model_name="salarycomponent",
            name="is_taxable",
            field=models.BooleanField(
                default=True,
                help_text="An earning that is not taxable is left out of the income PAYE is charged on.",
            ),
        ),
        migrations.AlterField(
            model_name="financeauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("JOURNAL_POSTED", "Journal posted"),
                    ("JOURNAL_REVERSED", "Journal reversed"),
                    ("JOURNAL_POST_REJECTED", "Journal posting rejected"),
                    ("INVOICE_POSTED", "Invoice posted"),
                    ("INVOICE_CANCELLED", "Invoice cancelled"),
                    ("INVOICE_REVERSED", "Invoice reversed"),
                    ("INVOICE_WRITTEN_OFF", "Invoice written off (bad debt)"),
                    ("INVOICE_PAY_LINK_REVOKED", "Invoice pay link revoked"),
                    ("PAYMENT_POSTED", "Payment posted"),
                    ("PAYMENT_ALLOCATED", "Payment allocated"),
                    ("PAYMENT_REVERSED", "Payment reversed"),
                    ("CREDIT_NOTE_POSTED", "Credit note posted"),
                    ("CREDIT_NOTE_ALLOCATED", "Credit note allocated"),
                    ("DEBIT_NOTE_POSTED", "Debit note posted"),
                    ("CREDIT_NOTE_REVERSED", "Credit/debit note reversed"),
                    ("REFUND_POSTED", "Customer refund posted"),
                    ("REFUND_REVERSED", "Customer refund reversed"),
                    ("PAYMENT_PLAN_ACTIVATED", "Installment plan activated"),
                    ("PAYMENT_PLAN_COMPLETED", "Installment plan completed"),
                    ("PAYMENT_PLAN_CANCELLED", "Installment plan cancelled"),
                    ("CONCESSION_POSTED", "Concession / discount / waiver posted"),
                    ("CONCESSION_REVERSED", "Concession / discount / waiver reversed"),
                    ("CUSTOMER_UPDATED", "Customer updated"),
                    ("CUSTOMER_DEACTIVATED", "Customer deactivated"),
                    ("CUSTOMER_REACTIVATED", "Customer reactivated"),
                    ("CUSTOMER_OPENING_POSTED", "Customer opening invoice posted"),
                    ("CREDIT_TRANSFER_POSTED", "Customer credit transfer posted"),
                    ("CREDIT_TRANSFER_REVERSED", "Customer credit transfer reversed"),
                    ("DEFERRED_INCOME_RELEASED", "Deferred income released"),
                    ("DEFERRED_RELEASE_REVERSED", "Deferred income release reversed"),
                    ("PROVISION_POSTED", "Doubtful-debt provision posted"),
                    ("WRITE_OFF_RECOVERED", "Written-off debt recovered"),
                    ("DEPOSIT_RELEASED", "Customer deposit released"),
                    ("DEPOSITS_FORFEITED", "Unclaimed deposits forfeited"),
                    ("RECEIPT_PARKED_AS_CREDIT", "Receipt parked as customer credit"),
                    ("DUNNING_RUN_GENERATED", "Dunning run generated"),
                    ("DUNNING_NOTICE_SENT", "Dunning notice marked sent"),
                    ("DUNNING_NOTICE_CANCELLED", "Dunning notice cancelled"),
                    ("PERIOD_CLOSED", "Period closed"),
                    ("PERIOD_REOPENED", "Period re-opened"),
                    ("ACCOUNT_CREATED", "Account created"),
                    ("ACCOUNT_UPDATED", "Account updated"),
                    ("FINANCE_SETTINGS_UPDATED", "Finance settings updated"),
                    (
                        "FIN_DOCUMENT_SETTINGS_UPDATED",
                        "Finance document settings updated",
                    ),
                    ("FIN_BANK_SETTINGS_UPDATED", "Finance banking settings updated"),
                    (
                        "FIN_CALENDAR_SETTINGS_UPDATED",
                        "Finance calendar settings updated",
                    ),
                    (
                        "FIN_RECEIVABLES_SETTINGS_UPDATED",
                        "Finance receivables settings updated",
                    ),
                    ("PROCUREMENT_SETTINGS_UPDATED", "Procurement settings updated"),
                    ("REQUISITION_APPROVED", "Requisition approved"),
                    (
                        "SPEND_APPROVAL_OVERRIDDEN",
                        "Spend approval released by override (no review)",
                    ),
                    ("RFQ_ISSUED", "Request for quotation issued"),
                    ("RFQ_CANCELLED", "Request for quotation cancelled"),
                    ("RFQ_CLOSED", "Request for quotation closed without award"),
                    ("QUOTATION_SUBMITTED", "Vendor quotation submitted"),
                    ("QUOTATION_AWARDED", "Vendor quotation awarded → PO"),
                    ("QUOTATION_REJECTED", "Vendor quotation rejected"),
                    ("VENDOR_CONTRACT_ACTIVATED", "Vendor contract activated"),
                    ("VENDOR_CONTRACT_RENEWED", "Vendor contract renewed"),
                    ("VENDOR_CONTRACT_TERMINATED", "Vendor contract terminated"),
                    ("CONTRACT_MILESTONE_COMPLETED", "Contract milestone completed"),
                    ("PURCHASE_ORDER_APPROVED", "Purchase order approved"),
                    ("PURCHASE_ORDER_CANCELLED", "Purchase order cancelled"),
                    ("PO_EMAIL_SCHEDULED", "Purchase order email scheduled"),
                    ("PO_EMAIL_QUEUED", "Purchase order email queued"),
                    ("PO_EMAIL_SENT", "Purchase order email sent"),
                    ("PO_EMAIL_FAILED", "Purchase order email failed"),
                    ("PO_EMAIL_CANCELLED", "Purchase order email cancelled"),
                    ("DOC_EMAIL_QUEUED", "Customer document email queued"),
                    ("DOC_EMAIL_SENT", "Customer document email sent"),
                    ("DOC_EMAIL_FAILED", "Customer document email failed"),
                    ("GRN_POSTED", "Goods receipt posted"),
                    ("GRN_POST_REJECTED", "Goods receipt posting rejected"),
                    ("VENDOR_INVOICE_MATCHED", "Vendor invoice matched"),
                    ("VENDOR_INVOICE_APPROVED", "Vendor invoice approved (workflow)"),
                    ("VENDOR_INVOICE_POSTED", "Vendor invoice posted"),
                    ("VENDOR_INVOICE_POST_REJECTED", "Vendor invoice posting rejected"),
                    ("VENDOR_PAYMENT_POSTED", "Vendor payment posted"),
                    ("VENDOR_PAYMENT_POST_REJECTED", "Vendor payment posting rejected"),
                    ("VENDOR_PAYMENT_ALLOCATED", "Vendor payment allocated"),
                    ("VENDOR_INVOICE_VOIDED", "Vendor invoice voided"),
                    (
                        "VENDOR_CREDIT_NOTE_APPROVED",
                        "Vendor credit note approved (workflow)",
                    ),
                    ("VENDOR_CREDIT_NOTE_POSTED", "Vendor credit note posted"),
                    ("VENDOR_CREDIT_NOTE_ALLOCATED", "Vendor credit note allocated"),
                    ("VENDOR_CREDIT_NOTE_VOIDED", "Vendor credit note voided"),
                    ("GOODS_RETURNED", "Goods returned to vendor"),
                    ("VENDOR_OPENING_BILL_POSTED", "Vendor opening bill posted"),
                    ("STOCK_RECEIVED", "Stock received (perpetual inventory)"),
                    ("STOCK_ISSUED", "Stock issued"),
                    ("STOCK_ISSUE_REJECTED", "Stock issue rejected"),
                    ("STOCK_ADJUSTED", "Stock adjusted"),
                    ("STOCK_ADJUST_REJECTED", "Stock adjustment rejected"),
                    ("BANK_STATEMENT_CORRECTED", "Bank statement corrected"),
                    ("BANK_RECONCILED", "Bank statement reconciled"),
                    ("BANK_CHARGE_POSTED", "Bank charge posted"),
                    ("BANK_TRANSACTION_POSTED", "Bank transaction posted"),
                    ("BANK_TRANSACTION_VOIDED", "Bank transaction voided"),
                    ("BANK_TRANSFER_POSTED", "Transfer between own accounts posted"),
                    ("BANK_TRANSFER_VOIDED", "Transfer between own accounts voided"),
                    ("EXPENSE_CLAIM_POSTED", "Expense claim posted"),
                    ("EXPENSE_CLAIM_POST_REJECTED", "Expense claim posting rejected"),
                    ("EXPENSE_CLAIM_SETTLED", "Expense claim settled"),
                    ("EXPENSE_CLAIM_VOIDED", "Expense claim voided"),
                    (
                        "PETTY_CASH_ESTABLISHED",
                        "Petty cash fund established / topped up",
                    ),
                    ("PETTY_CASH_VOUCHER_POSTED", "Petty cash voucher posted"),
                    ("PETTY_CASH_VOUCHER_REJECTED", "Petty cash voucher rejected"),
                    ("PETTY_CASH_VOUCHER_VOIDED", "Petty cash voucher voided"),
                    ("PETTY_CASH_REPLENISHED", "Petty cash fund replenished"),
                    ("PAYROLL_POSTED", "Payroll run posted"),
                    ("PAYROLL_POST_REJECTED", "Payroll run posting rejected"),
                    ("PAYROLL_PAID", "Payroll run disbursed"),
                    ("PAYROLL_CANCELLED", "Payroll run cancelled / voided"),
                    ("BUDGET_APPROVED", "Budget approved"),
                    ("BUDGET_DELETED", "Budget deleted"),
                    ("ASSET_ACQUIRED", "Fixed asset acquired"),
                    ("DEPRECIATION_POSTED", "Depreciation posted"),
                    ("ASSET_DISPOSED", "Fixed asset disposed"),
                    ("PERIOD_LOCKED", "Period locked"),
                    ("FISCAL_YEAR_OPENED", "Fiscal year opened"),
                    ("FISCAL_YEAR_CLOSED", "Fiscal year closed"),
                    ("FISCAL_YEAR_REOPENED", "Fiscal year re-opened"),
                    (
                        "FISCAL_CALENDAR_WARNED",
                        "Finance staff warned the fiscal calendar is running out",
                    ),
                    ("TAX_FILING_PREPARED", "Tax filing prepared"),
                    ("TAX_FILING_FILED", "Tax filing submitted to authority"),
                    ("TAX_FILING_UNFILED", "Tax filing un-filed (reverted to draft)"),
                    ("TAX_FILING_PAID", "Tax filing paid / remitted"),
                    ("TAX_FILING_REJECTED", "Tax filing action rejected"),
                    ("TAX_REMITTANCE_REVERSED", "Tax remittance reversed"),
                    (
                        "FIN_PAYROLL_SETTINGS_UPDATED",
                        "Finance payroll settings updated",
                    ),
                    ("SALARY_CREATED", "Employee salary added"),
                    ("SALARY_CHANGED", "Employee salary changed"),
                    ("SALARY_DEACTIVATED", "Employee salary deactivated"),
                    ("PAYE_OVERRIDE_CHANGED", "PAYE override set or cleared"),
                    ("SALARY_STRUCTURE_CHANGED", "Salary structure changed"),
                    ("PAYROLL_DEDUCTION_CHANGED", "Payroll deduction changed"),
                    ("PAYSLIPS_ISSUED", "Payslips issued"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="payrollline",
            name="net_amount",
            field=vs_finance.money.MoneyField(
                help_text="Take-home: gross - paye - pension - other deductions, in kobo."
            ),
        ),
        migrations.AlterField(
            model_name="taxobligation",
            name="obligation_type",
            field=models.CharField(
                choices=[
                    ("VAT", "Value Added Tax"),
                    ("WHT", "Withholding Tax"),
                    ("PAYE", "Pay-As-You-Earn (employee income tax)"),
                    ("PENSION", "Pension contribution"),
                    ("NHF", "National Housing Fund"),
                    ("NSITF", "NSITF employee compensation"),
                    ("ITF", "ITF training levy"),
                    ("OTHER", "Other statutory levy"),
                ],
                help_text="Which statutory tax this obligation covers.",
                max_length=12,
            ),
        ),
        migrations.AddIndex(
            model_name="salarycomponent",
            index=models.Index(
                fields=["structure", "effective_to"],
                name="vs_finance__structu_62e5eb_idx",
            ),
        ),
        migrations.AddField(
            model_name="employeededuction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="finance_employee_deductions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeededuction",
            name="salary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deductions",
                to="vs_finance.employeesalary",
            ),
        ),
        migrations.AddField(
            model_name="employeesalaryversion",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="finance_salary_versions",
                to="vs_tenants.branch",
            ),
        ),
        migrations.AddField(
            model_name="employeesalaryversion",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="salary_versions",
                to="vs_finance.costcenter",
            ),
        ),
        migrations.AddField(
            model_name="employeesalaryversion",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="finance_salary_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeesalaryversion",
            name="salary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="vs_finance.employeesalary",
            ),
        ),
        migrations.AddField(
            model_name="employeesalaryversion",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="salary_versions",
                to="vs_finance.salarystructure",
            ),
        ),
        migrations.AddField(
            model_name="financepayrollsettings",
            name="entity",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="finance_payroll_settings",
                to="vs_finance.ledgerentity",
            ),
        ),
        migrations.AddField(
            model_name="financepayrollsettings",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="finance_payroll_settings_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payetaxtable",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paye_tax_tables_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payetaxtable",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paye_tax_tables_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payetaxrelief",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reliefs",
                to="vs_finance.payetaxtable",
            ),
        ),
        migrations.AddField(
            model_name="payetaxband",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bands",
                to="vs_finance.payetaxtable",
            ),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="tax_table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_lines",
                to="vs_finance.payetaxtable",
            ),
        ),
        migrations.AddField(
            model_name="payrolldeductiontype",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_deduction_types",
                to="vs_finance.ledgerentity",
            ),
        ),
        migrations.AddField(
            model_name="payrolldeductiontype",
            name="liability_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_deduction_types",
                to="vs_finance.account",
            ),
        ),
        migrations.AddField(
            model_name="employeededuction",
            name="deduction_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="vs_finance.payrolldeductiontype",
            ),
        ),
        migrations.AddField(
            model_name="payrolllineitem",
            name="deduction_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="line_items",
                to="vs_finance.payrolldeductiontype",
            ),
        ),
        migrations.AddField(
            model_name="payrolllineitem",
            name="employee_deduction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="line_items",
                to="vs_finance.employeededuction",
            ),
        ),
        migrations.AddField(
            model_name="payrolllineitem",
            name="expense_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_item_expenses",
                to="vs_finance.account",
            ),
        ),
        migrations.AddField(
            model_name="payrolllineitem",
            name="liability_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_item_liabilities",
                to="vs_finance.account",
            ),
        ),
        migrations.AddField(
            model_name="payrolllineitem",
            name="line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="vs_finance.payrollline",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrolltaxjurisdiction",
            constraint=models.UniqueConstraint(
                fields=("country", "code"), name="uniq_finance_tax_jurisdiction_code"
            ),
        ),
        migrations.AddField(
            model_name="employeesalaryversion",
            name="residence_state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="salary_versions",
                to="vs_finance.payrolltaxjurisdiction",
            ),
        ),
        migrations.AddField(
            model_name="employeesalary",
            name="residence_state",
            field=models.ForeignKey(
                blank=True,
                help_text="State of residence, where PAYE is remitted. Empty: the branch's state.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="residents",
                to="vs_finance.payrolltaxjurisdiction",
            ),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="tax_state",
            field=models.ForeignKey(
                blank=True,
                help_text="The state whose revenue service this person's PAYE is remitted to.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_lines",
                to="vs_finance.payrolltaxjurisdiction",
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="finance_payslips",
                to="vs_tenants.branch",
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="finance_payslips",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payslips",
                to="vs_finance.ledgerentity",
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="line",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payslip",
                to="vs_finance.payrollline",
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payslips",
                to="vs_finance.payrollrun",
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="salary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payslips",
                to="vs_finance.employeesalary",
            ),
        ),
        migrations.AddField(
            model_name="employeesalary",
            name="pfa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="vs_finance.pensionfundadministrator",
            ),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="pfa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_lines",
                to="vs_finance.pensionfundadministrator",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollline",
            index=models.Index(
                fields=["salary"], name="vs_finance__salary__a7b265_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payetaxtable",
            constraint=models.UniqueConstraint(
                fields=("country", "tax_year"), name="uniq_finance_paye_table_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="payrolldeductiontype",
            constraint=models.UniqueConstraint(
                fields=("entity", "code"), name="uniq_finance_payroll_deduction_code"
            ),
        ),
        migrations.AddIndex(
            model_name="employeededuction",
            index=models.Index(
                fields=["salary", "is_active"], name="vs_finance__salary__7d7757_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrolllineitem",
            index=models.Index(fields=["line"], name="vs_finance__line_id_a960e9_idx"),
        ),
        migrations.AddIndex(
            model_name="payrolllineitem",
            index=models.Index(
                fields=["liability_account"], name="vs_finance__liabili_a87f59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeesalaryversion",
            index=models.Index(
                fields=["salary", "effective_from"],
                name="vs_finance__salary__2136e6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payslip",
            index=models.Index(
                fields=["employee", "pay_date"], name="vs_finance__employe_a3a0e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payslip",
            index=models.Index(
                fields=["entity", "run"], name="vs_finance__entity__14edd4_idx"
            ),
        ),
    ]
