# Generated by Django 5.2.10 on 2026-10-01 16:06

import django.db.models.deletion
import django.utils.timezone
import vs_finance.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0051_pay_breakdown_write_follows_gross"),
        ("vs_tenants", "0011_platform_tenant_lagos_branch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="journalline",
            name="counterparty_branch",
            field=models.ForeignKey(
                blank=True,
                help_text="The other branch of an inter-branch line; blank on every other line.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="vs_tenants.branch",
            ),
        ),
        migrations.AlterField(
            model_name="documentsequence",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("JN", "Journal Entry"),
                    ("IV", "Sales / AR Invoice"),
                    ("RC", "Receipt"),
                    ("PY", "Payment"),
                    ("CN", "Credit Note"),
                    ("DN", "Debit Note"),
                    ("RF", "Customer Refund"),
                    ("PP", "Installment Payment Plan"),
                    ("CC", "Concession / Discount / Waiver"),
                    ("WO", "Bad-debt Write-off"),
                    ("DU", "Dunning / Payment Reminder"),
                    ("PR", "Purchase Requisition"),
                    ("RQ", "Request for Quotation"),
                    ("QT", "Vendor Quotation"),
                    ("PO", "Purchase Order"),
                    ("GN", "Goods Received Note"),
                    ("VI", "Vendor Invoice"),
                    ("VP", "Vendor Payment"),
                    ("EX", "Expense Claim"),
                    ("PC", "Petty Cash Voucher"),
                    ("PL", "Payroll Run"),
                    ("FA", "Fixed Asset"),
                    ("TX", "Tax Filing / Remittance"),
                    ("BG", "Budget"),
                    ("BT", "Bank Transaction"),
                    ("BX", "Transfer Between Own Accounts"),
                    ("CT", "Customer Credit Transfer"),
                    ("DP", "Doubtful-debt Provision"),
                    ("IB", "Inter-branch Transfer"),
                    ("HF", "Receipt Held for Another Branch"),
                    ("RG", "Inter-branch Recharge"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="financeaccountmapping",
            name="key",
            field=models.CharField(
                choices=[
                    ("CASH_BANK", "Cash and bank"),
                    ("ACCOUNTS_RECEIVABLE", "Accounts receivable"),
                    ("ACCOUNTS_PAYABLE", "Accounts payable"),
                    ("CUSTOMER_CREDIT", "Customer credit"),
                    ("VENDOR_ADVANCE", "Vendor advances"),
                    ("GRIR_CLEARING", "GR/IR clearing"),
                    ("OUTPUT_VAT", "Output VAT"),
                    ("WHT_PAYABLE", "WHT payable"),
                    ("RETAINED_EARNINGS", "Retained earnings"),
                    ("BAD_DEBT_EXPENSE", "Bad debt expense"),
                    ("BANK_CHARGES", "Bank charges"),
                    ("INVENTORY_ASSET", "Inventory asset"),
                    ("INVENTORY_ADJUSTMENT", "Inventory adjustment"),
                    ("PURCHASE_PRICE_VARIANCE", "Purchase price variance"),
                    ("DEFERRED_INCOME", "Deferred income"),
                    ("DEPOSITS_HELD", "Customer deposits held"),
                    ("DOUBTFUL_DEBT_ALLOWANCE", "Allowance for doubtful debts"),
                    ("BAD_DEBT_RECOVERED", "Bad debts recovered"),
                    ("FORFEITED_DEPOSIT_INCOME", "Forfeited deposits income"),
                    ("GATEWAY_CLEARING", "Gateway clearing"),
                    ("CLIENT_FUNDS_HELD", "Client funds held"),
                    ("PROVIDER_BALANCE", "Payment provider balance"),
                    ("CLIENT_FUNDS_OWED", "Owed by clients"),
                    ("CHARGEBACKS", "Payment chargebacks"),
                    ("INTER_BRANCH", "Inter-branch balances"),
                    ("HELD_FOR_OTHER_BRANCHES", "Held for other branches"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="financeauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("JOURNAL_POSTED", "Journal posted"),
                    ("JOURNAL_REVERSED", "Journal reversed"),
                    ("JOURNAL_POST_REJECTED", "Journal posting rejected"),
                    ("INVOICE_POSTED", "Invoice posted"),
                    ("INVOICE_CANCELLED", "Invoice cancelled"),
                    ("INVOICE_REVERSED", "Invoice reversed"),
                    ("INVOICE_WRITTEN_OFF", "Invoice written off (bad debt)"),
                    ("INVOICE_PAY_LINK_REVOKED", "Invoice pay link revoked"),
                    ("PAYMENT_POSTED", "Payment posted"),
                    ("PAYMENT_ALLOCATED", "Payment allocated"),
                    ("PAYMENT_REVERSED", "Payment reversed"),
                    ("CREDIT_NOTE_POSTED", "Credit note posted"),
                    ("CREDIT_NOTE_ALLOCATED", "Credit note allocated"),
                    ("DEBIT_NOTE_POSTED", "Debit note posted"),
                    ("CREDIT_NOTE_REVERSED", "Credit/debit note reversed"),
                    ("REFUND_POSTED", "Customer refund posted"),
                    ("REFUND_REVERSED", "Customer refund reversed"),
                    ("PAYMENT_PLAN_ACTIVATED", "Installment plan activated"),
                    ("PAYMENT_PLAN_COMPLETED", "Installment plan completed"),
                    ("PAYMENT_PLAN_CANCELLED", "Installment plan cancelled"),
                    ("CONCESSION_POSTED", "Concession / discount / waiver posted"),
                    ("CONCESSION_REVERSED", "Concession / discount / waiver reversed"),
                    ("CUSTOMER_UPDATED", "Customer updated"),
                    ("CUSTOMER_DEACTIVATED", "Customer deactivated"),
                    ("CUSTOMER_REACTIVATED", "Customer reactivated"),
                    ("CUSTOMER_OPENING_POSTED", "Customer opening invoice posted"),
                    ("CREDIT_TRANSFER_POSTED", "Customer credit transfer posted"),
                    ("CREDIT_TRANSFER_REVERSED", "Customer credit transfer reversed"),
                    ("DEFERRED_INCOME_RELEASED", "Deferred income released"),
                    ("DEFERRED_RELEASE_REVERSED", "Deferred income release reversed"),
                    ("PROVISION_POSTED", "Doubtful-debt provision posted"),
                    ("WRITE_OFF_RECOVERED", "Written-off debt recovered"),
                    ("DEPOSIT_RELEASED", "Customer deposit released"),
                    ("DEPOSITS_FORFEITED", "Unclaimed deposits forfeited"),
                    ("RECEIPT_PARKED_AS_CREDIT", "Receipt parked as customer credit"),
                    ("DUNNING_RUN_GENERATED", "Dunning run generated"),
                    ("DUNNING_NOTICE_SENT", "Dunning notice marked sent"),
                    ("DUNNING_NOTICE_CANCELLED", "Dunning notice cancelled"),
                    ("PERIOD_CLOSED", "Period closed"),
                    ("PERIOD_REOPENED", "Period re-opened"),
                    ("ACCOUNT_CREATED", "Account created"),
                    ("ACCOUNT_UPDATED", "Account updated"),
                    ("FINANCE_SETTINGS_UPDATED", "Finance settings updated"),
                    (
                        "FIN_DOCUMENT_SETTINGS_UPDATED",
                        "Finance document settings updated",
                    ),
                    ("FIN_BANK_SETTINGS_UPDATED", "Finance banking settings updated"),
                    (
                        "FIN_CALENDAR_SETTINGS_UPDATED",
                        "Finance calendar settings updated",
                    ),
                    (
                        "FIN_RECEIVABLES_SETTINGS_UPDATED",
                        "Finance receivables settings updated",
                    ),
                    ("PROCUREMENT_SETTINGS_UPDATED", "Procurement settings updated"),
                    ("REQUISITION_APPROVED", "Requisition approved"),
                    (
                        "SPEND_APPROVAL_OVERRIDDEN",
                        "Spend approval released by override (no review)",
                    ),
                    ("RFQ_ISSUED", "Request for quotation issued"),
                    ("RFQ_CANCELLED", "Request for quotation cancelled"),
                    ("RFQ_CLOSED", "Request for quotation closed without award"),
                    ("QUOTATION_SUBMITTED", "Vendor quotation submitted"),
                    ("QUOTATION_AWARDED", "Vendor quotation awarded → PO"),
                    ("QUOTATION_REJECTED", "Vendor quotation rejected"),
                    ("VENDOR_CONTRACT_ACTIVATED", "Vendor contract activated"),
                    ("VENDOR_CONTRACT_RENEWED", "Vendor contract renewed"),
                    ("VENDOR_CONTRACT_TERMINATED", "Vendor contract terminated"),
                    ("CONTRACT_MILESTONE_COMPLETED", "Contract milestone completed"),
                    ("PURCHASE_ORDER_APPROVED", "Purchase order approved"),
                    ("PURCHASE_ORDER_CANCELLED", "Purchase order cancelled"),
                    ("PO_EMAIL_SCHEDULED", "Purchase order email scheduled"),
                    ("PO_EMAIL_QUEUED", "Purchase order email queued"),
                    ("PO_EMAIL_SENT", "Purchase order email sent"),
                    ("PO_EMAIL_FAILED", "Purchase order email failed"),
                    ("PO_EMAIL_CANCELLED", "Purchase order email cancelled"),
                    ("DOC_EMAIL_QUEUED", "Customer document email queued"),
                    ("DOC_EMAIL_SENT", "Customer document email sent"),
                    ("DOC_EMAIL_FAILED", "Customer document email failed"),
                    ("GRN_POSTED", "Goods receipt posted"),
                    ("GRN_POST_REJECTED", "Goods receipt posting rejected"),
                    ("VENDOR_INVOICE_MATCHED", "Vendor invoice matched"),
                    ("VENDOR_INVOICE_APPROVED", "Vendor invoice approved (workflow)"),
                    ("VENDOR_INVOICE_POSTED", "Vendor invoice posted"),
                    ("VENDOR_INVOICE_POST_REJECTED", "Vendor invoice posting rejected"),
                    ("VENDOR_PAYMENT_POSTED", "Vendor payment posted"),
                    ("VENDOR_PAYMENT_POST_REJECTED", "Vendor payment posting rejected"),
                    ("VENDOR_PAYMENT_ALLOCATED", "Vendor payment allocated"),
                    ("VENDOR_INVOICE_VOIDED", "Vendor invoice voided"),
                    (
                        "VENDOR_CREDIT_NOTE_APPROVED",
                        "Vendor credit note approved (workflow)",
                    ),
                    ("VENDOR_CREDIT_NOTE_POSTED", "Vendor credit note posted"),
                    ("VENDOR_CREDIT_NOTE_ALLOCATED", "Vendor credit note allocated"),
                    ("VENDOR_CREDIT_NOTE_VOIDED", "Vendor credit note voided"),
                    ("GOODS_RETURNED", "Goods returned to vendor"),
                    ("VENDOR_OPENING_BILL_POSTED", "Vendor opening bill posted"),
                    ("STOCK_RECEIVED", "Stock received (perpetual inventory)"),
                    ("STOCK_ISSUED", "Stock issued"),
                    ("STOCK_ISSUE_REJECTED", "Stock issue rejected"),
                    ("STOCK_ADJUSTED", "Stock adjusted"),
                    ("STOCK_ADJUST_REJECTED", "Stock adjustment rejected"),
                    ("BANK_STATEMENT_CORRECTED", "Bank statement corrected"),
                    ("BANK_RECONCILED", "Bank statement reconciled"),
                    ("BANK_CHARGE_POSTED", "Bank charge posted"),
                    ("BANK_TRANSACTION_POSTED", "Bank transaction posted"),
                    ("BANK_TRANSACTION_VOIDED", "Bank transaction voided"),
                    ("BANK_TRANSFER_POSTED", "Transfer between own accounts posted"),
                    ("BANK_TRANSFER_VOIDED", "Transfer between own accounts voided"),
                    ("EXPENSE_CLAIM_POSTED", "Expense claim posted"),
                    ("EXPENSE_CLAIM_POST_REJECTED", "Expense claim posting rejected"),
                    ("EXPENSE_CLAIM_SETTLED", "Expense claim settled"),
                    ("EXPENSE_CLAIM_VOIDED", "Expense claim voided"),
                    (
                        "PETTY_CASH_ESTABLISHED",
                        "Petty cash fund established / topped up",
                    ),
                    ("PETTY_CASH_VOUCHER_POSTED", "Petty cash voucher posted"),
                    ("PETTY_CASH_VOUCHER_REJECTED", "Petty cash voucher rejected"),
                    ("PETTY_CASH_VOUCHER_VOIDED", "Petty cash voucher voided"),
                    ("PETTY_CASH_REPLENISHED", "Petty cash fund replenished"),
                    ("PAYROLL_POSTED", "Payroll run posted"),
                    ("PAYROLL_POST_REJECTED", "Payroll run posting rejected"),
                    ("PAYROLL_PAID", "Payroll run disbursed"),
                    ("PAYROLL_CANCELLED", "Payroll run cancelled / voided"),
                    ("BUDGET_APPROVED", "Budget approved"),
                    ("BUDGET_DELETED", "Budget deleted"),
                    ("ASSET_ACQUIRED", "Fixed asset acquired"),
                    ("DEPRECIATION_POSTED", "Depreciation posted"),
                    ("ASSET_DISPOSED", "Fixed asset disposed"),
                    ("PERIOD_LOCKED", "Period locked"),
                    ("FISCAL_YEAR_OPENED", "Fiscal year opened"),
                    ("FISCAL_YEAR_CLOSED", "Fiscal year closed"),
                    ("FISCAL_YEAR_REOPENED", "Fiscal year re-opened"),
                    (
                        "FISCAL_CALENDAR_WARNED",
                        "Finance staff warned the fiscal calendar is running out",
                    ),
                    ("TAX_FILING_PREPARED", "Tax filing prepared"),
                    ("TAX_FILING_FILED", "Tax filing submitted to authority"),
                    ("TAX_FILING_UNFILED", "Tax filing un-filed (reverted to draft)"),
                    ("TAX_FILING_PAID", "Tax filing paid / remitted"),
                    ("TAX_FILING_REJECTED", "Tax filing action rejected"),
                    ("TAX_REMITTANCE_REVERSED", "Tax remittance reversed"),
                    (
                        "FIN_PAYROLL_SETTINGS_UPDATED",
                        "Finance payroll settings updated",
                    ),
                    ("SALARY_CREATED", "Employee salary added"),
                    ("SALARY_CHANGED", "Employee salary changed"),
                    ("SALARY_DEACTIVATED", "Employee salary deactivated"),
                    ("PAYE_OVERRIDE_CHANGED", "PAYE override set or cleared"),
                    ("SALARY_STRUCTURE_CHANGED", "Salary structure changed"),
                    ("PAYROLL_DEDUCTION_CHANGED", "Payroll deduction changed"),
                    ("PAYSLIPS_ISSUED", "Payslips issued"),
                    ("INTER_BRANCH_REQUESTED", "Inter-branch transfer requested"),
                    ("INTER_BRANCH_SENT", "Inter-branch transfer sent"),
                    ("INTER_BRANCH_DECLINED", "Inter-branch transfer request declined"),
                    (
                        "INTER_BRANCH_CONFIRMED",
                        "Inter-branch transfer arrival confirmed",
                    ),
                    ("INTER_BRANCH_VOIDED", "Inter-branch transfer voided"),
                    ("HELD_RECEIPT_POSTED", "Receipt held for another branch"),
                    ("HELD_RECEIPT_VOIDED", "Receipt held for another branch voided"),
                    ("RECHARGE_POSTED", "Shared cost recharged to other branches"),
                    ("RECHARGE_VOIDED", "Shared cost recharge voided"),
                    (
                        "RECEIVABLE_TRANSFERRED",
                        "Open receivable moved to another branch",
                    ),
                    ("SHARED_COST_RULE_CHANGED", "Shared cost rule changed"),
                    ("STOCK_TRANSFERRED", "Stock moved between stores"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="HeldForBranchReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Kobo received, always positive."
                    ),
                ),
                ("receipt_date", models.DateField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CARD", "Card"),
                            ("CHEQUE", "Cheque"),
                            ("ONLINE", "Online / Gateway"),
                            ("OTHER", "Other"),
                        ],
                        default="BANK_TRANSFER",
                        max_length=16,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                ("narration", models.CharField(blank=True, default="", max_length=255)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="held_receipts",
                        to="vs_finance.bankaccount",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_tenants.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="held_receipts",
                        to="vs_finance.customer",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "for_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="held_receipts_for",
                        to="vs_tenants.branch",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="held_receipts",
                        to="vs_finance.journalentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-receipt_date", "-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InterBranchRecharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="The whole cost being split, in kobo."
                    ),
                ),
                ("recharge_date", models.DateField()),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("COUNTS", "Per-branch counts"),
                            ("PERCENTAGES", "Fixed percentages"),
                        ],
                        max_length=12,
                    ),
                ),
                ("narration", models.CharField(max_length=255)),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_tenants.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "expense_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inter_branch_recharges",
                        to="vs_finance.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-recharge_date", "-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InterBranchTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("FORWARDED_RECEIPT", "Forwarded receipt"),
                            ("RECEIVABLE", "Receivable"),
                            ("RECHARGE", "Recharge"),
                            ("GOODS", "Goods"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Kobo passing from the sending to the receiving branch."
                    ),
                ),
                ("transfer_date", models.DateField()),
                ("purpose", models.CharField(max_length=255)),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                ("repay_by", models.DateField(blank=True, null=True)),
                (
                    "move_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The caller's key for a receivable move, so a repeated call moves nothing twice.",
                        max_length=96,
                    ),
                ),
                ("requested_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("arrival_date", models.DateField(blank=True, null=True)),
                ("declined_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decline_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_tenants.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Whose money or open balance moved, for a forwarded receipt or a receivable move.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inter_branch_transfers",
                        to="vs_finance.customer",
                    ),
                ),
                (
                    "declined_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "from_bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inter_branch_transfers_out",
                        to="vs_finance.bankaccount",
                    ),
                ),
                (
                    "held_receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="forwards",
                        to="vs_finance.heldforbranchreceipt",
                    ),
                ),
                (
                    "receipt",
                    models.OneToOneField(
                        blank=True,
                        help_text="The receipt a forwarded receipt raised at the receiving branch.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inter_branch_forward",
                        to="vs_finance.payment",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recharge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers",
                        to="vs_finance.interbranchrecharge",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inter_branch_transfers_in",
                        to="vs_finance.bankaccount",
                    ),
                ),
                (
                    "to_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inter_branch_transfers_in",
                        to="vs_tenants.branch",
                    ),
                ),
            ],
            options={
                "ordering": ["-transfer_date", "-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InterBranchRechargeLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("weight", models.BigIntegerField()),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="This branch's share, in kobo."
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vs_tenants.branch",
                    ),
                ),
                (
                    "recharge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="vs_finance.interbranchrecharge",
                    ),
                ),
                (
                    "transfer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recharge_line",
                        to="vs_finance.interbranchtransfer",
                    ),
                ),
            ],
            options={
                "ordering": ["recharge", "branch"],
            },
        ),
        migrations.CreateModel(
            name="InterBranchTransferLeg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SENDING", "Sending branch"),
                            ("RECEIVING", "Receiving branch"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inter_branch_legs",
                        to="vs_finance.bankaccount",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inter_branch_legs",
                        to="vs_tenants.branch",
                    ),
                ),
                (
                    "counterparty_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vs_tenants.branch",
                    ),
                ),
                (
                    "journal",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inter_branch_leg",
                        to="vs_finance.journalentry",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legs",
                        to="vs_finance.interbranchtransfer",
                    ),
                ),
            ],
            options={
                "ordering": ["transfer", "role"],
            },
        ),
        migrations.CreateModel(
            name="ReceivableTransferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("INVOICE", "Invoice"),
                            ("DEBIT_NOTE", "Debit note"),
                            ("RECEIPT_CREDIT", "Unapplied receipt"),
                            ("NOTE_CREDIT", "Unapplied credit note"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "amount",
                    vs_finance.money.MoneyField(
                        help_text="Open balance moved, or credit drawn, in kobo."
                    ),
                ),
                (
                    "deferred_amount",
                    vs_finance.money.MoneyField(
                        help_text="Income not yet earned that moved with an invoice, in kobo."
                    ),
                ),
                (
                    "from_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vs_tenants.branch",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receivable_moves",
                        to="vs_finance.invoice",
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receivable_moves",
                        to="vs_finance.creditnote",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receivable_moves",
                        to="vs_finance.payment",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moved_items",
                        to="vs_finance.interbranchtransfer",
                    ),
                ),
            ],
            options={
                "ordering": ["transfer", "kind", "id"],
            },
        ),
        migrations.CreateModel(
            name="SharedCostRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "treatment",
                    models.CharField(
                        choices=[
                            ("ABSORB", "Absorbed by the paying branch"),
                            ("RECHARGE", "Recharged to the other branches"),
                        ],
                        default="ABSORB",
                        max_length=10,
                    ),
                ),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("COUNTS", "Per-branch counts"),
                            ("PERCENTAGES", "Fixed percentages"),
                        ],
                        default="COUNTS",
                        max_length=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shared_cost_rules",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "expense_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="The account the cost is booked to, offered as the recharge's default.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shared_cost_rules",
                        to="vs_finance.account",
                    ),
                ),
            ],
            options={
                "ordering": ["entity", "name"],
            },
        ),
        migrations.AddField(
            model_name="interbranchrecharge",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recharges",
                to="vs_finance.sharedcostrule",
            ),
        ),
        migrations.CreateModel(
            name="SharedCostRuleShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("percent_bps", models.PositiveIntegerField()),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vs_tenants.branch",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="vs_finance.sharedcostrule",
                    ),
                ),
            ],
            options={
                "ordering": ["rule", "branch"],
            },
        ),
        migrations.AddIndex(
            model_name="heldforbranchreceipt",
            index=models.Index(
                fields=["entity", "receipt_date"], name="vs_finance__entity__7d79a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="heldforbranchreceipt",
            index=models.Index(
                fields=["for_branch", "receipt_date"],
                name="vs_finance__for_bra_4d4139_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="heldforbranchreceipt",
            constraint=models.UniqueConstraint(
                fields=("entity", "document_number"),
                name="uniq_vs_finance_heldforbranchreceipt_entity_docnum",
            ),
        ),
        migrations.AddConstraint(
            model_name="heldforbranchreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="ck_finance_heldreceipt_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="heldforbranchreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(("branch", models.F("for_branch")), _negated=True),
                name="ck_finance_heldreceipt_other_branch",
            ),
        ),
        migrations.AddIndex(
            model_name="interbranchtransfer",
            index=models.Index(
                fields=["entity", "transfer_date"],
                name="vs_finance__entity__15c636_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interbranchtransfer",
            index=models.Index(
                fields=["entity", "kind"], name="vs_finance__entity__5115a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interbranchtransfer",
            index=models.Index(
                fields=["to_branch", "transfer_date"],
                name="vs_finance__to_bran_501aa7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="interbranchtransfer",
            constraint=models.UniqueConstraint(
                fields=("entity", "document_number"),
                name="uniq_vs_finance_interbranchtransfer_entity_docnum",
            ),
        ),
        migrations.AddConstraint(
            model_name="interbranchtransfer",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="ck_finance_ibt_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="interbranchtransfer",
            constraint=models.CheckConstraint(
                condition=models.Q(("branch", models.F("to_branch")), _negated=True),
                name="ck_finance_ibt_two_branches",
            ),
        ),
        migrations.AddConstraint(
            model_name="interbranchtransfer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("move_key", ""), _negated=True),
                fields=("entity", "move_key"),
                name="uniq_finance_ibt_move_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="interbranchrechargeline",
            constraint=models.UniqueConstraint(
                fields=("recharge", "branch"), name="uniq_finance_rechargeline_branch"
            ),
        ),
        migrations.AddConstraint(
            model_name="interbranchtransferleg",
            constraint=models.UniqueConstraint(
                fields=("transfer", "role"), name="uniq_finance_ibtleg_role"
            ),
        ),
        migrations.AddConstraint(
            model_name="receivabletransferitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("invoice__isnull", False),
                        ("kind", "INVOICE"),
                        ("note__isnull", True),
                        ("payment__isnull", True),
                    ),
                    models.Q(
                        ("invoice__isnull", True),
                        ("kind__in", ["DEBIT_NOTE", "NOTE_CREDIT"]),
                        ("note__isnull", False),
                        ("payment__isnull", True),
                    ),
                    models.Q(
                        ("invoice__isnull", True),
                        ("kind", "RECEIPT_CREDIT"),
                        ("note__isnull", True),
                        ("payment__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_finance_receivablemove_one_document",
            ),
        ),
        migrations.AddConstraint(
            model_name="sharedcostrule",
            constraint=models.UniqueConstraint(
                fields=("entity", "name"),
                name="uniq_finance_sharedcostrule_entity_name",
            ),
        ),
        migrations.AddIndex(
            model_name="interbranchrecharge",
            index=models.Index(
                fields=["entity", "recharge_date"],
                name="vs_finance__entity__13986c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="interbranchrecharge",
            constraint=models.UniqueConstraint(
                fields=("entity", "document_number"),
                name="uniq_vs_finance_interbranchrecharge_entity_docnum",
            ),
        ),
        migrations.AddConstraint(
            model_name="interbranchrecharge",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="ck_finance_recharge_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="sharedcostruleshare",
            constraint=models.UniqueConstraint(
                fields=("rule", "branch"),
                name="uniq_finance_sharedcostshare_rule_branch",
            ),
        ),
        migrations.AddConstraint(
            model_name="sharedcostruleshare",
            constraint=models.CheckConstraint(
                condition=models.Q(("percent_bps__lte", 10000)),
                name="ck_finance_sharedcostshare_bps_max",
            ),
        ),
    ]
