# Generated by Django 5.2.10 on 2026-10-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0063_bank_document_cancel_and_correct"),
    ]

    operations = [
        migrations.AddField(
            model_name="financecalendarsettings",
            name="periods_close_in_order",
            field=models.BooleanField(
                default=True,
                help_text="A period closes only after every earlier one, and reopens only before every later one.",
            ),
        ),
    ]
