# Generated by Django 5.2.10 on 2026-10-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_finance", "0068_paired_account_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payrollline",
            name="paye_source",
            field=models.CharField(
                choices=[
                    ("COMPUTED", "Computed from the national tax table"),
                    ("OVERRIDE", "Overridden on the employee's salary"),
                    ("SUPPLIED", "Taken from the salary structure or roster"),
                    ("MANUAL", "Typed on a hand-raised run"),
                ],
                default="MANUAL",
                max_length=10,
            ),
        ),
    ]
