# Generated by Django 5.2.10 on 2026-07-28 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_backgroundjob_notify_owner_alter_backgroundjob_owner"),
        ("vs_finance", "0008_alter_financeauditlog_action"),
        ("vs_tenants", "0003_tenantdocumentsequence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="File name including extension.", max_length=255
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("csv", "CSV (.csv)"), ("xlsx", "Excel (.xlsx)")],
                        max_length=8,
                    ),
                ),
                (
                    "storage_name",
                    models.CharField(
                        help_text="Key into the platform's default storage backend.",
                        max_length=255,
                    ),
                ),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("row_count", models.PositiveIntegerField(default=0)),
                (
                    "columns_produced",
                    models.JSONField(
                        default=list,
                        help_text="Field ids actually written — may be fewer than the run requested.",
                    ),
                ),
                ("available_until", models.DateTimeField(db_index=True)),
                ("purged_at", models.DateTimeField(blank=True, null=True)),
                ("download_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExportDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dataset_key",
                    models.CharField(
                        help_text="Key into vs_exports.catalogue, e.g. 'finance.customer_invoices'.",
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "columns",
                    models.JSONField(
                        default=list,
                        help_text="Ordered list of catalogue field ids — this is the column order in the file.",
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        default=list,
                        help_text="List of filter specs, each {id, ...} per the filter's kind.",
                    ),
                ),
                (
                    "sort",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ordered list of {field, direction} — direction is 'asc' or 'desc'.",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("csv", "CSV (.csv)"), ("xlsx", "Excel (.xlsx)")],
                        default="xlsx",
                        max_length=8,
                    ),
                ),
                (
                    "format_options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Options for THIS format only, discriminated by format rather than a flat bag of nullable fields. Unknown keys are dropped on save.",
                    ),
                ),
                (
                    "values_mode",
                    models.CharField(
                        choices=[
                            ("people", "For people to read"),
                            ("system", "For another system to import"),
                        ],
                        default="people",
                        max_length=8,
                    ),
                ),
                (
                    "file_name_pattern",
                    models.CharField(
                        default="export-{date}",
                        help_text="Supports {date} {datetime} {entity} {run} tokens.",
                        max_length=180,
                    ),
                ),
                (
                    "sharing",
                    models.CharField(
                        choices=[("PRIVATE", "Private"), ("SHARED", "Shared")],
                        default="PRIVATE",
                        max_length=8,
                    ),
                ),
                (
                    "is_draft",
                    models.BooleanField(
                        default=False,
                        help_text="A recipe that is not finished — visible, not runnable.",
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "email_recipients",
                    models.BooleanField(
                        default=False,
                        help_text="Whether each run also sends a secure download link to the people this export is shared with. The Export Centre destination is always on — it is the record — so this is the only destination that is a choice.",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        help_text="The set of books this export reads, for entity-scoped datasets only. Null for tenant-scoped datasets, which cover the whole organisation.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="export_definitions",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Runs execute as the owner; sharing never widens what the data shows.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="export_definitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="export_definitions",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ExportDefinitionShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="vs_exports.exportdefinition",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExportDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.CharField(blank=True, default="", max_length=45)),
                (
                    "outcome",
                    models.CharField(
                        choices=[("ALLOWED", "Allowed"), ("REFUSED", "Refused")],
                        max_length=8,
                    ),
                ),
                (
                    "refusal_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXPIRED", "The file passed its availability date"),
                            ("PURGED", "The file has been deleted from storage"),
                            ("NO_ENTITY_ACCESS", "No access to the run's entity"),
                            ("NO_DATASET_ACCESS", "No access to the run's dataset"),
                            ("NOT_SHARED", "The export is not shared with this user"),
                            ("LINK_REVOKED", "The secure link was revoked"),
                        ],
                        default="",
                        max_length=24,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_downloads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="vs_exports.exportfile",
                    ),
                ),
            ],
            options={
                "ordering": ["-at"],
            },
        ),
        migrations.CreateModel(
            name="ExportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        help_text="Human-quotable run reference, e.g. RUN-7F31C2.",
                        max_length=24,
                        unique=True,
                    ),
                ),
                (
                    "frozen_config",
                    models.JSONField(
                        help_text="The configuration used at run time. Mandatory, never back-filled."
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("QUICK", "Quick export"),
                            ("RETRY", "Retry"),
                            ("API", "API"),
                        ],
                        default="MANUAL",
                        max_length=10,
                    ),
                ),
                (
                    "client_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Idempotency key: the same key inside the window returns this run.",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("COMPLETED_WITH_OMISSIONS", "Completed with omissions"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="QUEUED",
                        max_length=26,
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Waiting for a worker"),
                            ("COUNTING", "Counting rows"),
                            ("READING", "Reading rows"),
                            ("BUILDING", "Building file"),
                            ("DELIVERING", "Delivering"),
                            ("DONE", "Done"),
                        ],
                        default="QUEUED",
                        max_length=12,
                    ),
                ),
                ("rows_done", models.PositiveIntegerField(default=0)),
                (
                    "rows_total",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Null means the UI renders indeterminate progress — expected, not an error.",
                        null=True,
                    ),
                ),
                (
                    "row_count",
                    models.PositiveIntegerField(
                        blank=True, help_text="Rows actually written.", null=True
                    ),
                ),
                (
                    "omissions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Structured [{code, scope, detail, items[]}] behind COMPLETED_WITH_OMISSIONS.",
                    ),
                ),
                (
                    "failure_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DATASET_WITHDRAWN", "The dataset is no longer published"),
                            (
                                "DATASET_FORBIDDEN",
                                "No longer allowed to export this dataset",
                            ),
                            (
                                "ENTITY_FORBIDDEN",
                                "No longer allowed to use this entity",
                            ),
                            (
                                "FILTER_INVALID",
                                "A filter this export uses no longer exists",
                            ),
                            ("REQUIRED_FILTER_MISSING", "A required filter is not set"),
                            (
                                "NO_COLUMNS",
                                "Every selected column has become unavailable",
                            ),
                            (
                                "ROW_CAP_EXCEEDED",
                                "The result is larger than the row cap",
                            ),
                            (
                                "DATE_SPAN_EXCEEDED",
                                "The date range is wider than the dataset allows",
                            ),
                            (
                                "OWNER_INACTIVE",
                                "The owner of this export is no longer active",
                            ),
                            ("INFRASTRUCTURE", "A temporary system problem"),
                            ("UNKNOWN", "An unexpected problem"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "failure_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="User-safe. Never a traceback.",
                    ),
                ),
                ("attempt", models.PositiveSmallIntegerField(default=1)),
                (
                    "cancel_requested",
                    models.BooleanField(
                        default=False,
                        help_text="Cancellation is cooperative: the worker checks this.",
                    ),
                ),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "background_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.backgroundjob",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for a quick export, which never had a saved recipe.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="vs_exports.exportdefinition",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for entity-scoped datasets only; null for tenant-scoped ones.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="export_runs",
                        to="vs_finance.ledgerentity",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        help_text="The actor who asked for the run.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="export_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="export_runs",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-queued_at"],
            },
        ),
        migrations.AddField(
            model_name="exportfile",
            name="run",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file",
                to="vs_exports.exportrun",
            ),
        ),
        migrations.CreateModel(
            name="ExportDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination",
                    models.CharField(
                        choices=[
                            ("CENTRE", "Export Centre"),
                            ("EMAIL_LINK", "Secure download link by email"),
                        ],
                        default="EMAIL_LINK",
                        max_length=12,
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("REVOKED", "Revoked"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=8,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Opaque link token. Expires with the file and is revocable.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("attempted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "failure_reason",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="vs_exports.exportrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExportAnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="A key from vs_exports.analytics.Event. Unknown names are dropped.",
                        max_length=48,
                    ),
                ),
                (
                    "properties",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Whitelisted, bucketed scalars only. Never row data or field values.",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Opaque client-generated id, so one builder session can be stitched.",
                        max_length=64,
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nullable so a deleted account does not take the metric with it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_analytics",
                        to="vs_tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "name", "-occurred_at"],
                        name="vs_exports__tenant__76de0e_idx",
                    ),
                    models.Index(
                        fields=["session_key"], name="vs_exports__session_8da820_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="exportdefinition",
            index=models.Index(
                fields=["tenant", "-updated_at"], name="vs_exports__tenant__f40c94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportdefinition",
            index=models.Index(
                fields=["entity", "dataset_key"], name="vs_exports__entity__aae2b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportdefinition",
            index=models.Index(
                fields=["owner", "-updated_at"], name="vs_exports__owner_i_f10b94_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="exportdefinitionshare",
            constraint=models.UniqueConstraint(
                fields=("definition", "user"), name="uniq_export_share_definition_user"
            ),
        ),
        migrations.AddIndex(
            model_name="exportdownload",
            index=models.Index(
                fields=["file", "-at"], name="vs_exports__file_id_bf7aca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportdownload",
            index=models.Index(
                fields=["user", "-at"], name="vs_exports__user_id_6e3efa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportrun",
            index=models.Index(
                fields=["tenant", "-queued_at"], name="vs_exports__tenant__a82e47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportrun",
            index=models.Index(
                fields=["definition", "-queued_at"],
                name="vs_exports__definit_ddf680_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exportrun",
            index=models.Index(
                fields=["status", "-queued_at"], name="vs_exports__status_07ae09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportrun",
            index=models.Index(
                fields=["requested_by", "-queued_at"],
                name="vs_exports__request_66adae_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exportrun",
            index=models.Index(
                fields=["client_key"], name="vs_exports__client__0c847d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportfile",
            index=models.Index(
                fields=["available_until"], name="vs_exports__availab_cdfbc5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportdelivery",
            index=models.Index(
                fields=["run", "state"], name="vs_exports__run_id_48b548_idx"
            ),
        ),
    ]
