# Generated by Django 5.2.10 on 2026-08-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_exports", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exportdefinition",
            name="email_recipients",
        ),
        migrations.AlterField(
            model_name="exportdownload",
            name="refusal_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXPIRED", "The file passed its availability date"),
                    ("PURGED", "The file has been deleted from storage"),
                    ("NO_ENTITY_ACCESS", "No access to the run's entity"),
                    ("NO_DATASET_ACCESS", "No access to the run's dataset"),
                    ("NOT_SHARED", "The export is not shared with this user"),
                ],
                default="",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="exportrun",
            name="phase",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Waiting for a worker"),
                    ("COUNTING", "Counting rows"),
                    ("READING", "Reading rows"),
                    ("BUILDING", "Building file"),
                    ("DONE", "Done"),
                ],
                default="QUEUED",
                max_length=12,
            ),
        ),
        migrations.DeleteModel(
            name="ExportDelivery",
        ),
    ]
