# Generated by Django 5.2.10 on 2026-08-11 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_exports", "0002_remove_exportdefinition_email_recipients_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportrun",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("SCHEDULED", "Scheduled"),
                    ("QUICK", "Quick export"),
                    ("RETRY", "Retry"),
                    ("API", "API"),
                ],
                default="MANUAL",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ExportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("ONCE", "Once, at a future date"),
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="1-31 for MONTHLY/QUARTERLY, 0-6 (Monday-Sunday) for WEEKLY, ignored otherwise. A day past the end of a short month runs on its last day.",
                        null=True,
                    ),
                ),
                (
                    "at_time",
                    models.TimeField(
                        help_text="Local wall-clock time in `timezone_name`."
                    ),
                ),
                (
                    "timezone_name",
                    models.CharField(default="Africa/Lagos", max_length=64),
                ),
                ("starts_on", models.DateField()),
                (
                    "ends_on",
                    models.DateField(
                        blank=True, help_text="Null means no end date.", null=True
                    ),
                ),
                (
                    "skip_when_empty",
                    models.BooleanField(
                        default=False,
                        help_text="Produce no file when nothing matched, instead of an empty one. Off by default: an empty file is itself evidence that nothing happened, and a missing file is indistinguishable from a schedule that never ran.",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("FINISHED", "Finished"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "pause_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BY_PERSON", "Paused by a person"),
                            ("CONSECUTIVE_FAILURES", "Paused after repeated failures"),
                            (
                                "OWNER_INACTIVE",
                                "Paused because the owner was deactivated",
                            ),
                        ],
                        default="",
                        max_length=24,
                    ),
                ),
                (
                    "pause_detail",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("consecutive_failures", models.PositiveSmallIntegerField(default=0)),
                (
                    "next_run_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Derived from the local fields; the dispatcher's only index.",
                        null=True,
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="vs_exports.exportdefinition",
                    ),
                ),
                (
                    "last_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="vs_exports.exportrun",
                    ),
                ),
            ],
            options={
                "ordering": ["next_run_at"],
            },
        ),
        migrations.AddField(
            model_name="exportrun",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when a schedule started this run rather than a person.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="runs",
                to="vs_exports.exportschedule",
            ),
        ),
        migrations.AddIndex(
            model_name="exportschedule",
            index=models.Index(
                fields=["state", "next_run_at"], name="vs_exports__state_7c7952_idx"
            ),
        ),
    ]
