# Generated by Django 5.2.10 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_exports", "0003_alter_exportrun_trigger_exportschedule_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportrun",
            name="reference",
            field=models.CharField(
                help_text="Tenant-level daily run reference, e.g. XR-12608291.",
                max_length=48,
                unique=True,
            ),
        ),
    ]
