# Generated by Django 5.2.10 on 2026-09-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_exports", "0004_alter_exportrun_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportdownload",
            name="access_kind",
            field=models.CharField(
                choices=[("VIEW", "View"), ("DOWNLOAD", "Download")],
                default="DOWNLOAD",
                max_length=8,
            ),
        ),
    ]
