# Generated by Django 5.2.13 on 2026-04-10 13:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PackagePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("code", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("YEARLY", "Yearly"), ("MONTHLY", "Monthly")],
                        default="YEARLY",
                        max_length=20,
                    ),
                ),
                ("max_students", models.PositiveIntegerField(blank=True, null=True)),
                ("max_teachers", models.PositiveIntegerField(blank=True, null=True)),
                ("max_admins", models.PositiveIntegerField(blank=True, null=True)),
                ("max_branch", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Package Plan",
                "verbose_name_plural": "Package Plans",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="XVSModules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.SlugField(
                        help_text="Unique machine key, e.g. students, finance, procurement",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Platform Module",
                "verbose_name_plural": "Platform Modules",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["email"], name="vs_schools__email_1e99c1_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe unique school identifier. Lowercase, hyphen-separated.",
                        max_length=80,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Slug must be lowercase letters/numbers separated by single hyphens.",
                                regex="^[a-z0-9]+(?:-[a-z0-9]+)*$",
                            )
                        ],
                    ),
                ),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                (
                    "ownership_type",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("PRIVATE", "Private"),
                            ("FAITH_BASED", "Faith-Based"),
                            ("NGO", "Non-Governmental Organization"),
                        ],
                        default="PUBLIC",
                        max_length=80,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, default="", max_length=32, unique=True
                    ),
                ),
                ("website", models.URLField(blank=True, default="")),
                ("motto", models.CharField(blank=True, default="", max_length=255)),
                (
                    "term_structure",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("2_SEMESTERS", "2 Semesters"),
                            ("3_TERMS", "3 Terms"),
                        ],
                        default="3_TERMS",
                        max_length=255,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[("NGN", "Nigerian Naira"), ("USD", "US Dollar")],
                        default="NGN",
                        max_length=8,
                    ),
                ),
                (
                    "registration_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["slug"], name="vs_schools__slug_2c251f_idx"),
                    models.Index(
                        fields=["status", "created_at"],
                        name="vs_schools__status_29c4f3_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("slug", ""), _negated=True),
                        name="slug_not_empty",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Branch display name, e.g., 'Lekki Campus'",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.PositiveIntegerField(
                        db_index=True,
                        editable=False,
                        help_text="Branch code unique per school (1..N).",
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False,
                        help_text="Marks the primary/main branch for this school.",
                    ),
                ),
                ("_type", models.CharField(max_length=80)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("country", models.CharField(default="Nigeria", max_length=80)),
                ("state", models.CharField(blank=True, default="", max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PENDING", "Pending Activation"),
                            ("SUSPENDED", "Suspended"),
                            ("INACTIVE", "Inactive"),
                            ("CLOSED", "Closed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="vs_schools.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchoolBranding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="school_logos/"),
                ),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branding",
                        to="vs_schools.school",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SchoolPrimaryAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school_role",
                    models.CharField(blank=True, default="IT Head", max_length=80),
                ),
                (
                    "role_label",
                    models.CharField(blank=True, default="SCHOOL_ADMIN", max_length=80),
                ),
                (
                    "invite_status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="QUEUED",
                        max_length=16,
                    ),
                ),
                ("invite_queued_at", models.DateTimeField(blank=True, null=True)),
                ("invite_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_admin_for_schools",
                        to="vs_schools.contactinfo",
                    ),
                ),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_admin",
                        to="vs_schools.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchoolPackageSetup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("student_capacity", models.PositiveIntegerField()),
                ("teacher_capacity", models.PositiveIntegerField()),
                ("admin_capacity", models.PositiveIntegerField()),
                ("subscription_expires_at", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "package_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="school_setups",
                        to="vs_schools.packageplan",
                    ),
                ),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_setup",
                        to="vs_schools.school",
                    ),
                ),
                (
                    "enabled_modules",
                    models.ManyToManyField(
                        blank=True,
                        related_name="school_package_setups",
                        to="vs_schools.xvsmodules",
                    ),
                ),
            ],
            options={
                "verbose_name": "School Package Setup",
                "verbose_name_plural": "School Package Setups",
            },
        ),
        migrations.CreateModel(
            name="BranchLifecycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_state",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PENDING", "Pending Activation"),
                            ("SUSPENDED", "Suspended"),
                            ("INACTIVE", "Inactive"),
                            ("CLOSED", "Closed"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "to_state",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PENDING", "Pending Activation"),
                            ("SUSPENDED", "Suspended"),
                            ("INACTIVE", "Inactive"),
                            ("CLOSED", "Closed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("actor_id", models.CharField(max_length=120)),
                ("reason", models.TextField(blank=True, default=None)),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lifecycle_events",
                        to="vs_schools.branch",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["branch", "occurred_at"],
                        name="vs_schools__branch__111587_idx",
                    ),
                    models.Index(
                        fields=["branch", "to_state"],
                        name="vs_schools__branch__ced428_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BranchPrimaryAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch_role",
                    models.CharField(blank=True, default="Head Teacher", max_length=80),
                ),
                (
                    "role_label",
                    models.CharField(blank=True, default="BRANCH_ADMIN", max_length=80),
                ),
                (
                    "invite_status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="QUEUED",
                        max_length=16,
                    ),
                ),
                ("invite_queued_at", models.DateTimeField(blank=True, null=True)),
                ("invite_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_admin",
                        to="vs_schools.branch",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_admin_for_branches",
                        to="vs_schools.contactinfo",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["branch", "invite_status"],
                        name="vs_schools__branch__ba96f8_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["school", "is_main"], name="vs_schools__school__38f3c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["school", "status"], name="vs_schools__school__e52510_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["school", "code"], name="vs_schools__school__b13fda_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code", 0), _negated=True),
                fields=("school", "code"),
                name="uniq_branch_code_per_school_when_present",
            ),
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_main", True)),
                fields=("school",),
                name="uniq_one_main_branch_per_school",
            ),
        ),
        migrations.AddIndex(
            model_name="schoolprimaryadmin",
            index=models.Index(
                fields=["school", "invite_status"],
                name="vs_schools__school__79923c_idx",
            ),
        ),
    ]
