# Generated by Django 5.2.10 on 2026-07-10 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_schools", "0001_initial"),
        ("vs_config", "0004_migrate_legacy_configuration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schoolpackagesetup",
            name="enabled_modules",
        ),
        migrations.DeleteModel(
            name="XVSModules",
        ),
    ]
