# Generated by Django 5.2.10 on 2026-08-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_schools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branchlifecycle",
            name="reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
