# Generated by Django 5.2.13 on 2026-04-24 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_schools", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="branch",
            name="uniq_branch_code_per_school_when_present",
        ),
        migrations.RemoveConstraint(
            model_name="branch",
            name="uniq_one_main_branch_per_school",
        ),
    ]
