# Generated by Django 5.2.10 on 2026-06-11 13:17

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_schools", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelManagers(
            name="branch",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
