# Generated by Django 5.2.13 on 2026-05-10 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_schools", "0002_remove_mariadb_unsupported_constraints"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="school",
            options={"ordering": ["-created_at"]},
        ),
    ]
