# Generated by Django 5.2.13 on 2026-05-10 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vs_schools", "0003_alter_school_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={"ordering": ["-created_at"]},
        ),
    ]
