# Generated by Django 5.2.13 on 2026-05-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vs_schools", "0004_alter_branch_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("PENDING", "Pending"),
                ],
                db_index=True,
                default="PENDING",
                max_length=16,
            ),
        ),
    ]
